### ISSUE TITLE
abyss-pe: make --mean the default method for DistanceEst when scaffolding 

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#100]
At some point, @sjackman explained to me that the default method for DistanceEst (`--mle`) is O(n^2) with respect to the distance between read pairs.   As a result it can be quite slow when running on large mate pair libraries.  The default should be changed to `--mean` for the scaffolding stage of `abyss-pe`.

In the meantime, the workaround is to add `DISTANCEEST_OPTIONS='--mean'` to the `abyss-pe` command.

**Comment by sjackman** [comment]
`abyss-scaffold` doesn't currently use the distance estimates, other than for picking the number of Ns between contigs in the scaffolds output by `MergeContigs`. So it's not really necessary to spend the time to get a more accurate distance estimate.

**Comment by sjackman** [comment]
Another approach is for `DistanceEst` to pick which algorithm depending on the fragment size of the library. If the maximum fragment size (calculated by DistanceEst with trimming) is less than 2000 bp, use `--mle`, if it's more than 2000 bp, use `--mean`. I picked 2000 bp out of thin air. The user can override the automatic choice by specifying one or the other.

**Comment by benvvalk** [comment]
Good idea.  Thanks, Shaun!

**Comment by benvvalk** [comment]
`DistanceEst --mean` is now the default choice for the scaffolding stage (commit  8470469)
