### ISSUE TITLE
DistanceEst --mind and --maxd not apparently working

### ISSUE THREAD

**Issue by dbrowneup** [bcgsc/abyss#101]
Hi guys,

I think I have encountered a bug in DistanceEst, where although I am specifying --mind and --maxd, the program is reporting distance estimates outside the specified limits. For example, I issued this command:

```
$ABYSS_PATH/abyss-map -v  -j20 -l100    ../../02_Separated_Pairs/Library.HOOW.L.fq.gz ../../02_Separated_Pairs/Library.HOOW.R.fq.gz SEQ1K_100-3.fa \
              |$ABYSS_PATH/abyss-fixmate -v  -l100  -h mp1-3.hist \
              |sort -snk3 -k4 \
              |$ABYSS_PATH/DistanceEst -v  --dot -j20 -k100 --mean --mind=-6000 --maxd=6000 -l100 -s1000 -n5 -o mp1-3.dist.dot mp1-3.hist
```

And here are the results:

```
[dbrowne@ada2 Modified_v4]$ grep -o "d=.[0-9]*" mp1-3.dist.dot | tr -d 'd=' | sort -n | uniq -c > DISTANCE_ESTIMATES.txt
[dbrowne@ada2 Modified_v4]$ head DISTANCE_ESTIMATES.txt 
      2 -47567
      2 -23980
      2 -23208
      2 -22336
      2 -20922
      2 -19024
      2 -18163
      2 -18055
      2 -17622
      2 -17597
[dbrowne@ada2 Modified_v4]$ tail DISTANCE_ESTIMATES.txt 
      4 3490
      2 3491
      2 3492
      6 3493
      4 3495
      4 3496
      4 3499
      4 3501
      2 3503
      4 3505
```

Did I do something wrong that would cause it to report such enormous estimated overlaps? I want to cap the distance estimates at -6000 bp minimum and 6000 bp maximum because the library is a 4kb insert size and the maximum observed insert size is just under 6000 bp. Any suggestions on what I could do to correct this?

**Comment by dbrowneup** [comment]
Also, similar story with `abyss-scaffold` --min-gap. Here's the command I issued:
```
$ABYSS_PATH/abyss-scaffold -v -k100 -n5 -s1000 --min-gap=1 --max-gap=6000 --complex -o SEQ1K_100-7.path -g SEQ1K_100-7.dot SEQ1K_100-6.dot mp1-3.dist.dot
```
And here are the results:
```
[dbrowne@ada2 Modified_v4]$ grep -o "[0-9]*N" SEQ1K_100-7.path | tr -d 'N' | sort -n | uniq -c > ABYSS_SCAFFOLD_PATH_N_CONTENT.txt
[dbrowne@ada2 Modified_v4]$ head ABYSS_SCAFFOLD_PATH_N_CONTENT.txt 
   5812 100
      6 101
      4 102
      3 103
      7 104
      3 105
      7 106
      3 107
      6 108
      4 109
[dbrowne@ada2 Modified_v4]$ tail ABYSS_SCAFFOLD_PATH_N_CONTENT.txt 
      1 6021
      1 6024
      1 6030
      1 6035
      1 6041
      1 6062
      1 6068
      1 6072
      1 6075
      1 6093
[dbrowne@ada2 Modified_v4]$ less ../RUN_ABySS_Contig_Test_Modified_v4.job 
```
I specified `--min-gap=1` but the minimum gap reported in the `path` file is clearly 100N. Though oddly enough, despite the largest distance estimate being reported as 3505 bp, the largest gap set by abyss-scaffold is 6093N.

**Comment by sjackman** [comment]
The first issue is either a bug or a documentation error, depending on your opinion. The `--mind` and `--maxd` options are only used by the `--mle` algorithm. It specifies the range of values to optimize over. The size of the range directly affects the run time. The `--mean` algorithm does not optimize over a range. It's a closed-form solution. It could artificially clamp its results to the range specified by `--mind` and `--maxd`, which actually isn't a bad idea.

**Comment by sjackman** [comment]
Due to historical reasons I'd rather not get into over a text medium (because ugh), the values of the `N` in the `.path` file are offset by a constant of `k-1` bp. That is `100N` at `k=100` is in fact a 1 bp gap. `99N` is a 0 bp gap, that is, directly adjacent. `98N` is a 1 bp overlap. `0N` (which doesn't happen) is a `k-1` bp overlap. I apologize for this disaster.
