### ISSUE TITLE
Compilation error: [abyss_db_csv-db-csv.o] Error 1

### ISSUE THREAD

**Issue by shashidhar22** [bcgsc/abyss#103]
Compiling  abyss from source give the following make error:
```{sh}
db-csv.cc: In function ‘bool existFile(const char*)’:
db-csv.cc:23:9: error: cannot convert ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘bool’ in return
  return file;
         ^~~~
make[2]: *** [abyss_db_csv-db-csv.o] Error 1
make[2]: Leaving directory `/data/users/sravishankar9/malaria/Toolkit/abyss/DataBase'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/users/sravishankar9/malaria/Toolkit/abyss'
make: *** [all] Error 2
```

Linux distribution:
Linux version 2.6.32-504.8.1.el6.x86_64 (gcc version 4.4.7 20120313 (Red Hat 4.4.7-9) (GCC) )

Any help with this issue would be appreciated.
Thanks

**Comment by benvvalk** [comment]
Hi @shashidhar22,

Never seen that one before.  I'm guessing it can be fixed with the following change:
```
diff --git a/DataBase/db-csv.cc b/DataBase/db-csv.cc
index 05cac19..c2c53f3 100644
--- a/DataBase/db-csv.cc
+++ b/DataBase/db-csv.cc
@@ -20,7 +20,7 @@ typedef vector<string> vs;
 static bool existFile(const char* f)
 {
        ifstream file(f);
-       return file;
+       return file.good();
 }
 
 template <typename D>
```

Can you try making that change and seeing if your problem goes away? If so, I'll push it to the public repo.

**Comment by shashidhar22** [comment]
Hi @benvvalk 

Thank you for getting back to me, that fix worked, but the compilation encountered another error after that:

```{sh}
SimpleGraph.cpp: In function ‘void* worker(void*)’:
SimpleGraph.cpp:650:28: error: cannot convert ‘std::istream {aka std::basic_istream<char>}’ to ‘bool’ in initialization
   bool good = (*arg.in) >> er;
                            ^~
make[2]: *** [SimpleGraph-SimpleGraph.o] Error 1
make[2]: Leaving directory `/data/users/sravishankar9/malaria/Toolkit/abyss/SimpleGraph'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/users/sravishankar9/malaria/Toolkit/abyss'
make: *** [all] Error 2
```
Again any help with this issue would be appreciated.
Thanks

**Comment by benvvalk** [comment]
Hmm.  What version of C++ compiler are you using? (And what version)

If it is a really old compiler, that might explain the odd behaviour.

**Comment by shashidhar22** [comment]
I'm using the latest version of gcc: 
gcc version 6.0.0 20160316 (experimental) (GCC)

**Comment by shashidhar22** [comment]
Error resolved, setting CPPFlag -std=c++98 seems to have done the job.
Thank you

**Comment by benvvalk** [comment]
Okay, good!

**Comment by sjackman** [comment]
By chance I just fixed this bug in the `develop` branch. https://github.com/bcgsc/abyss-dev/commit/cd0ee685a0228bfe6a111cc7c8abb8f6fa093337
The fix is to explicitly cast to `bool`.
```c++
return (bool)ifstream(f);
```
Unfortunately, and this is bizarre, `(bool)ifstream` and `bool.good()` are *not* synonyms.
`(bool)ifstream` and `!bool.fail()` are however synonyms. 
For details see http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool

**Comment by benvvalk** [comment]
Noted! (I hate that goodbit, badbit, failbit, eofbit business...)
