### ISSUE TITLE
Abyss fails on empty hist files (mate-pairs)

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#104]
I was wondering whether it might not be beneficial to allow abyss to be more lenient on the mapping results for mate pair libraries?
I'm currently running a fairly long assembly run with abyss and I noticed it 'crashes' once in a while when there can't be any mate-pair reads mapped to the contigs and thus created an empty hist file for that specific library. 
I do understand that when no pairs are mapped on a single contig, the length distribution can't be made but would it not be feasible to then just ignore that library for downstream processing (and proved a warning message or so) instead of letting abyss die on it? Now I constantly have to keep on eye on it and restart the analysis (after removing the specific library from the input cmd) when needed. 
On a side note: I personally would prefer that my mate-pair reads map on different contigs (= maximal scaffolding possibility) in stead of accurate length estimation when all map to a single contig (= minimal to no scaffolding possibilities). Perhaps in that case an 'arbitrary' (=gap of unknown size) insert length can be used then?

**Comment by sjackman** [comment]
If for a particular sequencing library no single pair of reads maps to the same contig, it's usually a sign of bigger problems. The safer plan in this case would be to stop the assembly. It would mean that the largest contig of the assembly is smaller than the smallest mate-pair fragment of the sequencing library. I've never seen that case unless either sequencing library or the the contig assembly was badly broken.

**Comment by lsterck** [comment]
Yes I tend to agree with your comment, in an ideal theoretical world :-). However I can think of a few biological cases where these things might happen nonetheless. Imagine a large very repetitive genome, then the contigs will not be very large and if you combine that with a very strictly constructed (and large insert) mate-pair library (or a very low coverage MP library) you might end up in case where very few to no MP are aligned on the contigs. Along the same line, the pipeline smoothly continues when for example only a single MP is aligned to the contigs, you have to agree that there is very little value (read: no accurate insert estimate) when this is the case. Moreover the estimate is going to be seriously biased towards the lower end since these ones are the most likely to be aligned on a single contig.

**Comment by sjackman** [comment]
> Along the same line, the pipeline smoothly continues when for example only a single MP is aligned to the contigs, you have to agree that there is very little value (read: no accurate insert estimate) when this is the case.

Good point. It should probably also stop the assembly if it has too few same-contig mate-pairs to construct a histogram.

When the user is assembling a single genome, the best thing to do I think is to stop.
When the user is assembling thousands of individual fosmids (for example) and doesn't have the time to inspect individual assemblies, it should probably just continue through to the end however it can. ABySS doesn't currently know which is which.

I think what we're saying is that an empty histogram is currently a hard error, and it should be configurable by the user to be a warning instead.

For it to proceed without a histogram, it could either make no merges at all, or potentially the user could supply a distribution, either empirical from aligning the reads to a closely-related reference, or a mean and standard deviation. That feature doesn't yet exist, but has been requested.

**Comment by lsterck** [comment]
Hi Shaun,
yes, I'm totally comfortable with how you described the feature request! 
thx.
