### ISSUE TITLE
abyss-fatoagp outputs ultra-short contigs that are rejected during genbank submission

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#105]
It has been reported to me that:

When the sequences between stretches of "N"s is short (e.g. 1 base), `abyss-fatoagp` will generate short contigs in the output AGP file that are rejected during submission to genbank.   The suggested solution is to add a new minimum contig length parameter and mask scaftigs shorter than this threshold with "N"s before splitting to AGP.

**Comment by sjackman** [comment]
> When the sequences between stretches of "N"s is short (e.g. 1 base)

Although this situation is possible, it's definitely unexpected. I believe it work require PathConsensus merging four alleles into a single consensus, like so:

````
AAAAAAA
AACACAA
AAGAGAA
AATATAA
```
and yielding the consensus
```
AANANAA
```

I'd love to see an example if this came up in the real world.

**Comment by sjackman** [comment]
`abyss-fatoagp` has the option `-s` which defaults to 200 bp to specify the minimum *scaffold* length, but does not have a corresponding option for the minimum *contig* length.

**Comment by sjackman** [comment]
A contig of length *k* between gaps of *N*s that is less than 200 bp would result in the same situation.

**Comment by benvvalk** [comment]
> I'd love to see an example if this came up in the real world.

Greg Taylor has some (he's the one who asked for the fix) :-)

I'm working on a patch right now.

**Comment by sjackman** [comment]
Do you know whether it was due to the PathConsensus consensus sequence issue or the k-mer-sized-contig issue?

**Comment by benvvalk** [comment]
@sjackman Greg was reporting contigs of length 1 between consensus codes, so it is probably PathConsensus.

**Comment by benvvalk** [comment]
I pushed a fix to abyss-dev/develop so that I can include it in the next release.

In the meantime I will send Greg a copy of the script for testing.

**Comment by benvvalk** [comment]
@sjackman Thanks for your help, btw!
