### ISSUE TITLE
Sealer parameter -F

### ISSUE THREAD

**Issue by Reedwarbler** [bcgsc/abyss#110]
Hi Sir/Madam, 

I am trying to use sealer to close the gaps of a draft genome. I want to know what's the meaning of:
"-F, --max-frag=N             max fragment size in base pairs [1000]" ?  
Is this the insert size? 

I have a mate-pair reads with insert size around 3000bp, read length 100bp, and the coverage around 40X, and from my understanding I set the parameters as:
"-k90 -k80 -k70 -k60 -k50 -k40 -k30  -j 10 -B 1000 -F4500 -P10" 
Does this make sense? I didn't find a very detailed explanation of the parameters, so post here and hope you can help. Thank you very much.

Best,
Chong

**Comment by benvvalk** [comment]
Hi @Reedwarbler,

Unfortunately, the `--max-frag` option has a very misleading name.  It is actually the maximum gap size to close (gaps larger than `--max-frag` will be skipped by Sealer).  Please see here for a more detailed explanation: https://github.com/bcgsc/abyss/issues/82

Increasing `--max-frag` will close more gaps, but the running time will increase exponentially as `--max-frag` increases.   It is recommended to leave it at the default value of 1000, or decrease it if your job is running too slowly.

Sealer does not require any information about your library read size, insert size, coverage, etc.   And the input read files may be specified in any order (it does not use read pairing information).

**Comment by Reedwarbler** [comment]
Thank you for the help. Will adjust the parameter accordingly.

Best,
Chong

**Comment by Reedwarbler** [comment]
Hi @benvvalk 

I try two runnings with "-F 4500" and "-F 1000" respectively. The "-F 4500" running now has finished after running for 3521 minutes, but it seems no gap is filled (the "xxx_merged.fa" is empty, and the "NNNN" remaining in the "xxx_scaffold.fa"). Any reason causes this? 

The parameters I use: "-k90 -k80 -k70 -k60 -k50 -k40 -k30 -o sealer_out -j 10 -B 1000 -F4500 -P10 ". The reads are mate-pair with insert size 3000, and we have trimmed the adapter from the reads, so some reads will be like 50bp, while the original one is 100bp. Does this matter? 

Thank you.

Best,
Chong

**Comment by benvvalk** [comment]
Hi Chong,

Could you please also provide the log output, if you have it? Without that information, it is very hard to tell what went wrong.  Sealer provides a breakdown of failure reasons (e.g. TOO_MANY_BRANCHES, NO_PATH) at the end of the iteration for each k-mer size.

Sealer generally does not work well with very small k-mer sizes (e.g. < 50bp), because the de Bruijn graph is very dense at small k.  It has an internal limit on the width of the graph search frontier (-B 1000), after which it will give up and move on to the next gap.  You can try increasing that limit (e.g. -B 5000), but the running time will be much longer.  Really, what would help the most would be longer reads (if you have them) and larger k-mer sizes.  (Larger k simplifies the de Bruijn graph.)

A couple of other common reasons for failed Sealer jobs are:
* Bloom filter is too small (i.e. Bloom filter false positive rate is too high).  Roughly speaking, Bloom filter size should be about 40GB for a human genome.
* k-mer sizes are longer than the reads (based on what you said above, doesn't seem to be the case)

**Comment by Reedwarbler** [comment]
Hi Ben,

Here is the content of the log:

Finding flanks
220318 gaps found
220292 flanks extracted

Building bloom filter
Starting K run with k = 90
Flanks inserted into k run = 220292
0 unique gaps closed for k90
No start/goal kmer: 383
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 219933
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k90 run complete
Total gaps closed so far = 0

Building bloom filter
Starting K run with k = 80
Flanks inserted into k run = 220292
0 unique gaps closed for k80
No start/goal kmer: 316
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 220000
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k80 run complete
Total gaps closed so far = 0

Building bloom filter
Starting K run with k = 70
Flanks inserted into k run = 220292
0 unique gaps closed for k70
No start/goal kmer: 240
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 220076
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k70 run complete
Total gaps closed so far = 0

Building bloom filter
Starting K run with k = 60
Flanks inserted into k run = 220292
0 unique gaps closed for k60
No start/goal kmer: 153
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 220163
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k60 run complete
Total gaps closed so far = 0

Building bloom filter
Starting K run with k = 50
Flanks inserted into k run = 220292
0 unique gaps closed for k50
No start/goal kmer: 47
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 220269
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k50 run complete
Total gaps closed so far = 0

Building bloom filter
Starting K run with k = 40
Flanks inserted into k run = 220292
0 unique gaps closed for k40
No start/goal kmer: 29
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 220287
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k40 run complete
Total gaps closed so far = 0

Building bloom filter
Starting K run with k = 30
Flanks inserted into k run = 220292
0 unique gaps closed for k30
No start/goal kmer: 14
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 220302
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Exceeded mem limit: 0
Skipped: 0
220292 flanks left
k30 run complete
Total gaps closed so far = 0

K sweep complete
Creating new scaffold with gaps closed...
New scaffold complete
Gaps closed = 0
0%

Seems like because of "Exceeded mem limit".

Best,
Chong

**Comment by benvvalk** [comment]
Hi Chong,

The main reason for failure is "too many branches" .

I just realized that you are not explicitly setting your Bloom filter size, so instead it is using the default size (500MB).  Probably what is happening is that the Bloom filter size is way too small and it is completely being filled with 1's -- which corresponds to a de Bruijn graph with every possible k-mer.

What is the size of the target genome?  If it's human, try adding "-b40G" for example (assuming that you have 40GB RAM available on the machine -- if not, use less).

**Comment by Reedwarbler** [comment]
Yes, it's human. Let me adjust the parameter and re-run. Thank you for the help.

**Comment by sjackman** [comment]
> I just realized that you are not explicitly setting your Bloom filter size, so instead it is using the default size (500MB). Probably what is happening is that the Bloom filter size is way too small and it is completely being filled with 1's -- which corresponds to a de Bruijn graph with every possible k-mer.

If the FPR exceeds some threshold perhaps it could exit with failure and print an error message.
