### ISSUE TITLE
Sealer/Konnector: make Bloom filter size (-b) a required parameter

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#111]
Using a default size 500M causes too much trouble -- users unknowingly get a Bloom filter that is way too small for their  dataset and end up with an FPR 100%. And it all goes downhill from there.  See for example #110.

**Comment by sjackman** [comment]
Additionally perhaps it could exit with failure and print an error message if the FPR exceeds some threshold, say 20%.

**Comment by sjackman** [comment]
The default size could also be changed to the total available memory of the machine (without counting swap). `abyss-pe` could get this information from `free`, or in C++ we can parse it from `/proc/meminfo`.

**Comment by benvvalk** [comment]
Yes, sounds like a good idea about the FPR threshold.

That's interesting about getting the available amount of real (non-swap) memory available.  Not sure that using all of the available memory is a good default, though -- the user could be running the job on a shared server.

**Comment by sjackman** [comment]
Yeah, there's definitely challenges. A sane default would be nice though. Perhaps the default could still be constant, but changed to a value that's appropriate for a human genome assembly.

**Comment by sjackman** [comment]
It's really nice when a program provides a sane default value for a parameter when possible.

**Comment by benvvalk** [comment]
Fixed in Sealer by 2f3b868
