### ISSUE TITLE
How to use ABySS-P on multiple machines?

### ISSUE THREAD

**Issue by zhaoletian** [bcgsc/abyss#112]
Hello,
  Everyone.
  Now I'm using ABySS to run some RNA-Seq data on the cluster which use Torque. I write a PBS script to try to run abyss-pe or ABySS-P on muliple machines. 
  My problem is how to tell hostfile to abyss-pe (or ABySS-P)?
  
> my command is : 
`abyss-pe np=16 mpirun=PATH to OPENMPI/bin/mpirun name=... k=25 in="PATH to input data"`

I use qsub-like command ask for 2 nodes, each node has 8 cores, so here I set np=16 (two nodes are listed below : -)
>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ End of output ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- Program ended at:	2016年 05月 18日 星期三 15:28:01 CST
- Measured performance (flops, aggregate/peak,  sampling interval: 0.5s):
  Node    	CPU0            	CPU1            
  ----    	----            	----            
  c14b02  	n.a./n.a.       	n.a./n.a.       
  c13b14  	n.a./n.a.       	n.a./n.a.  

The output I get is :

> 
Running on 16 processors
10: Running on host c13b14
14: Running on host c13b14
1: Running on host c13b14
2: Running on host c13b14
6: Running on host c13b14
8: Running on host c13b14
9: Running on host c13b14
12: Running on host c13b14
13: Running on host c13b14
3: Running on host c13b14
4: Running on host c13b14
5: Running on host c13b14
7: Running on host c13b14
0: Running on host c13b14
11: Running on host c13b14
15: Running on host c13b14


Why do all 16 processes run on the same node??
Thanks for advices!

**Comment by benvvalk** [comment]
Hi @zhaoletian,

Your abyss-pe command looks correct.  It is probably has more to do with your resource requests in your qsub script.  I'm not familiar with Torque (we use SGE here), but on SGE the number of MPI processes ("ranks") assigned to each machine is determined by a combination of: (i) the number of cores on the machine ("CPU slots") and the amount of memory you are requesting *per MPI process*.  So supposing your total memory on per machine was 80GB and you requested 10GB per MPI process, then SGE would actually distribute the job across two nodes.

**Comment by sjackman** [comment]
> I use qsub-like command ask for 2 nodes, each node has 8 cores, so here I set np=16 (two nodes are listed below : -)

My guess is that your machine is hyperthreaded and has 8 cores but 16 threads. Try doubling `np=16` to `np=32` and see if you get two machines.

**Comment by zhaoletian** [comment]
> My guess is that your machine is hyperthreaded and has 8 cores but 16 threads. Try doubling np=16 to np=32 and see if you get two machines.

np=32 also has the same result as before. 

I've noticed the code in `abyss-pe` here:
`# Integrate with Portable Batch System (PBS) \
ifdef PBS_JOBNAME \
name?=$(PBS_JOBNAME) \
endif \
ifdef PBS_ARRAYID \
k?=$(PBS_ARRAYID) \
endif \
ifdef PBS_NODEFILE \
NSLOTS=$(shell wc -l <$(PBS_NODEFILE)) \
ifneq ($(NSLOTS), 1) \
np?=$(NSLOTS) \
endif \
endif`


and here:
`ifdef np
	$(mpirun) -np $(np) ABYSS-P $(abyssopt) $(ABYSS_OPTIONS) -o $@ $(in) $(se)
`
Could I change the code to 
`ifdef np
	$(mpirun) -hostfile $(PBS_NODEFILE) ABYSS-P $(abyssopt) $(ABYSS_OPTIONS) -o $@ $(in) $(se)
`
?

**Comment by zhaoletian** [comment]
The problem is solved.
only use -np parameter for abyss-pe/ABYSS-P is enough to use openmpi. The problem I've met before may due to there are different types of mpi in the computer cluster I use. 
Thanks for all the help~

**Comment by sjackman** [comment]
Glad to hear that you got it working!
