### ISSUE TITLE
update abyss-pe parameter defaults for modern Illumina data 

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#113]
Shaun has proposed:

* set default `maxk` = 128
* set default `s` = 500 (or may 1000)

And one other thing I never fixed:

* set default `l` = 40, rather than `l` = `k`

**Comment by sjackman** [comment]
The equivalent default value for `bwa mem` is 30, for comparison.
```
-T INT        minimum score to output [30]
```

**Comment by benvvalk** [comment]
@sjackman good to know, thanks!

**Comment by sjackman** [comment]
I'd like to test setting the default `s` to `3*k`, which is the default value for `b`.

**Comment by sjackman** [comment]
The default value for `S` should be changed to `100-10000`

**Comment by sjackman** [comment]
I want to test disabling the bubble popping at the preunitig (ABYSS) stage and use PopBubbles instead.

**Comment by sjackman** [comment]
> The default value for S should be changed to 100-10000.

@benvvalk The release notes say `Change 'S=s' => 'S=1000-10000' (do a param sweep of 'S')`. 1000 may be too large for assemblies of smaller reads / smaller values of *k*.

**Comment by sjackman** [comment]
I just realized that `DistanceEst` of the scaffolding stage uses the `s` parameter (rather than `S`), so setting `S` to a smaller value than `s` will have no effect. So, `-S1000-10000` makes sense given that `s` is set to 1000. My gut sense would have been to bump `s` from 200 to 500 rather than 1000, but I have no data to back this up. Have you compared assemblies using `s=500` and `s=1000`?

**Comment by benvvalk** [comment]
Ah, thanks Shaun.  Good to know about `s` vs `S`.

At some point I did compare `s=500` to `s=1000`.  IIRC it was with the bullfrog assembly and `s=1000` was the better result.   And I think you said before that you tried different values of `s` for the ABySS-1.9.0 assembly of the GIAB data and found `s=1000` to be the best.

The new default param values don't work quite as well with our old stock data sets (e.g. Human BAC HS0674), but I think that's okay.  We want to optimize for recent Illumina data.

**Comment by benvvalk** [comment]
Fixed by 84cca39, 55d992d, 01a5675

**Comment by sjackman** [comment]
> And I think you said before that you tried different values of s for the ABySS-1.9.0 assembly of the GIAB data and found s=1000 to be the best.

I don't recall doing these tests. It's probably not a big difference. I'd like to do the tests when I get back to find out for sure.

**Comment by benvvalk** [comment]
Oh sorry, you're right.  We didn't test with different values of `s` on the GIAB assemblies.  (I was thinking of something else.)

And if you want to help with testing different values for `s`, I would appreciate it.
