### ISSUE TITLE
compilation error: SimpleGraph.cpp:650:28

### ISSUE THREAD

**Issue by cliu6688** [bcgsc/abyss#116]
Dear Author: 

I am having a very similar problem with the closed issue https://github.com/bcgsc/abyss/issues/103. The error message I have is: 

```
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I/home/cliu/my_apps/abyss-1.9.0 -isystem/share/apps/include/ -isystem/share/apps/include//include -isystem/share/apps/lib/openmpi/include   -I/share/apps/include/ -isystem/home/cliu/my_apps/abyss-1.9.0/boost_1_56_0 -Wall -Wextra -Wno-strict-aliasing -g -O2 -MT SimpleGraph-SimpleGraph.o -MD -MP -MF .deps/SimpleGraph-SimpleGraph.Tpo -c -o SimpleGraph-SimpleGraph.o `test -f 'SimpleGraph.cpp' || echo './'`SimpleGraph.cpp
SimpleGraph.cpp: In function 'void* worker(void*)':
SimpleGraph.cpp:650:28: error: cannot convert 'std::istream {aka std::basic_istream<char>}' to 'bool' in initialization
   bool good = (*arg.in) >> er;
                            ^~
make: *** [SimpleGraph-SimpleGraph.o] Error 1
```

I am trying to compile abyss 1.9.0. I am using gcc (GCC) 6.1.0. I have tried to change the code to 

``` c++
bool good = (bool) ((*arg.in) >> er);
```

This solves the compilation problem but later I have segmentation fault with SimpleGraph. So I suppose my solution is not correct. Your help on this is greatly appreciated. 

best, 

chang

**Comment by benvvalk** [comment]
Hi Chang,

Shaun recently noticed the same problem and made some fixes. I've included a patch below.   I've also pushed the changes to the `master` branch of the public repo, so you can just pull from there if you prefer.

[gcc-6.1.0.patch.txt](https://github.com/bcgsc/abyss/files/291643/gcc-6.1.0.patch.txt)
