### ISSUE TITLE
MPI run question && insert_length for paired-end read question

### ISSUE THREAD

**Issue by zhaoletian** [bcgsc/abyss#118]
I have generated the dry-run before the real run(see the attachment), and find only the first step calls mpirun.   `AdjList` reports 'st9bad_alloc' and fails to work. I search on the Internet and learn that it may be caused by memory leak. So can I understand this event as only first step can use multiple nodes as well as all the memory, and then `abyss` will run only on a single node, therefore only can use that single node's memory?
[Uploading abyss-pe_steps.txt…]()

Besides above, another question:
The paired-end reads have the insert length information. I didn't find there is any parameters in abyss o tell the assembler use this information. Why?

**Comment by benvvalk** [comment]
Hi @zhaoletian,

Yes, you are correct -- only the first step uses MPI, and then the remained of the `abyss-pe` pipeline runs on a single node (many of the downstream programs are multithreaded).

Yes, `AdjList` is running out of memory.  I don't think it is a memory leak, but it does require significant memory for its data structures (hash table and suffix array).  Unfortunately, there is not much you can do besides run the assembly on a machine with more RAM.  If you don't have a machine with more RAM, you may be able to work around the memory limitation by adding the parameter `m=<k-1>` (replace <k-1> with your k-mer size and subtract one). to your `abyss-pe` command.  By default `AdjList` will try to find overlaps as small as 50bp, but setting `m=<k-1>` will cause it not to build the suffix array data structure used to find smaller overlaps.

ABySS estimates the insert size distribution by aligning the reads to the contigs -- read pairs that align to the same contig provide information about the distance between the pairs.

**Comment by zhaoletian** [comment]
@benvvalk Thanks for your reply! `m=<k-1>` works, and I move the left non MPI steps after `ABYSS-P` to another machine which has larger memory and finally gets the result.

**Comment by benvvalk** [comment]
@zhaoletian Excellent, glad to hear.
