### ISSUE TITLE
Optimize abyss-scaffold n parameter

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#122]
`abyss-scaffold` can optimize the `S` parameter if you set `S=200-20000`. This behaviour is not currently the default and should be.
The same optimization feature should be implemented for the `N` parameter as well, and enabled by default.

**Comment by sjackman** [comment]
I'd still like to implement this feature.

**Comment by sjackman** [comment]
Shh stale bot

**Comment by lsterck** [comment]
Would indeed be a nice addition.
I'm however wondering if ABySS does not do this already? (version 2.0.2) I see in my output that it tries scaffolding with a couple of diff values for contig length and then decide to go for the one that is most 'optimal' (== gives the best contiguity and/or N50) ?

**Comment by sjackman** [comment]
It already optimizes `S` but does not yet optimize `N`.
https://github.com/bcgsc/abyss/blob/578d094ba065e6c950cd0e2cb04c45c5b95f83c8/bin/abyss-pe#L313

**Comment by lsterck** [comment]
no, indeed.
would be extremely useful addition I feel. (and not only because of an N-related issue i have with one of my recent abyss assemblies ;) )

**Comment by sjackman** [comment]
I've had to manually optimize `N` too many times to count. I'll see if I can find next week for this task.

**Comment by benvvalk** [comment]
@sjackman is working on this

**Comment by sjackman** [comment]
I've completed this work. It will be included in the next release of ABySS.
