### ISSUE TITLE
abyss-pe is linked to make

### ISSUE THREAD

**Issue by mictadlo** [bcgsc/abyss#123]
Hi 
abyss-pe is linked to make. 

    # abyss-pe -h
    Usage: make [options] [target] ...

I install it from github in the following way:

    ./autogen.sh
    ./configure
    make
    make install

What did go wrong?

Thank you in advance.

Mic

**Comment by sjackman** [comment]
`abyss-pe` is a Makefile script. Try `abyss-pe help`
