### ISSUE TITLE
Bits or bytes? B: Bloom filter size (e.g. "100M")

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#126]
> If no unit is specified, bytes are assumed.
> …
> B: Bloom filter size (e.g. "100M")

@benvvalk Could you please clarify in the second line whether the Bloom filter size `B` is specified in bits or bytes?

> `-b  --bloom-size=N         Bloom filter memory size with unit suffix 'k', 'M', or 'G' [required] `

Also here.

**Comment by sjackman** [comment]
> If no unit is specified, bytes are assumed.

Can you give in the README the formula to calculate memory usage based on `B` and `H`?
I specified B=100G H=1 and the memory usage is 25 GB, which is not what I expected.

**Comment by benvvalk** [comment]
Okay, I updated `README.md` / `--help` and pushed to public/master.

For the record, the `B` param specifies the overall memory budget for the Bloom filter assembly step (`abyss-bloom-dbg`) in _bytes_ (not bits).  Internally, the memory allocated with `B` is split equally across (`kc` + 1) Bloom filters, where `kc` Bloom filters are allocated for the cascading Bloom filter and one additional Bloom filter is allocated to track k-mers that have been included in the contigs during the course of the assembly.

In your particular case, the memory usage shown in `top` should be roughly 100 gigabytes for the duration of the program.  My only guess as to why you saw 25 GB is that it was early in the program's execution and it was still allocating memory.

**Comment by sjackman** [comment]
Thanks for the explanation, Ben.
