### ISSUE TITLE
abyss-bloom-dbg: Disable buffering on stdout

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#128]
The progress reports come in fits and bursts, I suspect due to buffering of stdout. To set stdout to line-buffering, use:

``` c++
setvbuf(stdout, NULL, _IOLBF, 0);
```

See https://github.com/bcgsc/abyss/blob/master/ABYSS/abyss.cc#L127

**Comment by benvvalk** [comment]
Not sure about this.  `abyss-bloom-dbg` does all of its logging to STDERR, which is never buffered as far as I understand.  Its probably something else causing the chunkiness.

**Comment by sjackman** [comment]
Hmm. That's confusing. You're right, stderr is line buffered. I'll do some troubleshooting.

**Comment by benvvalk** [comment]
Cloning this issue because it is probably related to system configuration, rather than a problem with the software.
