### ISSUE TITLE
option -c is not recognised for bloom filter

### ISSUE THREAD

**Issue by KamilSJaron** [bcgsc/abyss#132]
Hello, 

I have compiled AbySS 2.0.0 on our computational server (without obvious problem). Some of modules were working (`abyss-pe name=Tge_abyss_k83 k=83 lib=<...>` made an assembly). However, when I tried to use bloom filter:

```sh
abyss-pe name=Tge_abyss_k83 k=83 lib=<...> B=20G H=4 c=3 v=-v
```
it returned

```
abyss-bloom-dbg -k83 -q15 -c3 -v -b26G -H4 -j2  Tge_R1t_is_225.fq.gz Tge_R2t_is_225.fq.gz Tge_R1t_is_350.fq.gz Tge_R2t_is_350.fq.gz Tge_R1t_is_550.fq.gz Tge_R2t_is_550.fq.gz Tge_R1t_is_700.fq.gz Tge_R2t_is_700.fq.gz  > Tge_abyss_k83-1.fa
abyss-bloom-dbg: invalid option -- 'c'
abyss-bloom-dbg: invalid option -- '3'
Try `abyss-bloom-dbg --help' for more information.
make: *** [Tge_abyss_k83-1.fa] Error 1
```
when I deleted `-c`, it runs, not sure how reasonable result I will get out of it....

(probably unrelated) I have also some troubles with parameter np=<number_of_threads>, when np is specified, I am confronted with following message

```
/bin/bash: /mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/bin/mpirun.lsf: No such file or directory
```

However, I do not think that this will be a problem of AbySS, it is more problem of configuration of our server... I mentioned it just because it might be related to previous problem.

**Comment by benvvalk** [comment]
Hi @KamilSJaron,

You need to use `kc=3` instead of `c=3`.

I've changed the name of that parameter since the prelease version that was evaluated in the ABySS 2.0 paper on BioRxiv. Other than that, the command lines in the paper should work fine.  Sorry for the confusion.

**Comment by benvvalk** [comment]
I agree about your other error.  It is probably a server configuration issue.  Using `np=<num_mpi_processes>` triggers an MPI assembly.  If you want to specify number of threads for Bloom filter assembly, use `j=<num_threads>` instead.

**Comment by KamilSJaron** [comment]
Ah, sorry, I have not noticed this change. Works like charm now (both multithreading and kc)! Thanks.

**Comment by benvvalk** [comment]
Welcome!
