### ISSUE TITLE
make check fails with clang

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#133]
```
clang++ -DHAVE_CONFIG_H -I. -I..  -DGTEST_USE_OWN_TR1_TUPLE=0 -I.. -I../lib/gtest-1.7.0/include -I/private/tmp/abyss-20161025-32376-1ryvcau/abyss-2.0.2      -isystem/private/tmp/abyss-20161025-32376-1ryvcau/abyss-2.0.2/boost_1_56_0 -Wall -Wextra -D_THREAD_SAFE -pthread -Wno-error -g -O2 -c -o Common/KmerTest.o Common/KmerTest.cpp
In file included from Common/BitUtilTest.cpp:2:
In file included from ../lib/gtest-1.7.0/include/gtest/gtest.h:58:
In file included from ../lib/gtest-1.7.0/include/gtest/internal/gtest-internal.h:40:
../lib/gtest-1.7.0/include/gtest/internal/gtest-port.h:594:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^
In file included from Common/KmerTest.cpp:2:
In file included from ../lib/gtest-1.7.0/include/gtest/gtest.h:58:
In file included from ../lib/gtest-1.7.0/include/gtest/internal/gtest-internal.h:40:
```

See for example https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/6210/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_science_abyss/

**Comment by benvvalk** [comment]
*sigh*

**Comment by sjackman** [comment]
I haven't tested `make check` with GCC 6. It may reproduce the same issue. It may help to update the bundled version of `gtest` to 1.8.0.

**Comment by benvvalk** [comment]
I think I know what I did wrong.   I am unconditionally disabling GTest's own `tr1::tuple` implementation with `-DGTEST_USE_OWN_TR1_TUPLE=0`, whereas it needs to be set based on the existence/non-existence of `tr1::tuple` in the C++ standard library.

I tested `-DGTEST_USE_OWN_TR1_TUPLE=0` with gcc 4.4 and gcc 6 on Linux, and also our CircleCI tested that for clang on Linux as well.  But I guess it doesn't work for clang on Mac.

**Comment by sjackman** [comment]
Sounds about right. I can confirm that I can reproduce this issue on my machine.
```
In file included from ../../lib/gtest-1.7.0/include/gtest/internal/gtest-internal.h:40:
../../lib/gtest-1.7.0/include/gtest/internal/gtest-port.h:594:13: fatal error: 
      'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^
1 error generated.
```
