### ISSUE TITLE
abyss-map cannot handle multi-line fasta

### ISSUE THREAD

**Issue by jts** [bcgsc/abyss#14]
I'm trying to use abyss-map with a multi-line fasta file (sequences are broken across multiple lines). Unfortunately FastaIndex assumes that the sequence are on a single line, so the assertion on line 83 trips. Would it be possible to support multi-line fasta?

**Comment by dbrowneup** [comment]
I know this is pretty old, but considering it is still open, thought I'd leave my 2 cents here. You could very easily convert a multi-line fasta to single-line fasta with awk, as follows:

`$ awk '/^>/{print (NR==1)?$0:"n"$0;next}{printf "%s", $0}END{print ""}' InputFastaFile.fasta > OutputFastaFile.fasta`

Source: http://itrylinux.com/use-sed-or-awk-to-remove-newline-breaks-from-fasta-file/

Thus abyss-map could accept multi-line fasta files, then quickly convert them to single-line prior to mapping.

**Comment by sjackman** [comment]
I agree it's a bit dumb that `abyss-map` can't read multiline FASTA files, but I'm afraid it's not a priority at the moment to fix it. Sorry. =/ Perhaps take it as an opportunity to obliterate multiline FASTA files once and for all? They are arguably more brain dead than the tools that can't read them. I use Heng Li's `seqtk seq` to remove the line breaks.
