### ISSUE TITLE
orientation of mate-pairs

### ISSUE THREAD

**Issue by KamilSJaron** [bcgsc/abyss#144]
Hello, I am very happy with set of contigs produced by abyss (N50 ~ 2-5k, 2-5M of contigs depending on species). In my pipeline I scaffold contigs with BESST which produces assembly with really decent continuity (N50 ~ 170k) and completeness (BUSCO: 92% of complete genes, 1.7% fragmented).

However, abyss scaffolding is a disaster (N50 increases by less than 100) and my personal guess is that abyss expect mate pairs in FR orientation, whereas I provide mate pairs in RF orientation and scaffolding happened only though PE contamination of mate pairs. 

Therefore I wanted to ask, what orientation of mate pairs is expected? And maybe suggest to add this information to manual.

All genomes are 1.3G. Insects. Input data: cca 60x HiSeq pair-end reads and cca 2x of mate pairs (3k, 5k). This is how I run abyss, if it is relevant (and if you would like to suggest some awesome trick how to improve it):

```
abyss-pe name=Tge_abyss_k87 j=32 k=87 lib='pea peb pec ped pef' mp='mpa mpb' <read_specification> B=26G H=4 ks=3 v=-v
```

**Comment by benvvalk** [comment]
@KamilSJaron:

ABySS tries to automatically determine the orientation of the mate pair reads, based on alignments of the mate pairs to the assembly.  You can see the decision it makes by looking for a line like this in the log output:
```
The library pe600-6.hist is oriented forward-reverse (FR)
```

If you want to force reverse-forward orientation for your mate pair libraries, you can add the following to your abyss-pe command line:
```
mpa_de=--rf mpab_de=--rf
```

The `de` is short for `DistanceEst` and allows you to specify extra options to that program.

Of course, the reason the scaffolding is performing poorly for some other reason.  For scaffolding, the most important parameters are `l` (minimum alignment length) and `N` (minimum number of aligned pairs).  I may be able to help further if you can show me the log output from your abyss-pe run.

**Comment by KamilSJaron** [comment]
Thank you, I found it in err log, AbySS indeed recognises mate pairs in correct orientation. Logs are pretty big to upload here, I have sent you email with link to ftp server (uploading now).

**Comment by sjackman** [comment]
To troubleshoot, I'd suggest taking the `abyss-scaffold` command line from your log and executing that command with different values of `-n`. Trying setting `-s` to `-s500-10000` and trying different values of `n` from 1 to 100 (say). It should run pretty fast, so you can do it in a for loop.
```sh
for n in `seq 1 100`; do abyss-scaffold -s500-10000 -n$n …; done
```
Then check the logs and find the value of `n` that maximizes `N50`. Then rerun the `abyss-pe` pipeline using that value for the parameter `abyss-pe N=…`.

**Comment by benvvalk** [comment]
@sjackman  Thank you, Shaun.  I also examined @KamilSJaron's logs and sent him some advice by e-mail.  He is doing a Bloom filter assembly and made a typo when setting `kc`, so his assembly was defaulting to `kc=2`.  Since his unitig N50 was quite low, I recommended that he conduct sweeps for both `k` and `kc` to get better results.

**Comment by sjackman** [comment]
I'll close this issue for now. Feel free to follow up, Kamil.

**Comment by KamilSJaron** [comment]
Thanks both of you. I will need bit of time to investigate. Cheers!
