### ISSUE TITLE
fatoagp

### ISSUE THREAD

**Issue by ivyhzau** [bcgsc/abyss#145]
how to get agp file by abyss-fatoagp. Thanks for your help

**Comment by sjackman** [comment]
```sh
abyss-fatoagp -f contigs.fa scaffolds.fa >contigs.agp
```
Read the file `scaffolds.fa` and produce the FASTA file `contigs.fa` and AGP file `contigs.agp`

**Comment by benvvalk** [comment]
Thank you, Shaun.
