### ISSUE TITLE
Abyss appears to struggle with read orientation when processing multiple displacement amplification data (i.e. single cell)

### ISSUE THREAD

**Issue by michaelbarton** [bcgsc/abyss#146]
I've been benchmarking abyss on single cell data and got the following error:

```
abyss-map   -j2 -l40    reads.fq.gz genome-3.fa \
        |abyss-fixmate   -l40  -h genome-3.hist \
        |sort -snk3 -k4 \
        |DistanceEst   -j2 -k64 -l40 -s1000 -n10   -o genome-3.dist genome-3.hist
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Mateless         0
Unaligned    21845  0.874%
Singleton    43532  1.74%
FR           68376  2.74%
RF               7  0.00028%
FF          178491  7.14%
Different  2187749  87.5%
Total      2500000
abyss-fixmate: error: The mate pairs of this library are oriented forward-forward (FF), which is not supported by ABySS.
/usr/local/bin/abyss-pe:559: recipe for target 'genome-3.dist' failed
make: *** [genome-3.dist] Error 1
make: *** Deleting file 'genome-3.dist'
```

I assume this is because either the quality of the data is very low at the ends of the reads, or perhaps MDA is creating chimeric DNA? This is just an uninformed guess on my part however.

The command I used is:
```
abyss-pe name=genome k=64 in=...
```

**Comment by sjackman** [comment]
ABySS stopping in this situation is intentional. If 2.6 times the number of reads are oriented FF than FR, then the library prep has issues that ABySS will not be able to handle. Better to stop and tell the user. You could omit the paired-end information by using `se= reads.fq.gz` rather than `in= reads.fq.gz`.

I'm not terribly familiar with single-cell MDA, so I can't say whether this quality is typical of MDA. Do other MDA libraries have this FF orientation issue? If not, I'd recommend against using this library for benchmarking.

It'd be good to confirm with an orthogonal pipeline such as aligning the reads to a reference using BWA that the reads are in fact oriented largely FF as ABySS reports.

**Comment by michaelbarton** [comment]
Thanks Shaun. This is a dataset that some assemblers struggle with, but others are able to complete. I'm not sure of the exact issues in the data, I will investigate further.

**Comment by sjackman** [comment]
ABySS will complete if you use `se=reads.fq.gz`. The paired-end info in the library is suspect, and perhaps should be ignored.

**Comment by michaelbarton** [comment]
This is using the abyss biobox image, and for other datasets it works:

https://github.com/bioboxes/abyss/blob/master/image/bin/assemble.sh#L12

**Comment by sjackman** [comment]
This data set is effectively unpaired, as far as ABySS is concerned, so that command won't work because you're telling ABySS that the data set is paired (by using `in=` rather than `se=`).

**Comment by michaelbarton** [comment]
Thanks Shaun.

> This data set is effectively unpaired, as far as ABySS is concerned,

The data was generated from a paired sequencing library at the JGI, but
sequencing, multiple displacement amplification or other unidentified root
causes appear to be causing the issue.

> so that command won't work because you're telling ABySS that the data set is
> paired (by using `in=` rather than `se=`).

Bioboxes currently only supports using paired-end interleaved libraries in the
input format for all assembler. I think I would not prefer not to change the
abyss biobox to use `se=` as I assume this would likely result in worse
performance for all libraries . The possible solution would be to update the
biobox assemble script to revert to using `se=` if identified problems with
using the `in=` flag. This would likely have a low return on the investment,
given that there only appears to be one library causing this issue, rather
than a systematic problem.

**Comment by sjackman** [comment]
Being that this library is rather weird, I don't feel that it's a good choice for benchmarking. It'd be good to confirm that it's FF-oriented using BWA to align to a reference.
