### ISSUE TITLE
Miss ABYSS-P after the compiling

### ISSUE THREAD

**Issue by zhouqiansolab** [bcgsc/abyss#150]
Hi,
 I downloaded the source code from GitHub and installed it by the following steps.
```sh
./autogen.sh 
./configure --prefix=$HOME --enable-maxk=224  --without-sparsehash
make 
make install
```
At last I got many executable files in ~/bin, but no ABYSS-P. Shaun Jackman recommended using Linuxbrew to install ABySS, but my cluster is unable to connect the internet. I need to compile it locally.

Could you have any idea about this? Thank you.

**Comment by zhouqiansolab** [comment]
I have figured out it. 
The "lib" and "include" directories of openmpi should be included in same directory, for example openmpi_zhou. Then install with --with-mpi=openmpi_zhou/.

I got clues from this site  http://www.cnblogs.com/yumtaoist/p/4250442.html .

Anyway, thank you!

**Comment by zhouqiansolab** [comment]
I have figured it out !

The "lib" and "include" directories of openmpi should be included in same directory, for example openmpi_zhou. Then install with --with-mpi=openmpi_zhou/.

I got clues from this site http://www.cnblogs.com/yumtaoist/p/4250442.html .

Anyway, thank you!

**Comment by sjackman** [comment]
Glad to hear that you got it figured out.
