### ISSUE TITLE
DistanceEst: DistanceEst.cpp:619: int main(int, char**): Assertion `in' failed.

### ISSUE THREAD

**Issue by rafelafrance** [bcgsc/abyss#151]
I'm having some trouble running abyss on certain data. I am new to all of this assembly stuff so there may be problems with what I'm feeding into abyss but the error message is not really helpful and looking at the DistanceEst.cpp source is not shedding any light either.

There is no obvious log file produced so I'm attaching the screen output (it's short) and an input file that fails as described in the title.

The command is:

```
abyss-pe E=0 k=64 name=error in=paired_ends.fasta.txt
```

[screen_output.txt](https://github.com/bcgsc/abyss/files/906199/screen_output.txt)
[paired_ends.fasta.txt](https://github.com/bcgsc/abyss/files/906200/paired_ends.fasta.txt)

**Comment by benvvalk** [comment]
Hi @rafelafrance,

You are not specifying your input files correctly.

See https://github.com/bcgsc/abyss#assemble-a-small-synthetic-data-set in the ABySS README.md for an example of how to use `in=...`.   Or see the abyss-pe.1 man page in the doc subdirectory.

**Comment by rafelafrance** [comment]
Thank you for your prompt reply. 

I may be confused but, I started from that format. The files I gave you were simplified to ease reproducing the error. Originally, I ran:
```
abyss-pe E=0 k=64 name='error' in='paired_end_1.fasta paired_end_2.fasta'
```
I just concatenated the two files for ease of use and put the .txt suffix on so that I could upload it.

**Comment by sjackman** [comment]
Hi, Rafe. I just ran
```sh
abyss-pe E=0 k=64 name='error' in='end_bad_1.fasta end_bad_2.fasta end_good_1.fasta end_good_2.fasta'
```
and then assembly succeeded.
```
❯❯❯ abyss-fac error-scaffolds.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
47	13	4	505	541	693	2123	1063	2123	10341	error-scaffolds.fa
```
Can you try the above command?

**Comment by sjackman** [comment]
I can confirm that
```sh
abyss-pe E=0 k=64 name=error in=paired_ends.fasta
```
with the same error that you saw above.

**Comment by sjackman** [comment]
```
Mateless     3  2.14%
Unaligned    0
Singleton    9  6.43%
FR         128  91.4%
RF           0
FF           0
Different    0
Total      140
gunzip -c error-3.sam.gz \
|DistanceEst   -j2 -k64 -l40 -s1000 -n10   -o error-3.dist error-3.hist
DistanceEst: DistanceEst.cpp:619: int main(int, char**): Assertion `in' failed.
/bin/bash: line 1:  3631 Done                    gunzip -c error-3.sam.gz
      3632 Aborted                 (core dumped) | DistanceEst -j2 -k64 -l40 -s1000 -n10 -o error-3.dist error-3.hist
/opt/abyss/bin/abyss-pe:551: recipe for target 'error-3.dist' failed
make: *** [error-3.dist] Error 134
make: *** Deleting file 'error-3.dist'
```
DistanceEst is failing because none of the read pairs map with the two reads on different contigs. The error message is admittedly terrible. You should have a file named `error-unitigs.fa`, which in this case is the final assembly.
```
❯❯❯ abyss-fac error-unitigs.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
3	1	1	1359	1359	1359	1359	1359	1359	1359	error-unitigs.fa
```

**Comment by rafelafrance** [comment]
Thanks
