### ISSUE TITLE
Use of named pipes

### ISSUE THREAD

**Issue by TomNash** [bcgsc/abyss#153]
Apologies if this is too general of a question, but we're looking at using named pipes (FIFOs) for some I/O reduction. Are these supported by ABySS? We're in the early stages of development and this is more of a hypothetical at this point.

**Comment by benvvalk** [comment]
@TomNash:

Most of the programs that make up the ABySS pipeline are streaming (read once, write once), although there are some exceptions. 

However, ABySS writes out a lot of intermediate files (one for each step of the assembly pipeline), and I am not aware of any easy tricks to replace all of those intermediate files with FIFOs.

If you want to better understand the mechanics of the ABySS, please have a look at `bin/abyss-pe`, which is the Makefile that runs the pipeline.   That is also most likely where you would implement any hacks regarding FIFOs.

**Comment by sjackman** [comment]
The files passed as input to ABySS are read multiple (precisely three) times: once to assemble the unitigs, the contigs, and the scaffolds. Each step streams the reads, as Ben mentioned, but it must be possible to read those files multiple times. My best suggestion is to use a local solid state disk drive or a local RAM disk to store the reads and intermediate files.

**Comment by TomNash** [comment]
Thanks guys

**Comment by sjackman** [comment]
No problem, Tom.
