### ISSUE TITLE
abyss-sealer keeps going after closing all gaps

### ISSUE THREAD

**Issue by notestaff** [bcgsc/abyss#154]
When specifying multiple kmer sizes, if kmer sizes listed earlier have resulted in the closing of all gaps, abyss-sealer keeps going with the remaining kmer sizes.  Is there a reason?

**Comment by notestaff** [comment]
Also, if there were too many paths at some kmer size, there'll be too many paths at smaller kmer sizes.  (If the flanking sequences have not changed.)

**Comment by benvvalk** [comment]
@notestaff You are right, that is a bit silly (continuing with smaller k-mer sizes when all gaps have already been closed).  Thanks for reporting the bug.  It will probably be a while before I get around to fixing it -- I am pretty busy for the next few weeks at least.  (If you like, you can give it a try and submit a pull request.)

What you say about the "too many paths" is true.   Implementation-wise, it would require some heavy refactoring to pass outcomes for specific pairs between different k-mer runs.  My feeling is that it is probably not worth the effort.

**Comment by notestaff** [comment]
Ok, thanks, I might try to fix these myself.  Your code is remarkably clear, esp. for a research project :)

**Comment by benvvalk** [comment]
Thanks for the compliment!

Credit goes to @dpaulino for the nice job on the Sealer source code. (I wrote the supporting bidirectional graph search routine (`connectPairs`), which is also used by the `konnector` program (read merging tool)).
