### ISSUE TITLE
FastaReader: don't trim lowercase bases by default

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#158]
By default lower-case bases are trimmed from the beginning/end of sequences.

If the user has lower case bases in their input reads/contigs (for whatever reason), surprising behaviour can result such as the removal of entire sequences that happen to be in lower case.

This issue was pointed out by someone using Sealer.

**Comment by sjackman** [comment]
I endorse this change. The historical purpose of this feature was for 454 reads, which masked the adapter/poor-quality sequence at the ends of reads with lower case nucleotides.

**Comment by benvvalk** [comment]
Thanks, Shaun.  I didn't know what the original application was, so that's very helpful.
