### ISSUE TITLE
build error in ABYSS 1.5.2

### ISSUE THREAD

**Issue by cd-ccmb** [bcgsc/abyss#159]
I am getting the following error while building ABYSS1.5.2 (needed for transabyss) using boost1.56.0. I have tried several boost libraries both higher and lower once but the same error is coming.

```
make[2]: Entering directory '/home/rka/Tools/abyss-1.5.2/Overlap'
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I../DataLayer -I/home/rka/Tools/abyss-1.5.2 -isystem/home/rka/Tools/abyss-1.5.2/boost_1_56_0 -isystem/usr/local/bin/include  -I/home/rka/Tools/sparsehash-master -isystem/home/rka/Tools/abyss-1.5.2/boost_1_55_0 -Wall -Wextra -Werror -g -O2 -MT Overlap-Overlap.o -MD -MP -MF .deps/Overlap-Overlap.Tpo -c -o Overlap-Overlap.o `test -f 'Overlap.cpp' || echo './'`Overlap.cpp
Overlap.cpp: In function ‘int main(int, char**)’:
Overlap.cpp:441:5: error: no match for ‘operator!’ (operand type is ‘std::_Bind_helper<false, bool (&)(const ContigGraph<DirectedGraph<ContigProperties, Distance> >&, ContigGraph<DirectedGraph<NoProperty, Overlap> >&, std::pair<ContigNode, ContigNode>), const boost::reference_wrapper<const ContigGraph<DirectedGraph<ContigProperties, Distance> > >, const boost::reference_wrapper<ContigGraph<DirectedGraph<NoProperty, Overlap> > >, const boost::lambda::lambda_functor<boost::lambda::placeholder<1> >&>::type {aka std::_Bind<bool (*(boost::reference_wrapper<const ContigGraph<DirectedGraph<ContigProperties, Distance> > >, boost::reference_wrapper<ContigGraph<DirectedGraph<NoProperty, Overlap> > >, boost::lambda::lambda_functor<boost::lambda::placeholder<1> >))(const ContigGraph<DirectedGraph<ContigProperties, Distance> >&, ContigGraph<DirectedGraph<NoProperty, Overlap> >&, std::pair<ContigNode, ContigNode>)>}’)
     !bind(checkEdgeForOverlap,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      boost::cref(graph), boost::ref(scaffoldGraph),
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      _1),
      ~~~
Overlap.cpp:441:5: note: candidate: operator!(bool) <built-in>
Overlap.cpp:441:5: note:   no known conversion for argument 1 from ‘std::_Bind_helper<false, bool (&)(const ContigGraph<DirectedGraph<ContigProperties, Distance> >&, ContigGraph<DirectedGraph<NoProperty, Overlap> >&, std::pair<ContigNode, ContigNode>), const boost::reference_wrapper<const ContigGraph<DirectedGraph<ContigProperties, Distance> > >, const boost::reference_wrapper<ContigGraph<DirectedGraph<NoProperty, Overlap> > >, const boost::lambda::lambda_functor<boost::lambda::placeholder<1> >&>::type {aka std::_Bind<bool (*(boost::reference_wrapper<const ContigGraph<DirectedGraph<ContigProperties, Distance> > >, boost::reference_wrapper<ContigGraph<DirectedGraph<NoProperty, Overlap> > >, boost::lambda::lambda_functor<boost::lambda::placeholder<1> >))(const ContigGraph<DirectedGraph<ContigProperties, Distance> >&, ContigGraph<DirectedGraph<NoProperty, Overlap> >&, std::pair<ContigNode, ContigNode>)>}’ to ‘bool’
In file included from /home/rka/Tools/abyss-1.5.2/boost_1_56_0/boost/lambda/lambda.hpp:26:0,
                 from Overlap.cpp:19:
/home/rka/Tools/abyss-1.5.2/boost_1_56_0/boost/lambda/detail/operators.hpp:339:1: note: candidate: template<class Arg> const boost::lambda::lambda_functor<boost::lambda::lambda_functor_base<boost::lambda::logical_action<boost::lambda::not_action>, boost::tuples::tuple<boost::lambda::lambda_functor<T> > > > boost::lambda::operator!(const boost::lambda::lambda_functor<T>&)
 BOOST_LAMBDA_UE(operator!, logical_action<not_action>)
 ^
/home/rka/Tools/abyss-1.5.2/boost_1_56_0/boost/lambda/detail/operators.hpp:339:1: note:   template argument deduction/substitution failed:
Overlap.cpp:443:8: note:   ‘std::_Bind_helper<false, bool (&)(const ContigGraph<DirectedGraph<ContigProperties, Distance> >&, ContigGraph<DirectedGraph<NoProperty, Overlap> >&, std::pair<ContigNode, ContigNode>), const boost::reference_wrapper<const ContigGraph<DirectedGraph<ContigProperties, Distance> > >, const boost::reference_wrapper<ContigGraph<DirectedGraph<NoProperty, Overlap> > >, const boost::lambda::lambda_functor<boost::lambda::placeholder<1> >&>::type {aka std::_Bind<bool (*(boost::reference_wrapper<const ContigGraph<DirectedGraph<ContigProperties, Distance> > >, boost::reference_wrapper<ContigGraph<DirectedGraph<NoProperty, Overlap> > >, boost::lambda::lambda_functor<boost::lambda::placeholder<1> >))(const ContigGraph<DirectedGraph<ContigProperties, Distance> >&, ContigGraph<DirectedGraph<NoProperty, Overlap> >&, std::pair<ContigNode, ContigNode>)>}’ is not derived from ‘const boost::lambda::lambda_functor<T>’
      _1),
        ^
Makefile:382: recipe for target 'Overlap-Overlap.o' failed
make[2]: *** [Overlap-Overlap.o] Error 1
make[2]: Leaving directory '/home/rka/Tools/abyss-1.5.2/Overlap'
Makefile:456: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rka/Tools/abyss-1.5.2'
Makefile:376: recipe for target 'all' failed
make: *** [all] Error 2
```

Thanks

**Comment by benvvalk** [comment]
My best guess is that ABySS is not finding the Boost library that you installed, and is falling back on the system-wide installation of Boost, which happens to be too old. 

I would recommend explicitly specifying the location of Boost at the `configure` step with `./configure --with-boost=<boost_path>`, where `<boost_path>` is the path to unpacked boost source tarball.  ABySS will then look for the `include` subdirectory underneath `<boost_path>` to find the Boost library files.

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Consider installing ABySS using Linuxbrew.
Instructions to Install Linuxbrew are found at http://linuxbrew.sh
Then run…
```sh
brew install homebrew/science/abyss
```

**Comment by cd-ccmb** [comment]
I have tried ./configure --with-boost=<boost_path> but it didnt work . I will try Linux brew once though I am not sure how to go about it..!

**Comment by mbargull** [comment]
@cd-ccmb for `1.5.2` you'll need to use `--with-boost=<boost_path>/include`. For later versions `--with-boost=<boost_path>` is fine.

**Comment by mspiffy** [comment]
Hi Ben, tried linking 1.5.2 against Boost 1.5.0 and 1.5.5 while checking the generated include paths and overriding system-wide 1.6x on Debian 9; it still excepts as cd-ccmb initially reported in this issue. The current ABySS builds no issues.  

Just tried to roll back the graph change to add diameter in [filtered_graph](https://github.com/boostorg/graph/commit/50bfd8dad0ded59e3335d7f577549c968b371a80#diff-a5c77d1d8ece9123864fd9c09741588f) in Boost 1.66 for the try of it but more graph things seem to depend on it by now. 

The cleanest solution  would be to fix trans-abyss for which the ABySS 1.5.2 building is the use-case. There apparently is already an issue open on it [there](https://github.com/bcgsc/transabyss/issues/7). I volunteer to add instrumentation and some debugging ..

**Comment by sjackman** [comment]
@benvvalk Would it be worth doing a point release of 1.5.x to build with a current version of Boost?

**Comment by schloegl** [comment]
This patch fixed the compilation problem on debian9 for me
`
diff --git a/include/boost/graph/reverse_graph.hpp b/include/boost/graph/reverse_graph.hpp
index 24eb1c7c..56ffe72d 100644
--- a/include/boost/graph/reverse_graph.hpp
+++ b/include/boost/graph/reverse_graph.hpp
@@ -322,6 +322,13 @@ target(const detail::reverse_graph_edge_descriptor<Edge>& e, const reverse_graph
     return source(e.underlying_descx, g.m_g);
 }
 
+template <class BidirectionalGraph, class GRef>
+inline typename graph_traits<BidirectionalGraph>::degree_size_type
+degree(const typename graph_traits<BidirectionalGraph>::vertex_descriptor u,
+          const reverse_graph<BidirectionalGraph,GRef>& g)
+{
+    return degree(u, g.m_g);
+}
 
 namespace detail {
 
diff --git a/test/reverse_graph_cc.cpp b/test/reverse_graph_cc.cpp
index eef53bf9..145eb306 100644
--- a/test/reverse_graph_cc.cpp
+++ b/test/reverse_graph_cc.cpp
@@ -25,6 +25,7 @@ int main(int,char*[])
     > AdjList;
     typedef reverse_graph<AdjList> Graph;
     BOOST_CONCEPT_ASSERT(( VertexListGraphConcept<Graph> ));
+    BOOST_CONCEPT_ASSERT(( BidirectionalGraphConcept<Graph> ));
     typedef graph_traits<Graph>::vertex_descriptor Vertex;
     typedef graph_traits<Graph>::edge_descriptor Edge;
     BOOST_CONCEPT_ASSERT(( ReadablePropertyGraphConcept<Graph, Vertex, vertex_color_t> ));
@@ -43,6 +44,7 @@ int main(int,char*[])
     > AdjList;
     typedef reverse_graph<AdjList,AdjList&> Graph;
     BOOST_CONCEPT_ASSERT(( VertexListGraphConcept<Graph> ));
+    BOOST_CONCEPT_ASSERT(( BidirectionalGraphConcept<Graph> ));
     typedef graph_traits<Graph>::vertex_descriptor Vertex;
     typedef graph_traits<Graph>::edge_descriptor Edge;
     BOOST_CONCEPT_ASSERT(( PropertyGraphConcept<Graph, Vertex, vertex_color_t> ));
`

**Comment by benvvalk** [comment]
@mspiffy Thanks for your patience and your generous offer to pitch in with the work!  I will raise the issue of the outdated Trans-ABySS at our next lab meeting and see if we can get someone working on it.

@schloegl Thanks very much for your patch! It very helpful  to know exactly which differences between boost versions are causing the issues.
