### ISSUE TITLE
version `GLIBC_2.14' not found (required by ABYSS-P)

### ISSUE THREAD

**Issue by aersoares81** [bcgsc/abyss#160]
Hi,
I've been having trouble running abyss-pe, it spits this error a lot of times then exits:
```
ABYSS-P: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ABYSS-P)
ABYSS-P: /usr/local/gcc-4.8.1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ABYSS-P)
ABYSS-P: /usr/local/gcc-4.8.1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ABYSS-P)
```
I compiled the program in the same machine it's running, so I don't get why it's complaining. Any suggestions on how to fix it?

**Comment by benvvalk** [comment]
I'm not sure, but my suspicion is that you have multiple versions of `gcc` on your machine, and that when you run ABySS it is not able to find the version of `libc` that you originally compiled it with.

You can change the search path for shared libaries at runtime with something like:
```
export LD_LIBRARY_PATH=/usr/local/gcc-4.8.1/lib64
```

That might help it find the version of `libc`that the ABySS binary needs (i.e. the one it was compiled against.)

`ldd` is a useful tool for debugging these sorts of issues -- it shows the shared libraries that the program depends, and where it is loading them from.

**Comment by sjackman** [comment]
Check that you're running the `ABYSS-P` that you compiled, and you don't have another version of it in your `PATH` (possibly compiled by someone else).

Consider installing ABySS using Linuxbrew.
Instructions to Install Linuxbrew are found at http://linuxbrew.sh
Then run…
```sh
brew install homebrew/science/abyss
```

**Comment by aersoares81** [comment]
Hi, thank you for the quick reply, and sorry for taking so long to reply! I liked the idea of using Linuxbrew, it doesn't require sudo, which is great on a shared computer.

Anyway, I ran into this problem now:
```/bin/sh: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
PID 147260 exited with status 127
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[47477,1],0]
  Exit code:    1
--------------------------------------------------------------------------
make: *** [bemteabyss-1.fa] Error 1```

**Comment by sjackman** [comment]
Is that with Linuxbrew? Ensure that the environment variable `LD_LIBRARY_PATH` is not set. Check the warnings produced by `brew doctor`.

**Comment by aersoares81** [comment]
Yeah, it's with Linuxbrew. I removed the environment variable LD_LIBRARY_PATH from .bash_profile, but when I (echo $LD_LIBRARY_PATH) I see it's still there somewhere... I'll have to dig and find it (I have no idea where it would be, and I don't have admin privileges in this machine), so thanks for pointing me in the right direction! And for replying so quickly too. :)

**Comment by benvvalk** [comment]
@aersoares81 

FYI, you can run
```
unset LD_LIBRARY_PATH
```

to clear the value in your current shell.

**Comment by aersoares81** [comment]
Thanks, I tried that but I still got the exact same error message as above.

**Comment by sjackman** [comment]
`mpirun` sets `LD_LIBRARY_PATH` in a sneaky way. That may be what's going on here. Please report the entire output `abyss-pe`, including the path to the `mpirun` executable that's being used. Are you using `mpirun` installed by Linuxbrew, or that comes with your HPC environment?

**Comment by aersoares81** [comment]
I'm using the mpirun installed by Linuxbrew.
The full output is below:

```
/home/asoares81/.linuxbrew/bin/mpirun -np 84 ABYSS-P -k51 -q3    --coverage-hist=coverage.hist -s outputname-bubbles.fa  -o outputname-1.fa /PEreads/library1.R1.fq.gz /PEreads/library1.R2.fq.gz /PEreads/library2.R1.fq.gz /PEreads/library2.R2.fq.gz /PEreads/library3.R1.fq.gz /PEreads/library3.R2.fq.gz /PEreads/library4.R1.fq.gz /PEreads/library4.R2.fq.gz /PEreads/library5.R1.fq.gz /PEreads/library5.R2.fq.gz /PEreads/library6.R1.fq.gz /PEreads/library6.R2.fq.gz 
ABySS 2.0.2
ABYSS-P -k51 -q3 --coverage-hist=coverage.hist -s outputname-bubbles.fa -o outputname-1.fa /PEreads/library1.R1.fq.gz /PEreads/library1.R2.fq.gz /PEreads/library2.R1.fq.gz /PEreads/library2.R2.fq.gz /PEreads/library3.R1.fq.gz /PEreads/library3.R2.fq.gz /PEreads/library4.R1.fq.gz /PEreads/library4.R2.fq.gz /PEreads/library5.R1.fq.gz /PEreads/library5.R2.fq.gz /PEreads/library6.R1.fq.gz /PEreads/library6.R2.fq.gz
Running on 84 processors
31: Running on host labhost
32: Running on host labhost
33: Running on host labhost
34: Running on host labhost
35: Running on host labhost
36: Running on host labhost
37: Running on host labhost
38: Running on host labhost
39: Running on host labhost
40: Running on host labhost
41: Running on host labhost
42: Running on host labhost
43: Running on host labhost
44: Running on host labhost
45: Running on host labhost
46: Running on host labhost
47: Running on host labhost
48: Running on host labhost
49: Running on host labhost
50: Running on host labhost
51: Running on host labhost
52: Running on host labhost
53: Running on host labhost
54: Running on host labhost
55: Running on host labhost
56: Running on host labhost
57: Running on host labhost
58: Running on host labhost
59: Running on host labhost
60: Running on host labhost
61: Running on host labhost
62: Running on host labhost
63: Running on host labhost
64: Running on host labhost
65: Running on host labhost
66: Running on host labhost
67: Running on host labhost
68: Running on host labhost
69: Running on host labhost
70: Running on host labhost
71: Running on host labhost
72: Running on host labhost
73: Running on host labhost
74: Running on host labhost
75: Running on host labhost
76: Running on host labhost
77: Running on host labhost
78: Running on host labhost
79: Running on host labhost
80: Running on host labhost
81: Running on host labhost
82: Running on host labhost
83: Running on host labhost
0: Running on host labhost
2: Running on host labhost
3: Running on host labhost
4: Running on host labhost
5: Running on host labhost
6: Running on host labhost
7: Running on host labhost
8: Running on host labhost
9: Running on host labhost
10: Running on host labhost
11: Running on host labhost
12: Running on host labhost
13: Running on host labhost
14: Running on host labhost
15: Running on host labhost
16: Running on host labhost
17: Running on host labhost
18: Running on host labhost
20: Running on host labhost
21: Running on host labhost
22: Running on host labhost
23: Running on host labhost
24: Running on host labhost
25: Running on host labhost
26: Running on host labhost
27: Running on host labhost
28: Running on host labhost
29: Running on host labhost
30: Running on host labhost
19: Running on host labhost
1: Running on host labhost
0: Reading `/PEreads/library1.R1.fq.gz'...
/bin/sh: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
PID 147260 exited with status 127
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[47477,1],0]
  Exit code:    1
--------------------------------------------------------------------------
make: *** [outputname-1.fa] Error 1

```

**Comment by benvvalk** [comment]
It looks like it is still picking up the wrong version of GLIBC for some reason.

For example, see this post where the person is getting the same error message as you have posted above: https://stackoverflow.com/questions/13668457/vdso-time-missing-from-core-utils

I think mpirun/mpiexec has options for setting environment variables for the job.  You might try using those to change or unset LD_LIBRARY_PATH.

To change the mpirun/mpiexec command used by `abyss-pe`, you can add
```
export mpirun='mpirun <... your args here ...>'
```
to the top of the script that runs your abyss-pe command.

**Comment by sjackman** [comment]
The problem comes from an mpi "feature" that I dislike. If you run the executable using the full path like `/home/asoares81/.linuxbrew/bin/mpirun` it helpfully sets the `LD_LIBRARY_PATH` for you. You need to run `mpirun` without specifying the full path, to avoid setting `LD_LIBRARY_PATH`. Try
```sh
abyss-pe mpirun=mpirun …
``

**Comment by aersoares81** [comment]
Thank you, adding mpirun=mpirun works! Thank you guys for taking the time to reply to my questions, much appreciated. :)

**Comment by sjackman** [comment]
@benvvalk I think `mpirun=mpirun` should be the default value in `abyss-pe`, because of this issue.

**Comment by sjackman** [comment]
Happy to help, Andre! 👍

**Comment by aersoares81** [comment]
I guess I spoke too soon...
After reading all the reads, it spit the error
```
make: *** [outputabyss-1.fa] Error 1
```
Do you think it could be related or should I open a new thread?

**Comment by sjackman** [comment]
Please open a new issue and include the complete command line and text output by `abyss-pe` before this error message.
