### ISSUE TITLE
Problem compiling with boost 1.64.0

### ISSUE THREAD

**Issue by dmonism** [bcgsc/abyss#162]
For Boost 1.64.0, compilation requires adding the line to the cholesky.hpp file in Common.  The following #include needs to be added before all others in the file.

```
#include <boost/serialization/array_wrapper.hpp>
```

I recommend using a #if to check the BOOST_VERSION number.  I'm not sure how far back this issue goes with boost.

**Comment by benvvalk** [comment]
Thanks for the report (and workaround)!

If you still have it, can you post the compile error(s) that result?

**Comment by benvvalk** [comment]
@dmonism 

Also, which file did you add the `array_wrapper.hpp` header to?

**Comment by sjackman** [comment]
```
Common/cholesky.hpp
```

**Comment by benvvalk** [comment]
Oops, its right in the post (`cholesky.hpp`).  Thanks, @sjackman.

**Comment by dmonism** [comment]
See below for the error, which occurred near the end of the compilation steps.

...
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I/opt/sources/abyss -isystem/opt/boost/1.64.0/gnu -isystem/opt/boost/1.64.0/gnu/include -isystem/opt/openmpi-2.0/gcc/include -I/opt/sqlite/3.20.0/gnu/include -isystem/opt/sparsehash/2.0.3/gnu/include -I/opt/sparsehash/2.0.3/gnu/include -I/opt/sqlite/3.20.0/gnu/include -I/opt/boost/1.64.0/gnu/include -I/opt/python/2.7.13/gnu/include -isystem/opt/sources/abyss/boost_1_56_0 -Wall -Wextra -Werror -g -O2 -MT abyss_drawgraph-drawgraph.o -MD -MP -MF .deps/abyss_drawgraph-drawgraph.Tpo -c -o abyss_drawgraph-drawgraph.o `test -f 'drawgraph.cc' || echo './'`drawgraph.cc
In file included from /opt/boost/1.64.0/gnu/include/boost/numeric/ublas/vector.hpp:21:0,
                 from ../Common/cholesky.hpp:29,
                 from drawgraph.cc:17:
/opt/boost/1.64.0/gnu/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
/opt/boost/1.64.0/gnu/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^
/opt/boost/1.64.0/gnu/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
/opt/boost/1.64.0/gnu/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^
In file included from ../Common/cholesky.hpp:32:0,
                 from drawgraph.cc:17:
/opt/boost/1.64.0/gnu/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
/opt/boost/1.64.0/gnu/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, N);
                  ^
make[2]: *** [abyss_drawgraph-drawgraph.o] Error 1
make[2]: Leaving directory `/opt/sources/abyss/Scaffold'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/sources/abyss'
make: *** [all] Error 2

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
@benvvalk We don't use serialization. Another option is to delete that code or enclose it in `#if 0 … #endif`

**Comment by benvvalk** [comment]
Thanks @dmonism @sjackman

**Comment by sjackman** [comment]
Thanks, @dmonism and Ben!
