### ISSUE TITLE
abyss-todot: output graph missing symmetric edges 

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#163]
For visualization purposes, it would be helpful if `abyss-todot` always generated both orientations of an edge.

However, when running:
```
abyss-todot -e contigs.fa contigs.dist > contigs.dist.dot
```
the output graph does not always contain both orientations of an edge.  For example
```
1+ -> 2+
```
might be present, but not
```
2- -> 1-
```

This is likely due to the asymmetric nature of the `s` (contig seed size) parameter.

Adding a command-line switch and/or a call to `addComplementary` edges somewhere in `todot.cc`code would probably fix this issue.

**Comment by sjackman** [comment]
I recently needed this feature as well, so your wish is my command! =)
https://github.com/bcgsc/abyss/blob/master/Graph/todot.cc#L84
```sh
brew upgrade --HEAD abyss
abyss-todot -e --add-complements contigs.dist > contigs.dist.dot
```

**Comment by benvvalk** [comment]
Nice! Thank you, @sjackman!

(Lauren who ran into this today, but I'm sure I will find it useful as well.)
