### ISSUE TITLE
How does Abyss determine insert size and read  length if not provided

### ISSUE THREAD

**Issue by chirrie** [bcgsc/abyss#170]
I have done assembly of paired end reads sequences using latest Abyss. 
This are the parameters I used.

```sh
abyss-pe name=goat k=77 -j 4 np=4  v=-v  in='~/goat/denovo/goat1.fastq ~/goat/denovo/goat2.fastq' -C $WORKING_DIR
```

The assembly looks good but I am wondering how does Abyss estimate the insert size and maximum read length... For soapdenovo you supply it as config file but for Abyss I haven't seen that option.

**Comment by benvvalk** [comment]
Hi @chirrie,

ABySS estimates the fragment size by mapping the paired-end reads to the unitig assembly and measuring the distance between read pairs that align to the same unitig.

The maximum read length is not required by any of the ABySS assembly algorithms.  If you set k-mer size greater than the read length that will create problems, of course.

**Comment by AllisonStander** [comment]
Good Day,

Regarding the calculation of insert size, does ABySS 2.0 report on only the distance between the two read pairs, or does it report on the distance between the two read pair, plus the length of the two read pair sequences?

Kind regards,
Allison

**Comment by sjackman** [comment]
Hi, Allison. ABySS reports the distance from the first base of read 1 to the first base of read 2. For FR-oriented paired-end reads, that's the size of the DNA molecule (the size including the reads and the distance between the reads). I prefer the term fragment size over insert size.

**Comment by AllisonStander** [comment]
Thank you for the clarification :)
