### ISSUE TITLE
Default number of buckets

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#171]
Regarding commit 6b580d301287e6e532737dcbd32bdff37191cc82 that increases the default number of buckets. How many cores/threads-of-execution does each compute node of the Numbers cluster have, and how much memory is available per node? The previous commit had the following comment. I'd like to repeat this calculation for Numbers.

> Make room for 200 million k-mers. Approximately 58 million
96-mers fit into 2 GB of ram, which results in a hash load
of 0.216, and approximately 116 million 32-mers, which
results in a hash load of 0.432.

**Comment by benvvalk** [comment]
Re: our discussion just now, I think we should also aim to do the human assembly from the ABySS 2.0 paper with 64 threads, without triggering hash table resizes.

As you mentioned, the new value set in 6b580d3 entails a minimum RAM usage of 0.5 GB per MPI process, which was possibly overkill on my part.

**Comment by sjackman** [comment]
The default `max_load_factor` is 80%.
https://github.com/sparsehash/sparsehash/blob/master/src/sparsehash/internal/sparsehashtable.h#L357

The GIAB HG004 dataset has 8,704,901,295 distinct 144-mers.
/projects/btl/abyss-2.0-paper/sjackman/abyss/k144/coverage.hist

8,704,901,295 / 64 = 136,014,083
The previous value of 200,000,000 is sufficient for this use case.

No hash table resizes occurred with 64 threads.
/projects/btl/abyss-2.0-paper/sjackman/abyss/k144/log/k144-contigs.log

```
0: Read 100000 reads. 0: Hash load: 10575692 / 268435456 = 0.0394 using 712 MB
…
0: Loaded 135820207 k-mer.
0: Hash load: 135820207 / 268435456 = 0.506 using 6.96 GB
```

The actual memory usage of 6.96 GB agrees with the theoretical
Memory for buckets: 268435456 * 2.67 / 8 = 0.09 GB
Memory for k-mers: 135820207 * 48 = 6.52 GB
Estimated memory usage = 6.61 GB
Actual memory usage = 6.96 GB
Difference is 5%
This estimation does not account for MPI buffers or other overhead.

**Comment by sjackman** [comment]
The current value of 200,000,000 would be good for up to 214,748,364 distinct k-mers per node (268435456 * 0.8), or 60% more than we saw in this data set.

**Comment by sjackman** [comment]
Using fewer threads than 64 (say 32) would require increasing the number of buckets.

**Comment by benvvalk** [comment]
@sjackman:  Thanks, for doing this!

I'm not 100% sure, but I think it was the ABySS assembly of the raw reads (i.e. not BFC correctly) that required 128 threads to avoid hash table resizing.  I'll take a second now and go look at the stats for the raw reads assembly.

**Comment by benvvalk** [comment]
From raw reads assembly:
```
/projects/btl/abyss-2.0-paper/benv/raw/abyss-1.9/k144/coverage.hist
```
20,317,980,431 / 64 = 317,468,444

**Comment by benvvalk** [comment]
So, you were right -- increasing the bucket size by a factor of 10 from 200,000,000 to 2,000,000,000 was a bit overboard.

Want to meet half way and set it to 1,000,000,000?

That would still allow the raw Chromium assembly to run without resizes.

**Comment by sjackman** [comment]
Sounds good, Ben.
20,317,980,431 / 32 = 634,936,889
Asking for one million buckets will get you 2^30 = 1,073,741,824 buckets
1073741824 * 2.67 / 8 = 0.358 GB of memory for buckets
634,936,889 / 1,073,741,824 = 59% load factor
