### ISSUE TITLE
bcgsc/abyss:latest docker container is broken when running bloom filters

### ISSUE THREAD

**Issue by antonkulaga** [bcgsc/abyss#176]
Whenever I run anything with bloom-filters and bcgsc/abyss:latest I get the following error:
```
abyss-bloom-dbg: error while loading shared libraries: libgomp.so.1: cannot open shared object 
```
Probably, you forgot to put libgomp.so in the official docker container.
An example of the command that crashes with such message:
```
abyss-pe k=25 name=test_assembly in='/cromwell-executions/genome_assembly/281bd5e5-1ccc-43a1-890b-06b5b6d2a97d/call-test/inputs/pipelines/indexes/TEST/test-data/reads1.fastq /cromwell-executions/genome_assembly/281bd5e5-1ccc-43a1-890b-06b5b6d2a97d/call-test/inputs/pipelines/indexes/TEST/test-data/reads2.fastq' B=2G H=4 kc=3
```

**Comment by sjackman** [comment]
Thanks for the bug report, Anton! It's hopefully fixed now.

**Comment by antonkulaga** [comment]
thank you @sjackman , I was amazed how fast you reacted. 
So, it looks fixed, but now I have a problem with column https://github.com/bcgsc/abyss/issues/177
