### ISSUE TITLE
abyss/Sealer (stand-alone) README.md

### ISSUE THREAD

**Issue by ckeeling** [bcgsc/abyss#178]
May I suggest a couple of edits to this readme?

(1) The **Options** section does not reflect the current version. I.e. it is not the same as is currently shown with --help.  Specifically, description of the "-G" option is missing.  And similarity, the depreciated "-F" option rather than "-G" is described in **Runtime and memory usage**.

(2) The **Description**/**Suggested parameters for first run**/**How to optimize for gap closure** sections may not fully make it clear (at least to me) that Sealer _should_ generally be run iteratively in a cascading fashion at various values of k to get the largest number of gaps closed.  Also, in **Suggested parameters for first run** there is the statement, "Note that these suggested k values are only applicable for datasets without a pre-built Bloom Filter."  Does this mean, "If using pre-built Bloom Filters, filters for these k values must also be pre-built" or are you saying something else?

I'm still optimizing, but it is working beautifully. Cheers!

**Comment by sjackman** [comment]
> Sealer should generally be run iteratively in a cascading fashion at various values of k to get the largest number of gaps closed.

Sealer should be run with multiple values of *k*. It's just a single run of Sealer though. You can specify *k* multiple times in a single run. e.g. `abyss-sealer -k25 -k50 -k75 -k100 -k150 -k200 -k250`. If using pre-built Bloom filters, they can be specified using the `-i` option multiple times. A couple of examples would help clarify its usage.

**Comment by mmokrejs** [comment]
Thanks @ckeeling for opening this Issue. It made me aware of abyss-sealer existence at all. Would you expect https://github.com/bcgsc/abyss/blob/master/README.md to point users to it for further improvements of their scaffolds?

Anyway, I also have a question after reading https://github.com/bcgsc/abyss/blob/master/Sealer/README.md . Why do you advice the k-mer sizes in incremenatal fashion? Isn't decremental series preferred (causing less errors)?

Does `-L,--flank-length=N` relate to k-mer sizes? Am I supposed to set `-L 200` if I want to include `-k 128` or does that happen automagically? I assume mixing `-L 100` and `-k 128` is non-sense.

The readme could explain what is the goal. I have 2x250 reads so should I increase the `-L` parameter to say `500`?

The `-P,--max-paths=N` parameter has default value 2. Is that practically speaking it will merge two alleles of a diploid input data into just one allele? I have a trouble understanding what therein mentioned `-P 10` really means.

It is scary to read the help text of `--trim-masked` and `--no-trim-masked .. [default]`. Sealer ignores eventual lower-cased letters in FASTA/Q input? By default? Why?

I have my original reads mapped in BAM format to the scaffolds (too late, I wasn't aware of sealer so I prepared to use https://github.com/broadinstitute/pilon for gap closing and error-corrections of the reference sequence). Could the existing BAM's be used to quickly find the reads surrounding the gap?

Also, `-e,--fix-errors` help text is too short for me to understand. I am glad I did not run `abyss-pe` with the Bloom filter thing, so it probably does not apply to my case anyway.

**Comment by sjackman** [comment]
> Would you expect https://github.com/bcgsc/abyss/blob/master/README.md to point users to it for further improvements of their scaffolds?

Yes, good idea. `README.md` should include a one-line summary of the independent tools included with ABySS.

**Comment by sjackman** [comment]
> Why do you advice the k-mer sizes in incremenatal fashion? Isn't decremental series preferred (causing less errors)?

It's a bit counter-intuitive, but starting with the largest k-mers causes assembly errors. Assembly errors are caused not be repetitive k-mers, those are handled properly, but by gaps in the de Bruijn graph due to a lack of coverage, which are more likely with large values of *k*. So large values of *k* are more likely to create misassemblies.

**Comment by sjackman** [comment]
> Does -L,--flank-length=N relate to k-mer sizes? Am I supposed to set -L 200 if I want to include -k 128 or does that happen automagically? I assume mixing -L 100 and -k 128 is a non-sense.

`-L` is measured in nucleotides and must be larger than the largest `-k`.

> The https://github.com/bcgsc/abyss/blob/master/Sealer/README.md could explain what is the goal. I have 2x250 reads so should I increase the -L parameter to say 500?

Set `-L` to somewhat larger than your largest *k*. I'm afraid I don't have a recommendation for how much larger. The results shouldn't be terribly sensitive to this parameter.
 
> The -P,--max-paths=N parameter has default value 2. Is that practically speaking: it will merge two alleles of a diploid input data into just one allele in the reference? I have a trouble understanding what therein mentioned -P 10 example really means.

Yes, that's the intention with the default `-P2`. With `-P10`, it could for example create a consensus sequence of a 10 copy repeat.

> It is scary to read the help text of --trim-masked and --no-trim-masked .. [default]. Sealer ignores eventual lower-cased letters in FASTA/Q input? By default? Why?

No trimming `--no-trim-masked [default]` is the default, as it says. This allows using a separate tool to soft-mask adapter sequence from your reads.

> I have my original reads mapped in BAM format to the scaffolds (too late, I wasn't aware of sealer so I prepared to use https://github.com/broadinstitute/pilon for gap closing and error-corrections of the reference sequence). Could the existing BAM's be used to quickly find the reads surrounding the gap?

Sealer uses a Bloom filter de Bruijn graph to fill the gap sequence, and it has no way of using read alignments.

> Also, -e,--fix-errors help text is too short for me to understand. I am glad I did not run abyss-pe with the Bloom filter thing, so it probably does not apply to my case anyway.

I didn't know that `-e,--fix-errors` existed. This enables functionality somewhat similar to the tool https://github.com/lh3/bfc if there are no matching *k*-mers found in the flank region. This should never happen when running Sealer in it's normal mode of operation, with contigs assembled from the same reads being used to fill the gap.

**Comment by ckeeling** [comment]
OK, now I am confused regarding incremental versus decremental k-mer sweep.  The [ReadMe](https://github.com/bcgsc/abyss/blob/master/Sealer/README.md) suggests a decremental sweep.  Has this changed now?

**Comment by mmokrejs** [comment]
> -L is measured in nucleotides and must be larger than the largest -k.

It doesn't sound that abyss will automatically raise the `-L` value if `-k` is larger, but you know where to look in the code.

> No trimming --no-trim-masked [default] is the default, as it says. This allows using a separate tool to soft-mask adapter sequence from your reads.

But are we speaking about FASTA/FASTQ input of SAM/BAM alignments? How do you soft-mask adapters in your FASTA/Q files? ... other than lower-casing them? So why does it consider lower-cased letters by default (if they are demed to be ignored, aka soft-masked)? BTW, I was unpleasantly surprised by read abyss-pe log that it discarded all my reads bearing any 'N' in the sequence. would I have known that beforehand I would bother to error-correct them with some tool prior feeding into abyss. again something to be covered in README.md.

> Sealer uses a Bloom filter de Bruijn graph to fill the gap sequence, and it has no way of using read alignments.

Sorry for my laziness to study wikipedia atm. Most likely it would anyway not tell me how does this translate to repeat sequence (where the N's are now) and to the flanking sequences present in scaffolds. However, then I am not going to follow those portions of README.md speaking about the new features of Bloom filter (and some minor disadvantages). and that is exactly why I sticked to the default method, taking more RAM but being said to be faster.

The `-e` is still not clear to me. What could abyss do if there are no reads/k-mers covering the gap (or the flanking sequence?). What kind of error could it fix and by what means? When there is no evidence?

**Comment by mmokrejs** [comment]
> OK, now I am confused regarding incremental versus decremental k-mer sweep. The ReadMe suggests a decremental sweep. Has this changed now?

Not, that was just my question why it is in decreasing ordering. However, it should be make clear how to provided the k-mer values.

**Comment by sjackman** [comment]
> But are we speaking about FASTA/FASTQ input of SAM/BAM alignments? How do you soft-mask adapters in your FASTA/Q files? ... other than lower-casing them? So why does it consider lower-cased letters by default (if they are demed to be ignored, aka soft-masked)?

Lower-cased letters are soft masked. No trimming `--no-trim-masked [default]` is the default, as it says. It says so in `--help`, and I've said it twice now.

**Comment by ckeeling** [comment]
I think the README is clear in indicating a decremental k-mer sweep in all the example commands and suggestions, but @sjackman is saying incremental sweep. (me confused)

**Comment by sjackman** [comment]
> BTW, I was unpleasantly surprised by read abyss-pe log that it discarded all my reads bearing any 'N' in the sequence. would I have known that beforehand I would bother to error-correct them with some tool prior feeding into abyss. again something to be covered in README.md.

ABySS does not ignore reads including Ns. It ignores *k*-mers that include Ns.

**Comment by sjackman** [comment]
> I think the README is clear in indicating a decremental k-mer sweep in all the example commands and suggestions, but @sjackman is saying incremental sweep. (me confused)

@ckeeling Thanks for pointing out this documentation error. I've corrected the README.
https://github.com/bcgsc/abyss/pull/188/files
Click the "rich diff" button to see the changes.

**Comment by benvvalk** [comment]
Just a bit of explanation about `-L` (`--flank-length`) and `-e` (`--fix-errors`).

The way Sealer operates is to first identify start/goal k-mers in the flank sequences on each side of a gap, and then navigate the (Bloom filter) de Brujin graph to find a connecting path.   That is why `-L` must be greater than `-k`.  The `--fix-errors` option makes Sealer try single-base mutations to recover k-mers, in the case that it cannot find start/goal k-mers in the flank sequences that are also present in the de Bruijn graph (that was built from the reads).  This kind of mismatch could happen, for example, if  SNPs from different alleles were collapsed during assembly.  While to my knowledge this effect has never been quantified,  it is likely a minor issue in terms of missed opportunities to fill gaps.  So I would recommend leaving the `-e` option disabled (as it is by default).

**Comment by benvvalk** [comment]
>I've corrected the README.
> https://github.com/bcgsc/abyss/pull/188/files
> Click the "rich diff" button to see the changes.

Thanks, @sjackman!

**Comment by benvvalk** [comment]
@ckeeling

IMO, using a decrementing k-mer sweep is not catastrophic, but I agree with @sjackman's logic that it is better practice to use an incrementing k-mer sweep in order to decrease the chance of misassemblies.

**Comment by sjackman** [comment]
I tested this once in with an *E. coli* data set and saw fewer misassemblies with increasing values of *k*. That was a few years ago. See https://github.com/sjackman/abyss-pipeline/blob/master/ecoli/Makefile#L131

**Comment by mmokrejs** [comment]
> Thanks for pointing out this documentation error. I've corrected the README.
> https://github.com/bcgsc/abyss/pull/188/files

I would not advise -k 144 there if the compiled default maximum is 128. Many users will be surprised later on. There are a few minor typos.

**Comment by mmokrejs** [comment]
Thak you @benvvalk for the `-L` and `-e` explanatiuon, nice text which could go right away to official documentation.

**Comment by mmokrejs** [comment]
Interesting, the k=128 assembly went better IMO than the k=64 assembly. These are the contigs but I think it is correct to check those well-assembled segments before scaffodling happens. What am I missing here? Was our discussion only about sealing gaps?

```
$ BBmap-37.90/stats.sh in=abyss_k64/tt_16D1C3L12__abyss_64-3.fa 
A	C	G	T	N	IUPAC	Other	GC	GC_stdev
0.3026	0.1979	0.1980	0.3014	0.0000	0.0000	0.0000	0.3959	0.1092

Main genome scaffold total:         	8970038
Main genome contig total:           	8970038
Main genome scaffold sequence total:	1545.997 MB
Main genome contig sequence total:  	1545.997 MB  	0.000% gap
Main genome scaffold N/L50:         	984481/207
Main genome contig N/L50:           	984481/207
Main genome scaffold N/L90:         	6786697/66
Main genome contig N/L90:           	6786697/66
Max scaffold length:                	48.544 KB
Max contig length:                  	48.544 KB
Number of scaffolds > 50 KB:        	0
% main genome in scaffolds > 50 KB: 	0.00%


Minimum 	Number        	Number        	Total         	Total         	Scaffold
Scaffold	of            	of            	Scaffold      	Contig        	Contig  
Length  	Scaffolds     	Contigs       	Length        	Length        	Coverage
--------	--------------	--------------	--------------	--------------	--------
    All 	     8,970,038	     8,970,038	 1,545,997,227	 1,545,997,227	 100.00%
     50 	     8,970,038	     8,970,038	 1,545,997,227	 1,545,997,227	 100.00%
    100 	     4,217,230	     4,217,230	 1,211,849,941	 1,211,849,941	 100.00%
    250 	       763,487	       763,487	   724,479,476	   724,479,476	 100.00%
    500 	       386,281	       386,281	   597,014,844	   597,014,844	 100.00%
   1 KB 	       218,620	       218,620	   479,261,380	   479,261,380	 100.00%
 2.5 KB 	        56,120	        56,120	   220,798,793	   220,798,793	 100.00%
   5 KB 	         9,411	         9,411	    66,580,089	    66,580,089	 100.00%
  10 KB 	           875	           875	    11,287,016	    11,287,016	 100.00%
  25 KB 	            12	            12	       371,039	       371,039	 100.00%

$ BBmap-37.90/stats.sh in=abyss_k128/tt_16D1C3L12-3.fa 
A	C	G	T	N	IUPAC	Other	GC	GC_stdev
0.3002	0.2001	0.2002	0.2995	0.0000	0.0000	0.0000	0.4003	0.0996

Main genome scaffold total:         	3835048
Main genome contig total:           	3835048
Main genome scaffold sequence total:	1651.869 MB
Main genome contig sequence total:  	1651.869 MB  	0.000% gap
Main genome scaffold N/L50:         	280737/938
Main genome contig N/L50:           	280737/938
Main genome scaffold N/L90:         	2578210/142
Main genome contig N/L90:           	2578210/142
Max scaffold length:                	56.412 KB
Max contig length:                  	56.412 KB
Number of scaffolds > 50 KB:        	1
% main genome in scaffolds > 50 KB: 	0.00%


Minimum 	Number        	Number        	Total         	Total         	Scaffold
Scaffold	of            	of            	Scaffold      	Contig        	Contig  
Length  	Scaffolds     	Contigs       	Length        	Length        	Coverage
--------	--------------	--------------	--------------	--------------	--------
    All 	     3,835,048	     3,835,048	 1,651,869,106	 1,651,869,106	 100.00%
    100 	     3,835,048	     3,835,048	 1,651,869,106	 1,651,869,106	 100.00%
    250 	     1,733,198	     1,733,198	 1,333,132,564	 1,333,132,564	 100.00%
    500 	       475,698	       475,698	   956,024,894	   956,024,894	 100.00%
   1 KB 	       267,415	       267,415	   813,134,944	   813,134,944	 100.00%
 2.5 KB 	       116,134	       116,134	   571,167,119	   571,167,119	 100.00%
   5 KB 	        38,065	        38,065	   299,800,293	   299,800,293	 100.00%
  10 KB 	         6,544	         6,544	    88,583,607	    88,583,607	 100.00%
  25 KB 	           125	           125	     3,756,838	     3,756,838	 100.00%
  50 KB 	             1	             1	        56,412	        56,412	 100.00%

$
```

**Comment by sjackman** [comment]
```
k=64 Main genome contig N/L50:           	984481/207
k=128 Main genome contig N/L50:           	280737/938
```
*k*=64 is the more contiguous assembly. Try *k*=80,96,112.
I'd suggest using ntCard and GenomeScope first before assembling with ABySS to get a sense of the *k*-mer distribution.

**Comment by mmokrejs** [comment]
Those numbers were from step `-3`. In final scaffolds in `-8` files there is:

```
k=64 Main genome contig N/L50:           	703390/232
k=128 Main genome contig N/L50:           	108612/2.736 KB
```
Those `KB` are certainly not kilobytes, it is just weird.

**Comment by mmokrejs** [comment]
I asked Brian Bushnell for meaning of the MB and KB in the output, here is the answer.

_Indeed, those are Kbp and Mbp; I should change them.  You can add the flag "format=2" to print whole numbers of bp with no commas or decimals, instead of Kbp or Mbp.  Also, note that "L50" for stats.sh means a Length and "N50" means a Number of contigs, so the L50 (length of 50th percentile contig) increased from 232 to 2736 in that case, when K increased, meaning continuity improved.  There are some programs that have L50 and N50 reversed._

**Comment by mmokrejs** [comment]
> ABySS does not ignore reads including Ns. It ignores k-mers that include Ns.

```
0: Read 314500000 reads. 0: Hash load: 174632622 / 268435456 = 0.651 using 7.54 GB
1: Read 311500000 reads. 1: Hash load: 173567722 / 268435456 = 0.647 using 7.5 GB
0: Read 314600000 reads. 0: Hash load: 174673652 / 268435456 = 0.651 using 7.54 GB
0: Read 314671967 reads. 0: Hash load: 174702526 / 268435456 = 0.651 using 7.54 GB
'file.fastq': discarded 2978895 reads shorter than 128 bases
'file.fastq': discarded 73242 reads containing non-ACGT characters
```

**Comment by sjackman** [comment]
If a read contains no valid *k*-mers, it is discarded.
See https://github.com/bcgsc/abyss/blob/7203899f5b8220819a4f9ef37ca031ae3734f25a/Assembly/LoadAlgorithm.h#L65

**Comment by mmokrejs** [comment]
You asked for the numbers from abyss-fac so that we do not have to think of what Brian has eventually swapped. The mapped used was the abyss-map (the default sor far):

```
abyss_k80 $ for f in tt_16D1C3L12__abyss_80-?.fa; do echo $f; abyss-fac $f; done
tt_16D1C3L12__abyss_80-1.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
13.12e6	446607	100548	500	968	2003	3865	2719	40026	684.4e6	tt_16D1C3L12__abyss_80-1.fa
tt_16D1C3L12__abyss_80-2.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
7098314	446607	100548	500	968	2003	3865	2719	40026	684.4e6	tt_16D1C3L12__abyss_80-2.fa
tt_16D1C3L12__abyss_80-3.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
6781726	423529	92333	500	1071	2247	4374	3073	48480	707.5e6	tt_16D1C3L12__abyss_80-3.fa
tt_16D1C3L12__abyss_80-4.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
4693	0	0	0	0	0	0	0	0	0	tt_16D1C3L12__abyss_80-4.fa
tt_16D1C3L12__abyss_80-5.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
6110	0	0	0	0	0	0	0	0	0	tt_16D1C3L12__abyss_80-5.fa
tt_16D1C3L12__abyss_80-6.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
5820652	308849	55950	500	1887	3813	7894	5337	59232	755e6	tt_16D1C3L12__abyss_80-6.fa
abyss_k80 $
```

```
abyss_k128 $ for f in tt_16D1C3L12-?.fa; do echo $f; abyss-fac $f; done
tt_16D1C3L12-1.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
7603647	540270	98987	500	1042	2609	5644	3732	45325	940.8e6	tt_16D1C3L12-1.fa
tt_16D1C3L12-2.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
4164814	540270	98987	500	1042	2609	5644	3732	45325	940.8e6	tt_16D1C3L12-2.fa
tt_16D1C3L12-3.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
3835048	475698	83169	500	1260	3192	6791	4462	56412	956e6	tt_16D1C3L12-3.fa
tt_16D1C3L12-4.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
11372	0	0	0	0	0	0	0	0	0	tt_16D1C3L12-4.fa
tt_16D1C3L12-5.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
5300	0	0	0	0	0	0	0	0	0	tt_16D1C3L12-5.fa
tt_16D1C3L12-6.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
3011140	310186	43902	500	2643	6415	13450	8757	104425	1.006e9	tt_16D1C3L12-6.fa
tt_16D1C3L12-7.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
772	429	133	500	786	1261	2004	1414	3662	482664	tt_16D1C3L12-7.fa
tt_16D1C3L12-8.fa
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
2876731	189115	4029	500	9361	56647	164847	94949	793681	1.003e9	tt_16D1C3L12-8.fa
abyss_k128$
```

**Comment by sjackman** [comment]
```
n	n:500	L50	min	N80	N50	N20	E-size	max	sum	name
8066430	203300	7924	500	1783	15776	59085	34309	290392	632.8e6	tt_16D1C3L12__abyss_64-8.fa
2876731	189115	4029	500	9361	56647	164847	94949	793681	1.003e9	tt_16D1C3L12-8.fa
```
*k*=128 looks like the better of these two assemblies to me. I'd suggest trying larger values of *k*. Note that the assembly size differs quite a bit between the two assemblies. That's something to keep in mind when interpreting these numbers. I'd suggest adding a `-G` parameter to `abyss-fac` that is your best estimate of the genome size to calculate NG50, which is generally better for comparing the contiguity of two assemblies. Note that `abyss-fac` can accept multiple FASTA files on its command line.

**Comment by mmokrejs** [comment]
```
$ abyss-fac -G 1267403131 ./abyss_k64/tt_16D1C3L12__abyss_64-scaffolds.fa ./abyss_k80/tt_16D1C3L12__abyss_80-scaffolds.fa ./abyss_k96/tt_16D1C3L12__abyss_96-scaffolds.fa ./abyss_k128/tt_16D1C3L12__abyss_128-scaffolds.fa
n	n:500	L50	LG50	NG50	min	N80	N50	N20	E-size	max	sum	name
8066430	203300	7924	203300	500	500	1783	15776	59085	34309	290392	632.8e6	./abyss_k64/tt_16D1C3L12__abyss_64-scaffolds.fa
5696462	191129	5702	43046	1934	500	2941	28235	91696	52410	565062	753.4e6	./abyss_k80/tt_16D1C3L12__abyss_80-scaffolds.fa
4344599	184154	4671	14726	10390	500	5460	40717	121439	70922	851373	852.6e6	./abyss_k96/tt_16D1C3L12__abyss_96-scaffolds.fa
2876731	189115	4029	7223	30658	500	9361	56647	164847	94949	793681	1.003e9	./abyss_k128/tt_16D1C3L12__abyss_128-scaffolds.fa
```

I am glad that now you agree the `k128` result is better than k64. Pity I confused you with the output from `stats.sh`. The `k112` and `k156` computations are ongoing, the `k156` will take days due to cluster maintenance.

**Comment by sjackman** [comment]
You could try some ABySS 2 assemblies in the mean time if you liked, which require about a tenth of the RAM. Perhaps that'd be easier for you to get scheduled on your cluster.

**Comment by mmokrejs** [comment]
So, finally I have the assemblies with k160 and k192. I updated the comment https://github.com/bcgsc/abyss/issues/178#issuecomment-365316650 to reflect the new values.

**Comment by sjackman** [comment]
*k*=160 has the peak NG50. *k*=128 has the peak E-size and N50 and largest scaffold. Either of those look assemblies looks good to me.

**Comment by mmokrejs** [comment]
I have the impression I shall try `k144` too.
