### ISSUE TITLE
ABySS 2.0.2 crashed with BubbleAlgorithm error

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#179]
Hi,

recently I updated my local abyss installation to the newest release (2.0.2) , The first run I did with this version failed however with the following error message 
> ABYSS-P: ../Assembly/BubbleAlgorithm.h:240: void AssemblyAlgorithms::writeBubble(std::basic_ostream<char, std::char_traits<char>> &, const BranchGroup &, unsigned int): Assertion `out.good()' failed.
> make: *** [ppinTk77-1.fa] Error 134

This is what's written at the end of my run-output file:
>Pruned 3514443 tips in 10 rounds.
>Popping bubbles... 

Any idea what the problem might be? Is it abyss related or something to do with our cluster system?
thx

**Comment by sjackman** [comment]
> Assertion `out.good()' failed.

It failed while writing the bubbles FASTA file to disk. It may mean that your disk full. The error message could be improved.

**Comment by lsterck** [comment]
Hi Shaun,
thanks for confirming my suspicion it's a writing problem. It however can not be due to diskspace issues, I have over 1 Tb of space left. I rather suspect some network issues causing the storage to be inaccessible .

L.

**Comment by benvvalk** [comment]
Thank you, @sjackman!
