### ISSUE TITLE
Could not assemble

### ISSUE THREAD

**Issue by GideonPisanty** [bcgsc/abyss#182]
I have given a command to assemble 40 libraries with the program. The first two libraries went well, each took 5-10 min to complete. In the third library, it got stuck for hours and eventually gave the error "CRITICAL - Could not assemble". I started all over again and it got stuck on the same library. Do you have any hints how to solve this? Thanks.

**Comment by benvvalk** [comment]
I could not find the word "CRITICAL" in any of the ABySS source code (to determine where the error message is coming from).

Can you please provide your `abyss-pe` command and your log output (preferably after adding `v=-v` to your `abyss-pe` command to enable verbose logging)?

**Comment by sjackman** [comment]
Are you sure that you have forty libraries of the same sample, or perhaps you have one library each from forty different samples, or forty lanes (!) of one library?

**Comment by GideonPisanty** [comment]
Thanks for the answer. I was running Abyss through the PHYLUCE script. Here is the command and the log files:

**command**
phyluce_assembly_assemblo_abyss \
    --config /home/pisantyg/MiSeq_19Jan2018/config/config.conf \
    --output /home/pisantyg/MiSeq_19Jan2018/abyss_output \
    --kmer 60 \
    --subfolder split-adapter-quality-trimmed \
    --cores 10 \
    --clean \
    --log-path /home/pisantyg/MiSeq_19Jan2018/log

**phyluce_assembly_assemblo_abyss.log**
2018-01-31 10:07:44,991 - phyluce_assembly_assemblo_abyss - INFO - ============ Starting phyluce_assembly_assemblo_abyss ===========
2018-01-31 10:07:44,991 - phyluce_assembly_assemblo_abyss - INFO - Version: 1.5.0
2018-01-31 10:07:44,991 - phyluce_assembly_assemblo_abyss - INFO - Argument --clean: True
2018-01-31 10:07:44,991 - phyluce_assembly_assemblo_abyss - INFO - Argument --config: /home/pisantyg/MiSeq_19Jan2018/config/config.conf
2018-01-31 10:07:44,992 - phyluce_assembly_assemblo_abyss - INFO - Argument --cores: 10
2018-01-31 10:07:44,993 - phyluce_assembly_assemblo_abyss - INFO - Argument --dir: None
2018-01-31 10:07:44,993 - phyluce_assembly_assemblo_abyss - INFO - Argument --kmer: 60
2018-01-31 10:07:44,993 - phyluce_assembly_assemblo_abyss - INFO - Argument --log_path: /home/pisantyg/MiSeq_19Jan2018/log
2018-01-31 10:07:44,993 - phyluce_assembly_assemblo_abyss - INFO - Argument --output: /home/pisantyg/MiSeq_19Jan2018/abyss_output
2018-01-31 10:07:44,994 - phyluce_assembly_assemblo_abyss - INFO - Argument --subfolder: split-adapter-quality-trimmed
2018-01-31 10:07:44,994 - phyluce_assembly_assemblo_abyss - INFO - Argument --verbosity: INFO
2018-01-31 10:07:44,994 - phyluce_assembly_assemblo_abyss - INFO - Getting input filenames and creating output directories
2018-01-31 10:07:45,151 - phyluce_assembly_assemblo_abyss - INFO - --------------------- Processing aegyptiaca ---------------------
2018-01-31 10:07:45,152 - phyluce_assembly_assemblo_abyss - INFO - Finding fastq/fasta files
2018-01-31 10:07:45,221 - phyluce_assembly_assemblo_abyss - INFO - File type is fastq
2018-01-31 10:07:45,222 - phyluce_assembly_assemblo_abyss - INFO - Running abyss-pe against data
2018-01-31 10:16:13,462 - phyluce_assembly_assemblo_abyss - INFO - Symlinking assembled contigs into /home/pisantyg/MiSeq_19Jan2018/abyss_output/contigs
2018-01-31 10:16:13,612 - phyluce_assembly_assemblo_abyss - INFO - ---------------- Processing aerinifrons_levantina ---------------
2018-01-31 10:16:13,673 - phyluce_assembly_assemblo_abyss - INFO - Finding fastq/fasta files
2018-01-31 10:16:13,773 - phyluce_assembly_assemblo_abyss - INFO - File type is fastq
2018-01-31 10:16:13,785 - phyluce_assembly_assemblo_abyss - INFO - Running abyss-pe against data
2018-01-31 10:23:26,249 - phyluce_assembly_assemblo_abyss - INFO - Symlinking assembled contigs into /home/pisantyg/MiSeq_19Jan2018/abyss_output/contigs
2018-01-31 10:23:26,249 - phyluce_assembly_assemblo_abyss - INFO - ------------------- Processing alleghaniensis -------------------
2018-01-31 10:23:26,253 - phyluce_assembly_assemblo_abyss - INFO - Finding fastq/fasta files
2018-01-31 10:23:26,283 - phyluce_assembly_assemblo_abyss - INFO - File type is fastq
2018-01-31 10:23:26,284 - phyluce_assembly_assemblo_abyss - INFO - Running abyss-pe against data
2018-02-01 04:02:10,153 - phyluce_assembly_assemblo_abyss - CRITICAL - Could not assemble /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed

**abyss-k60.out.log**

ABYSS -k60 -q3  --coverage-hist=coverage.hist -s out_k60-bubbles.fa  -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
ABySS 1.3.7
ABYSS -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz'...
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz'...
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz'...
Loaded 47238114 k-mer

**abyss-k60.err.log**

`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz': discarded 1046 reads shorter than 60 bases
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz': discarded 1954 reads shorter than 60 bases
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz': discarded 7846 reads shorter than 60 bases
condaflmake: *** [out_k60-1.fa] Interrupt

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Add `-v` (verbose) to the command line to enable verbose output:
```sh
ABYSS -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
```

**Comment by GideonPisanty** [comment]
Thanks for the feedback. It's one library each from forty different samples

**Comment by GideonPisanty** [comment]
Here's the output with the new command. Again, the program is stuck on the singleton file.

'''
 v=-v ABYSS -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
ABySS 1.3.7
ABYSS -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz'...
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz': discarded 1046 reads shorter than 60 bases
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz'...
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz': discarded 1954 reads shorter than 60 bases
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz'...
'''

**Comment by sjackman** [comment]
Try this…
```sh
ABYSS -v -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
```

**Comment by GideonPisanty** [comment]
Thanks. I tried it, here's the output:

```
pisantyg@pisantyg-VirtualBox:~$ ABYSS -v -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
ABySS 1.3.7
ABYSS -v -k60 -q3 --coverage-hist=coverage.hist -s out_k60-bubbles.fa -o out_k60-1.fa /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz /home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz'...
Read 100000 reads. Hash load: 16384006 / 1073741824 = 0.0153 using 1.07 GB
Read 101696 reads. Hash load: 16633152 / 1073741824 = 0.0155 using 1.08 GB
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz': discarded 1046 reads shorter than 60 bases
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz'...
Read 100000 reads. Hash load: 22484025 / 1073741824 = 0.0209 using 1.31 GB
Read 100788 reads. Hash load: 22531055 / 1073741824 = 0.021 using 1.31 GB
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz': discarded 1954 reads shorter than 60 bases
Reading `/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz'...
Read 100000 reads. Hash load: 29560223 / 1073741824 = 0.0275 using 1.6 GB
Read 200000 reads. Hash load: 36267782 / 1073741824 = 0.0338 using 1.87 GB
```

**Comment by sjackman** [comment]
How many reads are in the file `alleghaniensis-READ-singleton.fastq.gz`?

**Comment by GideonPisanty** [comment]
I don't know how to check this. The file is 32 MB, I have much larger ones from other libraries...

**Comment by sjackman** [comment]
```sh
gunzip -c alleghaniensis-READ-singleton.fastq.gz
```
to report the number of lines, and then divide by 4.
Please also report the output of…
```sh
abyss-tofastq alleghaniensis-READ-singleton.fastq.gz | wc -l
```

**Comment by GideonPisanty** [comment]
it gives three numbers: 1515544, 1894430, 149810599. The second one gives 1515544, 1894430, 150568371.

Divided by 4:  378886, 473607.5, 37452650
                       378886, 473607.5, 37642093









--

**Comment by sjackman** [comment]
The first number is the number of lines. You have 378,886 reads. I would expect it to print at `Read 300000 reads.` and then `Read 378886 reads.`, but it appears to be getting stuck somewhere between 200k and 300k. How much memory do you have on this machine? Please report…
```sh
free -m
```

**Comment by sjackman** [comment]
> `abyss-k60.err.log`

```
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ1.fastq.gz': discarded 1046 reads shorter than 60 bases
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ2.fastq.gz': discarded 1954 reads shorter than 60 bases
`/home/pisantyg/share/Miseq_run_TE08_Jan_19_2018/uce-clean/alleghaniensis/split-adapter-quality-trimmed/alleghaniensis-READ-singleton.fastq.gz': discarded 7846 reads shorter than 60 bases
condaflmake: *** [out_k60-1.fa] Interrupt
```

Are you running this job on a local machine, or on a HPC cluster with a scheduler? `Interrupt` typically means that something intentionally killed job, possibly the scheduler, for exceeding RAM limits.

**Comment by GideonPisanty** [comment]
```
pisantyg@pisantyg-VirtualBox:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1994         178        1676           4         139        1660
Swap:          2045         402        1643
```

The "interrupt" is just because I stopped the program once I was frustrated with it after so many hours. I am running it on a local ubuntu.

**Comment by sjackman** [comment]
```
Read 200000 reads. Hash load: 36267782 / 1073741824 = 0.0338 using 1.87 GB
```
You have 2 GB of memory, so you're exceeding your available memory. You have two options:
1. Use a tool such as https://github.com/lh3/bfc to correct your reads before assembly
2. Use the Bloom filter assembly mode of ABySS, which uses roughly a tenth of the memory of the hash table mode that you're currently using.

See https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph

**Comment by benvvalk** [comment]
Thank you, @sjackman!

**Comment by sjackman** [comment]
@benvvalk ABySS could pretty easily get the available amount of memory and print a warning message when the amount being used exceeds that limit.

**Comment by benvvalk** [comment]
@sjackman Suggestion noted! I didn't know if there was a portable way to find out the available memory on a machine, but I've never looked into it.

**Comment by GideonPisanty** [comment]
Thank you very much for helping me out with this. I appreciate it. I should probably run the analysis on our institute's "biocluster" rather than a VBox.

**Comment by sjackman** [comment]
@benvvalk I haven't found a portable way. Here's some options:
macOS: `sysctl hw.memsize`
Linux: `sysinfo` https://stackoverflow.com/questions/349889/how-do-you-determine-the-amount-of-linux-system-ram-in-c

**Comment by benvvalk** [comment]
Thanks @sjackman :-)

**Comment by GideonPisanty** [comment]
Can I fix this by adding swap space? Or does only RAM count?

**Comment by GideonPisanty** [comment]
Actually the computer's RAM is 32GB. I don't know why only 2GB are available in the VBox. Maybe something in the settings.

**Comment by benvvalk** [comment]
@GideonPisanty Yes, there is a setting for how much memory you want to allocate for the VM.

**Comment by GideonPisanty** [comment]
Thanks

**Comment by mmokrejs** [comment]
```
linux$ free
              total        used        free      shared  buff/cache   available
Mem:       16366496     3535624      531852      579560    12299020    11915716
Swap:             0           0           0
linux$
```
