### ISSUE TITLE
Running 'ABYSS -k${ksize} -q3 --coverage-hist=coverage.hist -s ${proj}-bubbles.fa in parallel?

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#185]
Hi,
  I wonder why this is running only in a single thread. I have 2 PE libs and 9 MP files (various levels of confidence of true MP-pairs). Why couldn't abyss act on then in parallel?

`abyss-pe j=104 k=128 name=... lib='...' mp='...'.`

 I want to run using 104 local threads, no MPI. This is abyss-2.0.2.

**Comment by benvvalk** [comment]
Common point of confusion.  Parallelism in the first pipeline stage (de Bruijn graph assembly) is implemented with MPI, not with threads. (Later stages of the pipeline are multithreaded.) So if you want parallelism all the way through you will have to compile with MPI, even if you are just running the job on a single machine.  This is what I would recommend.

Alternatively, if use the new ABySS Bloom filter assembly mode (https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph), you *can* have parallelism all the way through using just threads.  The tradeoffs with using the Bloom filter assembly mode vs. the default (MPI) assembly mode are: (i) you have to manually calculate/estimate a few Bloom filter parameters, (ii) the running time is roughly twice as long, (iii) the contiguity is not (quite) up to par with the default assembly mode yet.   Positives of Bloom filter assembly mode are easier multithreading and greatly reduced memory usage (1/10th of MPI assembly mode).

**Comment by mmokrejs** [comment]
Hi Ben,
  1. please, update the manual to eplain that. I am not surprised this is a common confusion.
  2. could you elaborate how long is this single-threaded step going to last? It is still processing the first file paired-end file.
  3. your answer does not explain^H^H^H^H^Hexclude the possibility that all the input files would be processed in concurrent threads and the results merged ater that. Does it mean this is doable?
   4. I do have MPI support enabled but I did not bother to do that because I have 104 local CPUs and 3.2TB local RAM.
   5. I avoided the Bloom filter because I have no experince with abyss' requirements for this fish genome, supposedly 1.7Gbp haploid. I think I have at the moment enough RAM so another reason why I did not care about fiddling with the Bloom filter. If you have some general advices, please improve the manual. I will be happy to re-consider that.
   6. So shall I kill the jobs and start under MPI, albeit locally?

**Comment by sjackman** [comment]
> So shall I kill the jobs and start under MPI, albeit locally?

Yes. Local MPI uses shared memory to pass messages between processes and is quite fast, and you will benefit from your multiple CPUs.

**Comment by benvvalk** [comment]
@mmokrejs 

> 1. please, update the manual to eplain that. I am not surprised this is a common confusion.

Okay, criticism accepted.

> 6. So shall I kill the jobs and start under MPI, albeit locally?

Yes, it will be much, much faster.  Use the `np` parameter to specify number of MPI processes for the first (de Bruijn graph) stage and `j` to specify number of threads for later assembly stages.   If ABySS has been successfully compiled with MPI support, you should have a `ABYSS-P` binary on your `PATH`.

**Comment by benvvalk** [comment]
@mmokrejs 

> 3. your answer does not explain^H^H^H^H^Hexclude the possibility that all the input files would be processed in concurrent threads and the results merged ater that. Does it mean this is doable?

Unfortunately, no.   Genome is not an "embarassingly parallel" type of problem where the input files can be split up, processed independently, and then the results merged.

**Comment by mmokrejs** [comment]
> Unfortunately, no. Genome assembly is not an "embarassingly parallel" type of problem where the input files can be split up, processed independently, and then merged.

But during k-mer spliting and counting, you could do that in parallel, and then merge the dictionary counters right? It is my impression this "--coverage-hist" step is just about this.

**Comment by sjackman** [comment]
Loading is parallelized by file. Each process reads and distributes one file.

**Comment by mmokrejs** [comment]
Then something prevented this to happen, see the original posting. There were 2 libraries with paired-end data (split into _1 and _2 files), and several for mate-pair libraries. Please test this on your favorite dataset. Once I used the `np=104` it was running in parallel since the very beginning.

**Comment by sjackman** [comment]
> These two "0 and 1 workers" are because there are two paired-end dataset files

It sounds as though it's behaving as designed.

**Comment by sjackman** [comment]
> Once I used the np=104 it ran in parallel since the very beginning.

Oh, are you seeing that it's not running in parallel with `np=1`? That's expected.

**Comment by mmokrejs** [comment]
> Oh, are you saying that it's not running in parallel with np=1? That's expected.

Yes, that is what I mean but the confusion stems from the fact that `j=104` helps nothing in this routine but `np=104` sdoes miracles although I did not configure MPI on the local machine, as 104 phys cores are enough for me. I expected at least 2 processes to be running with `j=104 np=1` (if not 104 OpenMP threads), and actually I thought even the mate-pair data files could be also processed right-away, no matter they will be used a bit later. Probably they are not used at all for k-mer countings, only for read-mapping and a scaffolding?

Anyway, `np=`104` really made this 2-worker part parallel, as Ben and you suggested. And `np=104 j=104` did not make things worse (raising 104*104 threads). My point was that this hash-filling process seems to be rather slowly reading input data, whether that is because of MPI overhead on the local machine or elsewhere, i do not know.

**Comment by sjackman** [comment]
> Probably they are not used at all for k-mer countings, only for read-mapping and a scaffolding?

Yes, correct. This decision was made before Nextera libraries, when mate-pair reads were chimeric. With Nextera libraries corrected with NxTrim, you could use the mate-pair reads for *k*-mer coverage, if you needed the coverage.

**Comment by sjackman** [comment]
> And np=104 j=104 did not make things worse (raising 104*104 threads)

`ABYSS-P` is not hybrid OpenMPI + OpenMP. `np=104 j=104` uses only 104 threads, not 104*104.

**Comment by sjackman** [comment]
> My point was that this hash-filling process seems to be rather slowly reading input data

Yes, loading speeding could be improved, but it's not a development priority for us.

**Comment by mmokrejs** [comment]
> ABYSS-P is not hybrid OpenMPI + OpenMP. np=104 j=104 uses only 104 threads, not 104*104.

So then https://github.com/bcgsc/abyss/issues/185#issuecomment-363173408 was incorrect. That made to use `np=104 j=104` hoping sometimes it will run in MPI mode and sometime in OpenMP.

**Comment by sjackman** [comment]
ABYSS-P usen MPI. All subsequent programs of the `abyss-pe` pipeline use OpenMP.

**Comment by mmokrejs** [comment]
> Yes, correct. This decision was made before Nextera libraries, when mate-pair reads were chimeric. With Nextera libraries corrected with NxTrim, you could use the mate-pair reads for k-mer coverage, if you needed the coverage.

This is again missing from the README.md. Of course I can put aside all short-insert PE pairs if I run prior to abyss another tools to map my reads to temporary, strict assembly. One would have hoped that abyss could do this on-the-fly.

**Comment by mmokrejs** [comment]
> ABYSS-P usen MPI. All subsequent programs of the abyss-pe pipeline use OpenMP.

So Ben was correct.

**Comment by benvvalk** [comment]
@sjackman Thank you for taking the time to reply to this morning's deluge of messages. You are under no obligation, but I appreciate whatever help you are able to provide.

@mmokrejs Thank you for your many constructive suggestions and criticisms.

**Comment by mmokrejs** [comment]
But where are the commits of the improvements to the documentation? I would prefer if this issue was kept open until all of this gets transformed into documentation ofr everybody. Please reopen. Thank you.

**Comment by sjackman** [comment]
Feel free to open a pull request if you are so inclined.
