### ISSUE TITLE
abyss-overlap assertion errors

### ISSUE THREAD

**Issue by fungs** [bcgsc/abyss#192]
Hi,

I'm trying to overlap a small number of sequences in FASTA format, some of them are only 700 bp, some like 300 kb or longer. I'm unable to get a successful run of abyss-overlap with my input.

    abyss-overlap input.fna > output
    abyss-overlap: ../DataLayer/FastaIndex.h:83: void FastaIndex::index(const string&): Assertion `c == '>'' failed.

or

    abyss-overlap input.fna > output
    abyss-overlap: ../DataLayer/FastaIndex.h:38: std::istream& operator>>(std::istream&, FAIRecord&): Assertion `o.size == lineLen || lineLen == lineBinLen' failed.

I suppose that the command takes a FASTA file...

Thanks!

**Comment by sjackman** [comment]
Hi, Johannes. Sorry for the terrible error message. The input FASTA file must have no line breaks in the sequence. Use `seqtk seq input.fna` to remove the line breaks. `abyss-overlap` doesn't get a lot of usage. You may want to consider using `minimap2` instead.

**Comment by fungs** [comment]
Thanks! 

Minimap has IMO a terrible user experience :(

**Comment by mmokrejs** [comment]
@sjackman So why don't you take this Issue as a tracker to improve abyss or at least the error message? I suggest reopening this issue.

**Comment by sjackman** [comment]
We close issues on which no one is actively working. You're welcome to submit a PR if you'd like to adopt this issue.
