### ISSUE TITLE
Output N50 is 0

### ISSUE THREAD

**Issue by dearxxj** [bcgsc/abyss#198]
Hi Shaun and Ben,

Thank you for developping such a great tool. I recently used abyss2 to assemble a human genome. The program was able to finish without errors, but the output doesn't make sense to me. First I saw the stats are all zeros in the output-stats.tab file.

n	n:500	L50	min	N80	N50	N20	E-size	max	sum
6180060	0	0	0	0	0	0	0	0	0	
6180060	0	0	0	0	0	0	0	0	0	
6180060	0	0	0	0	0	0	0	0	0

Then I noticed that there are 8 sets of .dot/.path/.fa in the output folder. All .dot files are of the same size (167G), all but one (output-2.path) .path file are empty, and all .fa files are of the same size (799M). I checked the output-8.fa (scaffords) and found that the scaffords are simply the raw reads. The command I used is from the supplementary tables of your paper. I was wondering how I can fix this problem?  Thank you for your help.

module load openmpi
abyss-pe name=$PREFIX np=64 k=96 q=15 v=-v l=40 s=1000 n=10 B=40G H=4 kc=3 S=1000-10000 N=7 mp6k_de=--mean mp6k_n=1 in="$FASTQ_1 $FASTQ_2"

Fan

**Comment by benvvalk** [comment]
Hi @dearxxj,

Can you post your full ABySS log output (both STDERR and STDOUT)?  I think that will help to identify the problem.  You can either post the log output on this ticket or link to a Gist: https://gist.github.com/

Also can you show the output of running `abyss-fac *.fa` in your assembly directory?

**Comment by benvvalk** [comment]
Your `abyss-pe` command looks reasonable, btw.

**Comment by dearxxj** [comment]
Thank you for the quick response. The abyss-fac command also shows that N50 is zero.

n       n:500   L50     min     N80     N50     N20     E-size  max     sum     name
6197900 0       0       0       0       0       0       0       0       0       output-1.fa
6186533 0       0       0       0       0       0       0       0       0       output-2.fa
6180060 0       0       0       0       0       0       0       0       0       output-3.fa
output-4.fa:0: warning: file is empty
0       0       0       0       0       0       0       0       0       0       output-4.fa
output-5.fa:0: warning: file is empty
0       0       0       0       0       0       0       0       0       0       output-5.fa
6180060 0       0       0       0       0       0       0       0       0       output-6.fa
output-7.fa:0: warning: file is empty
0       0       0       0       0       0       0       0       0       0       output-7.fa
6180060 0       0       0       0       0       0       0       0       0       output-8.fa
6180060 0       0       0       0       0       0       0       0       0       output-contigs.fa
output-indel.fa:0: warning: file is empty
0       0       0       0       0       0       0       0       0       0       output-indel.fa
6180060 0       0       0       0       0       0       0       0       0       output-scaffolds.fa

A snapshot of the log output can be found here: [https://gist.github.com/dearxxj/223b61c0f2bf26616952a5d4de13a7c7]

I just realized that my fastq files have different read length for reverse and forward reads (All R1 reads are 100bp long, and all R2 reads are 80bp long). Will this be the problem?

Thanks.
Fan

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
What genome are you sequencing? What is its estimated genome size? How much sequencing data do you have? What is your estimated depth of sequencing?

**Comment by dearxxj** [comment]
It is from a human cancer tissue, so there can be aneuploidy and copy number change compared with the reference genome. The sequencing depth is about 100X.

**Comment by benvvalk** [comment]
@dearxxj I note the following line in your log output, which is probably the root cause of your problems:
```
slurmstepd: Job 285354 exceeded memory limit (172466316 > 157286400), being killed
```
Is it possible to test your assembly on a machine with more memory?

**Comment by dearxxj** [comment]
I thought I've solved this problem by re-ran it with larger memory (see log after that line). Is the program supposed to pick up from where it stopped?

**Comment by dearxxj** [comment]
I'm not sure this is the cause. The job was killed when generating output-6.dot, but the problem already seems to start from output-1.fa?

**Comment by sjackman** [comment]
100 and 80 bp paired-end reads are unusual. Did something go wrong with this sequencing run, or is there something else unusual about this sequencing data? Try running FastQC and ntCard + Genomescope on your sequencing data to rule out sequencing quality issues.
