### ISSUE TITLE
ABYSS-P would not compile

### ISSUE THREAD

**Issue by rhinempi** [bcgsc/abyss#199]
Hi, I have struggled with this problem for few days now, hope someone could help me.

I am trying to install abyss with MPI implementation on my cluster. I have properly configured the mpi lib with the option "--with-mpi" and also got the info dump as:
checking for PTHREAD_PRIO_INHERIT... yes
checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking for MPI_Init in -lmpi... yes
checking for sqrt in -lm... yes
checking for pow... yes

However, after installation. I still get no ABYSS-P executable in the bin dir.

I am using Abyss-2.0.2 pack on the github release with a mpi-3.0.0 installation.

Thank you in advance.
Liren

**Comment by rhinempi** [comment]
I have fixed it in the end.

**Comment by benvvalk** [comment]
Thanks for reporting back that you solved it.

If ABySS cannot find an MPI library during the `configure` step, the 
ABYSS-P binary is not built.  If your MPI library isn't installed in a 
standard location (i.e. /usr/lib), you need to specify the MPI 
installation directory (which should contain `include` and `lib` 
subdirectories) using the `--with-mpi` option of `configure`.

**Comment by sjackman** [comment]
@rhinempi I'd recommend installing ABySS using either Linuxbrew or Homebrew. See http://linuxbrew.sh for Linux or https://brew.sh for macOS then run…
```sh
brew install abyss
```
