### ISSUE TITLE
abyss-pe pe-bam default runs abyss-map twice

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#202]
Hi,
  I wonder what I did wrong on the commandline

`abyss-pe pe-bam mp-bam default ...`

  so that my paired-end datafiles are mapped twice using abyss-map. Once .bam file is created, second time .sam.gz is created. It is just wasting my CPU time. The SAM file could have been created by conversion from BAM, if needed (or vice versa). Anyway, I only asked for BAM, not SAM format.

```
$ grep -A 3 abyss-map abyss_ecc.69521.log
abyss-map -v  -j104 -l40    lib1.fasta orgname__abyss_160-3.fa \
	|abyss-fixmate -v  -l40  -h lib1.1.pe-3.hist \
	|sort -snk3 -k4 \
	|samtools view -Sb - -o lib1.1.pe-3.bam
--
abyss-map -v  -j104 -l40    lib2.fasta orgname__abyss_160-3.fa \
	|abyss-fixmate -v  -l40  -h lib2.2.pe-3.hist \
	|sort -snk3 -k4 \
	|samtools view -Sb - -o lib2.2.pe-3.bam
--
abyss-map -v  -j104 -l40    lib1.fasta orgname__abyss_160-3.fa \
	|abyss-fixmate -v  -l40  -h lib1.1.pe-3.hist \
	|sort -snk3 -k4 \
	|gzip >lib1.1.pe-3.sam.gz
--
abyss-map -v  -j104 -l40    lib2.fasta orgname__abyss_160-3.fa \
	|abyss-fixmate -v  -l40  -h lib2.2.pe-3.hist \
	|sort -snk3 -k4 \
	|gzip >lib2.2.pe-3.sam.gz
```

![after_back-mapping_of_2_pe_datasets](https://user-images.githubusercontent.com/3297852/37524427-1a1f3ae0-292a-11e8-8275-d9414fbcbce2.png)
The first two blue "peaks" are BAM-file mapping (since about 3AM), the latter two are "SAM-file" mapping processes.

Sidenote: I think we came already across this but could I prevent abyss-map from replacing readnames with the asterisk? I want valid SAM/BAM file for inspection by other tools.

**Comment by sjackman** [comment]
That's a bug in `abyss-pe`. GNU make 3.81 runs `abyss-map` only once. GNU make 4.2.1 runs `abyss-map` twice for the `pe-bam`, but oddly not for `mp-bam`, which is odd.

# make 3.81

```
❯❯❯ make --version
GNU Make 3.81
❯❯❯ make -f ~/.homebrew/bin/abyss-pe pe-bam mp-bam default name=foo lib=pea pea=pea.fq.gz -n | egrep 'abyss-map|samtools'
abyss-map   -j2 -l40    pea.fq.gz foo-3.fa \
samtools view -Sb pea-3.sam.gz -o pea-3.bam
samtools index pea-3.bam
abyss-map   -j2 -l40    pea.fq.gz foo-6.fa \
samtools view -Sb pea-6.sam.gz -o pea-6.bam
samtools index pea-6.bam
```

# make 4.2.1
```
❯❯❯ make --version
GNU Make 4.2.1
❯❯❯ make -f ~/.homebrew/bin/abyss-pe pe-bam mp-bam default name=foo lib=pea pea=pea.fq.gz -n | egrep 'abyss-map|samtools'
abyss-map   -j2 -l40    pea.fq.gz foo-3.fa \
	|samtools view -Sb - -o pea-3.bam
samtools index pea-3.bam
abyss-map   -j2 -l40    pea.fq.gz foo-3.fa \
abyss-map   -j2 -l40    pea.fq.gz foo-6.fa \
samtools view -Sb pea-6.sam.gz -o pea-6.bam
samtools index pea-6.bam
```

**Comment by sjackman** [comment]
A work around is to run `abyss-pe pe-sam mp-sam default` in one command, and then run `abyss-pe pe-bam mp-bam` in a second command, after the first has finished, which *should* use `samtools view` to convert the SAM.gz to BAM.

```
❯❯❯ gmake -f ~/.homebrew/bin/abyss-pe pe-sam mp-sam default name=foo lib=pea pea=pea.fq.gz -n | egrep 'abyss-map|samtools'
abyss-map   -j2 -l40    pea.fq.gz foo-3.fa \
abyss-map   -j2 -l40    pea.fq.gz foo-6.fa \
```

**Comment by sjackman** [comment]
> Sidenote: I think we came already across this but could I prevent abyss-map from replacing readnames with the asterisk? I want valid SAM/BAM file for inspection by other tools.

The query name is elided to significantly reduce disk space of the SAM.gz and BAM files. Set `abyss-pe FIXMATE_OPTIONS=--qname` to preserve it.
```
❯❯❯ abyss-fixmate --help | grep qname
      --no-qname        set the qname to * [default]
      --qname           do not alter the qname
```

Which tool doesn't like `qname` set to `*`? IGV is fine, I think, though it won't be able to pair the reads.

**Comment by mmokrejs** [comment]
Weird, I also have make 4.2.1 but although I ran `abyss-pe pe-sam mp-sam default ...` and then `abyss-pe pe-bam mp-bam default ...` it is runing `abyss-map` again, not samtools.

**Comment by sjackman** [comment]
Yes, I'm seeing two `abyss-map` at the unitigs stage as well with `make` 4.2.1. I've looked into it a bit just now, and as far as I can tell, it looks like it may be a bug in `make` 4.2.1. It's a bit weird in any case. The following patch helps, in that it prevents running `abyss-map` twice. It causes it to write to a SAM.gz file, and then convert that to a BAM file, which would be the preferred behaviour for `abyss-pe pe-sam mp-sam pe-bam mp-bam default`. The preferred behaviour for `abyss-pe pe-bam mp-bam default` would be to write directly to a BAM file.

```diff
diff --git a/bin/abyss-pe b/bin/abyss-pe
index 4170facb..437b2351 100755
--- a/bin/abyss-pe
+++ b/bin/abyss-pe
@@ -558,6 +558,9 @@ endif
 
 # Estimate distances between unitigs
 
+%-3.bam: %-3.sam.gz
+	samtools view -Sb $< -o $@
+
 %-3.sam.gz %-3.hist: $(name)-3.fa
 	$(align) $(mapopt) $(strip $($*)) $< \
 		|$(fixmate) $(fmopt) -h $*-3.hist \
@@ -648,6 +651,9 @@ endif
 
 # Estimate distances between contigs
 
+%-6.bam: %-6.sam.gz
+	samtools view -Sb $< -o $@
+
 %-6.sam.gz %-6.hist: $(name)-6.fa
 	$(align) $(mapopt) $(strip $($*)) $< \
 		|$(fixmate) $(fmopt) -h $*-6.hist \
```

**Comment by mmokrejs** [comment]
@sjackman Thank you, the patch at least works around the bug in `GNU make`. would be worth to report the bug to `make` developers.

**Comment by mmokrejs** [comment]
Seems the above patch causes `abyss-pe` to exit if I asked only for BAM files to be kept and after sam.gz files are deleted.

Full log is at http://195.113.57.32/~mmokrejs/tmp/abyss_ecc.38989.log The shellscript calling abyss-pe was executed via "bash -x script.sh".

```
abyss_k128_ecc_N10 $ ls -latr
total 17302844
-rw-rwx---  1 mmokrejs mmokrejs        447 Mar 31 23:20 abyss_ecc.pbs
-rw-------  1 mmokrejs mmokrejs          0 Apr  1 09:26 abyss_ecc_k128.o7925723
-rw-------  1 mmokrejs mmokrejs          0 Apr  1 09:26 abyss_ecc_k128.e7925723
-rw-rwx---  1 mmokrejs mmokrejs       8176 Apr  1 10:19 abyss_ecc.sh
drwxrwx--- 27 mmokrejs mmokrejs       4096 Apr  1 10:52 ..
-rw-rw----  1 mmokrejs mmokrejs     463186 Apr  2 07:57 coverage.hist
-rw-rw----  1 mmokrejs mmokrejs 2280354895 Apr  2 09:12 tt_16D1C3L12__abyss_128-1.fa
-rw-rw----  1 mmokrejs mmokrejs  147265493 Apr  2 09:12 tt_16D1C3L12__abyss_128-bubbles.fa
-rw-rw----  1 mmokrejs mmokrejs          0 Apr  2 09:14 tt_16D1C3L12__abyss_128-1.path
-rw-rw----  1 mmokrejs mmokrejs  938991794 Apr  2 09:14 tt_16D1C3L12__abyss_128-1.dot
-rw-rw----  1 mmokrejs mmokrejs  634066702 Apr  2 09:19 tt_16D1C3L12__abyss_128-2.dot1
-rw-rw----  1 mmokrejs mmokrejs 1668119753 Apr  2 09:20 tt_16D1C3L12__abyss_128-2.fa
-rw-rw----  1 mmokrejs mmokrejs  634066702 Apr  2 09:20 tt_16D1C3L12__abyss_128-2.dot
-rw-rw----  1 mmokrejs mmokrejs  595957642 Apr  2 09:24 tt_16D1C3L12__abyss_128-3.dot
-rw-rw----  1 mmokrejs mmokrejs    4002831 Apr  2 09:24 tt_16D1C3L12__abyss_128-2.path
-rw-rw----  1 mmokrejs mmokrejs 1601478564 Apr  2 09:25 tt_16D1C3L12__abyss_128-3.fa
-rw-rw----  1 mmokrejs mmokrejs   37444644 Apr  2 09:26 tt_16D1C3L12__abyss_128-indel.fa
-rw-rw----  1 mmokrejs mmokrejs 4172024922 Apr  2 12:15 HKMHTBCXX.1.pe-3.bam
-rw-rw----  1 mmokrejs mmokrejs  249212648 Apr  2 12:16 HKMHTBCXX.1.pe-3.bam.bai
-rw-rw----  1 mmokrejs mmokrejs      28970 Apr  2 15:02 HT5V3BCXY.2.pe-3.hist
-rw-rw----  1 mmokrejs mmokrejs 4500371552 Apr  2 15:21 HT5V3BCXY.2.pe-3.bam
-rw-rw----  1 mmokrejs mmokrejs  252003800 Apr  2 15:22 HT5V3BCXY.2.pe-3.bam.bai
-rw-rw----  1 mmokrejs mmokrejs    1739334 Apr  2 17:55 abyss_ecc.38989.log
```
