### ISSUE TITLE
abyss-2.0.2: --qname does not prevent zapping the other mate with an asterisk

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#207]
`abyss-pe FIXMATE_OPTIONS=--qname  ...` should prevent abyss with rewriting readnames with an asterisk ( see https://github.com/bcgsc/abyss/issues/202#issuecomment-373825553  ). Somehow, it helps only with the 'self' read, not with its 'mate'.
```
$ gzip -dc  HFYJ5AFXX.8kb.lmp-6.sam.gz | grep -v '^@SQ' | grep NB501598:62:HFYJ5AFXX:1:11112:24481:10845 
NB501598:62:HFYJ5AFXX:1:11112:24481:10845	129	6	1	0	2S150M	5969146	15	16	*	*
NB501598:62:HFYJ5AFXX:1:11112:24481:10845	65	5969146	15	0	121M	6	1	-16	*	*
```

**Comment by sjackman** [comment]
I'm not following. The QNAME of both the read and its mate is `NB501598:62:HFYJ5AFXX:1:11112:24481:10845`, and neither is `*`. The 10th and 11th sequence and quality fields are `*`.
