### ISSUE TITLE
abyss-fixmate: dump out plaintext files with read orientations and insert-sizes

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#211]
In https://github.com/bcgsc/abyss/issues/164#issuecomment-363865637 I already proposed improving `abyss-fixmate` to report separately read pairs with RF (Nextera long mate-pairs) and FR (Illumina paired-end reads) orientation. I tried to find out if anybody else tried to achieve this before but at the best I found https://sourceforge.net/p/samtools/mailman/message/27971698/ . My idea is to have two or even four files for FR, RF, RR, FF orientations. Each file would contain `readname` and `outer insertsize`, line by line. Thank you.

**Comment by sjackman** [comment]
Hi, Martin. We don't have the time to implement this feature ourselves in ABySS. You should be able to accomplish this task using `samtools view -f xxx -F yyy` and `gawk` to filter on whether the `inferred template size` is positive or negative. It may be easier to write a Python or R script to accomplish this task. I feel it's likely that someone has already done this before. You could try asking on Biostars, SEQanswers, or Twitter.
