### ISSUE TITLE
abyss-2.0.3: bgzip do not receive number of threads to be used from parent

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#212]
```
abyss-map -v  -j104 -l40    /scratch/work/project/bio/open-9-41/tt_16D1C3L12/paired_end_619bp//HKMHTBCXX.1.tt_16D1C3L12.trimmomatic.prinseq.minlen20.tadpole.k62.fasta tt_16D1C3L12__abyss_128-3.fa \
        |abyss-fixmate -v  -l40 --qname -h HKMHTBCXX.1.pe-3.hist \
        |sort -snk3 -k4 \
        |bgzip -@ >HKMHTBCXX.1.pe-3.sam.gz
bgzip: option requires an argument -- '@'

Reading from standard input...Version: 1.5

Reading `Usage:   bgzip [OPTIONS] [FILE] ...
tt_16D1C3L12__abyss_128-3.faOptions:
'...
   -b, --offset INT        decompress at virtual file pointer (0-based uncompressed offset)
   -c, --stdout            write on standard output, keep original files unchanged
   -d, --decompress        decompress
   -f, --force             overwrite files without asking
   -h, --help              give this help
   -i, --index             compress and create BGZF index
   -I, --index-name FILE   name of BGZF index file [file.gz.gzi]
   -r, --reindex           (re)index compressed file
   -g, --rebgzip           use an index file to bgzip a file
   -s, --size INT          decompress INT bytes (uncompressed size)
   -@, --threads INT       number of compression threads to use [1]
```

Seems variable `"$t"` is unset. Shouldn't it be filled-in by a value of `"$j"` or `"$np"`? Or at least a sane default? Full log is at http://195.113.57.32/~mmokrejs/tmp/abyss_ecc.38989.log The shellscript calling abyss-pe was executed via "bash -x script.sh".

```
abyss_k128_ecc_N10 $ ls -latr
total 17302844
-rw-rwx---  1 mmokrejs mmokrejs        447 Mar 31 23:20 abyss_ecc.pbs
-rw-------  1 mmokrejs mmokrejs          0 Apr  1 09:26 abyss_ecc_k128.o7925723
-rw-------  1 mmokrejs mmokrejs          0 Apr  1 09:26 abyss_ecc_k128.e7925723
-rw-rwx---  1 mmokrejs mmokrejs       8176 Apr  1 10:19 abyss_ecc.sh
drwxrwx--- 27 mmokrejs mmokrejs       4096 Apr  1 10:52 ..
-rw-rw----  1 mmokrejs mmokrejs     463186 Apr  2 07:57 coverage.hist
-rw-rw----  1 mmokrejs mmokrejs 2280354895 Apr  2 09:12 tt_16D1C3L12__abyss_128-1.fa
-rw-rw----  1 mmokrejs mmokrejs  147265493 Apr  2 09:12 tt_16D1C3L12__abyss_128-bubbles.fa
-rw-rw----  1 mmokrejs mmokrejs          0 Apr  2 09:14 tt_16D1C3L12__abyss_128-1.path
-rw-rw----  1 mmokrejs mmokrejs  938991794 Apr  2 09:14 tt_16D1C3L12__abyss_128-1.dot
-rw-rw----  1 mmokrejs mmokrejs  634066702 Apr  2 09:19 tt_16D1C3L12__abyss_128-2.dot1
-rw-rw----  1 mmokrejs mmokrejs 1668119753 Apr  2 09:20 tt_16D1C3L12__abyss_128-2.fa
-rw-rw----  1 mmokrejs mmokrejs  634066702 Apr  2 09:20 tt_16D1C3L12__abyss_128-2.dot
-rw-rw----  1 mmokrejs mmokrejs  595957642 Apr  2 09:24 tt_16D1C3L12__abyss_128-3.dot
-rw-rw----  1 mmokrejs mmokrejs    4002831 Apr  2 09:24 tt_16D1C3L12__abyss_128-2.path
-rw-rw----  1 mmokrejs mmokrejs 1601478564 Apr  2 09:25 tt_16D1C3L12__abyss_128-3.fa
-rw-rw----  1 mmokrejs mmokrejs   37444644 Apr  2 09:26 tt_16D1C3L12__abyss_128-indel.fa
-rw-rw----  1 mmokrejs mmokrejs 4172024922 Apr  2 12:15 HKMHTBCXX.1.pe-3.bam
-rw-rw----  1 mmokrejs mmokrejs  249212648 Apr  2 12:16 HKMHTBCXX.1.pe-3.bam.bai
-rw-rw----  1 mmokrejs mmokrejs      28970 Apr  2 15:02 HT5V3BCXY.2.pe-3.hist
-rw-rw----  1 mmokrejs mmokrejs 4500371552 Apr  2 15:21 HT5V3BCXY.2.pe-3.bam
-rw-rw----  1 mmokrejs mmokrejs  252003800 Apr  2 15:22 HT5V3BCXY.2.pe-3.bam.bai
-rw-rw----  1 mmokrejs mmokrejs    1739334 Apr  2 17:55 abyss_ecc.38989.log
```

**Comment by benvvalk** [comment]
@mmokrejs Thanks for reporting,  I think you are right.  I think this is fixed by ca7691242135d05012f339ab78b36d5a382d8a2a, which will be included in the next release.  I'm not sure when the next release will be, but you can additionally set `t` in the meantime, or compile from HEAD of `master`.

**Comment by mmokrejs** [comment]
I was more hoping your answer will be that it is intended to expose $t so that users could specify amount of threads to be used for pigz and bgzip. In the case I shoiwed I would otherwise assume t=$j - 4 and a check $t > 0.

**Comment by benvvalk** [comment]
@mmokrejs In the above-mentioned commit (ca76912), the number of threads for `bgzip` is taken from `$j`, as is currently done for all other multi-threaded programs in `abyss-pe`.  I think that would be the least surprising behaviour.

**Comment by mmokrejs** [comment]
I know but that does not make much sense (to allocate all threads to juzt pigz/bgzip if there are 4 other tools linked through pipes). I doubt pigz will be able to utilize 104 threads  in my case, and the other apps will be competing with them.

**Comment by benvvalk** [comment]
@mmokrejs Ah, I see your point now.  I was confused because you typed `$j - 4` instead of `$j / 4`.

**Comment by mmokrejs** [comment]
Actually `$j - 3` is correct:

```
abyss-map -v  -j104 -l40   foo.fasta tt_16D1C3L12__abyss_128-3.fa \
        |abyss-fixmate -v  -l40 --qname -h HKMHTBCXX.1.pe-3.hist \
        |sort -snk3 -k4 \
        |bgzip -@ >HKMHTBCXX.1.pe-3.sam.gz
```

There are four processes, the first three are assumingly single-threaded but the last is multithreaded.

**Comment by sjackman** [comment]
Do not set `t` which would set the trimming parameter of `ABYSS`.
You can install `pigz` to work around this error. Sorry for the gaff.
`sort` has to wait for `abyss-map` to finish mapping before it can complete the majority of its work.
Similarly `bgzip` must wait for `sort` to finish sorting before it can start compressing. For that reason, it's okay for `abyss-map`, `sort`, and `bgzip` to use 104 threads each.

I wonder what the default number of threads for GNU sort is. I can't find it in the manual page. I suppose 1?
```
❯❯❯ gsort --help | grep parallel
      --parallel=N          change the number of sorts run concurrently to N
```

**Comment by mmokrejs** [comment]
Hi Shaun,  you are right the last compression command has to wait for the previous `sort` to finish. Indeed, it sounds using `sort --parallel=$j` would be a helpful speedup and the default is most likely set to 1.

**Comment by sjackman** [comment]
Found it. `info sort`

> ‘--parallel=n’
Set the number of sorts run in parallel to n. By default, n is set to the number of available processors, but limited to 8, as there are diminishing performance gains after that. Note also that using n threads increases the memory usage by a factor of log n. Also see nproc invocation.

https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html
