### ISSUE TITLE
one more fall-through

### ISSUE THREAD

**Issue by notestaff** [bcgsc/abyss#218]
@sjackman is the fall-through here intentional?
https://github.com/bcgsc/abyss/blob/master/Common/SAM.h#L174

**Comment by benvvalk** [comment]
Looks like a bug to me, but I don't fully understand the logic of the method.  I may look at it again later.

**Comment by sjackman** [comment]
This one's not a bug. See https://github.com/bcgsc/abyss/pull/196/files#diff-21e390be6f90b1f6a7758f36250b1e72R175
