### ISSUE TITLE
Bloom Parameters for Assembling Human DNA (25-30X) 

### ISSUE THREAD

**Issue by kkapuria3** [bcgsc/abyss#219]
I am trying to assemble human DNA sequences with around (20-30X) coverage. I use multiple (3) paired-end inputs for this assembly. I am planning to run this on a 8 core 30 GB machine which I can scale up (on AWS) if it gives me a better assembly (not considering time as factor here). The command I am running is:

nohup abyss-pe k=64 lib='pe1 pe2 pe3' name=combined_aDNA pe1='1val_1.fq.gz 1val_2.fq.gz' pe2='2val_1.fq.gz 2val_2.fq.gz'  pe3='3val_1.fq.gz 3val_2.fq.gz'  B=30G H=3 j=6 kc=3 v=-v > abyss.combined.log

I wanted to know what values of B, H, kc, will help me increase the quality of assembly.

**Comment by benvvalk** [comment]
Hi @kkapuria3,

FYI, a good quality ABySS assembly requires >= 50X coverage.  But it is still worth a try.

Correcting the reads ahead of time with `bfc` (as done in the ABySS 2.0 paper) will help to greatly reduce your memory requirements.   If you don't correct the reads, I would expect the required memory to be more along the lines of 60GB-100GB.  The correction may (perhaps) help compensate for the low coverage.  Adding `q=15` (read quality trimming) can also help reduce memory usage. 

Your `B`, `H`, `kc` params look like a reasonable for a first attempt.  `B` and `H` don't matter so long as the assembler is reporting FPR (false positive rate) < ~15% in the log output.  `kc` can have a big impact on the results and must be determined trial and error, much like k-mer size.  I would recommend trying `kc=3` and `kc=4` to start.  Going lower than `kc=3` has never worked well for me and the running time increases a lot.

**Comment by kkapuria3** [comment]
Thank you so much. This helps a lot.
