### ISSUE TITLE
troubleshooting insufficient memory allocation

### ISSUE THREAD

**Issue by devonorourke** [bcgsc/abyss#223]
Hi folks,

Would love to know some strategies on how to reduce the memory needed to complete an assembly job. I have access to a compute cluster and in theory can do one of three things:
1. Access a node with ~ 1 Tb of memory.
2. Access up to four nodes with ~ 512 Gb of memory each.
3. Access up to twelve nodes with ~ 128 Gb of memory each. 

I'm trying to assemble a mammalian genome using just a single lane of Illumina 250 PE data. My first test was to try running `abyss-pe` without a Bloom filter for a variety of kmer lengths using the script below - the job failed when I specified five of the 128 Gb nodes first and indicated an insufficient memory issue; it then failed again when I specified seven of the 128 Gb nodes. 

**The command**:
```
mpirun -np 120 ABYSS-P -k51 -q3 -v   --coverage-hist=coverage.hist -s myse51-bubbles.fa  -o myse51-1.fa /pathto/reads1 /pathto/reads2
ABySS 2.1.0
ABYSS-P -k51 -q3 -v --coverage-hist=coverage.hist -s myse51-bubbles.fa -o myse51-1.fa /pathto/reads1 /pathto/reads2
```

**The error** message was always the same for every `k=...` value:
```
88: Hash load: 55607402 / 268435456 = 0.207 using 4.58 GB
82: Hash load: 55435977 / 268435456 = 0.207 using 4.56 GB
51: Hash load: 54978299 / 268435456 = 0.205 using 4.53 GB
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 68 with PID 124424 on node node132 exited on signal 9 (Killed).
--------------------------------------------------------------------------
make: *** [myse51-1.fa] Error 137
```

Thinking at applying a Bloom filter would reduce the memory usage significantly, I changed up my argument and selected just a single node with 512 Gb of memory and used the Bloom filter option. What's strange is that values for `k` of 51, 71, and 91 are all seeming to work just fine with the following parameters, but higher values like 111, 131, and 171 showed the same error message indicating jobs stopping due to insufficient memory allocation:

**The command** (one example for `k=51`:

```
make: Entering directory `/pathto/ABySS/k51'
abyss-bloom-dbg -k51 -q3 -v -b470G -H3 -j24 --kc=3  /pathto/reads1 /pathto/reads2 > myse51-1.fa
Assembling with k-mer size 51
Assembly parameters:
	K-mer size (-k): 51
	K-mer coverage threshold (--kc): 3
	Max branch trim length (-t): 51
	Bloom size in bytes (-b): 504658657280
	Bloom hash functions (-H): 3
```

**The error message** for `k=111`, or 131, or 171 is the same (in this example it's from `k=131`: 

```
Loaded 138110590 reads from `/pathto/reads2` into Bloom filter
Bloom filter FPR: 6.23e-05%
Stats for Bloom filter level 1:
        Bloom size (bits): 1009317314560
        Bloom popcount (bits): 22334581869
        Bloom filter FPR: 0.00108%
Stats for Bloom filter level 2:
        Bloom size (bits): 1009317314560
        Bloom popcount (bits): 9943749529
        Bloom filter FPR: 9.56e-05%
Stats for Bloom filter level 3:
        Bloom size (bits): 1009317314560
        Bloom popcount (bits): 8621000787
        Bloom filter FPR: 6.23e-05%
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
make: *** [myse131-1.fa] Aborted
```

Here's the weird thing: `k=151` doesn't fail. It proceeds past the point where the other moderately higher k-mer values were dying. Some info from the `k=151` log file:

```
abyss-bloom-dbg -k151 -q3 -v -b470G -H3 -j24 --kc=3  /pathto/reads1 /pathto/reads2  > myse151-1.fa
Assembling with k-mer size 151
Assembly parameters:
	K-mer size (-k): 151
	K-mer coverage threshold (--kc): 3
	Max branch trim length (-t): 151
	Bloom size in bytes (-b): 504658657280
	Bloom hash functions (-H): 3
Bloom filter FPR: 5.36e-05%
Stats for Bloom filter level 1:
	Bloom size (bits): 1009317314560
	Bloom popcount (bits): 21259842717
	Bloom filter FPR: 0.000935%
Stats for Bloom filter level 2:
	Bloom size (bits): 1009317314560
	Bloom popcount (bits): 9675196892
	Bloom filter FPR: 8.81e-05%
Stats for Bloom filter level 3:
	Bloom size (bits): 1009317314560
	Bloom popcount (bits): 8200510548
	Bloom filter FPR: 5.36e-05%
Trimming branches 151 k-mers or shorter
Assembly complete
AdjList -v   -k151 -m50 --dot myse151-1.fa >myse151-1.dot
```

I'm confused why I'd be running out of memory when all else is equal for `k=131` but not `k=151`; perhaps the issue isn't strictly the memory I've allocated? Even so, I'd love to better understand  what the best option would be to proceed to try testing out the higher kmer lengths. Thanks for any advice you can offer.

Cheers,
Devon

**Comment by sjackman** [comment]
> the job failed when I specified five of the 128 Gb nodes first and indicated an insufficient memory issue; it then failed again when I specified seven of the 128 Gb nodes.

```
51: Hash load: 54978299 / 268435456 = 0.205 using 4.53 GB
mpirun noticed that process rank 68 with PID 124424 on node node132 exited on signal 9 (Killed).
```
Your ABYSS-P job was using an aggregate ~4.6 * 120 = 552 GB of memory at this point, which is less than the allocated 7 * 128 = 896 GB. So, it should be possible. The job was killed (SIG 9 = SIGKILL) by either a scheduler, if you were running under the watchful eye of an HPC scheduler, or the Linux kernel OOM (out-of-memory) killer. If the former, you'll need to adjust the parameters of your job submission to request more memory. If the latter, were there any other processes running on this machine at the same time consuming memory? If not, check the memory usage of ABYSS-P by running `top`. Do you see the expected number of processes on this machine? 120 / 7 = ~17.14 processes per machine. It's quite possible that MPI did not distribute the processes evenly over the machines. I'd suspect this issue. Finally, check this FAQ https://github.com/bcgsc/abyss/wiki/ABySS-Users-FAQ#3-my-abyss-mpi-job-with-a-large-number-of-processors-over-1000-is-using-much-more-memory-than-expected-whats-up

@benvvalk can you answer your questions about the Bloom filter mode.

**Comment by sjackman** [comment]
@devonorourke A GDB backtrace could be helpful, if you know how to generate one. Something like…
```sh
ulimit -c unlimited
abyss-bloom-dbg …
gdb core.*
bt
```

**Comment by benvvalk** [comment]
@devonorourke I don't know what your genome size is (?),  but based on your reported FPR, you should be able to decrease -b470G to -b100G or perhaps even less. That may help to work around the issue, whatever it is. As long as the reported FPR for the final Bloom filter level is less than ~10% (i.e. 0.1),  neither the quality nor the running time should be affected.

**Comment by benvvalk** [comment]
Thank you, @sjackman. Yes, the GDB backtrace would be very helpful, if @devonorourke is able to generate it.

**Comment by devonorourke** [comment]
Thanks for all the advice @sjackman and @benvvalk. Oddly, I restarted the run the next morning and everything completed. I didn't change a thing, so without a reproducible error I'm not really sure what to make of this.

Should something like this pop up again I'll run the backtrace as suggested. Thanks again!

**Comment by benvvalk** [comment]
@devonorourke oh well, glad to hear it's working for you now, at least.
