### ISSUE TITLE
abyss-2.1.0:  cannot get openmpi recognized by configure

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#224]
Hi,
  I just realized that with abyss-2.1.0 I am not getting ABYSS-P binary. Would you please check the config.log and the other files. I see some gcc-7.3.0-related strict checks failing. I do have have this problem with abyss-2.0.2, though. Openmpi is 3.0.1 but I do not think this is relevant.

[build.log.txt](https://github.com/bcgsc/abyss/files/1979308/build.log.txt)
[config.log.txt](https://github.com/bcgsc/abyss/files/1979309/config.log.txt)
[config.status.txt](https://github.com/bcgsc/abyss/files/1979310/config.status.txt)

**Comment by mmokrejs** [comment]
```
$ pkg-config --list-all | grep -i mpi

ompi-fort                           Open MPI - Portable high-performance MPI implementation
orte                                Open MPI Run-Time Environment (ORTE) - Open MPI's run-time environment functionality
ompi-cxx                            Open MPI - Portable high-performance MPI implementation
ompi-f77                            Open MPI - Portable high-performance MPI implementation
ompi-f90                            Open MPI - Portable high-performance MPI implementation
ompi-c                              Open MPI - Portable high-performance MPI implementation
ompi                                Open MPI - Portable high-performance MPI implementation
```

```
$ pkg-config ompi --print-variables
exec_prefix
includedir
libdir
pcfiledir
pkgincludedir
prefix
$ pkg-config ompi --cflags
-pthread
$ pkg-config ompi --libs
-L/apps/gentoo/usr/lib -Wl,-rpath -Wl,/apps/gentoo/usr/lib -Wl,-rpath -Wl,/apps/gentoo/usr/lib64 -Wl,--enable-new-dtags -lmpi
```

**Comment by benvvalk** [comment]
Hi @mmokrejs,

I noticed in your `build.log.txt` you have `--enable-mpich` -- that is probably the source of your woes.  MPICH is an alternative/competitor to OpenMPI, which you probably do not have installed on your system.

```
./configure --prefix=/apps/gentoo/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/apps/gentoo/usr/share/man --infodir=/apps/gentoo/usr/share/info --datadir=/apps/gentoo/usr/share --sysconfdir=/apps/gentoo/etc --localstatedir=/apps/gentoo/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/apps/gentoo/usr/share/doc/abyss-2.1.0 --htmldir=/apps/gentoo/usr/share/doc/abyss-2.1.0/html --libdir=/apps/gentoo/usr/lib64 --enable-openmp --enable-mpich --with-sqlite --with-mpi --with-boost --with-sparsehash --enable-maxk=192
```

**Comment by mmokrejs** [comment]
Hi @benvvalk , ah, right, I was fiddling too much with the variables. Unfortunately, that is not the cause. See attached new files.

[build.log.txt](https://github.com/bcgsc/abyss/files/1980856/build.log.txt)
[config.log.txt](https://github.com/bcgsc/abyss/files/1980857/config.log.txt)
[config.status.txt](https://github.com/bcgsc/abyss/files/1980858/config.status.txt)

**Comment by sjackman** [comment]
You may wish to try installing ABySS using Linuxbrew. See http://linuxbrew.sh/ then `brew install abyss`

**Comment by benvvalk** [comment]
@mmokrejs haskell stuff is most likely unrelated.

From your most recent `build.log.txt`, your configure command is:
```
./configure --prefix=/apps/gentoo/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/apps/gentoo/usr/share/man --infodir=/apps/gentoo/usr/share/info --datadir=/apps/gentoo/usr/share --sysconfdir=/apps/gentoo/etc --localstatedir=/apps/gentoo/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/apps/gentoo/usr/share/doc/abyss-2.1.0 --htmldir=/apps/gentoo/usr/share/doc/abyss-2.1.0/html --libdir=/apps/gentoo/usr/lib64 --enable-openmp --disable-mpich --with-sqlite --with-mpi --with-boost --with-sparsehash --enable-maxk=192
```

Although it is counterintuitive, I'm suggesting that removing ` --disable-mpich` may help your cause.

**Comment by mmokrejs** [comment]
Ah, right, confirmed. But this should get fixed.

[build.log.txt](https://github.com/bcgsc/abyss/files/1989565/build.log.txt)
[config.log.txt](https://github.com/bcgsc/abyss/files/1989569/config.log.txt)
[config.status.txt](https://github.com/bcgsc/abyss/files/1989571/config.status.txt)

**Comment by sjackman** [comment]
What should get fixed?

**Comment by mmokrejs** [comment]
`--disable-mpich --with-mpi` breaks/overrides detection of open-mpi. In the package for Gentoo I will need to pass down something like `--disable-mpich --disable-mpich2 --disable-lam-mpi --disable-foo --enable-mpi` and OpenMPI should be picked properly.

**Comment by sjackman** [comment]
`--disable-mpich --with-mpi` should be changed to `--with-mpi=…`. Do not pass `--disable-mpich` nor `--disable-mpich --disable-mpich2 --disable-lam-mpi`.

There may be a bug where `--disable-mpich` is equivalent to `--enable-mpich=no` which ABySS is incorrectly interpreting as `--enable-mpich`, ignoring the argument.
@benvvalk Could you please confirm?

**Comment by benvvalk** [comment]
> There may be a bug where --disable-mpich is equivalent to --enable-mpich=no which ABySS is incorrectly interpreting as --enable-mpich, ignoring the argument.
> @benvvalk Could you please confirm?

@sjackman Yes, looking at the test in `configure.ac`, that seems to be exactly the issue (ignoring the argument value).

I'll keep this bug open until it is fixed, but I will treat it as a low priority item.

**Comment by sjackman** [comment]
@mmokrejs A PR to fix this issue would be welcome if you have the interest and inclination. Here's the problematic code:

https://github.com/bcgsc/abyss/blob/52b337d710657aa9b342983c9fdd6c75a0c10b99/configure.ac#L171
https://github.com/bcgsc/abyss/blob/52b337d710657aa9b342983c9fdd6c75a0c10b99/configure.ac#L176

**Comment by benvvalk** [comment]
want to fix this one

**Comment by benvvalk** [comment]
keeping this one alive

**Comment by benvvalk** [comment]
keeping this one open
