### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by monikasa** [bcgsc/abyss#226]
Hi, 
I was wondering if there is any more detailed documentation of abyss.
I was stuck for a while with finding the way to determine number of used cores. I found it, only because I stumbled upon the option, reading thread on completely different issue.  
Is there any paper, or thread, that summarizes all possible command and options? Not only within a given program like abyss-pe, but really all of the possibilities surrounding it? 

Thanks in advance for your answer!

**Comment by kkapuria3** [comment]
Did you get a chance to look at : 
http://manpages.ubuntu.com/manpages/bionic/man1/abyss-pe.1.html#contenttoc5

**Comment by sjackman** [comment]
See https://github.com/bcgsc/abyss#assembly-parameters

> j: number of threads [2]

**Comment by monikasa** [comment]
Thank you all for the answers. 

I have indeed seen all the sites you've linked.

benvvalk - I completely understand that getting all the details into documations is whole lot work and cost a lot of time.  Only thing i could't find in any of descriptions( very possible that i have simply overseen it) was the 'np=Nr of cores' - which is used before calling abyss-pe. Sp I was wandering if I wasn't looking for it in wrong places.


>

**Comment by monikasa** [comment]
Thank you all for the answers. 

I have indeed seen all the sites you linked. 
Now I also see, that I have missed, the nice and clear part about parallel processing in the documentation. It is clearly described there.  

Still thank you all very much for quick reactions and willingness to help!

**Comment by sjackman** [comment]
No worries! Happy to help.
