### ISSUE TITLE
parameter -S not passed to abyss-map step

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#228]
I'm currently tuning the parameters to scaffold my assembly. What I noticed when doing a dry-run is that the parameter values  I provide for -S (= the min contig length to use for scaffolding) is not being used in the abyss-map step of the scaffolding.

```
abyss-map -v  -j2 -l40   D1N60ACXX_8_0_1.cleanTrim.fq.gz D1N60ACXX_8_0_2.cleanTrim.fq.gz ppinAlla-6.fa \
                |abyss-fixmate -v  -l40  -h D1N60ACXX_8-6.hist \
                |sort -snk3 -k4 \
                |DistanceEst --dot --mean -v  -j2 -ka -l40 -s1000 -n5   -o D1N60ACXX_8-6.dist.dot D1N60ACXX_8-6.hist
abyss-scaffold -v   -ka -s500-5000 -n5 -g ppi
```
As you can see I requested a min length of 500bp but still the  mapping is done with -s1000 . Is this discrepancy an worth mentioning issue? If I also set the -s parameter to 500 it does indeed also use -s500 in the mapping step.

**Comment by benvvalk** [comment]
Hi @lsterck,

Yes, sounds like a bug.  I recall that issue being fixed previously, but I could be mistaken.  Are you using the latest ABySS version (2.1.0)?

Thanks for reporting this, in any case.

**Comment by lsterck** [comment]
Hi @benvvalk , no, I did not yet update to the latest version. I'm using 2.0.2 . 
I did noticed some mentioning on this topic in the changeLogs, I'm not sure thus if that resolved this already.

**Comment by lsterck** [comment]
Hi @sjackman ,

right, should have done that with my initial post indeed.
here it is:
```
abyss-pe -n np=$PBS_NP v=-v -C AllData_k${1}_500_n5 name=ppinAll$1 k=$1 n=5 S=500-5000 \
lib='C1J25ACXX_1 C1J25ACXX_2 C1J25ACXX_3 C1J25ACXX_4 C1J25ACXX_5 C1J25ACXX_6 ...
mp='C1J25ACXX_1 C1J25ACXX_2 C1J25ACXX_3 C1J25ACXX_4 C1J25ACXX_5 C1J25ACXX_6 ...
C1J25ACXX_1="$inDIR/C1J25ACXX_1_0_1.cleanTrim.fq.gz $inDIR/C1J25ACXX_1_0_2.cleanTrim.fq.gz" ...
se="$inDIR/C1J25ACXX_1_0.singl.merged.fq.gz $inDIR/C1J25ACXX_2_0.singl.merged.fq.gz ....
scaffolds
```
I am indeed using the same libraries for the lib and mp . I'm also aware of the auto optimisation for S , I'm just experimenting with it to see if it adds anything. Along the same line, I did change s as well (to 500bp) and it then only seemed logical to do (or at least try) this for S too. 
While we're at it, was the default value for these parameters not much lower (200bp) in previous version of abyss? What was the reasoning for increasing it in the later versions?

**Comment by lsterck** [comment]
Is it correct to assume actually that `-s` in DistanceEst is (or should be) linked to `-s` in abyss-scaffold ? I did a quick test and it also does not change if I run abyss with `S=2000-10000` (it then stays at 1000 in DistanceEst).

**Comment by sjackman** [comment]
> Is it correct to assume actually that -s in DistanceEst is (or should be) linked to -s in abyss-scaffold?

DistanceEst is run twice. Once at the contig stage, and once at the scaffold stage.
At the scaffold stage, the DistanceEst -s parameter should be set to the same value as the lower limit of the abyss-scaffold -s parameter. Any DistanceEst -s value less than or equal to the abyss-scaffold -s is fine, so your example of DistanecEst -s1000 and abyss-scaffold -s2000-10000 is fine. It'll produce the same result as DistanceEst -s2000 and abyss-scaffold -s2000-10000.

> I did a quick test and it also does not change if I run abyss with S=2000-10000 (it then stays at 1000 in DistanceEst).

This code does that:
https://github.com/bcgsc/abyss/blob/master/bin/abyss-pe#L337
It's new in ABySS 2.1.0.

**Comment by lsterck** [comment]
Hi @sjackman , makes all perfect sense, thanks.
