### ISSUE TITLE
difference in commands to run with and without the scaffolds target

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#229]
When i do a dry-run to check what will be done in the next step of the pipeline I noticed a difference when I used the scaffolds target and when I do not.
When I add the scaffolds target I get this : 
```
abyss-map -v  -j2 -l40    C1J25ACXX_1_0_1.cleanTrim.fq.gz C1J25ACXX_1_0_2.cleanTrim.fq.gz ppinAlla-6.fa \
                |abyss-fixmate -v  -l40  -h C1J25ACXX_1-6.hist \
                |sort -snk3 -k4 \
                |gzip >C1J25ACXX_1-6.sam.gz
PathOverlap --overlap -v  -ka --dot ppinAlla-5.dot ppinAlla-5.path >ppinAlla-6.dot
gunzip -c C1J25ACXX_1-6.sam.gz \
        |DistanceEst --dot --mean -v  -j2 -ka -l40 -s1000 -n5   -o C1J25ACXX_1-6.dist.dot C1J25ACXX_1-6.hist
```
When I omit the scaffolds target I get this : 
```
PathOverlap --overlap -v  -ka --dot ppinAlla-5.dot ppinAlla-5.path >ppinAlla-6.dot
ln -sf ppinAlla-6.dot ppinAlla-contigs.dot
abyss-map -v  -j2 -l40    C1J25ACXX_1_0_1.cleanTrim.fq.gz C1J25ACXX_1_0_2.cleanTrim.fq.gz ppinAlla-6.fa \
                |abyss-fixmate -v  -l40  -h C1J25ACXX_1-6.hist \
                |sort -snk3 -k4 \
                |DistanceEst --dot --mean -v  -j2 -ka -l40 -s1000 -n5   -o C1J25ACXX_1-6.dist.dot C1J25ACXX_1-6.hist
```
The difference is only for the first library that needs to be alinged. For all other libraries it's the same between both version (= not using the sam intermediate)
I'm confused now as in which commands are the correct ones.

**Comment by benvvalk** [comment]
@lsterck Hmm, yes we've seen this kind of (undesirable) behaviour before, but we've never really gotten to the bottom of it.  The choice of rules may be dependent on the version of `GNU Make` being used.

The results will be equivalent in either case, so you should use the `scaffolds` target here to avoid generating the unnecessary intermediate file.  These kinds of quirks are exactly why the `--dry-run` option is so valuable, I tthink.

FYI, the default targets are chosen in the following lines of `bin/abyss-pe`, based on the type of input reads that are provided.  Usually the default targets are `scaffolds scaffolds-graph`:

https://github.com/bcgsc/abyss/blob/52b337d710657aa9b342983c9fdd6c75a0c10b99/bin/abyss-pe#L426-L443

**Comment by benvvalk** [comment]
I am closing this issue because it is unlikely to be solved in the near future. (Sorry!)

**Comment by lsterck** [comment]
Thanks for the clarification @benvvalk
