### ISSUE TITLE
Building ABySS/2.1.0 with Intel 2018 toolchain

### ISSUE THREAD

**Issue by moravveji** [bcgsc/abyss#230]
Hello,

I am trying to build ABySS/2.1.0 with the intel/2018a toolchain, and other dependencies (also built with Intel), but somewhere during the manual build procedure I get an error message complaining about "std::swap". I get the same error when trying to build with EasyBuild. 
I have attached the error message and the build script below.

Any advice is well appreciated.

Regards,
Ehsan.

```
make[2]: Entering directory `/x0090231/easybuild/work/ABySS/abyss-2.1.0/ABYSS'
mpiicpc -DHAVE_CONFIG_H -I. -I..  -I.. -I/x0090231/easybuild/work/ABySS/abyss-2.1.0 -isystem/software/Boost/1.66.0-intel-2018a-Python-3.6.4/include -isystem/software/Boost/1.66.0-intel-2018a-Python-3.6.4/include/include  -I/software/SQLite/3.21.0-GCCcore-6.4.0/include  -I/software/sparsehash/2.0.3-GCCcore-6.4.0/include -isystem/x0090231/easybuild/work/ABySS/abyss-2.1.0/boost_1_56_0 -Wall -Wextra -g -O2 -MT ABYSS-abyss.o -MD -MP -MF .deps/ABYSS-abyss.Tpo -c -o ABYSS-abyss.o `test -f 'abyss.cc' || echo './'`abyss.cc
In file included from ../Assembly/AssemblyAlgorithms.h(4),
                 from abyss.cc(7):
../Assembly/BranchGroup.h(214): error: no instance of overloaded function "std::swap" matches the specified type
        inline void swap(BranchGroup&, BranchGroup&) { assert(false); }
                    ^

compilation aborted for abyss.cc (code 2)
make[2]: *** [ABYSS-abyss.o] Error 2
make[2]: Leaving directory `/x0090231/easybuild/work/ABySS/abyss-2.1.0/ABYSS'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/x0090231/easybuild/work/ABySS/abyss-2.1.0'
make: *** [all] Error 2`

And the build script:
`#!/bin/bash -l

set -e
set -x

module purge
module load intel/2018a
module load Boost/1.66.0-intel-2018a-Python-3.6.4
module load SQLite/3.21.0-GCCcore-6.4.0
module load sparsehash/2.0.3-GCCcore-6.4.0

dir_src='abyss-2.1.0'
dir_install='<BaseDir removed for security reasons>/software/ABySS/2.1.0-intel-2018a'
[[ -d $dir_install ]] || mkdir -p $dir_install

opt_dir_install="--prefix=$dir_install"
opt_openmp="CC=mpiicc CXX=mpiicpc"
opt_boost="--with-boost=$EBROOTBOOST/include"
opt_mpi=""
opt_sparsehash="CPPFLAGS=-I$EBROOTSPARSEHASH/include"
opt_sqlite="--with-sqlite=$EBROOTSQLITE"

options="$opt_dir_install $opt_openmp $opt_boost $opt_mpi $opt_sparsehash $opt_sqlite"

cd $dir_src

./configure $options
make
make install
```

**Comment by benvvalk** [comment]
Yes, I have seen this before.

If you build the HEAD version from git, it will hopefully solve the issue (assuming you're not already doing that), due to this commit: 52b337d710657aa9b342983c9fdd6c75a0c10b99. For future reference, that commit was based on pull request #222.

If that doesn't work, please let us know! An alternate solution might be to just remove that method, as suggested in #222.

**Comment by moravveji** [comment]
Thanks for your suggestion. 
I checked out the specific commit `52b337d` and tried to build it with EasyBuild, however, there is no `configure` file in the source folder. Can you please include that, and let me know to retry?

**Comment by benvvalk** [comment]
Hi @moravveji 

You have to run `autogen.sh` to generate the `configure` script first, i.e.:
```
$ ./autogen.sh
$ ./configure
$ make [-j$THREADS]
```

(The `autogen.sh` thing is a frequent convention for source code that is compiled directly from repositories, as opposed to compiling from a tarball.  The difference exists because developers ofa a project may often want to modify/regenerate the `configure` script, whereas end-users will rarely want to do that.)

**Comment by sjackman** [comment]
Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

**Comment by moravveji** [comment]
I am returning to this closed issue. 
We do not have an option to "brew" the desired software; we either build from the source or use [EasyBuild](https://github.com/easybuilders/easybuild). I tried the latest git commit of ABySS and still got the same error. I am wondering if the latest commit is supposed to have fixed that build issue?

As an alternative, how can I build ABySS from the 'bioconda' channel, and make sure it builds with intel/2018 compiler?

**Comment by benvvalk** [comment]
Hi @moravveji,

Yes, my intention with commit 52b337d was to solve the type of compile error you have posted above.  But it sounds like I was not successful. Can you please post the compile error output you are seeing when you are attempting to compile the ABySS HEAD commit (even if the error output is highly similar to your original post)? It would be very helpful.

Also, can you please provide the output of the following command, to confirm the ABySS commit you are building?
```
git rev-parse --short HEAD
```

I don't have any special expertise about the bioconda package manager.  My feeling is that if you are trying to compile using a specific compiler (the Intel compiler in your case), your original approach is probably the most straightforward, i.e. compile from the git repo using `autogen.sh`, `configure`, `make`.

**Comment by moravveji** [comment]
Thanks. 
Seems like I get the same error (below):

`mpiicpc -DHAVE_CONFIG_H -I. -I..  -I.. -I/x0090231/easybuild/work/ABySS/abyss -isystem//software/Boost/1.66.0-intel-2018a-Python-3.6.4/include -isystem/software/Boost/1.66.0-intel-2018a-Python-3.6.4/include/include  -I/software/SQLite/3.21.0-GCCcore-6.4.0/include  -I/software/sparsehash/2.0.3-GCCcore-6.4.0/include -isystem/x0090231/easybuild/work/ABySS/abyss/boost_1_56_0 -Wall -Wextra -g -O2 -MT ABYSS-abyss.o -MD -MP -MF .deps/ABYSS-abyss.Tpo -c -o ABYSS-abyss.o `test -f 'abyss.cc' || echo './'`abyss.cc
In file included from ../Assembly/AssemblyAlgorithms.h(4),
                 from abyss.cc(7):
../Assembly/BranchGroup.h(215): error: no instance of overloaded function "std::swap" matches the specified type
        inline void swap(BranchGroup&, BranchGroup&) NOEXCEPT { assert(false); }
                    ^

compilation aborted for abyss.cc (code 2)
make[2]: *** [ABYSS-abyss.o] Error 2
make[2]: Leaving directory `/x0090231/easybuild/work/ABySS/abyss/ABYSS'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/x0090231/easybuild/work/ABySS/abyss'
make: *** [all] Error 2`

And I am at the correct commit:

`$> git rev-parse --short HEAD

52b337d`

Please let m e know what other steps to take.

**Comment by benvvalk** [comment]
Hi @moravveji,

Thanks for providing the updated error output and confirming that you are using the correct git commit.

I don't think you are doing anything wrong with your build process.  I will have to revisit this error and see if I can fix it. I don't have access to the Intel compiler to reproduce your problem, but hopefully I can recreate it using a recent version of a free compiler such as gcc or clang.

Are you a C++ programmer? Would you be open to trying to fix the issue yourself? For the methods that just contain `assert(false)`, you can avoid the error message by removing the method entirely.  (The `assert(false)` is just there to prevent users from calling an unsupported method.)

**Comment by moravveji** [comment]
Thanks for your input. In fact, it it was Fortran, I would have been perfectly confident to resolve the error; but, with C/C++ I rather not touch the source code. Sorry for that.

**Comment by benvvalk** [comment]
@moravveji Okay, fair enough.  I'll keep you posted.  I may not have time to fix it this week, but I do feel that this an issue that needs to be addressed.

**Comment by benvvalk** [comment]
ssh, stalebot.

**Comment by moravveji** [comment]
I tried to build v. 2.1.1 with intel/2015a toolchain, and it went flawlessly, but with intel/2018a, I get the same error message as in the original message. I'm just providing a feedback here.

**Comment by benvvalk** [comment]
@moravveji Thanks for the update and info.  I still have not gotten around to fixing this issue, but I have not forgotten about it either.  Something about the `noexcept` implementation in newer compilers is not backwards compatible with our code.

**Comment by benvvalk** [comment]
ssh stalebot

**Comment by benvvalk** [comment]
ssh stalebot
