### ISSUE TITLE
Dealing with various and big data using Abyss

### ISSUE THREAD

**Issue by mossishahi** [bcgsc/abyss#231]
As you see in below we would like to use Abyss in order to do an assembly with a various bunch of data.
The main issue is that we don't know how to set these number of data as parameters for Abyss. 

Actually, we have about 1 TB Data shaped in about 1700 files from 3 kinds of reads, 10X(output of long-ranger), paired-end, and mate pair. Name of our files is in identified shape for paired-end data.

![report](https://user-images.githubusercontent.com/33085339/40630990-0352b0ce-62ed-11e8-8404-13fc65d43c16.jpg)

**Comment by benvvalk** [comment]
Hi @mossishahi, I think ABySS is a good choice for your task -- ABySS has excellent support for assembling with multiple read types and/or multiple libraries in an automated fashion.

Usage of paired-end and mate pair in the same assembly is fairly common.  For an example, see the following section of the ABySS README: https://github.com/bcgsc/abyss#scaffolding. In fact, I recommend having a good look through the [README.md](https://github.com/bcgsc/abyss) as there are a lot of examples and useful information in there.

` abyss-pe` is the main driver script for running assemblies, and the `abyss-pe` man page in the `doc` subdirectory (type `man doc/abyss.1` after unpacking the tarball) is also a useful resource.

Recently, ABySS added support for scaffolding and misassembly correction using Chromium reads, using external tools [ARCS](https://github.com/bcgsc/arcs) and [Tigmint](https://github.com/bcgsc/tigmint), respectively. See https://github.com/bcgsc/abyss#scaffolding-with-linked-reads for more info.

Another option for Chromium scaffolding that has worked well for us in the past has been running [ARCS](https://github.com/bcgsc/arcs) and [LINKS](https://github.com/bcgsc/LINKS) after running a standard ABySS assembly on the paired-end and mate-pair reads.

**Comment by sjackman** [comment]
What's the estimated size of your genome, and what's your estimated sequencing depth of coverage?

**Comment by mossishahi** [comment]
@sjackman estimated size of the Genome is about 1.52 GB and as you see our data is about 1 TB.

@benvvalk as I know this code might be useful for us to use PE reads for assembly. mate pairs for scaffolding and 10X data ( lr: improved by `longranger basic`) for correction of miss assemblies.

`abyss-pe name=ecoli k=96 in='reads1.fa reads2.fa'`
which I think a good way is to concatenate all forward files of our paired-end data(first half of 1688 files) in `reads1.fq` and all reverse reads in a single file(second half of 1688 files)  in `reads2.fq`

after the above line of code, a contig file is made, but I don't understand how to scaffold this contig file using mate-pair and 10X data. The only command in README that uses 10X data is something like this:
```
abyss-pe k=96 name=hsapiens \
	pe='pea' pea='lra.fastq.gz' \
	mp='mpa' mpa='lra.fastq.gz' \
	lr='lra' lra='lra.fastq.gz'
```
which needs paired-end data again. even I have 9 10X file should I concatenate them too ?

please don't close the issue. it seems many ambiguities are left

**Comment by sjackman** [comment]
How many bases have you sequenced for each type of library (paired-end, mate-pair, 10x)? What's your estimated sequencing depth of coverage?

There's no need to concatenate files. ABySS can accept multiple files.
```sh
abyss-pe k=96 name=foo lib="pe300 pe500" \
pe300="pe300a_1.fq.gz pe300a_2.fq.gz pe300b_1.fq.gz pe300b_2.fq.gz" \
pe500="pe500a_1.fq.gz pe500a_2.fq.gz pe500b_1.fq.gz pe500b_2.fq.gz"
```

**Comment by mossishahi** [comment]
![data-report](https://user-images.githubusercontent.com/33085339/40926180-d5025ad2-6830-11e8-80cc-586f1d500989.jpg)
@sjackman, sorry for the delay in replying. I was preparing some information of our data.
as you see the coverage changes in different samples or assemblers. but it's in the range of 16 and 70.

**Comment by sjackman** [comment]
You have 165 fold depth of coverage in paired-end data. Is that sequencing data all of a single individual organism? (not multiple individuals or a pool)

**Comment by mossishahi** [comment]
They are Multiple individuals, pooled together.

**Comment by sjackman** [comment]
That's not likely to give you a good assembly, unless the individuals are highly inbred, and even then it's not ideal. Are the individual samples barcoded with sample barcodes?

**Comment by mossishahi** [comment]
Only 10X data are barcoded.

**Comment by sjackman** [comment]
I wasn't referring to the linked read barcoding. Does each individual have a sample barcode? If you've pooled individuals without barcoding, you will have a difficult time assembling them. Are the individuals inbred?

**Comment by mossishahi** [comment]
@sjackman so sorry for my delay, I was studying some other subjects of our research in order to have a better idea.
Actually, our paired-end part of our data in the table is extracted from 200 planarians derived from a laboratory-bred asexual clonal strain. in brief, we want to use a pool of around 200 planarian individuals from an asexually propagating clonal strain of D. japonica and the Data is not barcoded by samples.
what do you recommend us to do?

**Comment by sjackman** [comment]
It's preferable to use a single individual when possible, but a pool of clonal individuals is okay.

Try assembling all of your data using ABySS.
See https://github.com/bcgsc/abyss/#scaffolding-with-linked-reads

Try running ABySS. If you get an error message, post your complete command line and the complete log including error message here, and we can help you troubleshoot.
