### ISSUE TITLE
The digest for the v1.5.2 tarball seems to have changed?

### ISSUE THREAD

**Issue by hartzell** [bcgsc/abyss#232]
Hi,

I'm trying to fix a problem with the Abyys package description in the [Spack](https://github.com/spack/spack) package manager.

It seems that something changed in the package for v1.5.2 so the digest value for it changed.

Here's the Spack PR fixing it: https://github.com/spack/spack/pull/8341

Here are the old and the new values:

```
-    version('1.5.2', '10d6d72d1a915e618d41a5cbbcf2364c')
+    version('1.5.2', '88400e39592ec69938512e2ad6f35245')
```

I believe that it changed sometime after August 7, 2017.

**Thanks!**

**Comment by hartzell** [comment]
It looks like it changed sometime after August 17, 2017.  Wasn't there something that github did that hiccuped a lot of the tarball shas?

Here's the issue over at abyss:  https://github.com/bcgsc/abyss/issues/232

**Comment by sjackman** [comment]
Yes, the GitHub tarballs are autogenerated, and their SHA-256 do occasionally but not often change. There's much more details in the Homebrew issue tracker.

This tarball is not autogenerated, and its SHA-256 should not have changed.
https://github.com/bcgsc/abyss/releases/download/1.5.2/abyss-1.5.2.tar.gz
See https://github.com/bcgsc/abyss/releases/tag/1.5.2

**Comment by hartzell** [comment]
It looks like the package originally fetched from bcgsc and then switched to the github archive tarballs.

```diff
-    url      = "http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/2.0.2/abyss-2.0.2.tar.gz"
+    url      = "https://github.com/bcgsc/abyss/archive/2.0.2.tar.gz"
```

It looks like the project consistently uploads tarballs, so the `.../download/...` URL is probably a better bet.

**Comment by sjackman** [comment]
Please use this GitHub URL rather than the www.bcgsc.ca URL: https://github.com/bcgsc/abyss/releases/download/2.0.2/abyss-2.0.2.tar.gz
Note that this tarball is not auto-generated, and its contents are identical to the BCGSC URL.
```sh
❯❯❯ curl -sL https://github.com/bcgsc/abyss/releases/download/2.0.2/abyss-2.0.2.tar.gz | gsha256sum -
d87b76edeac3a6fb48f24a1d63f243d8278a324c9a5eb29027b640f7089422df  -
❯❯❯ curl -sL http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/2.0.2/abyss-2.0.2.tar.gz | gsha256sum -
d87b76edeac3a6fb48f24a1d63f243d8278a324c9a5eb29027b640f7089422df  -
```

This tarball is auto-generated by GitHub, so best avoided: https://github.com/bcgsc/abyss/archive/2.0.2.tar.gz

Note also that ABySS 2.1.0 is available.

**Comment by benvvalk** [comment]
Thanks, @sjackman!

**Comment by sjackman** [comment]
> It looks like the project consistently uploads tarballs, so the .../download/... URL is probably a better bet. Is that a reasonable summary?

Ah, I misread your previous comment. Yes, that's accurate. Please do use the GitHub `.../download/...` URL.
