### ISSUE TITLE
Issues with boost Libraries 

### ISSUE THREAD

**Issue by Jome0169** [bcgsc/abyss#233]
Hello,

I am trying to install abyss, but whenever I attempt to configure abyss, it fails due to the Boost libraries with the error
```
configure: WARNING: boost/unordered_set.hpp: present but cannot be compiled
configure: WARNING: boost/unordered_set.hpp:     check for missing prerequisite headers?
configure: WARNING: boost/unordered_set.hpp: see the Autoconf documentation
configure: WARNING: boost/unordered_set.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: boost/unordered_set.hpp: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------- ##
configure: WARNING:     ## Report this to abyss-users@bcgsc.ca ##
configure: WARNING:     ## ----------------------------------- ##
checking for boost/unordered_set.hpp... no
configure: error: ABySS requires the Boost C++ libraries, which may
        be downloaded from here: http://www.boost.org/users/download/
        It is not necessary to compile Boost before installing it. The
        following commands will download and install Boost for ABySS:
        cd /data/pabster212/Programs/abyss
        wget http://downloads.sourceforge.net/project/boost/boost/1.56.0/boost_1_56_0.tar.bz2
        tar jxf boost_1_56_0.tar.bz2
        cd -
```

After checking the config.log file, the error can be traced to:

```
configure:6704: result: x86_64-unknown-linux-gnu
configure:6724: checking host system type
configure:6737: result: x86_64-unknown-linux-gnu
configure:6869: checking if compiler needs -Werror to reject unknown flags
configure:6885: gcc -c -g -O2 -Werror -Wunknown-warning-option -Wsizeof-array-argument -I/data/pabster212/Programs/abyss      -isystem/data/pabster212/Programs/abyss/boost_1_56_0 conftest.c >&5
gcc: error: unrecognized command line option '-Wunknown-warning-option'
gcc: error: unrecognized command line option '-Wsizeof-array-argument'
configure:6885: $? = 1
configure: failed program was:
```

Any idea how to rectify this problem? I have attempted to install both newer and older versions of boost to no effect. 

Thanks!

**Comment by sjackman** [comment]
Please report the version of ABySS, the exact `./configure` command line that you're using, and the version of GCC (or other compiler) that you're using. `gcc --version`.

Consider installing ABySS using Homebrew on macOS or Linuxbrew on Linux.
See https://brew.sh and https://linuxbrew.sh then `brew install abyss`

**Comment by Jome0169** [comment]
Gcc Version: gcc (GCC) 4.7.2 20120921 (Red Hat 4.7.2-2)
Abyss Version: 2.1.0
Linux Distro: Fedora 17

As for the command I'm running the basic `./configure` option. I have also tried pointing directly to the boost libraries with no effects  
`./configure --with-boost=/data/pabster212/Programs/abyss/boost_1_56_0/boost`

**Comment by sjackman** [comment]
Those two errors that you're seeing above may be a red herring. Please gist the file `config.log` using either `https://gist.github.com` or at the command line `gist config.log`

Have you tried installing ABySS using Linuxbrew or Bioconda?

**Comment by Jome0169** [comment]
Attached is the link to my gist, thanks again for you help.

https://gist.github.com/Jome0169/0960233391c9cd29ca7d4a9340dbb6f8

**Comment by sjackman** [comment]
Here's the relevant error:
```
configure:7946: checking boost/property_map/property_map.hpp usability
configure:7946: g++ -c -g -O2 -I/data/pabster212/Programs/abyss -isystem/data/pabster212/Programs/abyss/boost_1_56_0/boost -isystem/data/pabster212/Programs/abyss/boost_1_56_0/boost/include     -isystem/data/pabster212/Programs/abyss/boost_1_56_0 conftest.cpp >&5
In file included from /usr/local/include/assert.h:5:0,
                 from /data/pabster212/Programs/abyss/boost_1_56_0/boost/assert.hpp:54,
                 from /data/pabster212/Programs/abyss/boost_1_56_0/boost/property_map/property_map.hpp:14,
                 from conftest.cpp:99:
/usr/local/include/except.h:15:32: error: conflicting declaration 'typedef struct Except_Frame_T* Except_Frame_T'
/usr/local/include/except.h:15:16: error: 'struct Except_Frame_T' has a previous declaration as 'struct Except_Frame_T'
/usr/local/include/except.h:17:18: error: field 'prev' has incomplete type
```
https://gist.github.com/Jome0169/0960233391c9cd29ca7d4a9340dbb6f8#file-config-log-L2735

This problem is cause by the file `/usr/local/include/except.h`. It's not recommended to install anything in `/usr/local`, because it can break things in many strange ways that are hard to troubleshoot and diagnose. Please report…
```sh
which -a gcc
/usr/bin/gcc --version
/usr/local/bin/gcc --version
/usr/lib64/ccache/gcc --version
```

**Comment by sjackman** [comment]
> Also, as the system I am working on is older, and has not been updated recently, I am unable to get linuxbrew or Bioconda working currently. So manual install is kind of a must for me.

One of Linuxbrew's primary purpose is to install newer software in older systems. Please try installing Linuxbrew. Feel free to open an issue on GitHub if it doesn't work for you: https://github.com/Linuxbrew/brew/issues/new/choose

**Comment by Jome0169** [comment]
Here are the outputs to the command you indicated

```
[pabster212$ which -a gcc
/usr/lib64/ccache/gcc
/usr/local/bin/gcc
/usr/bin/gcc
[pabster212@$ /usr/bin/gcc --version
gcc (GCC) 4.7.2 20120921 (Red Hat 4.7.2-2)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[pabster212@$ /usr/local/bin/gcc --version
gcc (GCC) 4.7.2 20120921 (Red Hat 4.7.2-2)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[pabster212@ ~]$ /usr/lib64/ccache/gcc --version
gcc (GCC) 4.7.2 20120921 (Red Hat 4.7.2-2)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by sjackman** [comment]
Do you know why you have GCC 4.7.2-2 installed in both `/usr/bin/` and `/usr/local/bin/` ? I'd suggest removing (uninstalling) the copy installed in `/usr/local/bin/`.

**Comment by sjackman** [comment]
It's a shot in the dark, but try…
```sh
./configure CC=/usr/bin/gcc CXX=/usr/bin/g++
make
```
I'd strongly recommend trying Linuxbrew or Bioconda.

**Comment by Jome0169** [comment]
Hello again, sorry for the delay. After removing the accessory install of g++ everything seems to be working. Thanks!

**Comment by Jome0169** [comment]
The accessory install of g++ was the issue. After removing it compilation went smoothly. Thanks so much for your time.

-Pablo

**Comment by sjackman** [comment]
Glad to hear that you got it working, John.
