### ISSUE TITLE
iterative scaffolding

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#235]
Hi,

I was thinking of doing an iterative scaffolding of my contig assembly using abyss, mainly because then I have more control on the usage of different libraries (and technologies) I have at hand.
I'm however not 100% sure how I can 'trick' abyss to do so. I thought of using the .fa file of the first scaffolding step and re-use it as the contig .fa file and then run the next scaffolding on it. 
Is that an approach that makes sense? Is it is possible at all, which files do I have to 'revert' to achieve this. The -8.fa file is likely the minimum I assume.

thanks

**Comment by sjackman** [comment]
Hi, @lsterck. I'd suggest running your original `abyss-pe` command line with the `-n` (or `--dry-run`) option enabled to see what commands ABySS runs for scaffolding. You can then run the steps between creating the `$name-6.fa` and `$name-8.fa` files for whichever libraries / technologies you like in as many iterations as you like, without needing to modify or trick the `abyss-pe` script. I'd suggest also running all your scaffolding in a single round (the usual method) and comparing your result to that. If you're able to get better results than the usual method, we'd be interested in hearing back from you! Feel free to follow up here if you have any further questions on this topic.

**Comment by benvvalk** [comment]
@lsterck  I like Shaun's suggested approach and I think you are on the right track in general. If you would like help troubleshooting, please post the commands that you ran and the log output (or at least a long tail of the log output).

>Related: when doing the mapping of the reads to the scaffolds I notice very little difference in the stats compared to mapping them on the contigs. I would have expected to see that the majority of reads in the 'different' category would have dropped significantly (==meaning they have been used to link two contigs) but it seems it has only been reduced with a few percentages?

Depending on the number of merges you are making in the contig stage, the alignment stats may not change that much. I think running `abyss-fac` on your unitigs (-3.fa) and your contigs (-6.fa) would give you a better indication of improvement.

**Comment by sjackman** [comment]
> I think the issue is that at some point ABySS reads in the $name-5.dot and $name-5.path (though I do not see those mentioned in the dry-run mode).

ABySS only reads files specified on the command line. The exception is the `foo.fa.fai` and `foo.fai.fm` files read by `abyss-map` when you specify `abyss-map … foo.fa`

**Comment by lsterck** [comment]
> Depending on the number of merges you are making in the contig stage, the alignment stats may not change that much. 
in general there are indeed very similar and that's indeed as expected but would you not expect a switch from the different category to the FF/RF category?

**Comment by lsterck** [comment]
> ABySS only reads files specified on the command line. The exception is the foo.fa.fai and foo.fai.fm files read by abyss-map when you specify abyss-map … foo.fa

that was my understanding as well but when I execute the cmdline:
```
abyss-scaffold -v   -k85 -s200-2000 -n5-15 -g ppinAll85-6.path.dot  ppinAll85-6.dot <libs.dot files> >ppinAll85-6.path
PathConsensus -v --dot -k85  -p0.9  -s ppinAll85-7.fa -g ppinAll85-7.dot -o ppinAll85-7.path ppinAll85-6.fa ppinAll85-6.dot ppinAll85-6.path
cat ppinAll85-6.fa ppinAll85-7.fa \
                | MergeContigs -v  -k85 -o ppinAll85-8.fa - ppinAll85-7.dot ppinAll85-7.path
ln -sf ppinAll85-8.fa ppinAll85-scaffolds.fa
```

it reported:
```
Reading `ppinAll85-5.dot'...
Reading `ppinAll85-5.path'...
ambiguous overlap: 169960665- -> 171746357+
```

**Comment by lsterck** [comment]
In the meanwhile I think I understand what you were suggesting @sjackman . I actually only have to add the couple command lines I posted above together with the mapping step in a separate little script and run it on whatever files I want. right?

**Comment by benvvalk** [comment]
>> Depending on the number of merges you are making in the contig stage, the alignment stats may not change that much.

> in general there are indeed very similar and that's indeed as expected but would you not expect a switch from the different category to the FF/RF category?

From the Different category to the RF category, if they are mate pair reads and your mate pair preprocessing didn't mess with the orientations. Only the read pairs in the immediate neighborhood of the merges will change category, and those regions may constitute a small fraction of the total assembled sequence.

Your scaffolding commands look correct, given that you are doing the mapping step in a separate script. Don't know what's going on with the -5 files.

**Comment by sjackman** [comment]
> that was my understanding as well but when I execute the cmdline:
> …
> it reported:

Double-check the commands that you're running, and that you're looking at the correct log file.

**Comment by lsterck** [comment]
Checked the files and the commands, both looking OK. I did spot something though, when I did another dry-run I noticed that I think it's doing the `PathOverlap --overlap -v  -ksdyc --dot schisto_ksdyc-5.dot schisto_ksdyc-5.path >schisto_ksdyc-6.dot` as the first step in the contig-to-scaffold part . I did run abyss only until the contig stage (so then it stops before the pathOverlap command)  and then to the scaffold stage . So when I 'reverted' my -scaffolds file to -contigs file I also cleaned up everything with a creation date after the initial file.

Anyway, coming to think of it (and also reading your advices) I start to think I'm not doing this right :/ . I might need to rethink my 'procedure'. Up till now I always tried to have all my trials run by abyss itself, but from one of your comments above I understand I should just do it separately , using the abyss commands but for instance different file naming.

**Comment by sjackman** [comment]
> Up till now I always tried to have all my trials run by abyss itself, but from one of your comments above I understand I should just do it separately , using the abyss commands but for instance different file naming.

Yes, I think that'll be easier. It can be a bit tricky to get `abyss-pe` to start at a particular point in the middle of the pipeline.

**Comment by lsterck** [comment]
OK, I think I have put together a sensible approach to accomplish this. briefly what I want to achieve here: I want to take the result of a scaffolding run as input for another/next scaffolding run.

1. I take the `name-8.fa` file as my new input (as would it be the `name-6 `file for the 'normal' abyss run), let's call it `iteration-a.fa`
2. for that file I create a new index to be used in the read mapping step. I thus create `iteration-a.fa.fai` and `iteration-a.fm` file.
3. I do the read mapping against `iteration-a.fa`
4. since I also need a `iteration-a.dot` file I take the original `name-7.dot `and `name-7.path` to create a it (similar as abyss would use the `name-5` ones to create the `name-6.dot` file.)
5. I then run the commands that abyss would do for the scaffolding part: `abyss-scaffold` and following.
6. The resulting iteration-a-scaffolds.fa file will then become the input for the next iteration and repeat the above steps (except that I then use the iteration-a-7.dot and path file)

This seems to work from a technical point of view. I was just wondering if it makes any sense from an abyss command point of view (eg whether the -7.dot and -7.path file are to -8.fa as are -5.dot and -5.path are to -6.fa)

**Comment by sjackman** [comment]
You should be able to take `name-8.dot` and call that your new `name-6.dot`, rather than recreate it.

**Comment by sjackman** [comment]
You can add `scaffolds-graph` to your `abyss-pe` command line to create `name-8.dot`.

**Comment by lsterck** [comment]
right, I see, thanks again. (or I can also simply add that step in my abyss-subpart script?)
Since you only had constructive comments (much appreciated! ), I assume the approach is otherwise sound

**Comment by sjackman** [comment]
Iterative scaffolding isn't something we've done much, but yes, the general approach is sound.

**Comment by lsterck** [comment]
any particular reason why? risk of over-scaffolding is real I assume? or would the whole thing not be worth the effort?

**Comment by sjackman** [comment]
It's possible to create misassemblies. For example in the first round you merge `A` and `C` to create `A N C`, and then in the second round you add `B` to that to create `A N C N B`, when the true sequence is `A B C`.

**Comment by lsterck** [comment]
right, but is that something that can/will happen, I mean, why would it in the 'first' round not create A N B and then add C , if that is the correct solution I would assume there is at least data to back that up, no?

**Comment by sjackman** [comment]
Are you running multiple rounds of scaffolding with different data sets or with the same data set?
Let's say library 1 has data linking *A* to *C* (but missing data from *A* to *B* and *B* to *C*), and library 2 has data linking *A* to *B*, where *A* is large and *B* and *C* are small-ish. You scaffold with library 1 and it scaffolds `A N C`, then scaffold with library 2, which then adds `A N C N B`.
To say anecdotally that it can happen says nothing about how frequently it happens, just that it's possible.

**Comment by sjackman** [comment]
If you're interested in experimenting a bit… I designed our tool Tigmint to correct misassemblies using 10x Genomics Chromium data, but it should be work with mate-pair data too. It includes two tools, `tigmint-molecule` and `tigmint-cut`. To use it with mate-pair data, instead of `tigmint-molecule` run `bedtools bamtobed`, and then run `tigmint-cut`. Try different values for the parameters `-w` and `-n`, and then run abyss-scaffold after Tigmint. See if you can improve the NG50 with the combination of Tigmint and `abyss-scaffold`.

**Comment by lsterck** [comment]
> Are you running multiple rounds of scaffolding with different data sets or with the same data set?

now, initially, with the same one, I might think of using different 'mixtures' of datasets as well 

> To say anecdotally that it can happen says nothing about how frequently it happens, just that it's possible.

ok, makes sense indeed. 
So, here's how I think of tackling that issue. I start with the smallest libraries (as in 'bridging' length) and and then to add libraries with increasing size. I think this might work?

**Comment by lsterck** [comment]
> If you're interested in experimenting a bit…

what kind of scientist would I be if I was not into some experimenting ;) . Unfortunately a bit short on time though for the moment (and finish the other testing as well ). Sounds like a testable idea though. What would that resolve then? Do you advise to run it between (or before)  each iteration or only once at the end?  You mention `bedtools bamtobed` but I don't get a bam intermediate when running abyss?

But consider me interested.

**Comment by lsterck** [comment]
> So, here's how I think of tackling that issue. I start with the smallest libraries (as in 'bridging' length) and and then to add libraries with increasing size. I think this might work?

This is actually one of the reasons (beside being unhappy with the previous stats ;) ) for embarking on this route is that I have clear distinct sets of bridging libraries, each with their own strength and weaknesses. So I figured that by adding them one by one I could control those things better then with the all together approach

**Comment by sjackman** [comment]
> I start with the smallest libraries (as in 'bridging' length) and and then to add libraries with increasing size. I think this might work?

Yep, that seems reasonable to me.

**Comment by sjackman** [comment]
NxRepair is tool for correcting an assembly using Nextera mate-pair sequencing.
https://doi.org/10.7717/peerj.996
https://github.com/rebeccaroisin/nxrepair
https://nxrepair.readthedocs.io/en/latest/
Not sure how well it would fair with non-Nextera mate-pair data. Possibly badly. It's a good paper to read though.
