### ISSUE TITLE
abyss-map: recipe for target '<name>.dist' failed

### ISSUE THREAD

**Issue by Souzaph** [bcgsc/abyss#237]
# Please report

- [ ] version of ABySS with `abyss-pe version`
- [ ] distribution of Linux with `lsb_release -d`

# Assembly error

- [ ] complete `abyss-pe` command line
- [ ] last 20 lines of the output of `abyss-pe`
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ ] Have you tried installing ABySS using Brew or Bioconda?
- [ ] version of GCC or compiler with `gcc --version`
- [ ] complete `./configure` command line
- [ ] last 20 lines of the output of `./configure`
- [ ] last 20 lines of the output of `make`

**Comment by Souzaph** [comment]
Hello, I'm having a problem assembling an Ecoli fragment, I'm using (2.1.0 version). I think that the problem is in abyss-map, because every time I run the test I works well, but when  use my sequences it stops there.

I'm using that command:

# Multiple library
abyss-pe k=25 v=-v name=Ecoli lib='Ecoli5 Ecoli6' \
       Ecoli5='Ecoli5_PE_1.fq Ecoli5_PE_2.fq' Ecoli6='Ecoli6_PE_1.fq Ecoli6_PE_2.fq' \
       se='Ecoli5_SR_1.fq Ecoli5_SR_2.fq Ecoli6_SR_1.fq Ecoli6_SR_2.fq'

And the outcome is aways the same:
...
abyss-map -v  -j2 -l40    Ecoli5.PE.1.fq Ecoli5.PE.2.fq Ecoli-3.fa \
        |abyss-fixmate -v  -l40  -h Ecoli5-3.hist \
        |sort -snk3 -k4 \
        |DistanceEst -v  -j2 -k25  -l40 -s1000 -n10  -o Ecoli5-3.dist Ecoli5-3.hist
/usr/local/bin/abyss-pe:604: recipe for target 'Ecoli5-3.dist' failed
(END)
 And the file Ecoli5-3.hist have nothing within it (zero kb)

**Comment by Souzaph** [comment]
Hello, I'm having a problem assembling an Ecoli fragment, I'm using (2.1.0 version). I think that the problem is in abyss-map, because every time I run the test I works well, but when use my sequences it stops there.

I'm using that command:

Multiple library
abyss-pe k=25 v=-v name=Ecoli lib='Ecoli5 Ecoli6' 
Ecoli5='Ecoli5_PE_1.fq Ecoli5_PE_2.fq' Ecoli6='Ecoli6_PE_1.fq Ecoli6_PE_2.fq' 
se='Ecoli5_SR_1.fq Ecoli5_SR_2.fq Ecoli6_SR_1.fq Ecoli6_SR_2.fq'

And the outcome is aways the same:
...
abyss-map -v -j2 -l40 Ecoli5.PE.1.fq Ecoli5.PE.2.fq Ecoli-3.fa 
|abyss-fixmate -v -l40 -h Ecoli5-3.hist 
|sort -snk3 -k4 
|DistanceEst -v -j2 -k25 -l40 -s1000 -n10 -o Ecoli5-3.dist Ecoli5-3.hist
/usr/local/bin/abyss-pe:604: recipe for target 'Ecoli5-3.dist' failed
(END)

And the file Ecoli5-3.hist have nothing within it (zero kb)

**Comment by benvvalk** [comment]
Hi @Souzaph,

Your `abyss-pe` command should run successfully, but I would recommend removing the `se` part.  (It will cause each file to be included twice in unitig assembly stage.)

Can you possibly provide more of your log output (for example, the last 30 lines?)  Or you could post the full log to a Github gist. There is probably an error message near the end of your log output that indicates what the problem is, but it is not showing in the excerpt you have provided above.

**Comment by Souzaph** [comment]
Thanks @benvvalk 

Here is the complete outcome:
https://gist.github.com/Souzaph/23328718653af550c48131ea597bd8a9

In my humble opinion, I think that there is a problem happening with the information required for Abyss-map, probably I'm missing something.

Do you suggest that I just remove the "se" or substitute it for something else ?

Sorry for any inconvenience, but I'm crazy to learn more about bioinformatics !

**Comment by benvvalk** [comment]
I recommend just removing `se`.  It is supposed to be for additional single-read that are not already provided in `lib`. 

Your alignment stats say that zero reads mapped back to the assembly, which is very odd:
```
Read 14000000 alignments. Hash load: 0 / 4 = 0 using 418 kB.
Read 15000000 alignments. Hash load: 0 / 4 = 0 using 418 kB.
Read 16000000 alignments. Hash load: 0 / 4 = 0 using 418 kB.
Read 17000000 alignments. Hash load: 0 / 4 = 0 using 418 kB.
Mapped 0 of 17216218 reads (0%)
Mapped 0 of 17216218 reads uniquely (0%)
Read 17216218 alignments
Mateless         0
Unaligned  8608109  100%
Singleton        0
FR               0
RF               0
FF               0
Different        0
Total      8608109
error: the histogram `Ecoli5-3.hist' is empty
make: *** [Ecoli5-3.dist] Error 1
make: *** Deleting file 'Ecoli5-3.dist'
```

How long are your read lengths? By default, ABySS requires a perfect match of at least 40 bp in order to map the reads.  If that is the problem, you can try reducing it by adding `l=15` to your `abyss-pe` command, for example.

**Comment by Souzaph** [comment]
Thanks again @benvvalk ,

abyss-pe k=25 v=-v name=Ecoli lib='Ecoli5 Ecoli6' \
       Ecoli5='Ecoli5_PE_1.fq Ecoli5_PE_2.fq' Ecoli6='Ecoli6_PE_1.fq Ecoli6_PE_2.fq' \
       se='Ecoli5_SR_1.fq Ecoli5_SR_2.fq Ecoli6_SR_1.fq Ecoli6_SR_2.fq'

Well, the Ecoli_PE_1 and Ecoli_PE_2 are the 'pair end' sequences (1 - forward and 2 - reverse), and the SR are the 'single read' sequences, of two different libraries (Ecoli5 and Ecoli6). Im trying to assemble a contig using the two of them.
My reads are all 36 bp lenght

PS: I will try to use the l=15.

**Comment by benvvalk** [comment]
Oh, my mistake! You were right to include the `se` as you did, then. (I didn't look closely enough, and thought they were the same filenames as given in `lib`.)

Yes, if your read lengths are 36 bp, that would explain your problem!  (Those are very short reads, btw! Recent Illumina paired-end reads would typically be 150bp.)
