### ISSUE TITLE
using abyss for assembling 10X data

### ISSUE THREAD

**Issue by mossishahi** [bcgsc/abyss#238]
How is it possible to assemble only 10X data using abyss? (there isn't any paired-end or mate pair lib) and how if we have multiple libraries of 10X data?

**Comment by benvvalk** [comment]
@mossishahi Please see this section of the ABySS README.md: https://github.com/bcgsc/abyss#scaffolding-with-linked-reads

**Comment by benvvalk** [comment]
We have not done much testing with multiple Chromium libraries so far, but in principle it should work.

If you want to ensure that the barcodes are distinct across libraries, you will have to alter the barcodes in the FASTQ files yourself.  The simplest way is to change the `-1` suffix in the barcodes, e.g. change

```
BX:Z:AAACACCAGACAATAC-1
```
to

```
BX:Z:AAACACCAGACAATAC-2
```

For a small number of Chromium libraries, it may turn out that simply pooling all the read/barcodes together works just as well.

**Comment by sjackman** [comment]
Here's a one-line GNU sed script to change the BX tag as Ben suggested. `pigz` is parallel gzip and is much faster than gzip. You could use gzip instead.
```sh
	gunzip -c reads.fq.gz| sed '1~4s/-1$/-2/' | pigz >reads.bx.fq.gz
```

**Comment by mossishahi** [comment]
I did your suggestions and ran the abyss in a command like this:
`abyss-pe name=PG2103_03BE5 k=96 lr='lra lrb' lra=~/e/barcoded_1.fastq.gz lrb=~/e/barcoded_2.fastq.gz`
we had some errors on the output message:
![abyss-out](https://user-images.githubusercontent.com/33085339/42496856-9c462516-843c-11e8-906d-a4fd8c556a30.png)
and two output file named:
PG2103_03BE5-bubbles.fa  and  PG2103_03BE5-1.fa
**Q** my first question is about the reason of the errors on the output message
**Q** the other question that what's the meaning of index `1` at the end of `PG2103_03BE5-1.fa` name.
But about the final result:
we evaluated the result file using bbstats, and the statistics are not good at all:
![bbstats-abyss](https://user-images.githubusercontent.com/33085339/42496837-8d40b9f0-843c-11e8-879b-c6e306c499b1.png)
However, we assembled the 10X data with it's original assembler, Supernova and the result was much better than this experiment but since we expect a genome with a size greater than ~1.5Gbp  it wasn't good and considerable at all too.
the Supernova statistics:
![screenshot 485](https://user-images.githubusercontent.com/33085339/42497037-287e56ca-843d-11e8-9ba5-e7da0c05b523.png)
do you have any helpful idea?

**Comment by sjackman** [comment]
Please copy and paste logs rather than taking screen shots, and surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Consider installing ABySS using either [Linuxbrew](https://linuxbrew.sh) `brew install abyss` or [Bioconda](https://bioconda.github.io) `conda install -c bioconda abyss`.
If you install from source, use `./configure --prefix=$HOME/opt/abyss && make && make install`. I suspect that you skipped the last `make install` step.

**Comment by mossishahi** [comment]
Do you beleive that error has stopped the process and the draft is not reliable?

**Comment by sjackman** [comment]
It's likely just fine, but it stopped after the first de Bruijn graph unitig stage, so it's a very early draft. There's many more stages in the assembly pipeline. No paired-end or linked-read scaffolding has been done yet.

**Comment by mossishahi** [comment]
@sjackman Dear Mr. Shaun, our server admin confirms that abyss is installed on our server, (maybe he has reinstalled it ) 
I ran abyss in a command like this:
`abyss-pe name=PG2103_03BE5 k=96 lr='lra lrb' lra=~/e/Planaria_10X/Fastq/For_10x_Denovo_Data/PG2103_03BE5/Fastq/longranger/barcoded_1.fastq.gz lrb=~/e/Planaria_10X/Fastq/For_10x_Denovo_Data/PG2103_03BE5/Fastq/longranger/barcoded_2.fastq.gz`
and it faced an error:
```

which: no mpirun in (/usr/local/anaconda/bin/:/usr/local/anaconda/bin/:/s/chopin/a/grad/asharifi/bioconda/bin:/usr/local/cuda_8.0.61-cudnnv5/bin:/s/chopin/a/grad/asharifi/.nvm/versions/node/v7.5.0/bin:/s/chopin/a/grad/asharifi/bin:/s/chopin/a/grad/asharifi/e/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/s/damavand/e/asharifi/BS_Aligners/methylcode/bench/gsnap/gmap-2014-12-06/bin:.:/usr/local/anaconda/bin/:/usr/local/anaconda/bin/:/s/chopin/a/grad/asharifi/bioconda/bin:/usr/local/cuda_8.0.61-cudnnv5/bin:/s/chopin/a/grad/asharifi/bin:/s/chopin/a/grad/asharifi/e/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/s/damavand/e/asharifi/BS_Aligners/methylcode/bench/gsnap/gmap-2014-12-06/bin:.:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/s/chopin/a/grad/asharifi/.composer/vendor/bin:/s/chopin/a/grad/asharifi/bin:/s/chopin/a/grad/asharifi/S:/s/chopin/a/grad/asharifi/.local/bin:/s/chopin/a/grad/asharifi/e/Applications/weblogo:/s/chopin/a/grad/asharifi/e/Applications/gurobi652/linux64/bin:/s/chopin/a/grad/asharifi/f/miniconda3/bin:/s/chopin/a/grad/asharifi/e/Applications/Torch/bin:/usr/local/torch/install/bin:/s/chopin/a/grad/asharifi/e/Applications/gurobi652/linux64/bin:/s/chopin/a/grad/asharifi/f/miniconda3/bin:/s/chopin/a/grad/asharifi/e/Applications/Torch/bin:/usr/local/torch/install/bin)
abyss-pe: missing parameter `lib`, `in` or `se`
Try `abyss-pe help` for more information.
make: *** [abyss-pe:248: error] Error 1

```

**Comment by sjackman** [comment]
I suspect that your version of abyss-pe is out of date. Please report `abyss-pe version`. It should report 2.1.0.
