### ISSUE TITLE
abyss-pe under abyss 2.1.0

### ISSUE THREAD

**Issue by mortya** [bcgsc/abyss#240]
# Please report

- [ ] version of ABySS with `abyss-pe version`
abyss-pe (ABySS) 2.1.0
- [ ] distribution of Linux with `lsb_release -d`
Description:    CentOS Linux release 7.5.1804 (Core)

On CentOS7, running abyss-pe 2.1.0 results in:
zsh: no such option: pipefail

Apparently, we have zsh, but it's older and doesn't support pipefail.  Easily worked around by commenting out the zsh detection lines.

**Comment by benvvalk** [comment]
@mortya Thanks for reporting this.  It has come up a couple of times now.  Perhaps we can somehow check the zsh version in the `abyss-pe` Makefile, or test if the `pipefail` option is supported.

As a sidenote, Linuxbrew is a handy tool for installing current versions of software such as zsh, and it doesn't require root access.  You may be able to work around the problem that way as well.

**Comment by macmanes** [comment]
FWIW, conda does not have a mainstream distro of zsh, so those installing via conda are still in need of a solution. 

maybe something like this

```
zsh_version := $(shell zsh --version | awk '{print $$2})'
target:
    if [ ${zsh_version} -gt 5.0.8 ] ; then \
        ... ;\
    fi
```

**Comment by benvvalk** [comment]
Thanks @macmanes.  I agree, that sounds like the right approach.

**Comment by sjackman** [comment]
To work around this issue, edit the file `abyss-pe` and delete the line…
```sh
SHELL=zsh -e -o pipefail
```
