### ISSUE TITLE
CountingBloomFilter question

### ISSUE THREAD

**Issue by schutzekatze** [bcgsc/abyss#243]
So, in LogKmerCount/logcounter.cc, there is

	CountingBloomFilter<plc> bloom(opt::bloomSize, 1);
	for (int i = optind; i < argc; i++)  
		Bloom::loadFile(bloom, opt::k, string(argv[i]), opt::verbose);

And Bloom::loadFile is parallelized with OpenMP where threads insert into the filter simultaneously, but I haven't found any threadsafe guarantees in CountingBloomFilter. (Elsewhere in ABySS, ConcurrentBloomFilter is used for safety.) Am I missing something or is this not supposed to work correctly?

Moreover, I can't find logcounter being used anywhere in the bin scripts. Is this a standalone executable?

**Comment by JustinChu** [comment]
This code was only used for the spaced seed datastructures paper. It should probably be removed or placed in another development branch of the code. It probaby shouldn't have been added to the main abyss release.

As for thread safety. It is possible the load file function worked differently in the past where is was thread safe, but the code is fairly old now.

**Comment by benvvalk** [comment]
Thanks for the reply, @JustinChu.  I will remove that directory/code prior to the next ABySS release.

**Comment by benvvalk** [comment]
@schutzekatze I think you are right -- it would need to be wrapped in `ConcurrentBloomFilter` (or something similar) to correctly support multiple threads.  Sorry about leaving untested/unfinished code in the source tree.

**Comment by mmokrejs** [comment]
Hi, provided Vladimir is a summer student trying to isolate weak parts and to improve abyss would you doing the code cleanup commits a bit sooner rather than later? It would help him to get more easily through the code. Also, from the answer from @JustinChu it sounds there is some "never" code somewhere and abyss is using some 'fairly old code now'?
