### ISSUE TITLE
About assembling 10X data

### ISSUE THREAD

**Issue by EugeneKim76** [bcgsc/abyss#250]
Hi all,

I tried to assemble 10X linked read data using the command in the section of 'README.md' as shown below.

 abyss-pe k=96 name=hsapiens lr='lra' lra='lra.fastq.gz'

However, assemble failed with the error shown below.

abyss-pe: missing parameter `lib`, `in` or `se`
Try `abyss-pe help` for more information.
/usr/bin/abyss-pe:304: recipe for target 'error' failed
make: *** [error] Error 1

Is there any way to solve this problem?

Best,

**Comment by benvvalk** [comment]
Hi @EugeneKim76,

Your command looks correct.  I suspect you are just not using the latest version of ABySS.  You will need ABySS 2.1.0.

It may be a good idea to confirm which ABySS version is being used by running
```
abyss-pe version
```
inside your assembly job script.

**Comment by sjackman** [comment]
Consider installing ABySS using Homebrew on macOS or Linuxbrew on Linux.
```sh
brew install abyss
```

**Comment by EugeneKim76** [comment]
Thanks a lot.
Problem solved!
Best,

**Comment by sjackman** [comment]
Glad to hear it! Happy assembling!
