### ISSUE TITLE
Docker image does not include ABYSS-P

### ISSUE THREAD

**Issue by WEClarke** [bcgsc/abyss#253]
Hello,

Docker images for abyss (tried v2.1.0, but likely true for all versions) pulled from docker hub or built from the provided Dockerfiles appear to be broken due to the issues listed below:

1. Images do not build ABYSS-P due to openmpi linking issues. My experience is that default behavior for yum or apt-get is to install the mpi.h and other header files in a location that is not where abyss expects them. For example using yum to install openmpi and openmpi-devel installs openmpi to /usr/lib64/openmpi and the headers to /usr/include/openmpi-x86_64. My solution was to link /usr/include/openmpi-x86_64 to /usr/lib64/openmpi/include

2. Docker defaults to the root user and mpi will exit with the warning that mpi should not be run as root. You can bypass this with an mpirun flag (-allow-run-as-root) but this is strongly discouraged. My solution was to generate a user within docker and then run as that user.
`RUN groupadd -g 123 abyss && useradd -r -u 123 -g abyss abyss`
`USER abyss`

3. Updates are required to the PATH and LD_LIBRARY_PATH.
`ENV PATH=$PATH:/usr/lib64/openmpi/bin`
`ENV LD_LIBRARY_PATH=/usr/lib64/openmpi/lib`

**Comment by sjackman** [comment]
Thank you for the bug report, @WEClarke. I'll look into it. In the mean time, I suggest using Linuxbrew to install ABySS in Docker.

```sh
docker pull linuxbrew/linuxbrew
docker run -it linuxbrew/linuxbrew
brew install abyss
```

**Comment by WEClarke** [comment]
Mainly wanted to let you know about my experience. I was able to generate a working Docker image running as a non-root user using the workarounds I mentioned.

**Comment by sjackman** [comment]
Thanks for letting us know!

**Comment by sjackman** [comment]
This issue is hopefully resolved by PR https://github.com/bcgsc/abyss/pull/257.
