### ISSUE TITLE
make deleting contigs file in assembly step

### ISSUE THREAD

**Issue by abshah** [bcgsc/abyss#254]
Hi ABySS devs! 
I have strange error with running ABySS  with a bloom filter. The assembly runs for a few day, however, it crashes and then deletes the contigs file. Please advise! 

Thank You

Best Wishes,
Abhijeet

- [ ] version of ABySS
abyss-pe (ABySS) 2.1.1
- [ ] distribution of Linux
Ubuntu 16.04.4 LTS

# Assembly error
- [ ] complete `abyss-pe` command line

`abyss-pe name=Gsib_GB_half_sample k=43 in='/vol/animalbehaviour/subsampled/Gsib_GB_R1_half_sample.fastq /vol/animalbehaviour/subsampled/Gsib_GB_R2_half_sample.fastq' B=64G H=3 kc=3 v=-v np=16
`
- [ ] last 20 lines of the output of `abyss-pe`
Last 20 lines from stderr
```
Extended 22681985 of 55854000 reads (40.6%), saw 31253777 of 55854000 solid reads (56%), assembled 6724398914 bp so far
Extended 22682302 of 55855000 reads (40.6%), saw 31254281 of 55855000 solid reads (56%), assembled 6724453238 bp so far
Extended 22682617 of 55856000 reads (40.6%), saw 31254772 of 55856000 solid reads (56%), assembled 6724503890 bp so far
Extended 22682948 of 55857000 reads (40.6%), saw 31255279 of 55857000 solid reads (56%), assembled 6724562970 bp so far
Extended 22683275 of 55858000 reads (40.6%), saw 31255814 of 55858000 solid reads (56%), assembled 6724618299 bp so far
Extended 22683611 of 55859000 reads (40.6%), saw 31256335 of 55859000 solid reads (56%), assembled 6724673003 bp so far
Extended 22683915 of 55860000 reads (40.6%), saw 31256841 of 55860000 solid reads (56%), assembled 6724731354 bp so far
Extended 22684252 of 55861000 reads (40.6%), saw 31257373 of 55861000 solid reads (56%), assembled 6724784332 bp so far
Extended 22684586 of 55862000 reads (40.6%), saw 31257898 of 55862000 solid reads (56%), assembled 6724840040 bp so far
Extended 22684918 of 55863000 reads (40.6%), saw 31258419 of 55863000 solid reads (56%), assembled 6724899661 bp so far
Extended 22685222 of 55864000 reads (40.6%), saw 31258928 of 55864000 solid reads (56%), assembled 6724952168 bp so far
Extended 22685541 of 55865000 reads (40.6%), saw 31259431 of 55865000 solid reads (56%), assembled 6725003968 bp so far
Extended 22685847 of 55866000 reads (40.6%), saw 31259913 of 55866000 solid reads (56%), assembled 6725050810 bp so far
Extended 22686131 of 55867000 reads (40.6%), saw 31260413 of 55867000 solid reads (56%), assembled 6725101308 bp so far
Extended 22686439 of 55868000 reads (40.6%), saw 31260933 of 55868000 solid reads (56%), assembled 6725153717 bp so far
Extended 22686749 of 55869000 reads (40.6%), saw 31261439 of 55869000 solid reads (56%), assembled 6725206503 bp so far
Extended 22687045 of 55870000 reads (40.6%), saw 31261933 of 55870000 solid reads (56%), assembled 6725254831 bp so far
Extended 22687368 of 55871000 reads (40.6%), saw 31262454 of 55871000 solid reads (56%), assembled 6725309350 bp so far
make: *** [/homes/ashah/anaconda2/envs/snakes/bin/abyss-pe.Makefile:535: Gsib_GB_half_sample-1.fa] Killed
make: *** Deleting file 'Gsib_GB_half_sample-1.fa'

```

- [ ] number of sequenced bases
Approx 230 Gb PE

- [ ] estimated genome size and ploidy
Approx 8.9 Gb, diploid 
- [ ] estimated sequencing depth of coverage
Approx 25.8X

**Comment by sjackman** [comment]
Hi, Abhijeet.
```
make: *** [/…/bin/abyss-pe.Makefile:535: Gsib_GB_half_sample-1.fa] Killed
```
This error `Killed` means that ABySS has exceeded available memory and was killed by either the kernel or the scheduler. That's not expected to happen at this point in the assembly, after the Bloom filter has been constructed. Please report the output of `free -h`.

**Comment by benvvalk** [comment]
@sjackman Agreed -- that is not supposed to happen.

@abshah:

It is hard for me to guess what is causing the crash from the log output alone.  If you have time to help, can you please generate a core dump and stack trace with `gdb`?  That would provide me with some valuable information about where the program is crashing. 

To generate the core dump file, add `ulimit -c unlimited` to the top of your job script.   Then to generate the stacktrace, follow the instructions here: https://stackoverflow.com/questions/5745215/getting-stacktrace-from-core-dump.

It would be even more helpful if you could send me the core file somehow, but it will be a large file.

A Bloom filter size of 64 GB seems a bit low for a genome of that size.   I would recommend something more on the order of 300 GB based on my own experience.  (Hopefully you have a machine with that much memory...)  Can you check the Bloom filter false positive rate reported in the log output (search for "FPR")?  The goal is to have the FPR well below 10%, otherwise the results start to be adversely affected.

**Comment by abshah** [comment]
Hi Shaun, 
I was running this assembly on a cluster. I had requested for 96 GB of memory and 16 cores. Hope this help.

Best,
Abhijeet

**Comment by benvvalk** [comment]
@abshah Also, if you add `v=-vv` (double verbose) to your `abyss-pe` command, the log will report which sequencing read it was processing when it crashed, which may be helpful info.  I realize that this is all probably quite painful, given that the job takes a few days to run (that is expected for a genome of that size, btw).

**Comment by benvvalk** [comment]
@sjackman Thanks for mentioning it!  (I hadn't thought of that.)

**Comment by abshah** [comment]
Hi abyss dev team!
@sjackman @benvvalk  I had submitted this job to a "long" queue, I believe this may not be an issue. It is quite possible that job exceeded the allotted resources, and was killed by SGE/UGE.  I will be resubmitting the k=43 assembly again with more resources, and with stack trace and verbose output option.

@benvvalk 
I had also submitted 2 other jobs with k=91 and k=67 with more resources (about 256GB memory and 32 cores). The assembly with k=91 ran without a hitch (see last 20 lines from std output below), and k=67 is still running.

```
Best scaffold N50 is 1510 at n=10 s=1000.

n       n:1000  L50     min     N75     N50     N25     E-size  max     sum     name
32.48e6 182301  53960   1000    1182    1510    2518    13059   941852  305.3e6 n=10 s=1000
Reading `Gsib_GB_half_sample_k91-6.dot'...
Reading `Gsib_GB_half_sample_k91-6.fa'...
Reading `Gsib_GB_half_sample_k91-6.path'...
Read 426 paths
Ambiguous paths: 301
Merged:          186
No paths:        91
Too many paths:  1
Too complex:     4
Dissimilar:      19
Reading `Gsib_GB_half_sample_k91-7.dot'...
Read 64955696 vertices. Using 8.19 GB of memory.
Reading `-'...
Read 32477848 sequences. Using 19.1 GB of memory.
Reading `Gsib_GB_half_sample_k91-7.path'...
Read 439 paths. Using 19.1 GB of memory.
The minimum coverage of single-end contigs is inf.
The minimum coverage of merged contigs is inf.
n       n:200   L50     min     N75     N50     N25     E-size  max     sum     name
32.48e6 9877573 3031858 200     246     336     540     1521    941852  3.394e9 Gsib_GB_half_sample_k91-8.fa
time user=0.51s system=61.44s elapsed=3899.20s cpu=1% memory=1 job=
time user=4095.91s system=110.32s elapsed=4302.92s cpu=97% memory=18088 job=
Reading `Gsib_GB_half_sample_k91-7.dot'...
Reading `Gsib_GB_half_sample_k91-7.path'...
time user=1161.45s system=53.57s elapsed=1223.17s cpu=99% memory=6 job=
time user=0.00s system=0.00s elapsed=1223.19s cpu=0% memory=1 job=

```


About the FPR rate with the bloom filter:
I will summarize by assembly:
```
k=43: 
Bloom filter FPR: 0.414%
        Bloom filter FPR: 10.8%
        Bloom filter FPR: 0.957%
        Bloom filter FPR: 0.414%

k=67
Bloom filter FPR: 0.086%
        Bloom filter FPR: 3.7%
        Bloom filter FPR: 0.239%
        Bloom filter FPR: 0.086%
k=91
Bloom filter FPR: 0.0446%
        Bloom filter FPR: 3.07%
        Bloom filter FPR: 0.169%
        Bloom filter FPR: 0.0446%

```

So, does this mean that I will need to re-run the k=43 assembly **without** the bloom filter ? 

Thank You!

Best Wishes,
Abhijeet

**Comment by benvvalk** [comment]
@abshah Thanks for the update and additional info! It is a bit of a mystery to me why it would crash at k=43 but not other k values.  I don't often use k values that low, so perhaps the issue has been there all along.  Hopefully the log file and/or stack trace will give some helpful info.   Your Bloom filter FPR values are very low (which is good!).
