### ISSUE TITLE
Can I use different Kmer size within one ABySS assembly?

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#255]
Hi,
I currently have an assembly running where I have 150bp (paired-end) reads as input. However I noticed that my mate-pair data is remarkably smaller than 150bp (or at least a substantial fraction of it). This is something that I have observed in several different projects btw (= that the mate pair data has on average much smaller read lengths after NxTrim, cleaning etc compared to the paired-end). I was now wondering if it would make sense to run the ABySS pipeline up to the scaffold stage with eg Kmer of 120 and then use a kmer of 80 for the scaffolding part, or does this not make sense at all? 
This is mainly affecting the DistanceEST part for the scaffolds I assume.

**Comment by benvvalk** [comment]
HI @lsterck,

Yes, it is true, the trimmed mate pair reads are generally shorter than ordinary paired end reads.

It shouldn't be necessary to do two separate runs, though.  During scaffolding, the minimum alignment length is controlled by a separate parameter `l`, but in most cases the default value of `l=40` works fine.  When using the default aligner (`abyss-map`), `l=40` actually means that there must be a perfect match of 40 bases between each read and its target contig.

**Comment by lsterck** [comment]
Hi @benvvalk 

thanks for the reply.
Yes, I was aware of the `-l` parameter but I then have  a related question: what is the purpose of the `-k` (kmer size) in all this if it's the `-l` that controls the 'match' ? 
Can there be cases where the default `-l` might need to change anyway? highly heterozygous species perhaps?

**Comment by benvvalk** [comment]
@lsterck:

I agree that it is perhaps counterintuitive, but `k` is passed to most of the programs downstream of the de Bruijn graph assembly (e.g. `DistanceEst`) because it provides some info about the input assembly, i.e.:

(1) what is the minimum size of a contig (it is k)
(2) what is the maximum overlap between two contig ends (it is k-1)

**Comment by lsterck** [comment]
A more than sufficient answer, thanks for clarifying.
I'll close the issue.
