### ISSUE TITLE
How does ABySS determine whether read is FR (pe) or RF (mp)

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#259]
I was wondering how abyss (or any of the subprograms: abyss-fixmate? DistanceEst?) determine whether a read is FR or RF mapped, aka if a read-pair is PE or MP. I know there are samflags to indicate this in the sam file but I don't see those if I analyse the sam files produced by abyss-map.

I don't get how it determines whether a read pair is inward (PE) or outward (MP) aligned

**Comment by sjackman** [comment]
The SAM flags used to determine the orientation of a read and its mate are…
```
	0x10	REVERSE       .. SEQ is reverse complemented
	0x20	MREVERSE      .. SEQ of the next segment in the template is reversed
```
Those flags combined with the position of the reads on the contig indicate whether it's FR or RF oriented. Feel free to follow up if you have further questions.

**Comment by benvvalk** [comment]
Thanks, @sjackman.

**Comment by lsterck** [comment]
Hi Shaun,

yes I would think that too, but the sam files I get as output from abyss-map only show flags `0 `or `16 `and none of the other (eg 32), hence the confusion .

and then again, this only shows if the seq has been reverse complemented or not , not that it is inward or outward ampped, no?

**Comment by sjackman** [comment]
`abyss-map` is a single-end read aligner, so it does not use the `0x20 MREVERSE` flag. `abyss-fixmate` adds the `0x20 MREVERSE` flag and other mate information.

> and then again, this only shows if the seq has been reverse complemented or not , not that it is inward or outward ampped, no?

Correct. Whether it is FR or FR oriented is determine by both the flags and the positions of the read and its mate.

**Comment by lsterck** [comment]
makes perfect sense.
thanks

**Comment by lsterck** [comment]
slightly related question:
is it possible I get exactly the same result (stats wise) when I scaffold with a set of MP libraries once forced to `RF `and once with abyss selected `FR `? (yes the libraries are 'dirty' very mixed PE / MP) and I also have other libraries included which are OK.

**Comment by sjackman** [comment]
It's quite unlikely. If you kept the logs of the verbose output, you can diff the two logs and look for differences.

**Comment by lsterck** [comment]
doubled checked all, and, noop, exactly the same :/
no difference in the log file, and exactly the same output. The input is different though: the `.dist.dot` files differ (at least when simply taken diff of both) indeed when using `FR `or force `RF`, the `.hist` files not, but that's expected I assume.

**Comment by sjackman** [comment]
The `.hist` file should be the same. It's produced by `abyss-fixmate`. The `.dist.dot` files should definitely differ. Glad to hear that they do. Try running `abyss-scaffold` with one `.dist.dot` file, and then the other, and you should likely get different results.
