### ISSUE TITLE
Meaning of "Duplicate rate of spanning fragments"

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#262]
Hi,

when mapping reads back the the intermediate assemblies it reports at the end of that step some statistics on "Duplicate rate of spanning fragments"
`Duplicate rate of spanning fragments: 17857099/64966373 (27.5%)`
How should I interpret this? 

thx

**Comment by sjackman** [comment]
It should be roughly equivalent to the rate of PCR duplicates compute by a typical pipeline. You could very that by aligning your reads to either the reference or the assembled contigs and running `samtools markdup`. 27.5% is a pretty high rate of PCR duplicates.

**Comment by lsterck** [comment]
OK, got it.
So, in this case 27% of my reads are likely not that informative for the scaffolding stage? (I assume those duplicates are being filtered out somewhere?)

**Comment by sjackman** [comment]
Yes, PCR duplicates are uninformative, and yes, they're filtered out.
