### ISSUE TITLE
request: show compiled kmer max in --help and/or --version for sealer and bloom

### ISSUE THREAD

**Issue by jbh-cas** [bcgsc/abyss#271]
Currently I use the following to ensure the binaries have been compiled with the same kmer max settings:
#!/bin/bash
#use strings to look in executable for kmer maximum setting for the files on command line
#example usage: abyss-CheckKmerMax.sh abyss-bloom abyss-sealer
for f in $@; do
   printf $f": "; strings $f | grep "length <=[0-9]*"
done

However, it would be nice to have that info reported in either the --help output line:
-k, --kmer=N                 the size of a k-mer
and/or the --version output
thanks, 
Jim Henderson Research Associate California Academy of Sciences
# Please report

- [ ] version of ABySS with `abyss-pe version`
- [ ] distribution of Linux with `lsb_release -d`

# Assembly error

- [ ] complete `abyss-pe` command line
- [ ] last 20 lines of the output of `abyss-pe`
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ ] Have you tried installing ABySS using Brew or Bioconda?
- [ ] version of GCC or compiler with `gcc --version`
- [ ] complete `./configure` command line
- [ ] last 20 lines of the output of `./configure`
- [ ] last 20 lines of the output of `make`

**Comment by benvvalk** [comment]
Yes, I agree. Good suggestion, @jbh-cas.

**Comment by sjackman** [comment]
@sauparna Could you please address this issue?

**Comment by spalchowdhury** [comment]
@jbh-cas, @sjackman, @benvvalk.
Point noted, the fix will appear in the next release.
