### ISSUE TITLE
abyss-2.1.5: should exit when cmdline args have empty value(s)

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#272]
Hi,
  I wondered why my abyss runs now in a single-thread only ... It turned out I edited my shellscript so a variable ${threads} was unset which broke a latter abyss-pe call. However, I think abyss should exit with an error if `np=` or `j=` are empty.

 My command was:

`abyss-pe FIXMATE_OPTIONS=--qname v=-v np= j= k=160 s=500 S=300 n=6 ...`

**Comment by sjackman** [comment]
Hi, Martin. What error message did you eventually see, and how fast did it fail? I'm guessing that it would fail pretty quickly, when it tried to run `ABYSS` (or `ABYSS-P` or `abyss-bloom-dbg`). Is that the case?

If you add `set -eu` to your shell script, it'll catch empty environment variables like `$threads` and make them errors.

Testing that some parameters are non-empty would be useful though.

@TheSeaOfRhun Would you like to tackle this issue?

**Comment by mmokrejs** [comment]
> What error message did you eventually see, and how fast did it fail? I'm guessing that it would fail pretty quickly, when it tried to run ABYSS (or ABYSS-P or abyss-bloom-dbg). Is that the case?

Hi Shaun, it was still splitting input into k-mers, for almost 27hrs using a single-thread. I deleted the logfile already but there was no error AFAICT. Just silently running using single thread.

**Comment by mmokrejs** [comment]
And thanks for the tips. I run it using `bash -x` so that at least helped me to see the variables expanded into an empty string. Oh yes, I learned about `set -o pipefail` some time ago too but forget to use it regularly.

**Comment by sjackman** [comment]
Yep, that looks to be the case. When `j` is set to the empty string, it'll use a default value of `2`. We'll leave this behaviour as is. Though I could see increasing the default number of threads to say 4. I recommend using `set -eux -o pipefail`, which would have caught this issue.

https://github.com/bcgsc/abyss/blob/d4b4b5d3091d90a4967180d987bd7168dbf04585/bin/abyss-pe#L174-L184
