### ISSUE TITLE
Rescaffolding with long sequences QUESTION

### ISSUE THREAD

**Issue by kokyriakidis** [bcgsc/abyss#275]
@sjackman Hello, in order to use RNASeq with abyss do I need to assemble it with transabyss?

**Comment by kmnip** [comment]
Yes, [Trans-ABySS](https://github.com/bcgsc/transabyss
) is intended for assembling RNA-seq reads into transcript sequences.
Please see the wiki for its usage:
https://github.com/bcgsc/transabyss/wiki

You may use the `long` option in ABySS for scaffolding with the long transcript sequences from Trans-ABySS

**Comment by kokyriakidis** [comment]
OK thanks! I just wanted to clarify it! Have a happy new year!

**Comment by kmnip** [comment]
No problem, happy to help.
Happy new year to you, too!
