### ISSUE TITLE
Test failures on 32bit big endian hardware

### ISSUE THREAD

**Issue by tillea** [bcgsc/abyss#276]
Hi,
the Debian packaged version of ABySS 2.1.1 has received a [bug report](https://bugs.debian.org/918575) for architectures with 32bit big endian.  [Here](https://buildd.debian.org/status/package.php?p=abyss) you can see an overview about all afected architectures.  As an example you can review a [full build log for mips](https://buildd.debian.org/status/fetch.php?pkg=abyss&arch=mips&ver=2.1.5-1&stamp=1544257684&raw=0) (see end of that link).  Is there any chance to get the test working also on this architecture or should we simply exclude mips from the list of supported architectures?
Kind regards, Andreas.

**Comment by sjackman** [comment]
Hi, Andreas. Please exclude MIPS from the list of supported architectures. ABySS is intended primarily for high-performance computing (HPC) systems, and I'm not familiar with any MIPS HPC hardware.
