### ISSUE TITLE
abyss-2.1.5: /usr/bin/abyss-bowtie2: line 57: bowtie2-align: command not found

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/abyss#283]
Hi,
  did anybody use `bowtie2` recently from within `abyss`? Seems the change from about 2014 is still unnoticed.

```
bowtie2-align --local -p104 ${foo}-3.fa ${reads}.fa.gz
/usr/bin/abyss-bowtie2: line 57: bowtie2-align: command not found
```

See https://github.com/BenLangmead/bowtie2/issues/4 and http://seqanswers.com/forums/showpost.php?p=138017&postcount=7

So probably calling `bowtie2-align-s` would be a reasonable default. But the syntax has changed as well, so it seems `-x $prefix` and `-1 fwd.fa.gz` `-2 rev.fa.gz` are needed, maybe in conjunction with `-f` if input files are not in `FASTQ`. Support for interleaved FASTQ files was added in `bowtie-2.3.1` in https://github.com/BenLangmead/bowtie2/issues/75 via `--interleaved`.

**Comment by sjackman** [comment]
No, I haven't used ABySS with bowtie2. Feel free to submit a PR if you're interested in this feature.

**Comment by mmokrejs** [comment]
Finally, `bowtie2` received two relevant fixes so that `bowtie2-align-{s,l} --interleaved $file` should work for FASTA and FASTQ inputs. The patches should I assume appear in `bowtie-2.1.6`.

https://github.com/BenLangmead/bowtie2/commit/753df9deca210db54e1ecc94f946b413876e456e
https://github.com/BenLangmead/bowtie2/commit/d7eab7cf6b7e238047044cf61acc662b05c772c4

Here is a sketch of changes:

```
--- abyss/bin/abyss-bowtie2.ori	2019-01-24 01:04:29.000000000 +0100
+++ abyss/bin/abyss-bowtie2	2019-03-31 01:39:12.523886916 +0100
@@ -21,8 +21,63 @@
 		;;
 esac
 
+# Bowtie 2 version 2.3.5 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)
+# Usage: 
+#  bowtie2-align [options]* -x <bt2-idx> {-1 <m1> -2 <m2> | -U <r> | --interleaved <i>} [-S <sam>]
+#
+#  <bt2-idx>  Index filename prefix (minus trailing .X.bt2l).
+#             NOTE: Bowtie 1 and Bowtie 2 indexes are not compatible.
+#  <m1>       Files with #1 mates, paired with files in <m2>.
+#  <m2>       Files with #2 mates, paired with files in <m1>.
+#  <r>        Files with unpaired reads.
+#  <i>        Files with interleaved paired-end FASTQ/FASTA reads
+#  <sam>      File for SAM output (default: stdout)
+#
+#  <m1>, <m2>, <r> can be comma-separated lists (no whitespace) and can be
+#  specified many times.  E.g. '-U file1.fq,file2.fq -U file3.fq'.
+#
+# Bowtie 2 version 2.3.5 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)
+# Usage: 
+#  bowtie2-align [options]* -x <bt2-idx> {-1 <m1> -2 <m2> | -U <r> | --interleaved <i>} [-S <sam>]
+#
+#  <bt2-idx>  Index filename prefix (minus trailing .X.bt2l).
+#             NOTE: Bowtie 1 and Bowtie 2 indexes are not compatible.
+#  <m1>       Files with #1 mates, paired with files in <m2>.
+#  <m2>       Files with #2 mates, paired with files in <m1>.
+#  <r>        Files with unpaired reads.
+#  <i>        Files with interleaved paired-end FASTQ/FASTA reads
+#  <sam>      File for SAM output (default: stdout)
+#
+#  <m1>, <m2>, <r> can be comma-separated lists (no whitespace) and can be
+#  specified many times.  E.g. '-U file1.fq,file2.fq -U file3.fq'.
+#
+# ...
+#
+# -q                 query input files are FASTQ .fq/.fastq (default)
+# -f                 query input files are (multi-)FASTA .fa/.mfa
+# Paired-end:
+#  -I/--minins <int>  minimum fragment length (0)
+#  -X/--maxins <int>  maximum fragment length (500)
+#  --fr/--rf/--ff     -1, -2 mates align fw/rev, rev/fw, fw/fw (--fr)
+#  --no-mixed         suppress unpaired alignments for paired reads
+#  --no-discordant    suppress discordant alignments for paired reads
+#  --dovetail         concordant when mates extend past each other
+#  --no-contain       not concordant when one mate alignment contains other
+#  --no-overlap       not concordant when mates overlap at all
+#
+#  --no-unal          suppress SAM records for unaligned reads
+#  --rg-id <text>     set read group id, reflected in @RG line and RG:Z: opt field
+#  --rg <text>        add <text> ("lab:value") to @RG line of SAM header.
+#                     Note: @RG line only printed when --rg-id is set.
+#
+#  --xeq              Use '='/'X', instead of 'M,' to specify matches/mismatches in SAM record.
+#  --soft-clipped-unmapped-tlen Exclude soft-clipped bases when reporting TLEN
+#
+#  -p/--threads <int> number of alignment threads to launch (1)
+#  --mm               use memory-mapped I/O for index; many 'bowtie's can share
+
 # Parse the command line.
-bowtie2_align='bowtie2-align --local'
+bowtie2_align='bowtie2-align-l --very-sensitive-local -mm'
 while getopts :j:l:v opt; do
 	case $opt in
 		j) bowtie2_align="$bowtie2_align -p$OPTARG";;
@@ -42,16 +97,16 @@
 # Build the index.
 if [ ! -r $index ]; then
 	echo >&2 "Building the index $index..."
-	echo >&2 bowtie2-build $target $target
-	bowtie2-build $target $target 1>&2
+	echo >&2 bowtie2-build-l --threads $threads $target $target
+	bowtie2-build-l --threads $threads $target $target 1>&2
 elif [ $index -ot $target ]; then
 	echo >&2 "The index $index is stale. Rebuilding the index..."
-	echo >&2 bowtie2-build $target $target
-	bowtie2-build $target $target 1>&2
+	echo >&2 bowtie2-build-l --threads $threads $target $target
+	bowtie2-build-l --threads $threads $target $target 1>&2
 else
 	echo >&2 "The index $index is up to date."
 fi
 
 # Map the reads.
-echo >&2 $bowtie2_align $target "${query[@]}"
-exec abyss-tofastq -i "${query[@]}" |$bowtie2_align $target -
+echo >&2 $bowtie2_align -x $target --interleaved "${query[@]}"
+exec abyss-tofastq -i "${query[@]}" |$bowtie2_align -x $target --interleaved -
```

I had a look into `abyss-pe` but it seems there is no way to pass down number of threads for example? I am not sure but I suspect we need to pass down also information whether the input files are FASTA or FASTQ.
Does the `"${query[@]}"` contain only files with interleaved reads or are there also singleton files to be expected?
I emphasized other relevant options of `bowtie2` whcih we might want to expose.

**Comment by sjackman** [comment]
ABySS doesn't necessarily need a paired-end aware aligner. The reads can be aligned as single-end. The output of `abyss-bowtie2` is read by `abyss-fixmate`, which handles pairing up the paired reads.

This change assumes that the paired reads are interleaved. That's my preferred format too. ABySS doesn't assume the reads are interleaved though.

**Comment by mmokrejs** [comment]
Thank you. Well I did not spend enough time studying `abyss-pe` internals to realize what is really sent via `"${query[@]}"`. I would prefer if you finished the logic here. And the new `for` loop will maybe not work as expected.

**Comment by mmokrejs** [comment]
Hi,
  So I ran into this error again with `abyss-2.2.5` and `2.3.0`. `bowtie2-align` is gone at least in `bowtie-2.4.2`. Please call `bowtie2-align-l` instead in `abyss-bowtie2` script. The script should exist if for example `File not found` errors out. Would you mind revisiting the changes I proposed in teh past?

**Comment by sjackman** [comment]
Feel free to submit a PR if you're interested in this feature.

**Comment by mmokrejs** [comment]
Thank you. I tried my best in the past as you can see above, it did not capture all usage scenarios. And as I am getting lost in the upper levels of `abyss-pe` Makefile and its variables, I will not make this.

But let me mention that `align=bowtie2` does not work at the moment at all. The culprit is too new `bowtie2` on my side, true, not providing the wrapper anymore. I am free to test your eventual patches rescuing the `bowtie2` functionality.
