### ISSUE TITLE
abyss-1.3.5 error

### ISSUE THREAD

**Issue by maojn** [bcgsc/abyss#286]
Hi,

I am building a pipeline which require abyss-1.3.5. When I tried to compile, I got the following error:

```
In file included from DotWriter.cpp:5:0:
../Graph/ContigGraphAlgorithms.h: In function ‘OutIt assemble_if(Graph&, OutIt, Predicate)’:
../Graph/ContigGraphAlgorithms.h:202:44: error: typedef ‘vertex_descriptor’ locally defined but not used [-Werror=unused-local-typedefs]
  typedef typename Graph::vertex_descriptor vertex_descriptor;
                                            ^
cc1plus: all warnings being treated as errors
make[2]: *** [libassembly_a-DotWriter.o] Error 1
make[2]: Leaving directory `/scratch/maoj/abyss-1.3.5/Assembly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/scratch/maoj/abyss-1.3.5'
make: *** [all] Error 2
```

Could you advice what to do. Thank you.

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
If the pipeline is Trans-ABySS, I believe that recent versions of Trans-ABySS are able to use ABySS 2.

We don't recommend using old versions of ABySS, and they're not supported. That said, to get past this particular error, try…
```sh
./configure --disable-werror
make
```
