### ISSUE TITLE
abyss 2.1.4 doesn't detect OpenMPI on CentOS 7

### ISSUE THREAD

**Issue by alanorth** [bcgsc/abyss#288]
Similar to #224, I have problems getting abyss 2.1.4 to detect CentOS 7's OpenMPI 3.0 installation. If I set `CPPFLAGS` and `LIBS` manually then support is detected and `ABYSS-P` is compiled as expected.

Versions:

- CentOS Linux release 7.6.1810 (Core)
- openmpi3-devel-3.0.2-1.el7.x86_64
- gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

# Configure error
The `configure` script fails to detect OpenMPI when using `with-mpi`.

```
$ ./configure --prefix=/export/apps/abyss/2.1.4 --with-mpi=/usr/include/openmpi3-x86_64 2>/dev/null | grep -E '(mpi\.h|lmpi)'
checking mpi.h usability... no
checking mpi.h presence... no
checking for mpi.h... no
checking for MPI_Init in -lmpi... no
$ make
$ ls -l Parallel/ABYSS-P 
ls: cannot access Parallel/ABYSS-P: No such file or directory
```

If I set the paths manually it detects support and compiles `ABYSS-P`:

```
$ export CPPFLAGS='-pthread -I/usr/include/openmpi3-x86_64'
$ export LIBS='-Wl,-rpath -Wl,/usr/lib64/openmpi3/lib -Wl,--enable-new-dtags -L/usr/lib64/openmpi3/lib -lmpi'
$ ./configure --prefix=/export/apps/abyss/2.1.4 2>/dev/null | grep -E '(mpi\.h|lmpi)'
checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking for MPI_Init in -lmpi... yes
$ make
$ ls -l Parallel/ABYSS-P 
-rwxrwxr-x. 1 aorth aorth 3977960 Jul 10 17:40 Parallel/ABYSS-P*
```

**Comment by sjackman** [comment]
The directory structure of OpenMPI on CentOS 7 is a bit odd, in that there's no directory that has both a `lib` and `include` directory beneath it. You could create such a directory in your home directory using symlinks. The workaround that you found is fine though.

I recommend installing ABySS using either Homebrew on Linux or Bioconda. See https://github.com/bcgsc/abyss#quick-start and https://bioconda.github.io/recipes/abyss/README.html
