### ISSUE TITLE
abyss-pe using long pacbio reads stuck

### ISSUE THREAD

**Issue by rimjhimroy** [bcgsc/abyss#290]
Hi,

I am working on the assembly of a 1G diploid plant genome using abyss-pe 2.1.5 on a CentOS Linux 7 machine. I have 60x paired-end Illumina reads to assemble and I want to use 7x Pacbio reads for scaffolding. I have used the hybrid error correction program FMLRC and I am using the corrected Pacbio reads for the assembly. I am using the following command:

`abyss-pe G=1000000000 v=-v np=10 j=10 k=197 name=Blaev_Sq lib='bla blb' long='longa' bla='fastq/Blaev_Seq_S1_L001_1.fastq.gz fastq/Blaev_Seq_S1_L001_2.fastq.gz' blb='fastq/Blaev_Seq_S1_L002_1.fastq.gz fastq/Blaev_Seq_S1_L002_2.fastq.gz' se='fastq/Blaev_Seq_S1_L001_R1_001.unpaired.fastq.gz fastq/Blaev_Seq_S1_L001_R2_001.unpaired.fastq.gz fastq/Blaev_Seq_S1_L002_R1_001.unpaired.fastq.gz fastq/Blaev_Seq_S1_L002_R2_001.unpaired.fastq.gz' longa='pacbio1/blaev_corrected_pbio.fa'`

Abyss run pretty well with the paired-end reads and produced the '-contigs.fa' and '*-scaffolds.fa'. But now it is stuck for 20 hours in the long read stage:
`bwa mem -a -t10 -S -P -k40 Blaev_Sq-8.fa /data/users/rchoudhury/biscutella_genome/pacbio1/blaev_corrected_pbio.fa \
        |pigz -p10 >longa-8.sam.gz`

 
```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 15510 sequences (100000573 bp)...
[M::process] read 16048 sequences (100000970 bp)...
[M::mem_process_seqs] Processed 15510 reads in 21331.173 CPU sec, 10119.066 real sec
[M::process] read 15802 sequences (100034887 bp)...
[M::mem_process_seqs] Processed 16048 reads in 11724.295 CPU sec, 7223.371 real sec
[M::process] read 15886 sequences (100009053 bp)...
```
The bwa process is using just 1 cpu at the moment:
```
102642 rchoudh+  20   0 6818056   5.8g   1096 S  99.7  0.3   1873:28 bwa

strace -p 102642

strace: Process 102642 attached
futex(0x7f0998f919d0, FUTEX_WAIT, 102730, NULL
```

Do you think I should wait for it to finish or is there some problem with the run?

Thanks a lot,
Rimjhim

**Comment by sjackman** [comment]
Long reads aren't yet supported with ABySS. Sorry. Try changing `long='longa' ` to `se='longa'` and then use LINKS to scaffold the assembly afterward. See https://github.com/bcgsc/links
