### ISSUE TITLE
abyss -4.fa, -5.fa, -7.fa files do not include all sequences mentioned in their graph counterparts.

### ISSUE THREAD

**Issue by bjclavijo** [bcgsc/abyss#291]
When running a trivial example (e.coli dataset), the GFA output mentions sequences that are not defined on the .fa files corresponding to that graph for the graphs 4, 5, and 7. I am not sure if this is expected behaviour as these are intermediate steps, but it defeats the point of having the output on GFA. This is consistent when running with GFA and GFA2 outputs, as well as .dot. It seems to be just a matter of the dump to the .fa files.

This was tested on abyss-pe (ABySS) 2.1.5, on a Mac, installed via brew.

**Comment by sjackman** [comment]
This is indeed the intended behaviour. -3.fa and -4.fa together have the sequences for the -4.gfa file. It's done this way to reduce disk space. The files 1, 3, 6, 8 and are complete, and we refer to them as pre-unitigs, unitigs, contigs, and scaffolds. Although in retrospect, it should have been unitigs, bubble-popped, contigs, and scaffolds.

**Comment by bjclavijo** [comment]
Is this clarified anywhere? I honestly looked for it and couldn't find it.

Best,

bj

**Comment by sjackman** [comment]
No, I don't believe so. These numbered files are considered internal temporary files. The `name-unitigs.fa`, `name-contigs.fa`, and `name-scaffolds.fa` symlinks are intended to be exposed to the user.
