### ISSUE TITLE
Unable to run in parallel mode

### ISSUE THREAD

**Issue by soungalo** [bcgsc/abyss#292]
I am trying to run abyss-pe. It runs fine as long as I use a single thread. However, when I try to use parallel mode by specifying np=<n>, it crashes immediately and I get the following error:
```
ERROR: ld.so: object '/powerapps/share/ogrt/client/client-v0.5.0/lib64/libogrt.so' from LD_PRELOAD cannot be preloaded: ignored.
python2.4: error while loading shared libraries: libstdc++.so.5: cannot open shared object file: No such file or directory
make: *** [/groups/itay_mayrose/liorglic/miniconda3/envs/AbySS/bin/abyss-pe.Makefile:551: dixie-1.fa] Error 127
```
I was trying to run on a single machine, but I guess this has something to do with openmpi installation. Not sure how to proceed though. Can you please advise?

- [x] version of ABySS with `abyss-pe version`
2.15
- [x] distribution of Linux with `lsb_release -d`
CentOS Linux release 7.3.1611 (Core)
- [x] complete `abyss-pe` command line
`abyss-pe name=dt k=64 in='reads_1.fastq reads_2.fastq' np=20`
- [x] last 20 lines of the output of `abyss-pe`
`/usr/local/bin/mpirun -np 20 ABYSS-P -k64 -q3    --coverage-hist=coverage.hist -s dt-bubbles.fa  -o dt-1.fa reads_1.fastq reads_2.fastq`
- [x] number of sequenced bases
35Gb
- [x] estimated genome size and ploidy
Diploid, 900Mb
- [x] estimated sequencing depth of coverage
x38

**Comment by sjackman** [comment]
Try parallelizing ABySS using its Bloom filter de Brujin graph, rather than hash table dBG. The former uses MPI, whereas the later uses OpenMP, and is usually easier to get running. See http://bcgsc.github.io/abyss/#assembling-using-a-bloom-filter-de-bruijn-graph

**Comment by soungalo** [comment]
Thanks for the advice - this indeed runs fine.
I'm just unclear about which parameter controls the number of threads used - is it kc or H?
Any recommendations for the values of B, H and kc in my case?
I'm running on a 62G RAM machine with 20 CPUs, so I guess B=50G should work, but what about kc and H?
Thanks!

**Comment by sjackman** [comment]
`j` sets the number of threads. Try `abyss-pe j=20 B=50G kc=3 H=2`
