### ISSUE TITLE
Hi, I am currently trying to use abyss-sealer on an assembly produced by supernova in which pigment and arcs were run afterwards. My question is: which of the reads I should use? In most of the examples I see that they have reads1 and reads2 separately, but I have them interleaved after using longranger basic, or I have the pre-processed reads, is it fine to use the interleaved ones? Or is this going to mess with the algorithm?

### ISSUE THREAD

**Issue by majogomezhughes** [bcgsc/abyss#293]
# Please report

- [ ] version of ABySS with `abyss-pe version`
- [ ] distribution of Linux with `lsb_release -d`

# Assembly error

- [ ] complete `abyss-pe` command line
- [ ] last 20 lines of the output of `abyss-pe`
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ ] Have you tried installing ABySS using Brew or Bioconda?
- [ ] version of GCC or compiler with `gcc --version`
- [ ] complete `./configure` command line
- [ ] last 20 lines of the output of `./configure`
- [ ] last 20 lines of the output of `make`

**Comment by majogomezhughes** [comment]
Hi, I am currently trying to use abyss-sealer on an assembly produced by supernova in which tigmint and arcs were run afterwards. My question is: which of the reads I should use? In most of the examples I see that they have reads1 and reads2 separately, but I have them interleaved after using longranger basic, or I have the pre-processed reads, is it fine to use the interleaved ones? Or is this going to mess with the algorithm? Or should I use the reads as they were delivered by 10X?
Thanks!

**Comment by lcoombe** [comment]
Hi @majogomezhughes,

It is perfectly fine to use interleaved reads files with Sealer (It works with R1/R2 separate or interleaved in a file), and you should use the post-longranger reads (ie. So the barcode is removed from R1 and in the read header).

Hope that helps!
Lauren
