### ISSUE TITLE
COPYRIGHT doesn't match vendor/btl_bloomfilter/COPYING

### ISSUE THREAD

**Issue by mr-c** [bcgsc/abyss#295]
Would be great if it [btl_bloomfilter](https://github.com/bcgsc/btl_bloomfilter) was released under GPL-3, but it is not.

Without this being relicensed to a real free/open license we cannot distribute this code in Debian. Does Abyss work without this library? If not, we won't be distributing v2.2.0 and any subsequent released that rely on similarly non-F/OSS code :-(

Hopefully this is an easy fix!

**Comment by mr-c** [comment]
Seems to be a problem back to the v2.0.0 release: https://github.com/bcgsc/abyss/commit/652d1f5a76e705a4655b745cd4dcd6d8007a5578#diff-e8acc63b1e238f3255c900eed37254b8

**Comment by sjackman** [comment]
@JustinChu Can you please change https://github.com/bcgsc/btl_bloomfilter/blob/master/COPYING to GPL-3?

**Comment by sjackman** [comment]
I've opened PR https://github.com/bcgsc/btl_bloomfilter/pull/32 to change the license to GPL-3.

**Comment by mr-c** [comment]
Thank you @sjackman and @JustinChu ; let's keep this issue open until the local copy is updated

**Comment by sjackman** [comment]
@jowong4 Could you please update the `LICENSE` file of the `btl_bloomfilter` copy vendored into ABySS?

**Comment by jowong4** [comment]
@sjackman The `LICENSE` file within `btl_bloomfilter` has been updated in 2.2.1.
@mr-c Abyss 2.2.1 has been updated with 1.2.1 of `btl_bloomfilter` which is now released under GPL-3

**Comment by mr-c** [comment]
@jowong4 confirmed, thank you!
