### ISSUE TITLE
Error in mpirun configuration for Slurm

### ISSUE THREAD

**Issue by qyang13** [bcgsc/abyss#297]
Hi there, 

I noticed in the abyss-pe makefile, for slurm configuration you set the np equals the number of **tasks** for the job, instead of number of **nodes**.

```
# Integrate with SLURM
ifdef SLURM_JOB_NAME
name?=$(SLURM_JOB_NAME)
endif
ifdef SLURM_ARRAY_TASK_ID
k?=$(SLURM_ARRAY_TASK_ID)
endif
ifdef SLURM_NTASKS
np?=$(SLURM_NTASKS)
endif
```

However, for the typical mpich configuration on slurm, the -np for mpirun option corresponds to the number of **nodes**. This would cause mpich error when the user runs the slurm job using 1 node with 32 threads (the abyss-pe would set mpirun -np to 32).

If you change the block of code a little bit, the problem is resolved:

```
# Integrate with SLURM
ifdef SLURM_JOB_NAME
name?=$(SLURM_JOB_NAME)
endif
ifdef SLURM_ARRAY_TASK_ID
k?=$(SLURM_ARRAY_TASK_ID)
endif
ifdef SLURM_NNODES
np?=$(SLURM_NNODES)
endif
```

**Comment by sjackman** [comment]
On a machine with one node and 32 threads, the correct number of processes to run with ABYSS-P is 32 and so `mpirun -np 32`.

**Comment by sjackman** [comment]
I think I may see the source of the confusion. If you were to be running a program that is a hybrid OpenMPI and OpenMP job, where if you have 2 machines and each machine has 16 threads, then you would start two processes with `mpirun -np 2`, and then each process would then spawn 16 threads. ABYSS-P is not a hybrid OpenMPI / OpenMP program. It is pure OpenMPI. If you have 2 machines each with 16 threads, then you start 32 processes with `mpirun -np 32 ABYSS-P …`.
