### ISSUE TITLE
ABySS aborted (core dumped)

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/abyss#298]
# Please report

- [ ] version of ABySS with `abyss-pe version`

abyss-pe version 2.2.1

- [ ] distribution of Linux with `lsb_release -d`

ubuntu 18.04.3 LTS

# Assembly error

- [ ] complete `abyss-pe` command line

`abyss-pe k=75 j=24 G=4000000000 B=90G H=3 kc=3 v=-v name=lculinaris pe='pea peb pec ped' pea='/HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-1a_HLYL3DSXX_L3_val_1.fq.gz /HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-1a_HLYL3DSXX_L3_val_2.fq.gz' peb='/HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-1a_HLYL3DSXX_L4_val_1.fq.gz /HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-1a_HLYL3DSXX_L4_val_2.fq.gz' pec='/HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-2a_HLYL3DSXX_L4_val_1.fq.gz /HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-2a_HLYL3DSXX_L4_val_2.fq.gz' ped='/HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-2a_HM25NDSXX_L2_val_1.fq.gz /HDD2/Illumina_de_novo_fastq/DNA/LC002_FDES19H000909-2a_HM25NDSXX_L2_val_2.fq.gz' lr='lra lrb lrc lrd' lra='/HDD2/Illumina_10x_fastq/LC001_1/LC001_1_barcoded.fastq.gz' lrb='/HDD2/Illumina_10x_fastq/LC001_2/LC001_2_barcoded.fastq.gz' lrc='/HDD2/Illumina_10x_fastq/LC001_3/LC001_3_barcoded.fastq.gz' lrd='/HDD2/Illumina_10x_fastq/LC001_4/LC001_4_barcoded.fastq.gz'`

- [ ] last 20 lines of the output of `abyss-pe`

`Loaded 376650000 reads into Bloom filter
Loaded 376660000 reads into Bloom filter
Loaded 376670000 reads into Bloom filter
Loaded 376680000 reads into Bloom filter
Loaded 376690000 reads into Bloom filter
Loaded 376700000 reads into Bloom filter
Loaded 376710000 reads into Bloom filter
Loaded 376720000 reads into Bloom filter
Loaded 376730000 reads into Bloom filter
Loaded 376740000 reads into Bloom filter
Loaded 376750000 reads into Bloom filter
Loaded 376760000 reads into Bloom filter
Loaded 376770000 reads into Bloom filter
Loaded 376780000 reads into Bloom filter
Loaded 376790000 reads into Bloom filter
Loaded 376797580 reads from `/HDD2/Illumina_10x_fastq/LC001_4/LC001_4_barcoded.fastq.gz` into Bloom filter
Bloom filter FPR: 46.9%
Counting Bloom filter stats:
	#counters               = 96636764160
	#size (B)               = 96636764160
	threshold               = 3
	popcount                = 11336393515
	FPR                     = 0.161%
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
/home/linuxbrew/.linuxbrew/bin/abyss-pe:538: recipe for target 'lculinaris-1.fa' failed
make: *** [lculinaris-1.fa] Error 134`

- [ ] number of sequenced bases

800 Gb

- [ ] estimated genome size and ploidy

4Gb and diploid

- [ ] estimated sequencing depth of coverage

135x Illumina PE and 60x 10x Genomics PE reads

I installed ABySS from homebrew/bio with linuxbrew.

**Comment by jowong4** [comment]
How much ram does your system have?

**Comment by hidvegin** [comment]
I have got 96 GB ram and 24 CPU cores.

**Comment by jowong4** [comment]
> I have got 96 GB ram and 24 CPU cores.

In this version of abyss, with your command, abyss builds a counting bloom filter with 90 GB and then uses an additional 11.25 GB (12.5% of 90GB) to build another bloomfilter to track visited kmers. For now you can decrease 90GB to 80GB, and it should work. We will be releasing a version shortly to fix this issue. Sorry for the inconvenience.

**Comment by hidvegin** [comment]
Thank you for your fast reply and help. I will try it with your suggestion.

**Comment by jowong4** [comment]
@Stale It is still relevant, thanks for checking. Release is ready within the next couple days

**Comment by jowong4** [comment]
@hidvegin 

If you were to run the same command in release 2.2.3, it shoudn't fail anymore. Note, I did a run just like yours where I specified 90GB for the bloom filter and the peak memory usage for abyss was 95Gb so I don't recommend using 90GB for your specific system. To be safe I would set it to something between 80-85GB depending on what you also have running.
