### ISSUE TITLE
How to get sequences back into the ABySS 'pipeline'

### ISSUE THREAD

**Issue by lsterck** [bcgsc/abyss#299]
Hi,

following the advice from elsewhere in this github, I scaffolded my sequences using long reads with LINKS. Now I want to scaffold them again but this time using the long-read option (== for RNAseq data) in ABySS itself .

However I'm quite confused how to achieve this (if possible at all) since I have a hard time figuring out where to 'pick in' on the normal ABySS workflow. More precisely I be able to do the long option scaffolding in ABySS I need to have .dot and/or .path files but the steps that are generating these files always make use of similar kind of files of the previous step.

Is there any way I can generate .dot or .path files without building on top of existing .dot files?

thx in advance

**Comment by lcoombe** [comment]
Hi @lsterck,

Yes, to generate the dot file that you need for the abyss-longscaffolding, you can use `AdjList`:
```
AdjList -v -m50 -k${k} --dot ${prefix}-8.fa > ${prefix}-8.dot
```
Where `${prefix}-8.fa` is your assembly scaffolds file.

From there, you can run `abyss-pe` with the `long-scaffs` target, but I often find it easier to just extract the long-scaffolding commands from `abyss-pe` and run them separately -- it can be difficult to get ABySS to start from the stage you want it to using the Makefile.

You can see the commands you need to run by doing a `abyss-pe -n` dry-run, or in case you are unsure I also pasted the commands for long-scaffolding below (with variables that you'd have to fill in).

```
bwa index ${prefix}-8.fa
bwa mem -a -t$j -S -P -k50 ${prefix}-8.fa ${long} \
        |gzip > cDNA-8.sam.gz
abyss-longseqdist -k${k}  cDNA-8.sam.gz \
        |grep -v "l=" >cDNA-8.dist.dot
abyss-scaffold -v  -k${k} -s1000-10000 -n1 -g ${prefix}-8.path.dot  ${prefix}-8.dot cDNA-8.dist.dot >${prefix}-8.path
PathConsensus -v --dot -k${k}  -p0.9 -s ${prefix}-9.fa -g ${prefix}-9.dot -o ${prefix}-9.path ${prefix}-8.fa ${prefix}-8.dot ${prefix}-8.path
cat ${prefix}-8.fa ${prefix}-9.fa \
        |MergeContigs -v  -k${k} -o ${prefix}-10.fa - ${prefix}-9.dot ${prefix}-9.path
ln -sf ${prefix}-10.fa ${prefix}-long-scaffs.fa
```

Hope that helps!
Lauren

**Comment by lsterck** [comment]
Hi @lcoombe ,

super, that's just what I needed! 

yes, indeed, glad to see my approach being approved, that's actually how I've been running most of the abyss pipeline. I feel it offers more flexibility that way.

thanks a bunch.

**Comment by lcoombe** [comment]
No worries - Thank you for your interest in our tools!
