### ISSUE TITLE
Ambiguous bases problem with ABySS v.2.01

### ISSUE THREAD

**Issue by rahil19** [bcgsc/abyss#302]
# Please report

- [x] version of ABySS with `abyss-pe version`
abyss-pe (ABySS) 2.0.1

- [x] distribution of Linux with `lsb_release -d`
Description:	CentOS Linux release 7.4.1708 (Core) 

# Assembly error

- [x] complete `abyss-pe` command line
```
kmer=25 
while [ $kmer -le 96 ]

 do

  abyss-pe name=${sm}_assembly_kmer${kmer} k=$kmer in="$reads1 $reads2" &> ${sm}_abyss_run_log.txt

  kmer=`expr $kmer + 1`

 done


```

The assembly was done on mixed samples of provirus HIV. The samples were mixed to see if we can get ambiguous bases in the assembly. It seems like, irrespective of the contigs, small or large, none of the IUPAC mixed bases were found. Reads that were used in the assembly, were aligned to the contig of max length. Attached is the screenshot of IGV displaying positions of multiple bases of reads, but no corresponding mixed bases in assembly. Instead, base with major constituent is reported, irrespective of the percentage reads with such base. In some positions, such as position: 505 and 550 , in this example, the minor base (i.e. G with 33% and T with 37%) is reported. Please look at screenshot 2 and 3 for the same alignment for explanation of the above observation.

![Screen Shot 2019-10-04 at 10 09 07 AM](https://user-images.githubusercontent.com/32267950/66223041-83afc080-e6a0-11e9-9be4-2490c3be73aa.png)

![Screen Shot 2019-10-04 at 3 29 22 PM](https://user-images.githubusercontent.com/32267950/66234715-6557be00-e6bc-11e9-95d0-494605d29b20.png)

![Screen Shot 2019-10-07 at 10 33 35 AM](https://user-images.githubusercontent.com/32267950/66321102-142f1080-e8ee-11e9-9aa1-51e4cfab1954.png)

Could you let me know why is such a case, when ABySS is known to give ambiguous bases, according to IUPAC codes, in positions with multiple types of bases? Longest assembled contig from ABySS v2.01 is shown in the bottom of each IGV screenshot.

**Comment by kmnip** [comment]
These single nucleotide variants were most likely bubbles in the graph. If these bubbles were popped (ie. one branch remains and all others removed), then the variants won't be outputted as IUPAC codes.

If I remember correctly, ABySS would only output IUPAC codes during its PathConsensus steps.

**Comment by rahil19** [comment]
So what is making them pop? Any reason? If you look at either 2nd or 3rd screenshots,  you'll notice:
1. In 2nd pic, A is 67% and G is 33%. Instead of either A or R, ABySS calls G in assembly
2. In 3rd pic, C is 67% and T is 33%. Here too, instead of calling either C or Y, it calls T

Whatever is causing the bubbles to pop, it is generating wrong assembly. The reads I aligned to the AbySS assembly here, are the reads that were given as input to AbySS to generate such assembly.

**Comment by sjackman** [comment]
Most assemblers output the majority consensus base. If you want to call variants, you'll need to align the reads to the assembly and call variants in a second step with a different tool. ABySS chooses the majority consensus base using *k*-mer count frequencies, which usually correspond to the majority consensus base, but not always.
