### ISSUE TITLE
error: unexpected character: 'N'

### ISSUE THREAD

**Issue by tseemann** [bcgsc/abyss#303]
# Please report

- [x] version of ABySS with `abyss-pe version` = 2.2.1
- [ ] distribution of Linux with `lsb_release -d` 

# Assembly error

- [x] complete `abyss-pe` command line

```
byss-pe name=abyss-illumina K=16 k=96 B=100G H=3 kc=3 np=64 
in='trimmed-readsR1.fastq trimmed-readsR2.fastq'
```

- [x] last 20 lines of the output of `abyss-pe`

```
error: unexpected character: 'N'
AdjList: Sequence.cpp:103: uint8_t baseToCode(char): Assertion `false' failed.
make: *** [/shared/bin/abyss-pe:560: abyss-illumina-1.dot] Aborted (core dumped)
make: *** Deleting file 'abyss-illumina-1.dot'
```

- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

CC: @AnnaSyme

@sjackman said:
```
Paired de Bruin graph K and Bloom filter mode B can't be mixed.
The paired de Bruijn graph was our first attempt at reducing the memory usage of ABySS.
The Bloom filter de Bruijn graph was much more successful.
There's no reason to use K any more.
It's superseded by the Bloom filter de Bruijn graph.
```

**Comment by sjackman** [comment]
Specifying `K` should probably give an error. It was only ever experimental.
