### ISSUE TITLE
Test data no longer available for download

### ISSUE THREAD

**Issue by EricFromCanada** [bcgsc/abyss#305]
It seems the URL to download [test-data.tar.gz](http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.4/test-data.tar.gz) as mentioned in [README.md](https://github.com/bcgsc/abyss/blob/master/README.md) and the the [Homebrew formula](https://formulae.brew.sh/formula/abyss) is no longer valid, nor is this [later version](http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.6/test-data.tar.gz) pulled from the Google cache. Is it possible for someone to find and reupload it to a new location?

**Comment by jowong4** [comment]
@EricFromCanada The website hosting the data has undergone some update. I'm in contact with them and they are working on restoring the package.

**Comment by jowong4** [comment]
@EricFromCanada  Here it is. https://www.bcgsc.ca/sites/default/files/bioinformatics/software/abyss/releases/1.3.4/test-data.tar.gz
