### ISSUE TITLE
abyss HPC usage optimalization

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/abyss#308]
# Please report

- [X ] version of ABySS with `abyss-pe version`
2.2.3
- [X ] distribution of Linux with `lsb_release -d`
Ubuntu 18.04.3 LTS

# Assembly error

- [ ] complete `abyss-pe` command line
- [ ] last 20 lines of the output of `abyss-pe`
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ ] Have you tried installing ABySS using Brew or Bioconda?
- [ ] version of GCC or compiler with `gcc --version`
- [ ] complete `./configure` command line
- [ ] last 20 lines of the output of `./configure`
- [ ] last 20 lines of the output of `make`

I would like to use abyss-pe 2.2.3 for mapping de novo 4 Gbp plant genome. I have got 100x coverage Illumina PE reads and 60x coverage 10x Genomics linked reads. Could you give some advice about how can I decide or optimalize the right K-mer value? How can I calculate the optimal CPU core and memory usage for HPC based on the 4 Gbp whole genome size and coverage of Illumina reads? I have to calculate the CPU hour for the HPC.

Thank you for your help.

**Comment by jowong4** [comment]
When we assemble our genomes, we typically do a k-sweep (from 64 with steps of 8, 16 or 32) up to the `sample-1.fa` and continue assembling the `sample-1.fa` with the highest N50. 

The bulk of the memory consumed by abyss is used to allocate the CountingBloomFilter. You can run ntCard on your read set to give you the expected number of unique k-mers in your dataset. Based on that you can make a CountingBloomFilter of a desired size to get a desired FPR using `-B` option. This would allow you to optimize the memory usage. 

As for CPU core usage, abyss scales pretty well, and we typically use 48 threads for our assembly. I'm not sure how I would go around the total CPU hours needed for the HPC though.

Hope this helps.

**Comment by hidvegin** [comment]
Thank you for your answer. Could you give more details about the k-sweep, ntCard and CountingBloomFilter especially about the parameters? I read the abyss user manual but I did not find too much details about it.

So, If I calculate with 50 threads for my assembly it will be enough and I will calculate an about CPU hours for it.

**Comment by jowong4** [comment]
k sweep just means you do multiple runs with different ks and choose the best k to use. The metric we typically use is N50. ntCard is a tool that would give you a kmer distribution. You will use it for another purpose here which is to obtain the number of unique kmer. The number of kmer here is directly related to the occupancy of the bloom filter. 

The `CountingBloomFilter` has two parameters: size and hash. Both of these affect how well the CountingBloomFilter performs. I recommend you read https://en.wikipedia.org/wiki/Bloom_filter. We typically use 4 hashes and a large Bloom filter size to reduce false positive rate(FPR) since we are not quite limited by memory. If you are limited by memory then you do the following. Find the number of unique kmers and the desired FPR and solve for size in the following formula. `(uniqueKmer/size)^numHash = FPR`.  We typically want < 1% (0.01) FPR.

With regards to CPU calculation. Not everything in abyss is multithreaded.

Hope this helps.

**Comment by hidvegin** [comment]
It helped a lot, thank you. How can I run the CountingBloomFilter? Is this part of abyss?

**Comment by jowong4** [comment]
See https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph. My apologies, I forgot there was a third parameter that you have to specify which is `kc`.

**Comment by hidvegin** [comment]
So, if I understund it: Firstly, I have to find the optimal k-mer based on this: [https://github.com/bcgsc/abyss#optimizing-the-parameter-k](url) between 64 and 96. After that I have to use ntCard based on this: [https://github.com/bcgsc/ntCard#run-ntcard](url) for get the expected number of unique k-mers. Last, I have to run abyss-pe with using Bloom filter de Bruijn graph based on this: [https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph](url) where I should try different `B`, `H` and `kc` values (between 2 and 4) and I should check the log file where I get the best FPR (less than 5% or 1%). Is it right?

**Comment by jowong4** [comment]
` try different B, H and kc values (between 2 and 4) and I should check the log file where I get the best FPR (less than 5% or 1%). Is it right?` Trying 3 combinations will take too long. You can try different `kc` and optimize it just as you did with `k`. For `B` and `H`, follow the formula `(uniqueKmer/size)^numHash = FPR` (size=B, numHash=H). Ideally, you want less than one percent.

**Comment by hidvegin** [comment]
Thank you for your help. It helped a lot. I will try it with your suggestions.

**Comment by jowong4** [comment]
Feel free to re-open this ticket if you have more questions

**Comment by sjackman** [comment]
If we could do one thing to improve the user experience of ABySS, I'd suggest automatically determining the values of `B` and `H` for the user using `ntcard`. Picking a default reasonable value of `kc` would be good too, either a constant like `3` or based on the depth of coverage of the data set, using the results of `ntcard`. Finally, a script to sweep `k` and pick the assembly with the best NG50 (or NGA50 with a reference) would be very helpful.

**Comment by sjackman** [comment]
Also Bloom filter mode should probably be the default mode, with an option required to enable MPI mode.

**Comment by hidvegin** [comment]
I tried today the ntCard with this parameters: `ntcard -k32,64,96 -p freq -t2 R1.fastq R2.fastq`
I get freq_k32.hist, freq_k64.hist and freq_k96.hist files which is tab text files. How can I interpret the output files? How can I choose the optimal k-mer based on this *.hist files?
[freq_k32.hist.txt](https://github.com/bcgsc/abyss/files/3990301/freq_k32.hist.txt)
[freq_k64.hist.txt](https://github.com/bcgsc/abyss/files/3990302/freq_k64.hist.txt)
[freq_k96.hist.txt](https://github.com/bcgsc/abyss/files/3990303/freq_k96.hist.txt)

**Comment by sjackman** [comment]
Try using GenomeScope to interpret these *k*-mer depth of coverage histograms.
See http://qb.cshl.edu/genomescope/
and https://github.com/bcgsc/ntCard/issues/8
