### ISSUE TITLE
ABySS execution time

### ISSUE THREAD

**Issue by bvaldebenitom** [bcgsc/abyss#309]
# Please report

- [ ] **version of ABySS with `abyss-pe version`**

abyss-pe (ABySS) 2.1.5
Written by Shaun Jackman and Anthony Raymond.

Copyright 2012 Canada's Michael Smith Genome Science Centre

- [ ] **distribution of Linux with `lsb_release -d`**
Description:	Debian GNU/Linux 10 (buster)

# Assembly error

- [ ] complete `abyss-pe` command line

abyss-pe k=17 name=Assembly_k17 j=20 B=200G  
(what follows are the library descriptions: 6 paired-end, and 3 mate pairs)

- [ ] last 20 lines of the output of `abyss-pe`
abyss-stack-size 65536 abyss-bloom-dbg -k17 -q3  -b200G -j20 followed with the full path to each file described above.. > Assembly_k17-1.fa

Running with max stack size of 65536 KB: abyss-bloom-dbg -k17 -q3 -b200G -j20 followed again with the full path of the files

- [ ] **number of sequenced bases**
167226679146

- [ ] **estimated genome size and ploidy**
3.0 Gbp, diploid

- [ ] estimated sequencing depth of coverage
55x

# Question

Hi guys, so I attached all the required information. I wouldn't label this as an assembly error. I have the question of knowing if whether ABySS is doing anything at all. A few weeks ago I ran an assembly with another data set of 222133582560 sequenced bases, corresponding to about ~74x coverage. That assembly was ran with k=132, and everything else equal. It took about 33 hours to finish.

The assembly I'm running now has been running since December 19th, and top shows the abyss-bloom-dbg process running, but the log hasn't changed at all. Is there any way I could get an idea if the process is stuck, or what's its ending time?

**Comment by jowong4** [comment]
Are you redirecting the stderr or stdout to a file? They can be useful to troubleshoot.

**Comment by bvaldebenitom** [comment]
> Are you redirecting the stderr or stdout to a file? They can be useful to troubleshoot.

Thanks for the quick reply. stdout is redirected to a file, and stderr is usually written by default to "nohup.out", but this time that file doesn't even exist. stdout contents are the same as described above under "last 20 lines of the output of abyss-pe". 

It's a mess due to the amount of file, but here it is:
```
abyss-stack-size 65536 abyss-bloom-dbg -k17 -q3  -b200G -j20  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L005_R1_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L005_R2_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L006_R1_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L006_R2_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L007_R1_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L007_R2_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L005_R1_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L005_R2_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L006_R1_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L006_R2_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L007_R1_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L007_R2_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L005_R0_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L006_R0_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L007_R0_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L005_R0_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L006_R0_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L007_R0_001.fastq  16685_1p2_5kb-X_1p2_GCCAAT_L008_R0_001.fastq  16685_1p2_8kb-X_1p2_CTTGTA_L008_R0_001.fastq  16685_1p2_12kb-X_1p2_ACAGTG_L008_R0_001.fastq  > Assembly_k17-1.fa
Running with max stack size of 65536 KB: abyss-bloom-dbg -k17 -q3 -b200G -j20 1p2_350-X_1p2_TATCGCAC-ACACTAAG_L005_R1_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L005_R2_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L006_R1_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L006_R2_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L007_R1_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L007_R2_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L005_R1_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L005_R2_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L006_R1_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L006_R2_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L007_R1_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L007_R2_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L005_R0_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L006_R0_001.fastq  1p2_350-X_1p2_TATCGCAC-ACACTAAG_L007_R0_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L005_R0_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L006_R0_001.fastq  1p2_550-X_1p2_GTATGTTC-TTCCTGTT_L007_R0_001.fastq  16685_1p2_5kb-X_1p2_GCCAAT_L008_R0_001.fastq  16685_1p2_8kb-X_1p2_CTTGTA_L008_R0_001.fastq  16685_1p2_12kb-X_1p2_ACAGTG_L008_R0_001.fastq 
```

**Comment by jowong4** [comment]
Seems like it hanged. Can you restart the assembly and see if you observe the same problem. May I ask you why you are using k17? I don't think 17-mers are good.

**Comment by bvaldebenitom** [comment]
It was a choice based on the k-mer size at which the k-mer frequency histogram resembles a normal distribution, after the decreasing curve associated to erroneous k-mer. This pattern can still be observed up to k-mer size = 30 or 40, but not as clear as with k = 17.

Do you think that a good genome size estimation from k-mers histograms ≠ best k-mer for assembly?

**Comment by jowong4** [comment]
> Do you think that a good genome size estimation from k-mers histograms ≠ best k-mer for assembly?

Not necessarily. It is just that I imagine most the de Bruijn graph would be very tangled with such a low k.

**Comment by bvaldebenitom** [comment]
> Not necessarily. It is just that I imagine the de Bruijn graph would be very tangled with such a low k.

I thought about it before the assembly, but didn't thought it would apparently hang up. Probably that's the reason of this issue. Will wait it out for a bit, and if nothing happens, I will restart it with another k-mer size.

**Comment by bvaldebenitom** [comment]
So, the assembly file "Assembly_k17-1.fa", the only file generated so far, increased in size from 56 Gb to 57 Gb recently. Would it be recommended to wait, or just restart it?

**Comment by jowong4** [comment]
Even if the assembly completes, I still think using k=17 is incorrect. I would restart with a higher.

**Comment by sjackman** [comment]
I agree with Johnathan that *k*=17 is too small for a 3 Gbp genome. Try using ntCard to compute the *k*-mer depth of coverage histogram and then GenomeScope to plot it. You can post a link to that report here if you like. I suggest trying *k*=32, 64, 96, and 128 for a start. See https://github.com/bcgsc/ntCard/issues/8
