### ISSUE TITLE
Build fails: error: result of comparison of constant 18446744073709551615 with expression of type 'size_t'

### ISSUE THREAD

**Issue by yurivict** [bcgsc/abyss#310]
It fails on the i386 architecture:
http://beefy5.nyi.freebsd.org/data/120i386-default/523384/logs/abyss-2.2.3.log

**Comment by jowong4** [comment]
Hmm, we have CI for 32-bit systems so I'm not sure why that is happening but I'll look into it

**Comment by jowong4** [comment]
What is "c++" you are using? is that an alias for g++

**Comment by yurivict** [comment]
c++ is clang8

**Comment by yurivict** [comment]
@jowong4 So what's the resolution of this?

**Comment by sjackman** [comment]
`clang` compiler on `i386` architecture is not a supported target of ABySS. A PR to fix the issue is welcome if you are able to find a fix.

**Comment by jowong4** [comment]
@sjackman I had considered blanket substituting all `size_t` to `uint64_t` so that this never happens anymore but I recall you said the solution is non-ideal.

**Comment by sjackman** [comment]
No, it's not ideal. The C++ standard library uses `size_t` as the type of variables that represent a count or index into an array, such as `vector.size`. http://www.cplusplus.com/reference/vector/vector/size/

It's best in my opinion to stick with that convention. The alternative is a lot of casting from `size_t` to `uint64_t` and back when interacting with the standard library.

When a value represents not an index into an array, but is instead a counter (like a count of the number of observed k-mers), and that counter is likely to exceed a billion, then it's better to use a `uint64_t`.
