### ISSUE TITLE
ABySS Bloom filter FPR

### ISSUE THREAD

**Issue by PeiwenLi** [bcgsc/abyss#311]
# Please report

- [ ] version of ABySS with `abyss-pe version`: 2.2.3
- [ ] distribution of Linux with `lsb_release -d`: Ubuntu 18.04.3 LTS

# Assembly error

- [ ] complete `abyss-pe` command line:
`abyss-pe k=64 v=-v name=1181 np=42 j=42 B=200G H=4 kc=2 lib='1181pe003 1181pe004' \ 1181pe003='1181_S2_L003_R1_001.fastq.gz 1181_S2_L003_R2_001.fastq.gz' \ 1181pe004='1181_S2_L004_R1_001.fastq.gz 1181_S2_L004_R2_001.fastq.gz' >> log.txt 2>&1`

- [ ] last 20 lines of the output of `abyss-pe`
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

Hi! 
I am using abyss-pe with the Bloom filter to perform genome assembly. The false positive rate (FPR) was reported **twice** in the log file as shown below: 

_... 
Loaded 478640000 reads into Bloom filter Loaded 478650000 reads into Bloom filter 
Loaded 478658235 reads from 1181_S2_L004_R2_001.fastq.gz into Bloom filter 
Bloom filter FPR: 3.94% 
Counting Bloom filter stats: 
#counters = 190887435392 
#size (B) = 190887435392 
threshold = 2 
popcount = 13530549696 
FPR = 0.00252% 
..._

I wonder which FPR I should keep track of? And how are the two different?

Thanks! 
Peiwen

**Comment by jowong4** [comment]
The two FPR are different. The second one is what you should be concerned with. The first FPR you see is the FPR if you were to have a threshold of 1. Because you have a threshold of 2, entries in the bloom filter are 1 are equivalent to 0. resulting in a lower FPR.

**Comment by PeiwenLi** [comment]
> The two FPR are different. The second one is what you should be concerned with. The first FPR you see is the FPR if you were to have a threshold of 1. Because you have a threshold of 2, entries in the bloom filter are 1 are equivalent to 0. resulting in a lower FPR.

Thank you so much for your swift response! When you said 'you have a thredshold of 2', you are referring to 'kc=2' in my command right?

**Comment by jowong4** [comment]
Yes, that is correct.

**Comment by PeiwenLi** [comment]
Thank you again for your help!

**Comment by yiyian-Lee** [comment]
sorry for my stupid question. If I set kc=3 or kc=4, do I just need to concern the second FPR?
maybe this is too obvious, but I still worry about it...
