### ISSUE TITLE
ABySS version for Trans-ABySS?

### ISSUE THREAD

**Issue by rwhetten** [bcgsc/abyss#312]
The Trans-ABySS installation guide gives the required version of ABySS as 2.0.x, but the link provided leads to a page from which that version is not readily available. Some additional clarity regarding the required version of ABySS would be helpful - if the most recent version is suitable, then perhaps the Program Requirements for Trans-ABySS could be updated to reflect that. If the requirement for ABySS v 2.0.x is correct and newer versions won't do, it would be helpful to update the link on the Trans-ABySS page to point to a suitable archived version of ABySS.

**Comment by kmnip** [comment]
The readme of Trans-ABySS points to the ABySS release page on GitHub:
https://github.com/bcgsc/abyss/releases

Every version 2.0.x releases of ABySS can still be downloaded from there, ie.
https://github.com/bcgsc/abyss/releases/tag/2.0.0
https://github.com/bcgsc/abyss/releases/tag/2.0.1
https://github.com/bcgsc/abyss/releases/tag/2.0.2
https://github.com/bcgsc/abyss/releases/tag/2.0.3

Our three-digit versioning for ABySS has the following convention:
1st digit: publication
2nd digit: major release, eg. major code and file format changes
3rd digit: minor release, eg. bugfixes

Our last release of Trans-ABySS (2.0.1) was only tested to work with version 2.0.x and has not been tested for newer ABySS versions.

But you have a good point, we will confirm Trans-ABySS' compatibility with ABySS and adjust our readme accordingly.

If you have further issues with Trans-ABySS, please create an issue here:
https://github.com/bcgsc/transabyss/issues

Thank you
