### ISSUE TITLE
What are the lowercase nucleotides in the assemblies stand for? Thanks!

### ISSUE THREAD

**Issue by sisyyuan** [bcgsc/abyss#313]
# Please report

- [x] version of ABySS with `abyss-pe version`
- [x] distribution of Linux with `lsb_release -d`

# Assembly error

- [x] complete `abyss-pe` command line
- [ ] last 20 lines of the output of `abyss-pe`
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [x] Have you tried installing ABySS using Brew or Bioconda?
- [x] version of GCC or compiler with `gcc --version`
- [x] complete `./configure` command line
- [x] last 20 lines of the output of `./configure`
- [x] last 20 lines of the output of `make`

**Comment by sisyyuan** [comment]
Hi!
What are the lowercase nucleotides in the assemblies stand for? Thanks!

**Comment by sjackman** [comment]
Good question. I've added your question to the ABySS FAQ. What are the lower case characters in my assembly?

https://github.com/bcgsc/abyss/wiki/ABySS-Users-FAQ#7-what-are-the-lower-case-characters-in-my-assembly

> 7. What are the lower case characters in my assembly?
> Lower case characters represent positions where ABySS is unsure of the precise sequence at that location. The uncertainty could be due to heterozygous sequence or a collapsed repeat. Polishing your assembly using a tool such as Pilon, Racon, or Unicycler-polish will refine the sequence in these uncertain loci.
