### ISSUE TITLE
error when np>1

### ISSUE THREAD

**Issue by tomaszjacek** [bcgsc/abyss#314]
when runing command with one thread abyss doesnt throw error. just starts to work.
but when trying to use np parameter greater than 1 throws error "exited with status 127"

do you know what could be wrong? 
Thank you,
tj

# Please report

- [ ] version of ABySS with `abyss-pe version`
abyss-pe (ABySS) 2.2.3

- [ ] distribution of Linux with `lsb_release -d`
CentOS Linux release 7.7.1908 (Core)

# Assembly error

- [ ] complete `abyss-pe` command line
abyss-pe -C outABYSS V=-v np=2 k=41 name=Par_S6 in='/data/Par_S6/combinedR1.fastq.gz /data/Par_S6/combinedR2.fastq.gz'

- [ ] last 20 lines of the output of `abyss-pe`

make: Entering directory `/data/Par_S6/outABYSS'
/home/tomasz/.linuxbrew/bin/mpirun -np 2 ABYSS-P -k41 -q3    --coverage-hist=coverage.hist -s Par_S6-bubbles.fa  -o Par_S6-1.fa /data/Par_S6/combinedR1.fastq.gz /data/Par_S6/combinedR2.fastq.gz
ABySS 2.2.3
ABYSS-P -k41 -q3 --coverage-hist=coverage.hist -s Par_S6-bubbles.fa -o Par_S6-1.fa /data/Par_S6/combinedR1.fastq.gz /data/Par_S6/combinedR2.fastq.gz
Running on 2 processors
0: Running on host crunch.localhost
1: Running on host crunch.localhost
0: Reading `/data/Par_S6/combinedR1.fastq.gz'...
/bin/sh: @▒):ELF: x: Error 18446744072117248341
/data/Par_S6/combinedR1.fastq.gzPID 5453 exited with status 127
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[125,1],0]
  Exit code:    1
--------------------------------------------------------------------------
make: *** [Par_S6-1.fa] Error 1
make: Leaving directory `/data/Par_S6/outABYSS'

- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
chicken genome
- [ ] estimated sequencing depth of coverage
x15

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ ] Have you tried installing ABySS using Brew or Bioconda?
abyss was installed with brew

- [ ] version of GCC or compiler with `gcc --version`
- [ ] complete `./configure` command line
- [ ] last 20 lines of the output of `./configure`
- [ ] last 20 lines of the output of `make`

**Comment by jowong4** [comment]
Can you tell me which version of open-mpi you are using? On a related note, we suggest using abyss-bf by specifying the `-B` option. `-j` would be the equivalent to '-p'.

**Comment by tomaszjacek** [comment]
bash-4.2$ brew info open-mpi
open-mpi: stable 4.0.2, HEAD
High performance message passing library
https://www.open-mpi.org/
Conflicts with:
  mpich (because both install MPI compiler wrappers)
/home/tomasz/.linuxbrew/Cellar/open-mpi/4.0.2 (767 files, 13.2MB) *
  Built from source on 2020-01-29 at 08:38:25
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/open-mpi.rb
==> Dependencies
Required: gcc ✔, hwloc ✔, libevent ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 425 (30 days), 1,364 (90 days), 5,628 (365 days)
install-on-request: 31 (30 days), 166 (90 days), 879 (365 days)
build-error: 0 (30 days)

**Comment by tomaszjacek** [comment]
Hi,
Thank you for reply  Johnathan.
I'm trying to run abyss on server with 32cpus and 260G of RAM (but I would like to use only 120G for this task).
I have two 50G fastq files with paired-end 100bp reads (with depth of coverage = x15) .
Do you think is it possible to assemble chicken genome with this data (or this is mission imposible)?
Could you give me an example of command how to run abyss in multithread (not multi node)?
Thank you,
tj

**Comment by jowong4** [comment]
I cannot give you an ram usage estimate for abyss-mpi but if you were to use abyss-mpi and specify -B 100G then abyss should use no more than 120 GB of ram.
```
abyss-pe -C outABYSS V=-v j=2 B=100G H=4 kc=2 k=41 name=Par_S6 in='/data/Par_S6/combinedR1.fastq.gz /data/Par_S6/combinedR2.fastq.gz'``` I would also suggest doing a run with kc=3 too. Set j to something else if you have more threads to access.

**Comment by tomaszjacek** [comment]
Thank you!
I will test it and let you know the results.
tj

**Comment by jowong4** [comment]
I should mention that I don't think you will get a very good assembly with 15X coverage.

**Comment by tomaszjacek** [comment]
What coverage is a minimum for good assembly(with pairedreads 100bp)?
tj

**Comment by jowong4** [comment]
I'm afraid I don't have answers for either of your questions. With regards to coverage, I have not done progressively lower coverage assembly experiments to see when it breaks. For your second question, there are many factors in play here so it's hard to give an estimate. Typically the generation of "-1.fa" takes the longest.

**Comment by lcoombe** [comment]
@tomaszjacek - Generally, I'd want at least ~50X coverage for a decent assembly as a ballpark.
Longer read lengths and longer fragment lengths are beneficial to ABySS runs.
For human-sized genomes with 40 threads, my jobs tend to take 2-3 days or so. But as @jowong4 mentioned, there are many different factors, so your run might be more/less than that.

**Comment by tomaszjacek** [comment]
Hi All,
Thank you for your replies.

Here is the best results with sga assambler
<img width="1920" alt="chr1_SGA" src="https://user-images.githubusercontent.com/22526298/74163758-20700500-4c23-11ea-8829-be24183544c0.png">


Here is the best results I got till now for chr1 with abyss, parameters kc=2 and k=41
<img width="1920" alt="chr1_ABYSS" src="https://user-images.githubusercontent.com/22526298/74163599-e69efe80-4c22-11ea-9b2b-0dcf1083e87f.png">

The abyss much better. In my opinion abyss results are not bad (however I'm a newbie with denovo asembling) .
And realy not bad ... when I let you know that everything was done against best practices.
1. dna sample was a pull from 10 chickens.
2. fasta quality did not processed.
3. coverage = x15
4. adapters did not trimed
5. read pairs for which one of the reads is deemed unfixable not discarded 

I wish to have the same results on chrZ where gwas pointed many hits in our case but unfortunately got this.
<img width="1920" alt="chr33_W_Z_ABYSS" src="https://user-images.githubusercontent.com/22526298/74164361-f703a900-4c23-11ea-9a4f-665acd7857e4.png">


Do you have an idea why is that?? why chr W and chrZ is so bad? how to fix it?
Thank you,
tj

**Comment by jowong4** [comment]
chr W and Z are sex chromosomes so it has the half the coverage of autosomes, so your 15X coverage are split 7.5X each assuming all 10 of your chickens are female.

**Comment by tomaszjacek** [comment]
Yes, they were all females... 
Thank you,
tj

**Comment by jowong4** [comment]
If you have any other questions. Feel free to reopen the issue or submit a new one.
