### ISSUE TITLE
AdjList: command not found

### ISSUE THREAD

**Issue by spencer411** [bcgsc/abyss#316]
# Please report

- [x] version of ABySS with `abyss-pe version`
abyss-pe (ABySS) 2.2.3
- [x] distribution of Linux with `lsb_release -d`
Oracle Linux Server release 7.7
using openmpi/3.1.4

# Assembly error

- [x] complete `abyss-pe` command line
abyss-pe k=50 name=bowfin lib='pea peb' mp='mpc mpd mpe mpf mpg mph mpi mpj mpk' \
	pea='bowfin.trimmed.deduped.noMito.corrected_1.fq bowfin.trimmed.deduped.noMito.corrected_2.fq' \
	peb='bowfin_F.trimmed-pe-500_1.fq bowfin_F.trimmed-pe-500_2.fq' \
	se='bowfin.extendedFrags.deduped.noMito.corrected.fq'\
	mpc='bowfin_F.trimmed-mp-1000_1.fq bowfin_F.trimmed-mp-1000_2.fq' \
	mpd='bowfin_F.trimmed-mp-1500_1.fq bowfin_F.trimmed-mp-1500_2.fq' \
	mpe='bowfin_F.trimmed-mp-2000_1.fq bowfin_F.trimmed-mp-2000_2.fq' \
	mpf='bowfin_F.trimmed-mp-5000_1.fq bowfin_F.trimmed-mp-5000_2.fq' \
	mpg='bowfin_F.trimmed-mp-10000_1.fq bowfin_F.trimmed-mp-10000_2.fq' \
	mph='bowfin_F.trimmed-mp-20000_1.fq bowfin_F.trimmed-mp-20000_2.fq' \
	mpi='bowfin_F.trimmed-mp-50000_1.fq bowfin_F.trimmed-mp-50000_2.fq' \
	mpj='bowfin_F.trimmed-mp-100000_1.fq bowfin_F.trimmed-mp-100000_2.fq' \
	mpk='bowfin_F.trimmed-mp-200000_1.fq bowfin_F.trimmed-mp-200000_2.fq'
done
- [x] last 20 lines of the output of `abyss-pe`
10: Assembled 12560659 k-mer in 78906 contigs.
16: Assembled 13378421 k-mer in 81927 contigs.
5: Assembled 13147159 k-mer in 77436 contigs.
6: Assembled 13273717 k-mer in 78524 contigs.
13: Assembled 13083574 k-mer in 77066 contigs.
8: Assembled 13540861 k-mer in 83938 contigs.
17: Assembled 13453296 k-mer in 78324 contigs.
12: Assembled 13802190 k-mer in 82345 contigs.
Assembled 783839157 k-mer in 4794531 contigs.
Concatenating fasta files to bowfin-1.fa
Concatenating fasta files to bowfin-bubbles.fa
Done.
[rhea-05.rit.albany.edu:23226] PMIX ERROR: NO-PERMISSIONS in file dstore_base.c at line 234
AdjList    -k50 -m0 --dot bowfin-1.fa >bowfin-1.dot
bash: AdjList: command not found
make: *** [bowfin-1.dot] Error 127
make: *** Deleting file `bowfin-1.dot'
/tmp/slurmd/job680957/slurm_script: line 32: syntax error near unexpected token `done'
/tmp/slurmd/job680957/slurm_script: line 32: `done'
- [ ] number of sequenced bases
unknown
- [x] estimated genome size and ploidy
diploid, the organisms is ~945 Mb in size, although we arent expecting to have a full assembly (our assembly likely only partially covers the whole genome)
- [ ] estimated sequencing depth of coverage
unknwon

**Comment by jowong4** [comment]
can you show me your slurm script? and `ls` the path where you installed ABySS?

**Comment by spencer411** [comment]
see below, and script attached here.

-bash-4.2$ cd /network/rit/misc/software/abyss-2.2.3/
-bash-4.2$ ls
ABYSS                 CITATION.md    DataLayer        Konnector     ParseAligns
aclocal.m4            Common         depcomp          Layout        PathOverlap
AdjList               config.guess   dialign          LICENSE       PopBubbles
Align                 config.h       DistanceEst      LogKmerCount  README.md
Assembly              config.h.in    doc              m4            Scaffold
autogen.sh            config.log     Dockerfile       Makefile      Sealer
autom4te.cache        config.status  doxygen.conf     Makefile.am   SimpleGraph
azure-pipelines.yml   config.sub     FilterGraph      Makefile.in   stamp-h1
bin                   configure      FMIndex          Map           test-driver
Bloom                 configure.ac   GapFiller        MergePaths    Unittest
BloomDBG              _config.yml    Graph            Misc          vendor
boost_1_56_0          Consensus      install-sh       missing
boost_1_56_0.tar.bz2  COPYRIGHT      IntegrationTest  Overlap
ChangeLog             DAssembler     KAligner         PairedDBG
CITATION.bib          DataBase       kmerprint        Parallel

[abyss-parallel_2.txt](https://github.com/bcgsc/abyss/files/4186887/abyss-parallel_2.txt)

**Comment by jowong4** [comment]
I meant the binary directory where you installed  the abyss binaries.

**Comment by spencer411** [comment]
-bash-4.2$ cd bin
-bash-4.2$ ls
ABYSS                abyss-joindist
abyss-adjtodot.pl    abyss-kaligner
abyss-bloom-dist.mk  abyss-nompi
abyss-bowtie         ABYSS-P
abyss-bowtie2        abyss-pe
abyss-bwa            abyss-samtoafg
abyss-bwamem         abyss-stack-size
abyss-bwasw          abyss-tabtomd
abyss-cstont         Makefile
abyss-dida           Makefile.am
abyss-fac.pl         Makefile.in
abyss-fatoagp
-bash-4.2$

**Comment by jowong4** [comment]
Just to be clear, did you do this?
```
./configure
make
sudo make install
```
or 
```
./configure --prefix=/opt/abyss
make
sudo make install

```

**Comment by spencer411** [comment]
It was a problem with the make, I went through and linked every command that for some reason didn't seem to be connected originally. Sorry about the delayed response, but I wanted to get everything squared away and run a full assembly before updating. Nevertheless, I am having a new problem, see error below related to my 8th pair of mp reads:

abyss-map   -j60 -l40    bowfin_F.trimmed-mp-100000_1.fq bowfin_F.trimmed-mp-100000_2.fq bowfin-6.fa \
	|abyss-fixmate   -l40  -h mpj-6.hist \
	|sort -snk3 -k4 \
	|DistanceEst   --dot --median -j60 -k50  -l40 -s1000 -n10  -o mpj-6.dist.dot mpj-6.hist
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Mateless       0
Unaligned     43  0.227%
Singleton    669  3.53%
FR             0
RF             0
FF             0
Different  18244  96.2%
Total      18956
error: the histogram `mpj-6.hist' is empty
make: *** [mpj-6.dist.dot] Error 1
make: *** Deleting file `mpj-6.dist.dot'
/tmp/slurmd/job735697/slurm_script: line 32: syntax error near unexpected token `done'
/tmp/slurmd/job735697/slurm_script: line 32: `done'

Note that the mp reads referenced above are rather small (around 4.6MB a piece), so maybe there is just no usable information in those files? The seven pairs before them seemed to work fine. Just a guess, I dunno, any inference would be appreciated...

**Comment by lcoombe** [comment]
Hi @spencer411,

This looks to be related to a couple previous issues: #104, #208 - it is a known issue that ABySS fails when a library has no pairs of reads that map to the same contig.

Of the different mate-pair libraries you are using, do they each have a different estimated fragment size? If not, I'd suggest merging this very small one with a library with a similar/same fragment size to get past this error.

**Comment by sjackman** [comment]
Please consider installing ABySS using Homebrew on Linux. See

https://brew.sh for instruction to install Homebrew then run `brew install abyss`
Bioconda is an alternative to Homebrew.
