### ISSUE TITLE
abyss2 with paired reads of different lengths

### ISSUE THREAD

**Issue by sbilobram** [bcgsc/abyss#318]
# Please report

USING:  abyss-2.0.2/bin/abyss-pe
ON PLATFORM: CentOS Linux release 7.6.1810 (Core)

Hi Guys,
Trying to run Abyss2 with untrimmed read pairs (read1=150bp read 2 at 175bp).  Unsure if abyss can do this.   sweeping through k=40, k=50,..k=120.  and after 13 hours the k=40 failed with error 1 below.  K=120  got a little further but also failed after 13 hours with a different error,  ERROR 2 below: 
# Assembly error

 exec /projects/sbilobram_prj/abyss-2.0.2/bin/abyss-pe -C $dir \
	s=1000 v=-v q=3 n=10 B=120G kc=3 \
ERROR 1.)  at k=40
...
Extended 37047214 of 760975000 reads (4.87%), assembled 4858877978 bp so far
abyss-bloom-dbg: ../BloomDBG/bloom-dbg.h:716: void BloomDBG::printContig(const Sequence&, size_t, const string&, unsigned int, std::ostream&): Assertion `out' failed.
/bin/bash: line 1: 46342 Aborted                 (core dumped) abyss-bloom-dbg -k40 -q3 -v -b120G -j44 --kc=3 /projects/da_workspace/techd/UGNE1963/V300037441_L01_read_1.fq.gz /projects/da_workspace/techd/UGNE1963/V300037441_L01_read_2.fq.gz > tumor_2075-1.fa
make: *** [tumor_2075-1.fa] Error 134

ERROR 2.) at k=120
....
Read 804000000 alignments. Hash load: 16 / 64 = 0.25 using 524 kB.
Mapped 754913196 of 804024410 reads (93.9%)
Mapped 719269427 of 804024410 reads uniquely (89.5%)
Read 804024410 alignments
Mateless           0
Unaligned    7765024  1.93%
Singleton   33581166  8.35%
FR         231194410  57.5%
RF              6026  0.0015%
FF              5322  0.00132%
Different  129460257  32.2%
Total      402012205
FR Stats mean: 427 median: 418 sd: 100.8 n: 231171909 min: 75 max: 923 ignored: 28527
              ___▁▁▂▂▃▄▅▆▇▇██████▇▇▆▅▅▄▄▃▃▂▂▁▁▁_____
Mate orientation FR: 231194410 (100%) RF: 6026 (0.00261%)
The library pe1-3.hist is oriented forward-reverse (FR).
Stats mean: 427 median: 418 sd: 100.8 n: 231171909 min: 75 max: 923
              ___▁▁▂▂▃▄▅▆▇▇██████▇▇▆▅▅▄▄▃▃▂▂▁▁▁_____
Minimum and maximum distance are set to -109 and 923 bp.
Duplicate rate of spanning fragments: 117897/48784259 (0.242%)
Reading `tumor_2075-3.fa'...
V=12983554 E=0 E/V=0
Degree:  █
        01234
0: 1e+02% 1: 0% 2-4: 0% 5+: 0% max: 0
Reading `pe1-3.dist'...
V=12983554 E=1820492 E/V=0.14
Degree: █_
        01234
0: 87% 1: 11% 2-4: 1.4% 5+: 0.0036% max: 14
Reading `tumor_2075-4.dot'...
SimpleGraph: ../Common/StringUtil.h:13: char chop(std::__cxx11::string&): Assertion `s.length() > 1' failed.
make: *** [tumor_2075-4.path1] Aborted (core dumped)

This could be a memory issue so Im checking that out but should Abyss handle read pairs with different  lengths ??

thanks, 
Steve Bilobram

**Comment by jowong4** [comment]
ABySS can handle reads pairs with different lengths. I don't think it is a memory issue. Can you restart the command and see if you get the same error?
