### ISSUE TITLE
DistanceEst: DistanceEst.cpp:669: int main(int, char**): Assertion `in' failed.

### ISSUE THREAD

**Issue by rafelafrance** [bcgsc/abyss#319]
I spent some time making a minimal test case of 10 paired sequences.The real dataset is bigger and the abyss-pe command is slightly more complex.

Abyss works most of the time, however it fails on some assemblies with the following error which is different from the "can't assemble it" error.

`DistanceEst: DistanceEst.cpp:669: int main(int, char**): Assertion `in' failed

The attached files are ~1K each & they demonstrate the error on my system

[paired_2.fasta.txt](https://github.com/bcgsc/abyss/files/4326649/paired_2.fasta.txt)
[paired_1.fasta.txt](https://github.com/bcgsc/abyss/files/4326650/paired_1.fasta.txt)

.`

# Please report

- [x] version of ABySS with `abyss-pe version`
`abyss-pe (ABySS) 2.2.2`

- [x] distribution of Linux with `lsb_release -d`
`Description:	Pop!_OS 19.10`
(It's a variant of Ubuntu)

# Assembly error

- [x] complete `abyss-pe` command line
`abyss-pe v=-v E=0 k=32 name='output.fasta' in='paired_1.fasta paired_2.fasta'`

- [x] last 20 lines of the output of `abyss-pe`
```
Using 418 kB of memory and 824 B/bp.
Reading from standard input...
Mapped 8 of 10 reads (80%)
Mapped 8 of 10 reads uniquely (80%)
Read 10 alignments
Mateless   0
Unaligned  1  20%
Singleton  0
FR         4  80%
RF         0
FF         0
Different  0
Total      5
FR Stats mean: 305 median: 305 sd: 0 n: 1 min: 305 max: 305 ignored: 3
 ▄
Mate orientation FR: 4 (100%) RF: 0 (0%)
The library output.fasta-3.hist is oriented forward-reverse (FR).
Stats mean: 305 median: 305 sd: 0 n: 1 min: 305 max: 305
 ▄
Minimum and maximum distance are set to -31 and 305 bp.
DistanceEst: DistanceEst.cpp:669: int main(int, char**): Assertion `in' failed.
bash: line 3:  6562 Done                    abyss-map -v -j2 -l40 paired_1.fasta paired_2.fasta output.fasta-3.fa
      6563                       | abyss-fixmate -v -l40 -h output.fasta-3.hist
      6564                       | sort -snk3 -k4
      6565 Aborted                 (core dumped) | DistanceEst -v -j2 -k32 -l40 -s1000 -n10 -o output.fasta-3.dist output.fasta-3.hist
make: *** [/usr/bin/abyss-pe:611: output.fasta-3.dist] Error 134
make: *** Deleting file 'output.fasta-3.dist'
```

- [X] number of sequenced bases
Attached files demonstrate error.
- [X] estimated genome size and ploidy
Attached files demonstrate error.
- [X] estimated sequencing depth of coverage
Attached files demonstrate error.

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [X] Have you tried installing ABySS using Brew or Bioconda?
No, this is `apt install`ed
- [x] version of GCC or compiler with `gcc --version`
`gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008`
- [X] complete `./configure` command line
N/A
- [X] last 20 lines of the output of `./configure`
N/A
- [X] last 20 lines of the output of `make`
N/A

**Comment by sjackman** [comment]
Please report the output of `abyss-fac -t200 output.fasta-3.fa`. If you run `abyss-map -v -j2 -l40 paired_1.fasta paired_2.fasta output.fasta-3.fa` are there any SAM records in the resulting output?

**Comment by sjackman** [comment]
@lcoombe wrote…

> This looks to be related to a couple previous issues: #104, #208 - it is a known issue that ABySS fails when a library has no pairs of reads that map to the same contig.

> Of the different mate-pair libraries you are using, do they each have a different estimated fragment size? If not, I'd suggest merging this very small one with a library with a similar/same fragment size to get past this error.

**Comment by rafelafrance** [comment]
Thank you for the reply. Seeing that this is a known issue this one can be closed.

I already have a workaround for my uses.

**Comment by mmokrejs** [comment]
@rafelafrance Please try to execute the commands Shaun asked you, it would help others hitting the issue in the future.

**Comment by rafelafrance** [comment]
I had to build from source to do this. I verified that the error still occurs with the new build.
```
$ ~/bin/abyss/bin/abyss-fac -t200 output.fasta-3.fa
n	n:200	L50	min	N75	N50	N25	E-size	max	sum	name
2	2	1	238	238	245	245	241	245	483	output.fasta-3.fa
```

```
$ ~/bin/abyss/bin/abyss-map -v -j2 -l40 paired_1.fasta paired_2.fasta output.fasta-3.fa
Reading `output.fasta-3.fa'...
Using 410 kB of memory and 2.05e+05 B/sequence.
Reading `output.fasta-3.fa'...
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Read 507 B in 2 contigs.
Using 410 kB of memory and 808 B/bp.
@HD	VN:1.4
@PG	ID:abyss-map	PN:abyss-map	VN:2.2.4	CL:/home/rafe/bin/abyss/bin/abyss-map -v -j2 -l40 paired_1.fasta paired_2.fasta output.fasta-3.fa
@SQ	SN:0	LN:245
@SQ	SN:1	LN:238
DBRHHJN1:427:H9YYAADXX:1:1213:12461:6033/1	0	0	1	107	50S107M	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:19169:40202/1	0	0	1	157	157M	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:12461:6033/2	16	0	99	147	147M10S	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:5610:54319/1	0	1	1	157	157M	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:19169:40202/2	16	0	89	157	157M	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:5610:54319/2	16	1	125	114	114M43S	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:7921:86276/1	4	*	0	0	*	=	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1213:7921:86276/2	4	*	0	0	*	=	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1215:15051:34776/1	16	1	82	157	157M	*	0	0	*	*
DBRHHJN1:427:H9YYAADXX:1:1215:15051:34776/2	0	1	1	157	157M	*	0	0	*	*
Mapped 8 of 10 reads (80%)
Mapped 8 of 10 reads uniquely (80%)
```
