### ISSUE TITLE
unable to install abyss ?

### ISSUE THREAD

**Issue by sunnykevin19** [bcgsc/abyss#320]
HI
Notable to install abyss, facing error at make step. suggestions please!
CMD: 
./configure --prefix=/home/softwares/abyss-2.2.3 --with-boost=/home//softwares/boost_1_72_0/stage/lib --with-mpi=/home//softwares/openmpi-4.0.3/bin/

Last few lines of make:
In file included from PopBubbles.cpp:16:0:
../Graph/ContigGraph.h: In copy constructor ‘ContigGraph<G>::ContigGraph(const ContigGraph<G>&) [with G = DirectedGraph<ContigProperties, Distance>]’:
../Graph/ContigGraph.h:20:2: note: synthesized method ‘DirectedGraph<VertexProp, EdgeProp>::DirectedGraph(const DirectedGraph<VertexProp, EdgeProp>&) [with VertexProp = ContigProperties; EdgeProp = Distance]’ first required here 
  ContigGraph(const ContigGraph&) = default;
  ^
PopBubbles.cpp: In function ‘int main(int, char**)’:
PopBubbles.cpp:667:18: note: synthesized method ‘ContigGraph<G>::ContigGraph(const ContigGraph<G>&) [with G = DirectedGraph<ContigProperties, Distance>]’ first required here 
    Graph gorig = g;
                  ^
cc1plus: all warnings being treated as errors
make[2]: *** [PopBubbles-PopBubbles.o] Error 1
make[2]: Leaving directory `/DATA//softwares/abyss-2.2.3/PopBubbles'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/DATA/softwares/abyss-2.2.3'
make: *** [all] Error 2

**Comment by lcoombe** [comment]
Hi @sunnykevin19,
Have you tried installing ABySS using Homebrew on Linux?
See https://brew.sh for instructions to install Homebrew then run `brew install abyss`
You could also install ABySS using `bioconda`

**Comment by sunnykevin19** [comment]
HI,
I trying to install manual method. I don't want to install using sudo apt-get install abyss.
Thanks.

**Comment by lcoombe** [comment]
@sunnykevin19 - Is there a particular reason? You do not need root access to install `abyss` using the methods I mentioned above and really does make installation much easier. (Neither of the above installation approaches I mentioned require `sudo apt-get install abyss`)

**Comment by jowong4** [comment]
Can you try using g++ as the compiler and see if that resolves your issue?

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
