### ISSUE TITLE
Compile warning/error due to unused parameter in default copy constructor

### ISSUE THREAD

**Issue by lmjakt** [bcgsc/abyss#321]
Got compiler warnings turned to errors when compiling with gcc (see below for details). Warning for unused parameter from the inclusion of a named parameter in a default copy constructor. Compiles without problem after removal of offending parameter name (see output of `git diff` below).
Would suggest including fix in future releases, but seems to small for a pull request.

thanks,

Martin

- [ ] version of ABySS with `abyss-pe version`
abyss-pe (ABySS) 2.2.4
commit ffd5e372b94b26d1e302271c5fb8f92b85381f0a

- [ ] distribution of Linux with `lsb_release -d`
 CentOS Linux release 7.7.1908 (Core)

# Build error
Line 551 of 
Graph/DirectedGraph.h

has unused parameter that gcc chokes on. Compiles with no errors or warnings after removal of `d` :+1
```
git diff ffd5e372b94b26d1e302271c5fb8f92b85381f0a
diff --git a/Graph/DirectedGraph.h b/Graph/DirectedGraph.h
index ed29e93..71678d2 100644
--- a/Graph/DirectedGraph.h
+++ b/Graph/DirectedGraph.h
@@ -548,7 +548,7 @@ class Edge
   protected:
 
        /** Copy constructors */
-       DirectedGraph(const DirectedGraph& d) = default;
+       DirectedGraph(const DirectedGraph& ) = default;
        DirectedGraph(DirectedGraph&&) = default;
        DirectedGraph& operator=(const DirectedGraph&) = default;
        DirectedGraph& operator=(DirectedGraph&&) = default;
```

- [ ] version of GCC or compiler with `gcc --version`
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

- [ ] complete `./configure` command line
default:
autogen.sh; configure; make

**Comment by jowong4** [comment]
Hmm, it is passing the CI for me. Can you post the error from the make command.

**Comment by lmjakt** [comment]
I should have kept that, but left it in a scratch folder; so reverted my change and reran make and get the same error when compiling PopBubles. I suspect that it may relate to the specific version of gcc and whether a warning is given or not.
But in any case, all the other copy constructors in the same scope do not include named arguments, so if nothing else it would make sense to change for the sake of consistency.

Anyway, the error I get when reverting the change:

```
make[2]: Entering directory `/home/lmj/apps/abyss/abyss/PopBubbles'
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I.. -I../Align -I../Common -I../DataLayer -I/home/lmj/apps/abyss/abyss      -isystem/home/lmj/apps/abyss/abyss/boost_1_56_0 -Wall -Wextra -Werror -fopenmp -g -O2 -MT PopBubbles-PopBubbles.o -MD -MP -MF .deps/PopBubbles-PopBubbles.Tpo -c -o PopBubbles-PopBubbles.o `test -f 'PopBubbles.cpp' || echo './'`PopBubbles.cpp
In file included from PopBubbles.cpp:15:0:
../Graph/DirectedGraph.h:551:2: error: unused parameter ‘d’ [-Werror=unused-parameter]
  DirectedGraph(const DirectedGraph& d) = default;
  ^
In file included from ../Graph/ContigGraphAlgorithms.h:9:0,
                 from ../Graph/DepthFirstSearch.h:4,
                 from ../Graph/PopBubbles.h:5,
                 from PopBubbles.cpp:6:
../Graph/ContigGraph.h: In copy constructor ‘ContigGraph<G>::ContigGraph(const ContigGraph<G>&) [with G = DirectedGraph<ContigProperties, Distance>]’:
../Graph/ContigGraph.h:20:2: note: synthesized method ‘DirectedGraph<VertexProp, EdgeProp>::DirectedGraph(const DirectedGraph<VertexProp, EdgeProp>&) [with VertexProp = ContigProperties; EdgeProp = Distance]’ first required here 
  ContigGraph(const ContigGraph&) = default;
  ^
PopBubbles.cpp: In function ‘int main(int, char**)’:
PopBubbles.cpp:694:18: note: synthesized method ‘ContigGraph<G>::ContigGraph(const ContigGraph<G>&) [with G = DirectedGraph<ContigProperties, Distance>]’ first required here 
    Graph gorig = g;
                  ^
cc1plus: all warnings being treated as errors
make[2]: *** [PopBubbles-PopBubbles.o] Error 1
make[2]: Leaving directory `/home/lmj/apps/abyss/abyss/PopBubbles'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/lmj/apps/abyss/abyss'
make: *** [all] Error 2
```
