### ISSUE TITLE
ABySS 2.2.4 error: duplicate ID

### ISSUE THREAD

**Issue by xzhouaw** [bcgsc/abyss#322]
am fresh in genome assembly. Now I have 200bp paired end sequence data of a mouse cell line in hand and want to assemble it with Abyss 2.0 since it can run in multiple cluster nodes parallelly. the command line I used is attached below :

 $PATH/mpiexec --mca opal_cuda_support 1 abyss-pe name=test-1 k=50 in='V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq'  B=100G H=32 kc=3 v=-v np=4

I submitted it to the cluster and used 4 nodes to run it. It can load reads into Bloom filter and process normally. But after that it gave an error like the following:
 
Assembly complete
AdjList -v -k50 -m0 --dot test-1-1.fa > test-1-1.dot Reading `test-1-1.fa'...

error: duplicate ID: `4079879'

bash: line 1: 4493 Aborted

(core dumped)

AdjList -v -k50 -m0 --dot test-1-1.fa > test-1-1.dot

make: * [/home4/xzhouaw/miniconda2/bin/abyss-pe.Makefile:560: test-1-1.dot] Error 134

make: * Deleting file 'test-1-1.dot'

--------------------------------------------------------------------------
 Primary job terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted. 
-------------------------------------------------------------------------- 
make: * Deleting file 'test-1-1.fa'
 make: wait: No child processes. Stop. 
make: Waiting for unfinished jobs.... 
make: wait: No child processes. Stop. 
make: wait: No child processes. Stop. 
make: Waiting for unfinished jobs.... 
make: wait: No child processes. Stop. 
make: wait: No child processes. Stop. 
make: Waiting for unfinished jobs.... 
make: * wait: No child processes. Stop. 
-------------------------------------------------------------------------- 
mpiexec detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:

Process name: [[4772,1],2] Exit code: 2

I cannot check whether the duplicate ID is present in test-1-1.fa because the pipeline directly deleted the fa file. I am wondering why Abyss gave this error and what is the solution?

Thanks !!

**Comment by xzhouaw** [comment]
I am fresh in genome assembly. Now I have 200bp paired end sequence data of a mouse cell line in hand and want to assemble it with Abyss 2.0 since it can run in multiple cluster nodes parallelly. the command line I used is attached below :

`$PATH/mpiexec --mca opal_cuda_support 1 abyss-pe name=test-1 k=50 in='V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq' B=100G H=32 kc=3 v=-v np=4`

I submitted it to the cluster and used 4 nodes to run it. It can load reads into Bloom filter and process normally. But after that it gave an error like the following:

> Assembly complete
> AdjList -v -k50 -m0 --dot test-1-1.fa > test-1-1.dot Reading `test-1-1.fa'...
> 
> error: duplicate ID: `4079879'
> 
> bash: line 1: 4493 Aborted
> 
> (core dumped)
> 
> AdjList -v -k50 -m0 --dot test-1-1.fa > test-1-1.dot
> 
> make: * [/home4/xzhouaw/miniconda2/bin/abyss-pe.Makefile:560: test-1-1.dot] Error 134
> 
> make: * Deleting file 'test-1-1.dot'
> 
> Primary job terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted.
> make: * Deleting file 'test-1-1.fa'
> make: wait: No child processes. Stop.
> make: Waiting for unfinished jobs....
> make: wait: No child processes. Stop.
> make: wait: No child processes. Stop.
> make: Waiting for unfinished jobs....
> make: wait: No child processes. Stop.
> make: wait: No child processes. Stop.
> make: Waiting for unfinished jobs....
> make: * wait: No child processes. Stop.
> mpiexec detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
> 
> Process name: [[4772,1],2] Exit code: 2

I cannot check whether the duplicate ID is present in test-1-1.fa because the pipeline directly deleted the fa file. I am wondering why Abyss gave this error and what is the solution?

Thanks !!

**Comment by jowong4** [comment]
`abyss-pe name=test-1 k=50 in='V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq' B=100G H=4 kc=3 v=-v j=4` can you try this instead?

**Comment by lcoombe** [comment]
@xzhouaw - Yes, to be clear the Bloom filter functionality introduced in ABySS2 does not use MPI, so the correct way to specify the number of threads is `j=4`.
If you have issues after re-trying with Johnathan's suggested command (a fresh run), please post your full log.

**Comment by xzhouaw** [comment]
Thanks for your reply! I tried the suggestion (the code is exactly same as jowong suggested) and got the error:


>  which: no mpirun in (/home4/xzhouaw/miniconda2/lib/python2.7:/home4/xzhouaw/kit/software/zib/lib:/home4/xzhouaw/kit/software/Boost/boost_1_66_0:/home4/xzhouaw/kit/software/Quake/bin:/home4/xzhouaw/kit/software/bamtools/bamtools/build/bin:/home4/xzhouaw/kit/software/jelly/bin:/home4/xzhouaw/Program/bwa-0.7.17:/home4/xzhouaw/Program/coreutils_eric/coreutils/bin:/home4/share/dcyleung/miniconda2/bin:/home2/xzhouaw/miniconda2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/Bio/abyss/bin:/usr/local/Bio/allpathslg/bin:/usr/local/Bio/bowtie2:/usr/local/Bio/cufflinks:/usr/local/Bio/discovar/bin:/usr/local/Bio/EMBOSS/bin:/usr/local/Bio/FastQC:/usr/local/Bio/blat:/usr/local/Bio/weblogo:/usr/local/Bio/Homer/bin:/usr/local/Bio/ncbi-blast/bin:/usr/local/Bio/SICER:/usr/local/Bio/STAR/bin/Linux_x86_64_static:/usr/local/Bio/tophat:/usr/local/Bio/trinityrnaseq:/usr/local/Bio/wgs/Linux-amd64/bin:/usr/local/Bio/bismark:/usr/local/Bio/bsmap:/opt/ganglia/bin:/opt/ganglia/sbin:/home2/xzhouaw/Program/HOMER/bin/:/home4/xzhouaw/bin)
> abyss-filtergraph -v --dot   -k50 -g test-1-2.dot1 test-1-1.dot test-1-1.fa >test-1-1.path
> Loading graph from file: test-1-1.dot
> abyss-filtergraph: ../Graph/DotIO.h:302: std::istream& read_dot(std::istream&, Graph&, BetterEP) [with Graph = DirectedGraph<ContigProperties, Distance>, BetterEP = DisallowParallelEdges]: Assertion `num_vertices(g) > 0' failed.
> /bin/bash: line 1: 22812 Aborted                 (core dumped) abyss-filtergraph -v --dot -k50 -g test-1-2.dot1 test-1-1.dot test-1-1.fa > test-1-1.path
> make: *** [test-1-1.path] Error 134
> make: *** Deleting file `test-1-1.path'

**Comment by xzhouaw** [comment]
So it seems that the program still tried to open mpi. I am a little confused about that.  I am not sure how to correct the error.

**Comment by jowong4** [comment]
`num_vertices(g) > 0' this suggests an empty graph. Can you check to see if `test-1-1.dot` is empty. I also recommend restarting the run from the beginning so delete all the intermediate files and run my command again.

**Comment by xzhouaw** [comment]
Thanks!  I deleted  all the intermediate files and rerun. It works. But I have a question: how should I confirm that it is running in multiple nodes (I used 10 nodes (each node contains 24 cpu）). This is the log now:

> which: no mpirun in (/home4/xzhouaw/miniconda2/lib/python2.7:/home4/xzhouaw/kit/software/zib/lib:/home4/xzhouaw/kit/software/Boost/boost_1_66_0:/home4/xzhouaw/kit/software/Quake/bin:/home4/xzhouaw/kit/software/bamtools/bamtools/build/bin:/home4/xzhouaw/kit/software/jelly/bin:/home4/xzhouaw/Program/bwa-0.7.17:/home4/xzhouaw/Program/coreutils_eric/coreutils/bin:/home4/share/dcyleung/miniconda2/bin:/home2/xzhouaw/miniconda2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/Bio/abyss/bin:/usr/local/Bio/allpathslg/bin:/usr/local/Bio/bowtie2:/usr/local/Bio/cufflinks:/usr/local/Bio/discovar/bin:/usr/local/Bio/EMBOSS/bin:/usr/local/Bio/FastQC:/usr/local/Bio/blat:/usr/local/Bio/weblogo:/usr/local/Bio/Homer/bin:/usr/local/Bio/ncbi-blast/bin:/usr/local/Bio/SICER:/usr/local/Bio/STAR/bin/Linux_x86_64_static:/usr/local/Bio/tophat:/usr/local/Bio/trinityrnaseq:/usr/local/Bio/wgs/Linux-amd64/bin:/usr/local/Bio/bismark:/usr/local/Bio/bsmap:/opt/ganglia/bin:/opt/ganglia/sbin:/home2/xzhouaw/Program/HOMER/bin/:/home4/xzhouaw/bin)
> ABYSS -k50 -q3 -v   --coverage-hist=coverage.hist -s test-1-bubbles.fa  -o test-1-1.fa V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq 
> ABySS 1.9.0
> ABYSS -k50 -q3 -v --coverage-hist=coverage.hist -s test-1-bubbles.fa -o test-1-1.fa V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq
> Reading `V300032821_8A_L03_13.R1.fastq'...
> Read 100000 reads. Hash load: 14207100 / 1073741824 = 0.0132 using 985 MB
> Read 200000 reads. Hash load: 28300103 / 1073741824 = 0.0264 using 1.54 GB
> Read 300000 reads. Hash load: 41914298 / 1073741824 = 0.039 using 2.1 GB
> Read 400000 reads. Hash load: 55463556 / 1073741824 = 0.0517 using 2.66 GB
> Read 500000 reads. Hash load: 68791581 / 1073741824 = 0.0641 using 3.16 GB
> Read 600000 reads. Hash load: 82034396 / 1073741824 = 0.0764 using 3.63 GB
> Read 700000 reads. Hash load: 95133861 / 1073741824 = 0.0886 using 4.06 GB
> Read 800000 reads. Hash load: 108108561 / 1073741824 = 0.101 using 4.49 GB
> Read 900000 reads. Hash load: 120881167 / 1073741824 = 0.113 using 4.89 GB
> Read 1000000 reads. Hash load: 133694666 / 1073741824 = 0.125 using 5.3 GB
>

**Comment by xzhouaw** [comment]
Sorry. I just realized I can check it by run it with different numbers of nodes.
So thanks for your help!

**Comment by xzhouaw** [comment]
@jowong4 Could I ask another question about running abyss on a cluster?
I run the program with the following script:
`abyss-pe name=test-1 k=70 in='V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq' B=1000G H=5 kc=3 v=-v j=192`
I used 8 nodes [each contains 24 cores: "2 x Intel Xeon E5-2670 v3 (12-core, 2.3 GHz, 30 MB cache, 9.6 GT/s Intel QPI)"] of our cluster. and the RAM of each node is "16 x 8G DDR4-2133 RAM". 
The progress of the run slowed down after running for a few hours. and the log just seems to stop like: 

> Read 27400000 reads. Hash load: 3704295525 / 17179869184 = 0.216 using 136 GB
Read 27500000 reads. Hash load: 3706884697 / 17179869184 = 0.216 using 136 GB
Read 27600000 reads. Hash load: 3709417626 / 17179869184 = 0.216 using 136 GB
Read 27700000 reads. Hash load: 3711358962 / 17179869184 = 0.216 using 136 GB
Read 27800000 reads. Hash load: 3713202405 / 17179869184 = 0.216 using 137 GB
Read 27900000 reads. Hash load: 3714397205 / 17179869184 = 0.216 using 137 GB
Read 28000000 reads. Hash load: 3715374838 / 17179869184 = 0.216 using 137 GB
Read 28100000 reads. Hash load: 3718393204 / 17179869184 = 0.216 using 137 GB
Read 28200000 reads. Hash load: 3720092595 / 17179869184 = 0.217 using 137 GB
Read 28300000 reads. Hash load: 3722164267 / 17179869184 = 0.217 using 137 GB
Read 28400000 reads. Hash load: 3724173902 / 17179869184 = 0.217 using 137 GB
Read 28500000 reads. Hash load: 3726351474 / 17179869184 = 0.217 using 137 GB


I am not sure whether it is due to the wrong parameter setting or lack of RAM. this is only one subset of my data and the size of the whole fastq file (paired-end) is 668G. Do you think it is possible to finish running that on my cluster in 7 days (I can use 20 nodes at most)? and if so, what parameter should I use to run it?

Sorry for bothering you a lot! Thanks for your help!

**Comment by jowong4** [comment]
We can't really do time estimates because there are too many factors that can influence the problem. With regards to your command, I do not know how exactly your cluster is set up. But I don't think abyss-BF can communicate between nodes since it doesn't use MPI (@lcoombe do you know?)  so your parameters might not be valid.

**Comment by jowong4** [comment]
Can you also show me the very top of your log output?

**Comment by schutzekatze** [comment]
@xzhouaw 
The command you issued doesn't seem right: `abyss-pe name=test-1 k=70 in='V300032821_8A_L03_13.R1.fastq V300032821_8A_L03_13.R2.fastq' B=1000G H=5 kc=3 v=-v j=192`

If you specify the -B parameter, you're running abyss in Bloom filter mode, which runs on only one node (no MPI involved). Since -B parameter specifies how much memory you're using, 1000G in this case, your command should not be be able to run on any of the nodes as you indicated they have 128G RAM each.

**Comment by xzhouaw** [comment]
Ok. I got the problem now. thanks for your reply~ Maybe I will just try to run it with abyss1 rather than abyss2. Since Abyss1 allows me to run with multiple nodes. I will try it and ask help from you if I need.
Thanks!

**Comment by sjackman** [comment]
I'd recommend using ABySS 2 with Bloom filters and OpenMP. It uses one tenth (!) of the memory of ABySS 1 with hash tables and Open MPI.
