### ISSUE TITLE
Is abyss suitable for high heterozygous rate plant genome?

### ISSUE THREAD

**Issue by xiekunwhy** [bcgsc/abyss#323]
Hi,

I am looking for some assemblers to assemble a high heterozygous rate plant genome(diploid, het rate > 2%, haplotype genome size ~3.6G).
And I want to know how to use abyss to assemble such a genome.

Best wishes,
Kun

**Comment by lcoombe** [comment]
Hi @xiekunwhy,

Yes, you can certainly try ABySS on this data. If after your first try you have a lower contiguity, I'd suggest adding this parameter setting to your `abyss-pe` command:
```
POPBUBBLES_OPTIONS='--scaffold -a4'
```
This will help ABySS to better scaffold over bubbles (regions of heterozygosity in the assembly graph).

**Comment by sjackman** [comment]
You have a choice to make, whether you're attempting to assemble a single haploid genome, or the full diploid genome. What's your read length? With a 2% heterozygosity rate, I'd suggest aiming to assemble the full diploid genome. Areas of LOH larger than your fragment size will be collapsed to a single copy. Use a value of *k* of around say 96, and you should hope to assemble the full diploid genome.

I recommend using ntCard `brew install brewsci/bio/ntcard` and GenomeScope http://qb.cshl.edu/genomescope/ to inspect the *k*-mer depth distribution of the reads, and estimate the genome size and heterozygosity rate for many values of *k*, and inform the values of *k* that you're try for assembly.

You may also consider using K-mer Analysis Toolkit (KAT) using both your assembly and your reads to verify that you have assembled the diploid genome, and estimate the number of collapsed LOH regions.

Assembling heterozygous plant genomes is tricky. If you can go back to sequencing, you may wish to try adding some long reads into the mix, either Nanopore or PacBio. Best of luck!

**Comment by xiekunwhy** [comment]
Hi @sjackman ,

Thank you for your reply. we are now trying to assemble a full diploid genome use large k-mers.

The read length of our data is 2*149 (one N base trimmed from PE150), about 100X depth (if the genome size is 3.6G). And more, there are about 200X mate paired data (2k-20k) .

We have used ntcard and GenomeScope to estimate the genome size and heterozygosity rate (ntcard results were attached below). GenomeScope always telling us (or failing to estimate) the genome size of this plant is ~7G, double size of flow cytometer result (~3.6G), which we think is more reliable. And the heterozygosity rate estimated from GenomeScope is very low.
GenomeScope regard the only peak in the k-mers abundance histogram as the main peak and use it to estimate the genome size and heterozygosity rate, but I think the only peak there is the heterozygous peak, and the GenomeScope reults were wrong according to flow cytometer result.
[ntcards.zip](https://github.com/bcgsc/abyss/files/4446430/ntcards.zip)

After many assemble failures , we added ~30X (no money to add more) Nanopore long reads data, and we used wtdbg2 to do the assemble using only these long reads, and got ~4.1G assembly results (contig N50 is ~300kb), but BUSCO completeness is very low (~78%) after polishing(1 round using long reads and 3 rouds using NGS reads). We have also tried other tools, but wtdbg2 was the best.

And we want to do some more to improve the reults using NGS data, like hybrid assemble. So we need to try tools to assemble such a high heterozygosity rate genome using NGS data again. 
Since the limitation of computation resources we have (RAM <500G), we are now trying some resource efficiency tools like abyss, platanus-allee(memory cosuming), and megahit and some more.

Thank you again.
Best wishes,
Kun

**Comment by sjackman** [comment]
You can use our tool LINKS to scaffold your ABySS assembly of the short reads using the Nanopore sequencing data. https://github.com/bcgsc/LINKS

Are you getting a 7 GB genome size estimate from GenomeScope even using small values of _k_? Could you please post the URL to the GenomeScope reports for a few values of _k_ (say 19, 25, 64, 96, and 128)?
