### ISSUE TITLE
abyss 2.2.4 pe error

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/abyss#324]
# Please report

- [ ] version of ABySS with `abyss-pe version`
ABySS 2.2.4
- [ ] distribution of Linux with `lsb_release -d`
SUSE Linux Enterprise Server 12 SP1

# Assembly error

- [ ] complete `abyss-pe` command line
`abyss-pe k=64 name=lculinaris v=-v j=192 B=550G H=4 kc=2 G=4000000000 pe='pea peb pec ped' lr='lra lrb lrc lrd' pea='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_2.fq.gz' peb='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_2.fq.gz' pec='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_2.fq.gz' ped='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_2.fq.gz' lra='~/szeged/fk8jybr/input/Illumina_10x/LC001.fastq.gz' lrb='~/szeged/fk8jybr/input/Illumina_10x/LC002.fastq.gz' lrc='~/szeged/fk8jybr/input/Illumina_10x/LC003.fastq.gz' lrd='~/szeged/fk8jybr/input/Illumina_10x/LC004.fastq.gz'`
- [ ] last 20 lines of the output of `abyss-pe`
```
Loaded 420980000 reads into Bloom filter
Loaded 420990000 reads into Bloom filter
Loaded 421000000 reads into Bloom filter
Loaded 421010000 reads into Bloom filter
Loaded 421020000 reads into Bloom filter
Loaded 421030000 reads into Bloom filter
Loaded 421040000 reads into Bloom filter
Loaded 421050000 reads into Bloom filter
Loaded 421060000 reads into Bloom filter
Loaded 421070000 reads into Bloom filter
Loaded 421080000 reads into Bloom filter
Loaded 421090000 reads into Bloom filter
Loaded 421100000 reads into Bloom filter
Loaded 421110000 reads into Bloom filter
Loaded 421120000 reads into Bloom filter
Loaded 421130000 reads into Bloom filter
Loaded 421140000 reads into Bloom filter
Loaded 421150000 reads into Bloom filter
Loaded 421160000 reads into Bloom filter
Loaded 421170000 reads into Bloom filter
Loaded 421180000 reads into Bloom filter
Loaded 421190000 reads into Bloom filter
Loaded 421200000 reads into Bloom filter
Loaded 421210000 reads into Bloom filter
Loaded 421220000 reads into Bloom filter
Loaded 421230000 reads into Bloom filter
Loaded 421240000 reads into Bloom filter
Loaded 421250000 reads into Bloom filter
Loaded 421260000 reads into Bloom filter
/home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_1.fq.gz:1685836024: error: sequence and quality must be the same length near
TTACTCGTGTCAACTTGCCAAATCTTGAGTGGAAGGAGGTCCAATTTGAAGGAAACATGGTTGTGCCTTAAAAGACTTAGAGAAATCTTGAGAATTTTGGCTTAAAAGTATGTTTTTCATACGGAATGGTACGCAACA::,:FFFACTTCTTACTAAATAACGAAAAAAAAAAATAGTTAAGAACCATAGCATTTCGCCATTCATTGGTCAATCTACTTTG
FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF,FFFFFFFFFF:F:FFFFFFFFFFFF:FFF,FFFF,FF,F,:F:F:FF
Loaded 421270000 reads into Bloom filter
Loaded 421280000 reads into Bloom filter
/big/home/fk8jybr/.linuxbrew/bin/abyss-pe:538: recipe for target 'lculinaris-1.fa' failed
make: *** [lculinaris-1.fa] Error 1
```
- [ ] number of sequenced bases
- [ ] estimated genome size and ploidy
4 Gbp and diploid.
- [ ] estimated sequencing depth of coverage
120x Illumina PE and 30x 10xGenomics

How could I resolve this kind of error?

**Comment by jowong4** [comment]
```/home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_1.fq.gz:1685836024: error: sequence and quality must be the same length near```

Can you confirm if the file is properly formatted such that every read has the same number of bases and quality scores?

**Comment by hidvegin** [comment]
I used TrimGalore and FastQC for the quality check and trimming. I hope that every read has the same number of bases and quality scores. How could I check it from the fq.gz files?

**Comment by sjackman** [comment]
The most likely explanation is that your FASTQ file is truncated. Check that the last character of your FASTQ file is an end-of-line character. The very last character should be `0a` a line feed character.
```sh
gunzip -c LC002_L4B_1.fq.gz | xxd | tail -n2
```

**Comment by hidvegin** [comment]
Thank you for your answer. I checked the md5sum value and I found that the original LC002_L4B_1.fq.gz file is not the same with the uploaded version on the cluster. So, I deleted the uploaded version and reuploaded it. Now, I will rerun the abyss with the same paramaters.

**Comment by sjackman** [comment]
Glad to hear it!

**Comment by hidvegin** [comment]
I rerun the abyss-pe. Something went wrong with the python packages and the abyss-pe stoped with an error. I would like to continue the job with abyss-pe. Can I run abyss-pe with the same paramaters on the exist calculated files? This was the error:

```
abyss-index -v --fai lculinaris-8.fa
Reading `lculinaris-8.fa'...
Read 51441118 contigs.
Writing `lculinaris-8.fa.fai'...
abyss-map -v -j192 -l40  ~/szeged/fk8jybr/input/Illumina_10x/LC001.fastq.gz ~/szeged/fk8jybr/input/Illumina_10x/LC002.fastq.gz ~/szeged/fk8jybr/input/Illumina_10x/LC003.fastq.gz ~/szeged/fk8jybr/input/Illumina_10x/LC004.fastq.gz lculinaris-8.fa \
| samtools sort -@192 -tBX -l0 -T$(mktemp -u -t lculinaris-8.lr.bed.XXXXXX) \
| tigmint-molecule -a 0.65 -n 5 -q 0 -d 50000 - \
| sort -k1,1 -k2,2n -k3,3n >lculinaris-8.lr.bed
Reading `lculinaris-8.fa.fai'...
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffff79d0700 (most recent call first):
Using 2.47 GB of memory and 48 B/sequence.
Reading `lculinaris-8.fa'...
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Read 9.06 GB in 51441118 contigs.
Using 82 GB of memory and 9.05 B/bp.
Mapped 1530906882 of 1586927860 reads (96.5%)
Mapped 1318830806 of 1586927860 reads uniquely (83.1%)
[bam_sort_core] merging from 192 files and 192 in-memory blocks...
time user=6765107.53s system=42573.48s elapsed=54533.20s cpu=12483% memory=95474 job=abyss-map -v -j192 -l40 ~/szeged/fk8jybr/input/Illumina_10x/LC001.fastq.gz   
time user=35076.63s system=4052.19s elapsed=57717.99s cpu=67% memory=238315 job=samtools sort -@192 -tBX -l0 -T$(mktemp -u -t lculinaris-8.lr.bed.XXXXXX)
time user=0.01s system=0.00s elapsed=0.36s cpu=3% memory=4 job=tigmint-molecule -a 0.65 -n 5 -q 0 -d 50000 -
time user=0.00s system=0.00s elapsed=0.36s cpu=0% memory=0 job=
/big/home/fk8jybr/.linuxbrew/bin/abyss-pe:753: recipe for target 'lculinaris-8.lr.bed' failed
make: *** [lculinaris-8.lr.bed] Error 134
make: *** Deleting file 'lculinaris-8.lr.bed'
```

**Comment by lcoombe** [comment]
Hi @hidvegin,

Once you've worked out the python issue (it will be related to the python version used by `tigmint-molecule`), try re-running your `abyss-pe` with the `-n` option. This will do a 'dry run' - print out all the command that will be run without actually running them. Check that it will re-start at the correct spot (ie. at the step where you saw the error) - if not, you may have to delete some files to ensure it starts at that failed step.

Hope that helps!
Also, in the future, it would be a good idea to start a fresh issue for questions like this, since it is different from your initial question. That makes things more organized and easier for other users to search for any related issues.

Lauren

**Comment by hidvegin** [comment]
Hi **@lcoombe**

Thank you for your answer. I will try re-run the abyss-pe with your suggestion. In the feature, I will open a new issue for my questions.

**Comment by lcoombe** [comment]
Good luck!
