### ISSUE TITLE
goal of ghc and/or pandoc?

### ISSUE THREAD

**Issue by santiagorevale** [bcgsc/abyss#325]
Hi there,

When running `./configure` I've noticed the following:

checking for ghc... no
./configure: line 5816: : command not found
checking for pandoc... no

Although I didn't notice anything later when compiling, I was wondering: what would be the advantage of having `ghc` and/or `pandoc` installed? Will it compile different? Is it used for something else? Does it affect performance?

Thanks in advance and sorry for my ignorance.

Cheers,
Santiago

# Please report

- [ ] ABySS 2.2.4
- [ ] CentOS 7.7.1908
- [ ] GCC 4.8.5
- [ ] Boost 1.56.0

**Comment by sjackman** [comment]
`ghc` is used to assembly `abyss-samtobreak`, which I created to calculate scaffold NGA50 before QUAST existed. In general I recommend using QUAST-LG instead, but `abyss-samtobreak` is much much faster than QUAST, so it has its uses.
https://github.com/bcgsc/abyss/blob/master/Misc/samtobreak.hs

`pandoc` is used to convert `README.md` to `README.html`
https://github.com/bcgsc/abyss/blob/ffd5e372b94b26d1e302271c5fb8f92b85381f0a/Makefile.am#L17-L19

**Comment by santiagorevale** [comment]
Great answer. Thanks!

**Comment by sjackman** [comment]
`abyss-samtobreak` was modeled after Heng Li's `htsbox abreak`, which calculated contig NGA50, but not scaffold NGA50.
https://lh3.github.io/2014/07/07/abreak-evaluating-de-novo-assemblies
