### ISSUE TITLE
abyss-pe exceeded memory limit 

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/abyss#327]
# Please report

- [ ] version of ABySS with `abyss-pe version`
2.2.4
- [ ] distribution of Linux with `lsb_release -d`
SUSE Linux Enterprise Server 12 SP1

# Assembly error

- [ ] complete `abyss-pe` command line

`abyss-pe k=64 name=lculinaris v=-v j=192 B=550G H=4 kc=2 G=4000000000 pe='pea peb pec ped' lr='lra lrb lrc lrd' pea='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_2.fq.gz' peb='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_2.fq.gz' pec='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_2.fq.gz' ped='~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_2.fq.gz' lra='~/szeged/fk8jybr/input/Illumina_10x/LC001.fastq.gz' lrb='~/szeged/fk8jybr/input/Illumina_10x/LC002.fastq.gz' lrc='~/szeged/fk8jybr/input/Illumina_10x/LC003.fastq.gz' lrd='~/szeged/fk8jybr/input/Illumina_10x/LC004.fastq.gz'`

- [ ] last 20 lines of the output of `abyss-pe`

```
abyss-map -v -j192 -l40  ~/szeged/fk8jybr/input/Illumina_10x/LC001.fastq.gz ~/szeged/fk8jybr/input/Illumina_10x/LC002.fastq.gz ~/szeged/fk8jybr/input/Illumina_10x/LC003.fastq.gz ~/szeged/fk8jybr/input/Illumina_10x/LC004.fastq.gz lculinaris-8.fa \
| samtools sort -@192 -tBX -l0 -T$(mktemp -u -t lculinaris-8.lr.bed.XXXXXX) \
| tigmint-molecule -a 0.65 -n 5 -q 0 -d 50000 - \
| sort -k1,1 -k2,2n -k3,3n >lculinaris-8.lr.bed
Reading `lculinaris-8.fa.fai'...
Using 2.47 GB of memory and 48 B/sequence.
Reading `lculinaris-8.fa'...
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Read 9.06 GB in 51441118 contigs.
Using 82 GB of memory and 9.05 B/bp.
Mapped 1530906882 of 1586927860 reads (96.5%)
Mapped 1318830806 of 1586927860 reads uniquely (83.1%)
[bam_sort_core] merging from 192 files and 192 in-memory blocks...
time user=9141077.08s system=27187.54s elapsed=57659.33s cpu=15900% memory=95474 job=abyss-map -v -j192 -l40 ~/szeged/fk8jybr/input/Illumina_10x/LC001.fastq.gz   
time user=41751.92s system=7140.22s elapsed=75693.77s cpu=64% memory=306236 job=samtools sort -@192 -tBX -l0 -T$(mktemp -u -t lculinaris-8.lr.bed.XXXXXX)
time user=14639.08s system=192.54s elapsed=75629.86s cpu=19% memory=3275 job=tigmint-molecule -a 0.65 -n 5 -q 0 -d 50000 -
time user=86.64s system=2.27s elapsed=75687.57s cpu=0% memory=9 job=
tigmint-cut -p192 -n10 -w1000 -o lculinaris-8.tigmint.fa lculinaris-8.fa lculinaris-8.lr.bed
Started at: 2020-04-20 17:43:35.161366
Reading contig lengths...
Finding breakpoints...
slurmstepd: Job 18976 exceeded memory limit (737254376 > 688128000), being killed
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 18976 CANCELLED AT 2020-04-20T17:45:29 ***
/big/home/fk8jybr/.linuxbrew/bin/abyss-pe:770: recipe for target 'lculinaris-8.tigmint.fa' failed
make: *** [lculinaris-8.tigmint.fa] Terminated
```

- [ ] number of sequenced bases
4Gbp
- [ ] estimated genome size and ploidy

diploid

- [ ] estimated sequencing depth of coverage
120x Illumina PE and 30x 10xGenomics

How could I resolve this issue?

**Comment by lcoombe** [comment]
```
slurmstepd: Job 18976 exceeded memory limit (737254376 > 688128000), being killed
```
Looks like your job exceeded the memory limit on the node you were running the job on. You'll need to either request more memory or use a server with more memory available. 

Another way to reduce the memory would be to use less processes in `tigmint-cut` (`-p`) -- since that is a python script using multi-processing, the 192 processes that you launch will have separate memory allocation, which may be causing the large memory footprint you are seeing. That step runs quite fast even using 8 threads for human datasets.

**Comment by hidvegin** [comment]
Thank you for your answer. I tried run this: 
`tigmint-cut -p16 -n10 -w1000 -o lculinaris-8.tigmint.fa lculinaris-8.fa lculinaris-8.lr.bed`

After that I get this error message:
```
Traceback (most recent call last):
  File "/big/home/fk8jybr/.linuxbrew/Cellar/tigmint/1.1.2_2/libexec/bin/tigmint-cut", line 12, in <module>
    import pybedtools
  File "/big/home/fk8jybr/.linuxbrew/Cellar/tigmint/1.1.2_2/libexec/lib/python3.7/site-packages/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ModuleNotFoundError: No module named 'pybedtools.cbedtools'
```

I checked that I installed intervaltree pybedtools pysam statistics with pip3:

```
pip3 install intervaltree pybedtools pysam statistics
Requirement already satisfied: intervaltree in ./.linuxbrew/lib/python3.8/site-packages (3.0.2)
Requirement already satisfied: pybedtools in ./.linuxbrew/lib/python3.8/site-packages (0.8.1)
Requirement already satisfied: pysam in ./.linuxbrew/lib/python3.8/site-packages (0.15.4)
Requirement already satisfied: statistics in ./.linuxbrew/lib/python3.8/site-packages (1.0.3.5)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in ./.local/lib/python3.8/site-packages (from intervaltree) (2.1.0)
Requirement already satisfied: six in ./.local/lib/python3.8/site-packages (from pybedtools) (1.14.0)
Requirement already satisfied: docutils>=0.3 in ./.local/lib/python3.8/site-packages (from statistics) (0.16)
```

Based on the pip3 message I installed already the dependencies but tigmint can not find it.

**Comment by lcoombe** [comment]
Are you running `tigmint-cut` independently or using `abyss-pe`? You could still use the `abyss-pe` command to launch the assembly, it should re-start at the step where it failed before (`tigmint-cut`). You can check it will by adding the dry-run option (`-n`) to the `abyss-pe` command. 
Are you on the same machine as before? `tigmint-cut` found the python packages fine before based on your logs.

**Comment by hidvegin** [comment]
I am on the same node as before. I use tigmint-cut independently. If I would like to change the -p value for tigmint-cut, how could I handle it from abyss-pe?

**Comment by lcoombe** [comment]
The `-p` value for `tigmint-cut` is controlled by the `j` setting:
```
	$(gtime) tigmint-cut -p$j -n$(tigmint_n) -w$(tigmint_w) -o $@ $*.fa $<
```

**Comment by hidvegin** [comment]
Thank you. I will try it. Now I used only `tigmint-cut` independently. After that when it finished I started the abyss-pe with the same parameters which I used before. I hope this will be good.

**Comment by sjackman** [comment]
Consider installing ABySS and Tigmint using a package manager, such as Homebrew (which works on both macOS and Linux). See https://brew.sh and `brew install abyss`

**Comment by hidvegin** [comment]
@sjackman:
I installed ABySS and Tigmint with Homebrew.

**Comment by hidvegin** [comment]
`abyss-pe` is finished. I get this log file:

```
Best scaffold N50 is 3620 at n=5 s=1000.

n	n:1000	L50	LG50	NG50	min	N75	N50	N25	E-size	max	sum	name
51.44e6	164446	41828	164446	1000	1000	2262	3620	5985	5529	134218	514.3e6	n=5 s=1000
MergeContigs -v  -k64 -o lculinaris-8.tigmint.arcs.fa lculinaris-8.tigmint.fa lculinaris-8.tigmint.arcs.path
Reading `lculinaris-8.tigmint.fa'...
Read 51441652 sequences. Using 20.8 GB of memory.
Reading `lculinaris-8.tigmint.arcs.path'...
Read 1337 paths. Using 20.8 GB of memory.
The minimum coverage of single-end contigs is inf.
The minimum coverage of merged contigs is inf.
n	n:200	L50	min	N75	N50	N25	E-size	max	sum	name
51.44e6	2486829	317039	200	285	610	2919	2482	134218	1.261e9	lculinaris-8.tigmint.arcs.fa
ln -sf lculinaris-8.tigmint.arcs.fa lculinaris-scaffolds.fa
PathOverlap --overlap -v  -k64 --dot lculinaris-7.dot lculinaris-7.path >lculinaris-8.dot
Reading `lculinaris-7.dot'...
Reading `lculinaris-7.path'...
ln -sf lculinaris-8.dot lculinaris-scaffolds.dot
abyss-fac -G4000000000  lculinaris-unitigs.fa lculinaris-contigs.fa lculinaris-scaffolds.fa |tee lculinaris-stats.tab
n	n:500	L50	LG50	NG50	min	N75	N50	N25	E-size	max	sum	name
52.03e6	527283	123511	527283	500	500	844	1487	2643	2510	67386	652.2e6	lculinaris-unitigs.fa
51.47e6	440753	83610	440753	500	500	988	2375	4130	3611	134218	689.8e6	lculinaris-contigs.fa
51.44e6	422737	70361	422737	500	500	987	2627	4955	4299	134218	688.7e6	lculinaris-scaffolds.fa
time user=143.46s system=23.92s elapsed=168.16s cpu=99% memory=3 job=abyss-fac -G4000000000 lculinaris-unitigs.fa lculinaris-contigs.fa 
time user=0.00s system=0.00s elapsed=168.16s cpu=0% memory=0 job=
ln -sf lculinaris-stats.tab lculinaris-stats
tr '\t' , <lculinaris-stats.tab >lculinaris-stats.csv
abyss-tabtomd lculinaris-stats.tab >lculinaris-stats.md
```

How could I optimalize the `abyss-pe` for I get longer sequencies in the scaffold fasta file? I used this paramers: `abyss-pe k=64 name=lculinaris v=-v j=192 B=550G H=4 kc=2 G=4000000000` Should I try kc=3 and kc=4? k=64 is good because I choose this with `ntCard`.
