### ISSUE TITLE
abyss-pe: make: *** [A_c-1.fa] Error 127 [Conda env]

### ISSUE THREAD

**Issue by yyasinkaya** [bcgsc/abyss#333]
Hi, 
I worked with abyss-pe command for pair-end data by conda env. I encountered the make file error (because of the abyss-pe.Makefile:504) and aligning ended. (I used nohup command maybe it gives stderr but I didn't try 2>&1)

command:

nohup abyss-pe k=85 name=A_c in='V300054549_L3_PLAyviRAAAAAAA-685_1.fq.gz V300054549_L3_PLAyviRAAAAAAA-685_2.fq.gz' &

Error:

which: no abyss-pe.Makefile in (kaya/miniconda3/bin)
dirname: under-processed
Try 'dirname --help' for more information.
ABYSS -k85 -q3    --coverage-hist=coverage.hist -s A_c-bubbles.fa  -o A_c-1.fa V300054549_L3_PLAyviRAAAAAAA-685_1.fq.gz V300054549_L3_PLAyviRAAAAAAA-685_2.fq.gz
ABySS 2.0.2
ABYSS -k85 -q3 --coverage-hist=coverage.hist -s A_c-bubbles.fa -o A_c-1.fa V300054549_L3_PLAyviRAAAAAAA-685_1.fq.gz V300054549_L3_PLAyviRAAAAAAA-685_2.fq.gz
Reading `V300054549_L3_PLAyviRAAAAAAA-685_1.fq.gz'...
Reading `V300054549_L3_PLAyviRAAAAAAA-685_2.fq.gz'...
Loaded 1341720415 k-mer
Minimum k-mer coverage is 8
Using a coverage threshold of 3...
The median k-mer coverage is 12
The reconstruction is 417542959
The k-mer coverage threshold is 3.4641
Setting parameter e (erode) to 3
Setting parameter E (erodeStrand) to 1
Setting parameter c (coverage) to 3.4641
Generating adjacency
Added 2679656044 edges.
Eroding tips
Eroded 885994635 tips.
Eroded 0 tips.
Pruning tips shorter than 1 bp...
Pruned 8947 k-mer in 8947 tips.
Pruning tips shorter than 2 bp...
Pruned 12154 k-mer in 6288 tips.
Pruning tips shorter than 4 bp...
Pruned 33667 k-mer in 10076 tips.
Pruning tips shorter than 8 bp...
Pruned 114744 k-mer in 18534 tips.
Pruning tips shorter than 16 bp...
make: *** [/kaya/miniconda3/bin/abyss-pe.Makefile:504: A_c-1.fa] Ended
nohup.out (END)

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
There's not unfortunately enough information in this log to determine why the process stopped running. Are you running this job on a scheduled HPC cluster? If so, it's possible that the job exceeded the allocated memory or time reservation.

You may wish to try using ABySS 2 Bloom filter mode, which reduces memory consumption by ten fold. See https://github.com/bcgsc/abyss/#assembling-using-a-bloom-filter-de-bruijn-graph
