### ISSUE TITLE
Konnector output in abyss for assembly (Question, Not Issue)

### ISSUE THREAD

**Issue by adc0032** [bcgsc/abyss#336]
# Please report

- [X ] version of ABySS with `abyss-pe version`

`abyss-pe (ABySS) 2.0.1`

- [ X] distribution of Linux with `lsb_release -d`

`Description:	CentOS release 6.10 (Final)`

Hi! 
Thank you for these wonderful tools! 
I am attempting to assemble a genome (estimated size 2.08Gb) using a single chromium 10X library and some publicly available RNA-seq data. I have assembled the reads using supernova to get an initial assembly. I have used `rascaf` to improve that assembly with RNA-seq reads. 

I am now trying to use debarcoded reads from `longranger basic` to assembly in `abyss`. I first ran `konnector` and it produced a single fq file (I interpreted as connected reads) and two additional fq files (I interpreted as unconnected (possibly extended) paired end reads). 

QUESTION: when running `abyss-pe` should I use the unconnected 1.fq/2.fq reads as a pe library and the connected reads as single end input? 
I didn't see a lot of questions about this, so this may be my ignorance of something obvious. 
I appreciate any feedback on my understanding of using these tools and my methods!

**Comment by kmnip** [comment]
If you use connected reads, then you can use a larger k-mer size in your ABySS assembly.
I suggest that you use all PE reads (i.e. not just the unconnected read pairs) as `pe` library. The connected reads would still be shred into k-mers and read pairs are still needed create contigs from unitigs.

**Comment by lcoombe** [comment]
Just adding to Ka Ming's comment -- when I run ABySS assemblies using connected reads, I use the connected _and_ unconnected reads as single-end input for the unitig stage (and all PE reads pre-merging as `pe`, as Ka Ming mentioned). The unconnected reads may or may not be used depending on the k-mer size that you end up choosing, but it is good to set up your ABySS script like that for k-sweeps, and is often necessary depending on the read coverage you have and the success of the read merging. 

If you want to maximize the merging of your PE reads, you could also run the unconnected post-konnector reads through abyss-mergepairs, which merges overlapping reads -- that's also standard in our assembly pipelines.

**Comment by adc0032** [comment]
Thank you both so much for your replies!
I have ~50X coverage. I haven't assessed the success of read merging. 

Just to make sure i've absorbed your suggestions:
1. To maximize read merging  running `abyss-mergepairs` with unconnected konnector out is standard practice.
2. General practice when using connected reads for my k-sweep:
```
for k in `seq 60 8 120`;  do
    abyss-pe k=$k lib='se1 se2 pe' \
    pe='myreads.fq' \
    se1='konnector.fq' \
    se2='unkonnect1.fq unkonnect2.fq' 
#alternatively se2
    se2='abyss-mergepairsoutput.fq'
```
where `myreads.fq` are my PE debarcoded interleaved 10x reads. 
I assume i could use both `se2` variables instead of one being the alternative, but I thought I'd also consider of the possibility that it could connect them all :)?

When you say larger kmer sizes, you mean I could considered kmers longer than the read size (150bp), because I now expect to have fragment sized information (~350bp)? 
If so, I guess I should poke our HPC to recompile and up `enable-maxk`... otherwise, i'm not taking advantage of using (pseudo)longer reads.

**Comment by lcoombe** [comment]
Hi @adc0032,

1. Yup, that's right! And we would then use the merged reads via konnector/abyss-mergepairs + unconnected reads as `se` input for the assembly.

2. You have the right idea for the `abyss-pe` command -- here's how I would do it to ensure that only the `se` reads are used for the unitigs and the `pe` reads used for the contigging/scaffolding. You just don't want to accidentally duplicate sequences input to the unitig stage:
```
abyss-pe <params>   pe='pelib' pelib='myreads.fq'  se='konnector.fq unconnected.fq' ...
```
When I'm setting up a job I do a dry-run (add `-n` to the `abyss-pe` command), and you'll see all the commands that will be executed. For this case, just make sure that the `se` reads are being input to the initial graph construction (command `abyss-bloom-dbg` if using ABySS in Bloom filter mode), and the `pe` reads are being used in the `abyss-map` steps.

Yes, you could potentially try kmer sizes greater than the read length when using merged reads! I usually do a quick calculation of the expected coverage at various k-values based on the merged/unmerged reads. The coverage will go down as the k-value increases, as more sequences will be less than the k-mer size. If you only have ~50X coverage, you'll probably have to use a k-mer size that can utilize most of your reads -- the assembly quality tends to suffer when the coverage drops much lower than that.

**Comment by adc0032** [comment]
Sweet!
I've played around with ntcard and genomescope with my PE 10x reads to get an understanding of exp. coverage and and k-value. I will use my merged reads to do the same.

I truly appreciate your guidance!
@lcoombe and @kmnip 
-Amanda

**Comment by lcoombe** [comment]
Glad we could help -- good luck!
