### ISSUE TITLE
How to use mate pairs (around 35bp) for scaffolding along with paired end reads (around 100 bp in length)

### ISSUE THREAD

**Issue by k2bhide** [bcgsc/abyss#339]
Hello,

I ama using abyss version 2.2.4 for assembly using abyss-pe command.
I have paired end reads (100 bp in length) and mate pairs (3kb and 8kb) (35 bp in length).
I was able to get contigs file after generating assembly using kmers 69,73,77,81,85,89 and 93.

However since mate pairs files sequence length is less than selected kmer size, it failed to give scaffolds file.

Please let me know if there is any parameter/option in abyss to use mate pair files to generate scaffolds if mate pair sequence length is less than selected kmer size.

**Comment by k2bhide** [comment]
Hello,

I ama using abyss version 2.2.4 for assembly using abyss-pe command. 
I have paired end reads (100 bp in length) and mate pairs (3kb and 8kb) (35 bp in length).
I was able to get contigs file after generating assembly using kmers 69,73,77,81,85,89 and 93.

However since mate pairs files sequence length is less than selected kmer size, it failed to give scaffolds file.

Please let me know if there is any parameter/option in abyss to use mate pair files to generate scaffolds if mate pair sequence length is less than selected kmer size.

**Comment by sjackman** [comment]
Try setting the `l` parameter (minimum alignment length) to something less than 35, say 30.

**Comment by k2bhide** [comment]
Hii Shaun,

Thank you for your reply. Using l option worked fine.
