### ISSUE TITLE
How can I put output files in a subdirectory without using the --directory option?

### ISSUE THREAD

**Issue by CristianRiccio** [bcgsc/abyss#342]
I am using ABySS 2.2.4 on Mac and GNU/Linux to assemble a genome de novo using paired-end Illumina reads. At the moment, my comand is:

`abyss-pe --directory=output/folder name=organism k=25 in='../output/reads/dna/illumina/noPCR/organism/strain/readsSortedByName1Head4000.fq ../output/reads/dna/illumina/noPCR/organism/strain/readsSortedByName2Head4000.fq'`

It works fine but it's a bit inelegant. Is there a way to change it to something like

`abyss-pe  name=output/folder/organism k=25 in='output/reads/dna/illumina/noPCR/organism/strain/readsSortedByName1Head4000.fq output/reads/dna/illumina/noPCR/organism/strain/readsSortedByName2Head4000.fq'`

?

If I run the above command, I get this error:

`error: 'output/organism/organism-unitigs.fa': No such file or directory
make: *** [/Users/cr517/anaconda/envs/abyss=2.2.4/bin/abyss-pe.Makefile:932: output/organism/organism-stats.tab] Error 1
make: *** Deleting file 'output/organism/organism-stats.tab'`

It's weird because `output/organism/organism-unitigs.fa` does exist. It's a link to a file that exists.

**Comment by sjackman** [comment]
I agree that what you have is rather inelegant, but there's sadly no easy way to fix it. My two best suggestions would be to use either…
```bash
abyss-pe --directory=output/folder name=organism k=25 in="$PWD/output/reads/dna/illumina/noPCR/organism/strain/readsSortedByName1Head4000.fq $PWD/output/reads/dna/illumina/noPCR/organism/strain/readsSortedByName2Head4000.fq"
```
or
```bash
mkdir -p output/folder
ln -s $PWD/output/reads/dna/illumina/noPCR/organism/strain output/folder/data
abyss-pe --directory=output/folder name=organism k=25 in="data/readsSortedByName1Head4000.fq data/readsSortedByName2Head4000.fq"
```
