### ISSUE TITLE
What do contig titles mean?

### ISSUE THREAD

**Issue by shelkmike** [bcgsc/abyss#349]
The question is simple, yet I cannot find an answer.
Contig (and scaffold) titles of ABySS 2.2.4 look like 

>0 205 6231 read:K00370:74:HFWWFBBXY:1:1101:30959:1613/1

The first number is the ordinal number of the contig. The second number is the contig's length. Questions are:
1) What is the third number?
2) Which read's title is indicated in the contig's title? Is this the first read that was used during the assembly process of the contig?

I will be grateful for help.

**Comment by lcoombe** [comment]
Hi @shelkmike,

The third number is the total kmer coverage of the contig. 
The read ID shown there is the read that was extended using the Bloom filter de Bruijn graph to generate that sequence - there's more details about that algorithm in the [ABySS-2 paper](https://dx.doi.org/10.1101%2Fgr.214346.116). 

Hope that helps -- thank you for your interest in ABySS!
Lauren

**Comment by sjackman** [comment]
Could add this answer here: https://github.com/bcgsc/abyss/wiki/ABySS-File-Formats#fa
