### ISSUE TITLE
abyss-pe and abyss-map together

### ISSUE THREAD

**Issue by azrasid** [bcgsc/abyss#350]
**abyss-pe version 2.2.4**
HI ,
I want to give ABYSS assembler the reference  and the pair end  Fastq files as inputs.
The reason is I want a big contig/scaffold from ABYSS so that I can use that node to do multi sequence alignment.

I am giving this command
**abyss-pe name=out78  k=96 in='NA12878_R1.fq  NA12878_R2.fq' abyss-map cyp2c19ref.fa -o scaff78.fa** 

I got the following error
make: *** No rule to make target `abyss-map'.  Stop.

Please can you tell me what is the right way to do it.

Thanks,
Azra

**Comment by lcoombe** [comment]
Hi @azrasid,

To assemble those paired-end reads with ABySS, you don't need the part of the command after `abyss-map` above:
```
abyss-pe name=out78 k=96 in='NA12878_R1.fq NA12878_R2.fq' 
```
The assembled sequences will by default go through the unitig, contig and scaffold stages of ABySS. ABySS is a _de novo_ assembler, so it doesn't use an input reference in it's pipeline. 
If you wanted to do an assembly, and then perform reference-guided scaffolding, you could run ABySS, and then run [ntJoin](https://github.com/bcgsc/ntjoin).

Take a look here for more information about how to structure the `abyss-pe` command, particularly to run ABySS in the Bloom filter mode, which I recommend to lower the memory usage substantially: https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph

I hope that helps - thanks for your interest in ABySS!
Lauren

**Comment by azrasid** [comment]
Thanks.
Yes, I wanted to do assembly and then reference guided scaffolding.
Many thanks for suggesting ntJoin .
