### ISSUE TITLE
Compiled with openmpi, still getting an support for MPI error.

### ISSUE THREAD

**Issue by ctseto** [bcgsc/abyss#351]
Getting a

"error: ABySS was not configured with support for MPI. For details
       on compiling ABySS with MPI suppor see:
       https://github.com/bcgsc/abyss#compiling-abyss-from-source"

I think I correctly configured for OpenMPI. Checking my config logs

checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking for MPI_Init in -lmpi... yes

# Please report

- [X] version of ABySS with `abyss-pe version` 
(2.25)
- [X] distribution of Linux with `lsb_release -d`
Description:    CentOS Linux release 7.6.1810 (Core) 

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [X] Have you tried installing ABySS using Brew or Bioconda?
Abyss version from bioconda appears to work on interactive nodes, will see if it works on batch nodes
- [X] version of GCC or compiler with `gcc --version`
gcc (GCC) 6.3.0
- [ ] complete `./configure` command line
(SparseHash: ./configure --prefix=/scratch/07512/cseto/abyss/sparsehash/prefix/)
(OpenMPI: ./configure --prefix=/scratch/07512/cseto/openmpi-4.0.5/prefix/)
Abyss: ./configure --prefix=/scratch/abyss/prefix/ --with-sparsehash=/scratch//abyss/sparsehash/prefix/ --with-mpi=/scratch/openmpi-4.0.5/prefix/

- [X] last 20 lines of the output of `./configure`
config.status: creating SimpleGraph/Makefile
config.status: creating MergePaths/Makefile
config.status: creating KAligner/Makefile
config.status: creating PairedDBG/Makefile
config.status: creating ParseAligns/Makefile
config.status: creating PathOverlap/Makefile
config.status: creating Consensus/Makefile
config.status: creating FilterGraph/Makefile
config.status: creating GapFiller/Makefile
config.status: creating Sealer/Makefile
config.status: creating vendor/gtest-1.7.0/Makefile
config.status: creating Unittest/Makefile
config.status: creating LogKmerCount/Makefile
config.status: creating Bloom/Makefile
config.status: creating BloomDBG/Makefile
config.status: creating DataBase/Makefile
config.status: creating vendor/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

- [X] last 20 lines of the output of `make`
make[2]: Entering directory `/scratch/abyss/AdjList'
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I../DataLayer -DPAIRED_DBG -I/scratch/abyss  -isystem/scratch/openmpi-4.0.5/prefix//include  -isystem/scratch/abyss/sparsehash/prefix//include  -isystem/scratch/abyss/boost_1_56_0 -Wall -Wextra -Werror -g -O2 -MT AdjList-AdjList.o -MD -MP -MF .deps/AdjList-AdjList.Tpo -c -o AdjList-AdjList.o `test -f 'AdjList.cpp' || echo './'`AdjList.cpp
mv -f .deps/AdjList-AdjList.Tpo .deps/AdjList-AdjList.Po
g++ -std=c++11 -Wall -Wextra -Werror -g -O2  -L/scratch/openmpi-4.0.5/prefix//lib  -L/scratch/abyss/sparsehash/prefix//lib  -o AdjList AdjList-AdjList.o ../DataLayer/libdatalayer.a ../Common/libcommon.a ../PairedDBG/libpaireddbg.a ../DataBase/libdb.a -lsqlite3 -ldl -lm  -ldl -lm 
make[2]: Leaving directory `/scratch/abyss/AdjList'
Making all in vendor
make[2]: Entering directory `/scratch/abyss/vendor'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/scratch/abyss/vendor'
Making all in vendor/gtest-1.7.0
make[2]: Entering directory `/scratch/abyss/vendor/gtest-1.7.0'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/scratch/abyss/vendor/gtest-1.7.0'
Making all in Unittest
make[2]: Entering directory `/scratch/abyss/Unittest'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/scratch/abyss/Unittest'
make[2]: Entering directory `/scratch/abyss'
make[2]: Leaving directory `/scratch/abyss'
make[1]: Leaving directory `/scratch/abyss'

**Comment by jowong4** [comment]
Let me confirm a couple things. You successfully compiled ABySS and that the error "error: ABySS was not configured with support for MPI. For details
on compiling ABySS with MPI suppor see:
https://github.com/bcgsc/abyss#compiling-abyss-from-source" is triggered by a command?
Can you shared your command if that is the case.

**Comment by schutzekatze** [comment]
Check whether the command you run actually uses the ABySS you compiled (and not one from somewhere else) by doing `which abss-pe` to get the path of the abyss binaries.

**Comment by sjackman** [comment]
Bloom filter mode is much easier to get running than MPI mode. That solution should be preferred.
To install ABySS with MPI support, install ABySS using Homebrew on either macOS or Linux.
See https://github.com/bcgsc/abyss#install-abyss-on-linux-or-macos

See also https://github.com/bcgsc/abyss/issues/359#issuecomment-758866540
