### ISSUE TITLE
sparsehash FATAL ERROR: failed to allocate 10 groups

### ISSUE THREAD

**Issue by yanlina0205** [bcgsc/abyss#352]
# Please report
- [ ] version of ABySS with `abyss-pe version`
abyss-pe (ABySS) 2.2.5
- [ ] distribution of Linux with `lsb_release -d`
Description:	CentOS Linux release 7.2.1511 (Core)
# Assembly error
- [ ] complete `abyss-pe` command line
abyss-pe name=SS-RNA k=40 in='/asnas/wangqf_group/yanln/yln/RNA/tophat/5_output_2/unmapped.bam /asnas/wangqf_group/yanln/yln/RNA/tophat/9_output_2/unmapped.bam' SS=--SS
- [ ] last 20 lines of the output of `abyss-pe`
ABYSS -k40 -q3   --SS --coverage-hist=coverage.hist -s SS-RNA-bubbles.fa  -o SS-RNA-1.fa /asnas/wangqf_group/yanln/yln/RNA/tophat/5_output_2/unmapped.bam /asnas/wangqf_group/yanln/yln/RNA/tophat/9_output_2/unmapped.bam 
ABySS 2.2.5
ABYSS -k40 -q3 --SS --coverage-hist=coverage.hist -s SS-RNA-bubbles.fa -o SS-RNA-1.fa /asnas/wangqf_group/yanln/yln/RNA/tophat/5_output_2/unmapped.bam /asnas/wangqf_group/yanln/yln/RNA/tophat/9_output_2/unmapped.bam
Reading `/asnas/wangqf_group/yanln/yln/RNA/tophat/5_output_2/unmapped.bam'...
sparsehash FATAL ERROR: failed to allocate 10 groups
make: *** [/xtdisk/ENTER/bin/abyss-pe.Makefile:554: SS-RNA-1.fa] Error 1
- [ ] number of sequenced bases
2
- [ ] estimated genome size and ploidy
- [ ] estimated sequencing depth of coverage

# Build error

Consider installing ABySS using [Linuxbrew](https://linuxbrew.sh) on Linux or [Homebrew](https://brew.sh) on macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ ] Have you tried installing ABySS using Brew or Bioconda?
Bioconda
- [ ] version of GCC or compiler with `gcc --version`
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
- [ ] complete `./configure` command line
- [ ] last 20 lines of the output of `./configure`
- [ ] last 20 lines of the output of `make`

**Comment by sjackman** [comment]
Looks like you may have run out of memory. Try adding `abyss-pe v=-v` to get verbose logging, and try using Bloom filter mode to reduce memory usage by ten fold. See https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph

**Comment by yanlina0205** [comment]
You are right. I have solved the problem. Thank you very much.
