### ISSUE TITLE
Question regarding assembly time.

### ISSUE THREAD

**Issue by ms-gx** [bcgsc/abyss#355]
I know that this is a very generic question and I am aware you can not give an accurate estimate. I do not have the data yet, so I can not try, but I want to plan ahead.

What is your estimate regarding wall clock time if I have the following:
 - Most recent version of ABySS
 - about 1Gbp of genome size (diploid or tetraploid, not sure yet)
 - about 60Gbp of Illumina PE 150bp data
 - Machine: 32 Core (AMD EPYC 7502P) with 128GB DDR4 RAM
 - OS: Ubuntu 20.04

As I said, very rough estimate is fine: 5 hours, 10 hours, 1 day, 2 days?

**Comment by jowong4** [comment]
It is also quite dependent on the k size you run. A ~70x human (3 Gbp genome) run using 48 threads and k 128 typically takes a day when we run it in-house.

**Comment by ms-gx** [comment]
OK, this already helps me. So I guess my assemblies should not take more than roughly half a day in this case.

**Comment by mmokrejs** [comment]
> Machine: 32 Core (AMD EPYC 7502P) with 128GB DDR4 RAM

I guess only with a Bloom-filter enabled, if at all. Time? 5 days given you have only the 32 CPU cores. A fish genome 1.3Gbp took about 1-2 days for me using much input reads. I would have to sniff in some logs to see how much input reads we had. It may not be doable with your hardware.
