### ISSUE TITLE
SGE - submit JOBs properly or configuration 

### ISSUE THREAD

**Issue by ddelgadillod** [bcgsc/abyss#359]
Hello

In my organization we have a Sun Grid Engine system, in which I requested to IT department the installation of ABySS, everything runs fine without submitting any process as a job to the cluster, however, when submitting jobs (using more processors and memory), in the output logs I find the following message:

`error: ABySS was not configured with support for MPI. For details
       on compiling ABySS with MPI suppor see:
       https://github.com/bcgsc/abyss#compiling-abyss-from-source
error: ABySS was not configured with support for MPI. For details
       on compiling ABySS with MPI suppor see:
       https://github.com/bcgsc/abyss#compiling-abyss-from-source
error: ABySS was not configured with support for MPI. For details
       on compiling ABySS with MPI suppor see:
       https://github.com/bcgsc/abyss#compiling-abyss-from-source`

Another way I've tried to run some job is running directly with the command:

`qsub -N bact1-pe openmpi 4 -t 50-90:8 <<<'mkdir k$SGE_TASK_ID && abyss-pe -C k$SGE_TASK_ID in=Bact1_1.fastq.gz Bact1_2.fastq.gz'`

Getting the following message:

`Unable to run job: job rejected: the requested parallel environment "openmpi" does not exist.`

I noticed that all compiling from sources process was OK. 

Do you have any tutorial or suggestion to carry out the installation in SGE and properly MPI/openMPI environments configuration or suggest how to solve this issue?

Many thanks

Diego D

**Comment by lcoombe** [comment]
Hi Diego,

Have you tried running ABySS using the [Bloom filter de Bruijn graph](https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph)? That is our newer mode (introduced in ABySS v2), and uses much less memory with very similar assembly results. Using that mode doesn't require MPI.

Lauren

**Comment by sjackman** [comment]
Bloom filter mode is much easier to get running than MPI mode. That solution should be preferred.
To install ABySS with MPI support, install ABySS using Homebrew on either macOS or Linux.
See https://github.com/bcgsc/abyss#install-abyss-on-linux-or-macos

**Comment by sjackman** [comment]
@lcoombe This issue seems to be a FAQ. Any thoughts on enabling Bloom filter mode by default? ABySS could estimate the appropriate size for the Bloom filter using ntCard. I know there's always more work to be done than time available. Could be a good co-op project.

**Comment by lcoombe** [comment]
@sjackman - Yes that's a good point and a good idea. Personally, I agree that the Bloom filter mode could be default - that's the only way we run it even within our group these days. I'll make a note of that and bring it up with the group!

**Comment by sjackman** [comment]
The only real blocker and challenge to making it the default is that you need to pick some size for the Bloom filter, and there's not really any one-size-fits-all solution. Two options I see are estimating based on the size on disk of the (possibly compressed) input FASTA/FASTQ files, or using ntCard.

**Comment by kmnip** [comment]
You can introduce an FPR variable (adjustable by the user) and use the ntCard output to set `B` based on the `H` and `kc` values provided by the user.

**Comment by sjackman** [comment]
`H` and `kc` should have also have reasonable default values, like say `H=2 kc=2` (without any data whatsoever).
