### ISSUE TITLE
What does "Different" mean for mapping stats?

### ISSUE THREAD

**Issue by ms-gx** [bcgsc/abyss#360]
ABySS 2.2.5

What does `Different` in the log file mean regarding read mapping/orientation? What is their origin?

Like here:
```
Mateless           0
Unaligned     193071  0.106%
Singleton    2186472  1.2%
FR         145140850  79.8%
RF             19688  0.0108%
FF              8304  0.00456%
Different   34389238  18.9%
Total      181937623
```
Is 18.9% OK for this category?

**Comment by kmnip** [comment]
Hi @ms-gx ,

`Different` refers to the mates that are aligned to "different" unitigs. They contribute to paired-end supports and distance estimates between unitigs in ABySS.

The percentage values you reported are actually quite favorable, especially the low percentage of `Unaligned`. Having a high `FR` here indicates that majority of paired-end alignments are contained completely within unitigs. This is actually a good thing to see.

Hope that helps!
Ka Ming

**Comment by ms-gx** [comment]
Thanks, this helps a lot! :)
