### ISSUE TITLE
invalid option: `-b-j32' make: *** [032521-1-rr.dot] Error 1

### ISSUE THREAD

**Issue by maojn** [bcgsc/abyss#366]
Hi,

I just installed 2.3.0 and got the following error during my test

# Please report

- [x] version of ABySS with `abyss-pe version` version 2.3.0
- [x] distribution of Linux with `lsb_release -d`  Red Hat Enterprise Linux Server release 7.9 (Maipo)

`which abyss-pe` np=32 k=25 n=10 in='1.fq 2.fq' name=032521

...
....
Concatenating fasta files to 032521-1.fa
Concatenating fasta files to 032521-bubbles.fa
Done.
AdjList    -k25 -m0 --dot 032521-1.fa >032521-1.dot
abyss-rresolver-short  -b -j32 -k25  \
-h 032521-1-rr --dot -c 032521-1-rr.fa -g 032521-1-rr.dot 032521-1.fa 032521-1.dot /data/maoj/seq/ngs/mouse_rnaseq_nguyenck_2.fq /data/maoj/seq/ngs/mouse_rnaseq_nguyenck_1.fq 
abyss-rresolver-short: invalid option: `-b-j32'
make: *** [032521-1-rr.dot] Error 1

Looks like the space between parameters went missing.

**Comment by jowong4** [comment]
Hi, `abyss-rresolver-short` uses a Bloom filter, the size of which you have to specify using `B=`.  The size is dependent on various factors, such as genome size. I would recommend trying `B=45G` if you have the necessary resources.

**Comment by maojn** [comment]
Thank you for the response. Adding B=45G solved the error!

Jean

**Comment by mmokrejs** [comment]
Hi,
  I wondered why this thread quickly deteriorated from the seemingly misisngly space char in `-b-j32` to using a Bloom filter.

  So, I had to run into this myself too to get back to this:

```
abyss-pe FIXMATE_OPTIONS=--qname v=-v np=367 j=367 k=50 aligner=bowtie2 l=100 s=100 S=200 n=6 N=1 name=mygenome__abyss_50 pe-bam default lib=HYWW2DSXY.3 HYWW2DSXY.3.pe=foo.trimmomatic.tadpole.k62.shave.rinse.pairs.fasta 'se=foo.trimmomatic.1.singletons.fastq.gz foo.trimmomatic.2.singletons.fastq.gz' long=transcripts transcripts=transcripts.fasta
...
Finding overlaps of exactly k-1 bp...
V=732420 E=442596 E/V=0.604
Degree: █▂▁
        01234
0: 62% 1: 20% 2-4: 19% 5+: 0.0035% max: 5
abyss-rresolver-short: invalid option: `-b-j367'
make: *** [mygenome__abyss_50-1-rr.dot] Error 1
```

**Comment by mmokrejs** [comment]
There is probably another error later being triggered:

```
Returning block of 2825360 for bucket 1
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 901374
fchr[G]: 1400217
fchr[T]: 1919894
fchr[$]: 2825359
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 5494870 bytes to primary EBWT file: mygenome__abyss_114-3.fa.rev.1.bt2
Wrote 706344 bytes to secondary EBWT file: mygenome__abyss_114-3.fa.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 2825359
    bwtLen: 2825360
    sz: 706340
    bwtSz: 706340
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 176585
    offsSz: 706340
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 14716
    numLines: 14716
    ebwtTotLen: 941824
    ebwtTotSz: 941824
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:00:00
blah/usr/bin/abyss-bowtie2: line 56: query[@]: unbound variable
Read 0 alignments
Mateless   0
Unaligned  0
Singleton  0
FR         0
RF         0
FF         0
Different  0
Total      0
abyss-fixmate: error: All reads are mateless. This can happen when first and second read IDs do not match.
[main_samview] fail to read the header from "-".
make: *** [HYWW2DSXY.3-3.bam] Error 1
```

**Comment by schutzekatze** [comment]
The issue is not the missing space char alone, but a missing Bloom filter size (after `-b` param) for the rresolver stage. Right now, this stage has this parameter as mandatory even though ABySS didn't before, hence this error appears. I'll update it so that rresolver only runs in Bloom filter ABySS mode.

**Comment by mmokrejs** [comment]
Thank you Vladimir, maybe also sanitize the `abyss-bowtie2` script not to die badly on empty input and also not to be called too? I am not sure if the zero counts of read types caused the error are were just reported as zeroes due to the error.

**Comment by sjackman** [comment]
Looks like this issue was resolved in https://github.com/bcgsc/abyss/commit/25f5f66f4cc1b1a04fbe3082e17eb59cdeef0b76
