### ISSUE TITLE
abyss-rresolver-short not assigning a value for -b (invalid option: `-b-j2')

### ISSUE THREAD

**Issue by ericgarciaresearch** [bcgsc/abyss#368]
Hi There,

abyss-rresolver-short is terminating my runs, I believe, after failing to assign a value for "-b" as I interpreted from a similar post (https://www.gitmemory.com/issue/bcgsc/abyss/366/812285867) where Vladimir said he will "update it so that rresolver only runs in Bloom filter ABySS mode"

Yet, I can't find more info about this issue. What can I do? Thank you!

- [ ] version of ABySS with `abyss-pe version` = abyss-pe (ABySS) 2.3.0
- [ ] distribution of Linux with `lsb_release -d`= Ubuntu 18.04.5 LTS
- [ ] complete `abyss-pe` command line
abyss-pe k=50 name=Aur_test50 j=$THREADS in='r1.fq.gz r2.fq.gz'

- [ ] last 20 lines of the output of `abyss-pe`
Pruning tips shorter than 50 bp...
     63 Pruned 510018 k-mer in 14233 tips.
     64 Pruning tips shorter than 50 bp...
     65 Pruned 780 k-mer in 38 tips.
     66 Pruning tips shorter than 50 bp...
     67 Pruned 36 k-mer in 2 tips.
     68 Pruning tips shorter than 50 bp...
     69 Pruned 89985 tips in 9 rounds.
     70 Popping bubbles
     71 Removed 189580 bubbles.
     72 Removed 189580 bubbles
     73 Marked 1594128 edges of 743432 ambiguous vertices.
     74 Left 30347 unassembled k-mer in circular contigs.
     75 Assembled 440218456 k-mer in 1063856 contigs.
     76 Removed 497012817 k-mer.
     77 The signal-to-noise ratio (SNR) is -0.427002 dB.
     78 AdjList    -k50 -m0 --dot Aur_test50-1.fa >Aur_test50-1.dot
     79 abyss-rresolver-short  -b -j40 -k50  \
     80 -h Aur_test50-1-rr --dot -c Aur_test50-1-rr.fa -g Aur_test50-1-rr.dot Aur_test50-1.fa Aur_test50-1.dot /home/e1garcia/shotgun_PIRE/fastp_4_deno
     81 abyss-rresolver-short: invalid option: `-b-j40'
     82 make: *** [/opt/abyss/bin/abyss-pe:566: Aur_test50-1-rr.dot] Error 1

**Comment by schutzekatze** [comment]
This has been fixed in the master branch and will be in the next release of ABySS. Until then, I can recommend either running the previous version or running current version with Bloom filter mode (by specifying the `-B` parameter). This parameter specifies the size of Bloom filter and depends on the number of reads / size of the genome you're assembling. Some of the common Bloom filter sizes we use are `-B2G` for C. elegans, `-B40G` for H. sapiens, and `-B500G` for large genomes like spruce.

**Comment by desmodus1984** [comment]
Hi,
I am running with the same problem. I couldn't install that thing of homebrew so I used the conda version.
I used the following code for running which ran well until the rresolver;
abyss-pe k=59 np=48 name=myse lib='BGI' BGI='/fs/scratch/PHS0338/appz/musket-1.1/BGI-Readz.0 /fs/scratch/PHS0338/appz/musket-1.1/BGI-Readz.1' \
         long='ONT' ONT='/fs/scratch/PHS0338/appz/Ratatosk/bin/Rata-T3-Corr10K.fasta'

and the report is:
31: Assembled 49534054 k-mer in 453230 contigs.
41: Assembled 49326842 k-mer in 453550 contigs.
11: Assembled 49720430 k-mer in 467990 contigs.
37: Assembled 50094022 k-mer in 461638 contigs.
6: Assembled 49289166 k-mer in 457369 contigs.
5: Assembled 49614361 k-mer in 462785 contigs.
21: Assembled 49679695 k-mer in 462396 contigs.
40: Assembled 49841950 k-mer in 460174 contigs.
0: Assembled 49689297 k-mer in 463135 contigs.
44: Assembled 49643028 k-mer in 460170 contigs.
16: Assembled 49982515 k-mer in 465728 contigs.
32: Assembled 49536860 k-mer in 460534 contigs.
36: Assembled 49990791 k-mer in 467315 contigs.
24: Assembled 49868991 k-mer in 462242 contigs.
18: Assembled 49229501 k-mer in 453419 contigs.
30: Assembled 49240006 k-mer in 451837 contigs.
43: Assembled 49610542 k-mer in 463100 contigs.
42: Assembled 49705908 k-mer in 457602 contigs.
12: Assembled 49899551 k-mer in 462757 contigs.
22: Assembled 49477862 k-mer in 456036 contigs.
19: Assembled 49342631 k-mer in 456663 contigs.
4: Assembled 50175729 k-mer in 474550 contigs.
20: Assembled 50187262 k-mer in 467852 contigs.
Assembled 2378322000 k-mer in 22003600 contigs.
Concatenating fasta files to myse-1.fa
Concatenating fasta files to myse-bubbles.fa
Done.
AdjList    -k59 -m0 --dot myse-1.fa >myse-1.dot
abyss-rresolver-short  -b -j48 -k59  \
-h myse-1-rr --dot -c myse-1-rr.fa -g myse-1-rr.dot myse-1.fa myse-1.dot /fs/scratch/PHS0338/appz/musket-1.1/BGI-Readz.0 /fs/scratch/PHS0338/appz/musket-1.1/BGI-Readz.1
abyss-rresolver-short: invalid option: `-b-j48'
make: *** [/users/PHS0338/jpac1984/.conda/envs/busco/bin/abyss-pe.Makefile:566: myse-1-rr.dot] Error 1

**Comment by lcoombe** [comment]
Hi @desmodus1984,

As @schutzekatze suggested, either try compiling ABySS from the current master branch, or run ABySS in the Bloom filter mode: https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph

We will have a new release soon that has the fix currently in the master branch of the code.

**Comment by schutzekatze** [comment]
I've released version 2.3.1 which fixes this.

**Comment by desmodus1984** [comment]
Dear Lauren,

Sorry to bother you. Could you explain me how to and what to do.
I tried with homebrew as stated and it started with an error "Error: Curl must be installed and in your PATH!"  - and I do not have root permission to install Curl (which is extremely annoying), and with brew it stated:
"==> Pouring abyss-2.2.5.x86_64_linux.bottle.tar.gz"
So it was still downloading an old version, not the most updated version.

Thanks;


Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by lcoombe** [comment]
Hi @desmodus1984,

Thanks for the heads up - looks like we haven't updated ABySS in homebrew yet. We'll do that upstream and let you know when it's finished!

**Comment by desmodus1984** [comment]
Hi Lauren,

It would be incredibly helpful and fantastic if you could first update it in conda. It is way much easier and simpler and straight forward to install.

Get BlueMail for Android<http://www.bluemail.me/r?b=16696>
On Apr 22, 2021, at 11:35 AM, Lauren Coombe ***@***.******@***.***>> wrote:

Hi @desmodus1984<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdesmodus1984&data=04%7C01%7Cja569116%40ohio.edu%7C503f667ca5884546ad9908d905a43757%7Cf3308007477c4a70888934611817c55a%7C0%7C0%7C637547025125233216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dDLKszwEtEXTAuGTUZULLHplnFX8dSC213uNFc9YyXk%3D&reserved=0>,

Thanks for the heads up - looks like we haven't updated ABySS in homebrew yet. We'll do that upstream and let you know when it's finished!

**Comment by lcoombe** [comment]
Hi @desmodus1984,

Conda actually updates the packages automatically using a bot, so the update should be happening automatically in the next day or two -- but I'll keep an eye on it to make sure that PR gets opened!

**Comment by desmodus1984** [comment]
Hi Lauren,

That's awesome. I will run the update during the weekend and test it then.

I wanted to ask you a question.

As I mentioned I have Nanopore data, error corrected, plus a library of PE-100 reads. I was confused how to parameterize the PE library. I used lib="" but I read that it is also mentioned using in= and pe=.

I want to make sure that I use the proper parameters and not waste CPU hours.

Thanks.

Get BlueMail for Android<http://www.bluemail.me/r?b=16696>
On Apr 22, 2021, at 11:42 AM, Lauren Coombe ***@***.******@***.***>> wrote:

Hi @desmodus1984<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdesmodus1984&data=04%7C01%7Cja569116%40ohio.edu%7C407fd4bad76a4bae37aa08d905a54441%7Cf3308007477c4a70888934611817c55a%7C0%7C0%7C637547029634796357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LHW58UBbYYSYpRkgtnpQrlbp5vHsxQsVNZkadAuW0T8%3D&reserved=0>,

Conda actually updates the packages automatically using a bot, so the update should be happening automatically in the next day or two -- but I'll keep an eye on it to make sure that PR gets opened!

**Comment by lcoombe** [comment]
Hi @desmodus1984,

You can either use `lib=` as demonstrated here: https://github.com/bcgsc/abyss/#assembling-multiple-libraries 
Or using `in` is fine too: https://github.com/bcgsc/abyss/#assembling-a-paired-end-library

If you have multiple libraries, then using the `lib` approach is the way to go, but if you just have one paired-end library than either should work just fine.

BTW - conda hasn't triggered a PR for our ABySS release yet, but I'm keeping an eye on it!
