### ISSUE TITLE
Choosing appropriate `B` to minimize memory-usage

### ISSUE THREAD

**Issue by jamshed** [bcgsc/abyss#372]
Hello ABySS team,

Thanks for the excellent tool-set!  We (cc: @rob-p) intend to benchmark `abyss_bloom_dbg` for one of our lab tasks, and have some queries on which your input would be valuable.

The current GitHub README says the following regarding the choice of the parameters `kc`, `B`, and `H`:
> At the current time, the user must calculate suitable values for B and H on their own, and finding the best value for kc may require experimentation (optimal values are typically in the range of 2-4). Internally, the Bloom filter assembler allocates the entire memory budget (B * 8/9) to a Counting Bloom filter, and an additional (B/9) memory to another Bloom filter that is used to track k-mers that have previously been included in contigs. Users are recommended to target a Bloom filter false positive rate (FPR) that is less than 5%, as reported by the assembly log when using the v=-v option (verbose level 1).

How might we set a good enough `B` value that ensures a <5% FPR for the counting bloom filter and the plain bloom filter, simultaneously? Assume that for the benchmarks, we have estimates on the number of all distinct k-mers in the reads set, and also the number of solid k-mers (for some appropriately chosen count threshold `kc`). As per these, do you have any suggestions on how to choose `B` and `H`, **given that** we intend to minimize the memory-usage in the benchmarks?

We had a little chat with Shaun on the issue, so I'm also tagging @sjackman. In fact, Shaun suggested to use `H = 4`.

Thanks!

**Comment by sjackman** [comment]
I said `H=3` actually, but I said that only because https://github.com/bcgsc/abyss#assembling-using-a-bloom-filter-de-bruijn-graph mentions `H=3`. I'm sure there's a better answer.

FWIW here's the formula for choosing the optimal (minimal FPR) number of hash functions for a non-counting Bloom filter: https://en.wikipedia.org/wiki/Bloom_filter#Optimal_number_of_hash_functions

Note that increasing the number of hash functions should also increase compute run time, so there's a trade off there between memory usage, run time, and FPR in setting `B` and `H`.

**Comment by jamshed** [comment]
Hi @sjackman, thanks for the correction—I noted it incorrectly.

As you mention the formula for a (non-counting) Bloom filter—yes, suitable `B` and `H` could be calculated targeting a desired FPR, given that we have estimates on the number of solid k-mers `n`. For the counting variant however, I couldn't find a straightforward way to estimate `B` and `H` from the [FPR eqn.](https://en.wikipedia.org/wiki/Counting_Bloom_filter#Probability_of_false_positives).

**Comment by schutzekatze** [comment]
What genome are you assembling and what's the coverage? We generally use a heuristic for the memory budget.

**Comment by jamshed** [comment]
Hi @schutzekatze: for now, we'd like to test it for a human genome, e.g. on the NIST HG004 human dataset (SRR3440461-95, 70X Illumina short-reads) that's been used in the ABySS 2.0 paper.

**Comment by jamshed** [comment]
Hi @schutzekatze: based on your replies at #374, will `B=40G` and `H=3` be a good choice for this dataset?

Thanks!

**Comment by schutzekatze** [comment]
Hi @jamshed,

Sorry for slow response! `H=3` is good, but if you have sufficient memory, I'd probably increase `B` to e.g. `B=60G`.

**Comment by jamshed** [comment]
Hi @schutzekatze,

Thank you for your reply! Is there some rough heuristic policy that you follow to set the Bloom filter size as per the dataset-coverage?

We'd also like to inquire, should ABySS (at least its very first contigs-assembly step, i.e. `abyss-bloom-dbg`) be applicable for metagenomes, e.g. human gut microbiome or soil?

**Comment by schutzekatze** [comment]
There have been some changes to the counting Bloom filter implementation recently which somewhat affect the false positive rate and so right now I generally use a rough approximation. We commonly use 40G Bloom filter size for human assemblies for coverages around 40X and so given your coverage, I'd simply give the Bloom filter a bit more room for the extra coverage. There's no downside in giving the Bloom filter more memory if you can afford it, although you simply won't see any benefit past a certain size.

As for metagenomes, ABySS isn't exactly optimized for it. It is possible to run a metagenome assembly but we don't have a good sense of the results that you'd get.

**Comment by jamshed** [comment]
Thanks @schutzekatze for the information!
