### ISSUE TITLE
Assembly runtime error--> make: *** [/path/abyss-pe.Makefile:552: 75.fa] Error 1

### ISSUE THREAD

**Issue by hchetia** [bcgsc/abyss#374]
Hi, 
I am running an assembly for hg38 (using k=96)  and facing the same error as #369; i.e., make: *** [/path/abyss-pe.Makefile:552: 75.fa] Error 1
abyss-pe version 2.3.1
CentOS Linux release 7.9.2009 (Core) 
Cmd: abyss-pe np=2 name=75 k=96 in='75_R1.fq 75S1_R2.fq' 2>&1 | tee 7_log.txt
Fastq size - ~131G

With respect to the suggestion in #369, I have no idea how to calculate the appropriate bloom filter parameter values for my assembly. Are there any default values for hg38 similar to the values you provide for E.coli in your example?

My memory budget is shown below-
![image](https://user-images.githubusercontent.com/64626735/127531217-9d3960ec-1e80-4537-a8c8-a0a34a3c2aa9.png)
I will be able to the no. of bases by evening, but was hoping the file size would sorta provide an idea about it.

Related question- How high does the swap memory need to be for an ideal hg38 assembly with 30-40X coverage?

Thanks for your help.
Best,
Hasna

**Comment by schutzekatze** [comment]
A general heuristic we use is about a 40GiB size Bloom filter for H. sapiens assemblies, which you would specify as `-B40G`. When running in this mode, you don't need the `np` parameter, but should instead specify the `-j` parameter which is the number of threads. To finish in a reasonable time, I'd recommend something like -`j48` assuming your machine has that many CPU cores.

**Comment by hchetia** [comment]
Thanks. Other than -B40G -j48, Should I keep other params the same as shown in your manual? 
B=100M H=3 kc=3 v=-v

**Comment by schutzekatze** [comment]
`H=3` is fine, but I'd recommend setting `kc=2`. This specifies the minimum multiplicity of kmers in order to use them for assembly. Generally a value of 2 works well, although 3 might filter out some errors. Given your somewhat low coverage, I'd expect 3 to be too high, and so I'd go with 2.

**Comment by hchetia** [comment]
Will update issue when the run completes or fails.

**Comment by hchetia** [comment]
Run completed successfully. Thanks @schutzekatze

**Comment by hchetia** [comment]
Hi
I performed assembly using both kc=2 and kc=3. Using kc2, I got only one assembly.fa; while using kc3, I got 8 fastas. Do I need to concatenate those 8 fastas to get one comprehensive de novo genome assembly?

**Comment by schutzekatze** [comment]
You should be seeing an `*-scaffolds.fa` file, where * is the name of the assembly. This is the output of the final stage.

**Comment by hchetia** [comment]
Thanks.
