### ISSUE TITLE
abyss-fatoagp error when using the Biocontainers Docker build (from Conda)

### ISSUE THREAD

**Issue by oneillkza** [bcgsc/abyss#382]
# Please report

- [ abyss_2.3.3 ] version of ABySS with `abyss-pe version`
- [ lsb_release doesn't seem to be in it, but whatever the base is for Biocontainers  ] distribution of Linux with `lsb_release -d`

# Build error

Consider installing ABySS using [Homebrew](https://brew.sh) on either Linux or macOS with `brew install abyss`, or using [Bioconda](https://bioconda.github.io) with `conda install abyss`.

- [ Essentially yes ] Have you tried installing ABySS using Brew or Bioconda?
- [ THis is a PERL error ] version of GCC or compiler with `gcc --version`
- [ THis is a PERL error ] complete `./configure` command line
- [ THis is a PERL error ] last 20 lines of the output of `./configure`
- [ THis is a PERL error ] last 20 lines of the output of `make`

```
singularity exec -B /projects /projects/CanSeq/containers/abyss_2.3.3--hd403d74_0.sif abyss-fatoagp
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_CA.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't locate Getopt/Std.pm in @INC (you may need to install the Getopt::Std module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/abyss-fatoagp line 7.
BEGIN failed--compilation aborted at /usr/local/bin/abyss-fatoagp line 7.

```

**Comment by vlad0x00** [comment]
Hi Kieran,

It looks like your perl installation is missing the Getopt::Std module. Running `perl -MCPAN -e 'install Getopt::Std'` should solve it.

**Comment by oneillkza** [comment]
Thanks @vlad0x00 .

My "installation" is actually the Biocontainers docker container, which uses the official Conda environment for abyss. 

ie this:

https://quay.io/repository/biocontainers/abyss?tab=tags

Which builds from this:

https://anaconda.org/bioconda/abyss

Specifically from the recipe here:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/abyss/meta.yaml

Which I believe your group maintains. It probably needs `perl-getopt-long` added to the list of requirements in the yaml.

**Comment by vlad0x00** [comment]
I see. `perl-getopt-long` provides `Getopt::Long` which seems to be a different module from `Getopt::Std`. I just installed perl in a clean conda environment and it includes the `Getopt::Std` module by default. Since the yaml file doesn't have perl as a requirement at all, adding it should solve the problem. I'll update the conda abyss recipe.

**Comment by oneillkza** [comment]
Thanks so much @vlad0x00 ! 

I'll likely be including this in a workflow, so it'll be great to have a working container for it!

**Comment by vlad0x00** [comment]
The container has been updated on quay. I just tested the latest one (abyss:2.3.3--hd403d74_1) and it gives me no error on abyss-fatoagp. Let me know if you still see the issue.

**Comment by oneillkza** [comment]
Yep, seems to be working so far! Thanks so much!
