### ISSUE TITLE
Abyss version update

### ISSUE THREAD

**Issue by mesamuels** [bcgsc/abyss#446]
Vlad, I'm putting this in a new issue as things are otherwise going well. My first assembly ran very efficiently, just under 9 hours, now it's time to play with parameters. However, you suggested using a newer version of Abyss, 2.3.4, whereas CC apparently is only up to 2.2.5. Is there any chance you could update the version on the CC system, so it's available to everyone? I could learn how to install new software, but it's another big learning curve for me, presumably you know how to do it. That would be great if possible, I understand if it's not.

I did not realize that the other guy, Martin, is not in Vancouver but elsewhere in the world, it's not obvious just reading your comments here. You probably stopped reading that thread since it's been back and forth with just him. He suggested I try scaffolding with quinoa transcript sequences from NCBI, which I did but I'm not sure how to interpret the output yet. That extra step ran in less than 30 minutes anyway.

Thanks!
Mark

**Comment by jowong4** [comment]
We do not have the authority/permission to update the version of software on Compute Canada national systems. You have two options if you want to use new version of ABySS: 1. You can email support@computecanada.ca and ask them to update the software, or 2, install ABySS into your home directory (https://docs.computecanada.ca/wiki/Installing_software_in_your_home_directory). We highly recommend you use tools you install in your home directory as the Compute Canada staff can update the tools in the global directory and you may not get the same results between different run. It is also to your benefit to learn how to install software in your home directory as soon as possible. That way you have control over what version of programs to run and you are not at the mercy of how busy the support staff is at Compute Canada. The easiest way to install ABySS is to follow the instructions in https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html. and after doing that type `conda install -c bioconda abyss` into your terminal.

**Comment by mesamuels** [comment]
Thanks very much for the explanation Johnathan, it's all new to me so not sure what is allowed to whom in the whole Compute Canada ecosystem. I will do as you suggest. In your experience is the newer version significantly improved? My data are fairly limiting, having only paired-end short reads and no mate-pair or long read libraries, so the newer version may not be able to do much else with it. Still worth learning how to install software myself, just a question of how urgent it is for the present analysis.

Regards,
Mark

**Comment by vlad0x00** [comment]
The latest version has improvements in the initial stages of the assembly, so even without mate pairs or long reads, the assemblies will be somewhat improved. However, it's not something that is super important, so if updating is too much of a hassle at this time, sticking to 2.2.5 is alright.

Regarding the stats you got in your last assembly (NG50 contiguity in particular), I'd suggest playing around (likely lowering) the `k` parameter, as that can influence contiguity greatly.

**Comment by mesamuels** [comment]
Thanks Vlad. It's a bit counterintuitive, why would using smaller k-mers improve the assembly? I'd worry that it would encourage mis-alignment of reads from the different subgenomes, which are probably almost identical below a 100bp size range. But I can try it. For now I'm running with the input only trimmed for adapters and polyGs, using a k-mer of 96.

Mark
