### ISSUE TITLE
Highly Fragmented Assembly

### ISSUE THREAD

**Issue by BenParkerLab** [bcgsc/abyss#451]
I have 24.7 gigabase pairs of Illumina PE150 sequencing for de novo assembly of a non-model fungal species. When using a k-mer in the recommended range I see just over 50% of reads not aligning and an extremely small n50 (150-250 bp). I have run assemblies using a range of k-mers from 20 to 140, none of which produce a convincing assembly. When the k-mer value increases, I get an increased N50 at the cost of reads aligning to the assembly. I am currently using a 48 core compute node with 190Gb memory, but can request up to 2Tb memory if required. I plan to use Longstitch with 10 gigabase pairs of Nanopore sequencing to improve the abyss assembly once I have real scaffolds. 

I have attempted assemblies using Abyss, Wengan, HASLR, Canu, and Flye. The consensus assembly size is around 20Mb, with the caveat all assemblies failing Busco analysis. I do not have the capability of using estimating size with flow cytometry. 

I am running abyss-pe (ABySS) 2.3.4 via Conda. On a linux cluster running Red Hat Enterprise Linux release 8.5 (Ootpa). 

I am using a high bloom filter here because of the memory overhead and possibility of 1000X coverage if the previous assemblies are close to the actual genome size. We assume the vast majority of reads come from haploid tissue. 

Any advice or direction would be greatly appreciated. 

Batch job submission script
'''
#!/bin/bash
#SBATCH -J abyss_70
#SBATCH --account ACF-UTK0011
#SBATCH --time 1-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --ntasks-per-node=48
#SBATCH --partition=campus
#SBATCH --output=abyss_70.o%j
#SBATCH --error=abyss_70.e%j
#SBATCH --exclusive
#SBATCH --qos=campus

set -x

eval "$(conda shell.bash hook)"

conda activate abyss

abyss-pe name=pandora_70 j=48 k=70 kc=3 B=100G in='/lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/Pand_1.fastq /lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/Pand_2.fastq'
'''

Output from abyss-pe run
'''
The minimum number of pairs in a distance estimate is 10.
The minimum number of pairs used in a path is 10.
abyss-index  --fai pandora_70-3.fa
abyss-index  --fai pandora_70-4.fa
cat pandora_70-3.fa.fai pandora_70-4.fa.fai \
        | MergePaths   -j48 -k70 -s1000  -o pandora_70-4.path2 - pandora_70-4.path1
Ignored 0 paths whose seeds are shorter than 1000 bp.
PathOverlap --assemble   -k70  pandora_70-4.dot pandora_70-4.path2 >pandora_70-4.path3
cat pandora_70-3.fa pandora_70-4.fa \
        | abyss-stack-size 65536 PathConsensus  --dot -k70  -p0.9  -o pandora_70-5.path -s pandora_70-5.fa -g pandora_70-5.dot - pandora_70-4.dot pandora_70-4.path3
cat pandora_70-3.fa pandora_70-4.fa pandora_70-5.fa | MergeContigs   -k70 -o pandora_70-6.fa - pandora_70-5.dot pandora_70-5.path
ln -sf pandora_70-6.fa pandora_70-contigs.fa
PathOverlap --overlap   -k70 --dot pandora_70-5.dot pandora_70-5.path >pandora_70-6.dot
ln -sf pandora_70-6.dot pandora_70-contigs.dot
abyss-map   -j48 -l40    /lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/Pand_1.fastq /lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/Pand_2.fastq pandora_70-6.fa \
        |abyss-fixmate   -l40  -h pandora_70-6.hist \
        |sort -snk3 -k4 \
        |DistanceEst   --dot --median -j48 -k70  -l40 -s1000 -n10  -o pandora_70-6.dist.dot pandora_70-6.hist
abyss-scaffold    -k70 -s100-5000 -n15-20 -g pandora_70-6.path.dot  pandora_70-6.dot pandora_70-6.dist.dot >pandora_70-6.path
abyss-stack-size 65536 PathConsensus  --dot -k70  -p0.9  -s pandora_70-7.fa -g pandora_70-7.dot -o pandora_70-7.path pandora_70-6.fa pandora_70-6.dot pandora_70-6.path
cat pandora_70-6.fa pandora_70-7.fa \
        | MergeContigs   -k70 -o pandora_70-8.fa - pandora_70-7.dot pandora_70-7.path
ln -sf pandora_70-8.fa pandora_70-scaffolds.fa
PathOverlap --overlap   -k70 --dot pandora_70-7.dot pandora_70-7.path >pandora_70-8.dot
ln -sf pandora_70-8.dot pandora_70-scaffolds.dot
abyss-fac   pandora_70-unitigs.fa pandora_70-contigs.fa pandora_70-scaffolds.fa |tee pandora_70-stats.tab
n       n:500   L50     min     N75     N50     N25     E-size  max     sum     name
3042820 36021   15514   500     532     579     668     686     12816   21.95e6 pandora_70-unitigs.fa
3042705 35981   15480   500     532     579     668     698     12816   21.97e6 pandora_70-contigs.fa
3042541 35927   15426   500     532     579     669     790     26464   21.98e6 pandora_70-scaffolds.fa
ln -sf pandora_70-stats.tab pandora_70-stats
tr '\t' , <pandora_70-stats.tab >pandora_70-stats.csv
abyss-tabtomd pandora_70-stats.tab >pandora_70-stats.md
'''

output of 'cat abyss_70.e68685'

'''
Running with max stack size of 65536 KB: abyss-bloom-dbg -k70 -q3 --kc=3 -b100G -j48 /lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/Pand_1.fastq /lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/Pand_2.fastq
The minimum coverage of single-end contigs is 2.41429.
The minimum coverage of merged contigs is 3.
Consider increasing the coverage threshold parameter, c, to 3.
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Mateless          0
Unaligned  43756580  53.1%
Singleton  12641442  15.4%
FR         12380280  15%
RF               41  4.98e-05%
FF              204  0.000248%
Different  13573270  16.5%
Total      82351817
time user=48184.76s system=179.92s elapsed=1211.28s cpu=3992% memory=8730 job=abyss-map -j48 -l40   pandora_70-3.fa
time user=491.60s system=15.07s elapsed=1211.28s cpu=41% memory=3 job=abyss-fixmate -l40 -h pandora_70-3.hist
time user=253.38s system=10.63s elapsed=1464.28s cpu=18% memory=15 job=sort -snk3 -k4
time user=6277.29s system=3.54s elapsed=1464.66s cpu=428% memory=358 job=
Running with max stack size of 65536 KB: SimpleGraph -s1000 -n10 -j48 -k70 -o pandora_70-4.path1 pandora_70-4.dot pandora_70-3.dist
Reading `pandora_70-3.fa'...
Writing `pandora_70-3.fa.fai'...
Reading `pandora_70-4.fa'...
Writing `pandora_70-4.fa.fai'...
n	n:1000	L50	min	N75	N50	N25	E-size	max	sum	name
3042705	516	152	1000	1194	1644	2717	2713	12747	886587	pandora_70-4.path2
Running with max stack size of 65536 KB: PathConsensus --dot -k70 -p0.9 -o pandora_70-5.path -s pandora_70-5.fa -g pandora_70-5.dot - pandora_70-4.dot pandora_70-4.path3
Ambiguous paths: 8
Merged:          0
No paths:        0
Too many paths:  0
Too complex:     0
Dissimilar:      8
The minimum coverage of single-end contigs is 2.41429.
The minimum coverage of merged contigs is 5.47674.
Consider increasing the coverage threshold parameter, c, to 5.47674.
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
Mateless          0
Unaligned  43756580  53.1%
Singleton  12641442  15.4%
FR         12388138  15%
RF               66  8.01e-05%
FF              204  0.000248%
Different  13565387  16.5%
Total      82351817
time user=47944.24s system=183.47s elapsed=1205.95s cpu=3990% memory=8729 job=abyss-map -j48 -l40   pandora_70-6.fa
time user=492.10s system=15.08s elapsed=1205.95s cpu=42% memory=3 job=abyss-fixmate -l40 -h pandora_70-6.hist
time user=253.55s system=11.05s elapsed=1458.83s cpu=18% memory=16 job=sort -snk3 -k4
time user=6265.57s system=3.31s elapsed=1459.21s cpu=429% memory=359 job=
warning: Removed 14 invalid edges.
n	n:100	L50	min	N75	N50	N25	E-size	max	sum	name
3042559	2686906	1029099	100	194	228	296	265	26342	619.7e6	n=15 s=100
3042631	2686978	1029098	100	194	228	296	265	26022	619.7e6	n=15 s=200
3042653	2687000	1029117	100	194	228	296	264	25684	619.7e6	n=15 s=500
3042677	2687024	1029141	100	194	228	296	263	20412	619.7e6	n=15 s=1000
3042691	2687038	1029155	100	194	228	296	262	16934	619.7e6	n=15 s=2000
3042705	2687052	1029169	100	194	228	296	262	12816	619.7e6	n=15 s=5000
3042560	2686907	1029099	100	194	228	296	265	26342	619.7e6	n=16 s=100
3042631	2686978	1029098	100	194	228	296	265	26022	619.7e6	n=16 s=200
3042653	2687000	1029117	100	194	228	296	264	25684	619.7e6	n=16 s=500
3042677	2687024	1029141	100	194	228	296	263	20412	619.7e6	n=16 s=1000
3042691	2687038	1029155	100	194	228	296	262	16934	619.7e6	n=16 s=2000
3042705	2687052	1029169	100	194	228	296	262	12816	619.7e6	n=16 s=5000
3042565	2686912	1029104	100	194	228	296	265	26342	619.7e6	n=17 s=100
3042636	2686983	1029103	100	194	228	296	265	26022	619.7e6	n=17 s=200
3042655	2687002	1029119	100	194	228	296	264	25684	619.7e6	n=17 s=500
3042677	2687024	1029141	100	194	228	296	263	20412	619.7e6	n=17 s=1000
3042691	2687038	1029155	100	194	228	296	262	16934	619.7e6	n=17 s=2000
3042705	2687052	1029169	100	194	228	296	262	12816	619.7e6	n=17 s=5000
3042569	2686916	1029105	100	194	228	296	265	26342	619.7e6	n=18 s=100
3042639	2686986	1029105	100	194	228	296	265	26022	619.7e6	n=18 s=200
3042657	2687004	1029121	100	194	228	296	264	25684	619.7e6	n=18 s=500
3042678	2687025	1029142	100	194	228	296	263	20412	619.7e6	n=18 s=1000
3042691	2687038	1029155	100	194	228	296	262	16934	619.7e6	n=18 s=2000
3042705	2687052	1029169	100	194	228	296	262	12816	619.7e6	n=18 s=5000
3042570	2686917	1029106	100	194	228	296	265	26346	619.7e6	n=19 s=100
3042640	2686987	1029106	100	194	228	296	265	26022	619.7e6	n=19 s=200
3042658	2687005	1029122	100	194	228	296	264	25684	619.7e6	n=19 s=500
3042679	2687026	1029143	100	194	228	296	263	20412	619.7e6	n=19 s=1000
3042691	2687038	1029155	100	194	228	296	262	16934	619.7e6	n=19 s=2000
3042705	2687052	1029169	100	194	228	296	262	12816	619.7e6	n=19 s=5000
3042572	2686919	1029108	100	194	228	296	265	26346	619.7e6	n=20 s=100
3042642	2686989	1029108	100	194	228	296	265	26022	619.7e6	n=20 s=200
3042659	2687006	1029123	100	194	228	296	264	25684	619.7e6	n=20 s=500
3042679	2687026	1029143	100	194	228	296	263	20412	619.7e6	n=20 s=1000
3042691	2687038	1029155	100	194	228	296	262	16934	619.7e6	n=20 s=2000
3042705	2687052	1029169	100	194	228	296	262	12816	619.7e6	n=20 s=5000

Best scaffold N50 is 228 at n=15 s=100.

n	n:100	L50	min	N75	N50	N25	E-size	max	sum	name
3042559	2686906	1029099	100	194	228	296	265	26342	619.7e6	n=15 s=100
Running with max stack size of 65536 KB: PathConsensus --dot -k70 -p0.9 -s pandora_70-7.fa -g pandora_70-7.dot -o pandora_70-7.path pandora_70-6.fa pandora_70-6.dot pandora_70-6.path
Ambiguous paths: 41
Merged:          11
No paths:        2
Too many paths:  1
Too complex:     0
Dissimilar:      27
The minimum coverage of single-end contigs is 2.41429.
The minimum coverage of merged contigs is 6.71429.
Consider increasing the coverage threshold parameter, c, to 6.71429.
time user=8.17s system=1.89s elapsed=10.08s cpu=99% memory=3 job=abyss-fac pandora_70-unitigs.fa pandora_70-contigs.fa pandora_70-scaffolds.fa
time user=0.00s system=0.00s elapsed=10.07s cpu=0% memory=1 job=
'''

**Comment by vlad0x00** [comment]
Hi!

Given your high coverage, one thing you could try is increasing the `kc` parameter value. For finding the right `kc` value, pick a `k` value that works okay right now and then start increasing `kc` with a step of 1. So try `kc=4`, `kc=5`, `kc=6` and see if there's a trend of better assembly contiguity.

Your Bloom filter size looks fine given how much data you have, but it's not a bad idea to check the Bloom false positive rate to be sure. Is there a line in your log saying something similar to:
```
Bloom filter FPR: ...%
Counting Bloom filter stats:
# #counters = ...
# #size (B) = ...
# threshold = ...
# popcount = ...
# FPR = ...%
```
We'd want to see the last line, `# FPR = ...%` with 5% or less.

> When using a k-mer in the recommended range I see just over 50% of reads not aligning
Did you mean scaffolds (assembler output) are not aligning here?
