### ISSUE TITLE
'make check' fails: error: use of undeclared identifier 'EXPECT_DEATH'

### ISSUE THREAD

**Issue by yurivict** [bcgsc/abyss#453]
```
Common/SAM.cc:65:2: error: use of undeclared identifier 'EXPECT_DEATH'
        EXPECT_DEATH(SAMAlignment::parseCigar("20SS", false), "error: invalid CIGAR: `20SS'");
        ^
Common/SAM.cc:66:2: error: use of undeclared identifier 'EXPECT_DEATH'
        EXPECT_DEATH(SAMAlignment::parseCigar("20m", false), "error: invalid CIGAR: `20m'");
        ^
```

Version: 2.3.5
FreeBSD 13.1

**Comment by yurivict** [comment]
@lcoombe 

Tests still fail to compile.
Do you know how to fix them?

**Comment by lcoombe** [comment]
Hi @yurivict,

Could you provide us with updated information? (ie. release used, install method, commands, OS, etc)

Thanks!
Lauren

**Comment by yurivict** [comment]
Version: 2.3.8
Install method:
./autogen.sh
./configure
gmake
gmake check

**Comment by lcoombe** [comment]
And your full log from the command that causes the issues, please? And OS is still FreeBSD 13.1? 
The more info we have, the better we'll be able to help, as we do not use FreeBSD or have access to that OS.

**Comment by yurivict** [comment]
OS is FreeBSD 14.1
The current log is [here](https://freebsd.org/~yuri/abyss-2.3.8-build-test.log).

**Comment by lcoombe** [comment]
Can you confirm that ABySS works as expected after you install and run on some sample data? In other words, are you only seeing the issue in this `make check` gtest part, or is your installation itself also non-functional?
