### ISSUE TITLE
no abyss-pe.Makefile acess denied

### ISSUE THREAD

**Issue by Sabrin2020** [bcgsc/abyss#455]
**error after running my data with abyss-pe using slurm script, test data works fine**

**- [ ] version of ABySS with `abyss-pe version`**
abyss-pe (ABySS) 2.3.5

**- [ ] distribution of Linux with `lsb_release -d`**
(abyss) [asga9989@hpcl001 trim]$ lsb_release -d
Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)

# Assembly error      

Loaded 3030000 reads into Bloom filter
Loaded 3040000 reads into Bloom filter
**Loaded 3044782 reads from `trim800.2u.fastq` into Bloom filter
Bloom filter FPR: 0.000542%
Counting Bloom filter stats:
        #counters               = 238609294272
        #size (B)               = 238609294272
        threshold               = 2
        popcount                = 3562650019
        FPR                     = 4.97e-06%
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
bash: line 1:  5165 Aborted**                 **abyss-stack-size 65536 abyss-bloom-dbg** -k90 -q3 -v -b250G -j24 trim300_1.1p.fastq trim300_1.2p.fastq trim300_2.1p.fastq trim300_2.2p.fastq trim500.1p.fastq trim500.2p.fastq trim800.1p.fastq trim800.2p.fastq trim300_1.1u.fastq trim300_1.2u.fastq trim300_2.1u.fastq trim300_2.2u.fastq trim500.1u.fastq trim500.2u.fastq trim800.1u.fastq trim800.2u.fastq > Hypoplectrus-1.fa
make: *** [Hypoplectrus-1.fa] Error 134

- [ ] complete `abyss-pe` command line
abyss-pe k=90 name=Hypoplectrus  B=250G v=-v j=24 lib='lib1 lib2 lib3 lib4' \
            lib1='trim300_1.1p.fastq trim300_1.2p.fastq' lib2='trim300_2.1p.fastq trim300_2.2p.fastq' lib3='trim500.1p.fastq trim500.2p.fastq' lib4='trim800.1p.fastq trim800.2p.fastq' \
            se='trim300_1.1u.fastq trim300_1.2u.fastq trim300_2.1u.fastq trim300_2.2u.fastq trim500.1u.fastq trim500.2u.fastq trim800.1u.fastq trim800.2u.fastq'

**Comment by lcoombe** [comment]
Hi Sabrin,

I also responded to your google issue, but thank you for including more information here. We do monitor both methods of communication, but issues via github (only) is preferable.
You are using a rather old ABySS version - I'd first suggest updating your installation to the most recent release. In addition, I recommend testing your installation with our small test: https://github.com/bcgsc/abyss#assemble-a-small-synthetic-data-set

Hope that helps - thank you for your interest in ABySS!
Lauren

**Comment by Sabrin2020** [comment]
Thank you so much for your quick response. 

I do not know why everytime I try to get the latest version conda end it up with same old version of abyss.!!

I figured out that there was a problem with my path which once fixed made the error message shorter but I still get this error message.  
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/59876705/189053995-869b0f9d-40cd-4de7-b1e1-ebd3238a3dd2.png">

What does this means 
make: *** [/user/asga9989/.conda/envs/abyss-env/bin/**abyss-pe.Makefile:488**: Hypoplectrus-1.fa] **Error 134**
make: *** Deleting file 'Hypoplectrus-1.fa'

the test data run successfully!!

**Comment by Sabrin2020** [comment]
Okay now when i try to run test data again i get almost same error message
which: no abyss-pe.Makefile in (/user/asga9989/.conda/envs/abyss-env/bin)
dirname: missing operand
Try 'dirname --help' for more information.
abyss-pe: missing parameter `lib`, `in` or `se`
Try `abyss-pe help` for more information.
make: *** [/user/asga9989/.conda/envs/abyss-env/bin/abyss-pe.Makefile:335: error] Error 1

**Comment by lcoombe** [comment]
Hello @Sabrin2020,

So to be clear, the test data ran OK the first time, but not the second? Had you made any adjustments to your conda environment (installed any other tools, deactivated it, adjusted your path again, etc.)? What exact command did you run each time?

On our end, we can best help you troubleshoot if we have the full information (command used, full log, ABySS version, etc)

**Comment by Sabrin2020** [comment]
test data works after server admins installed latest version of abyss.

**Comment by lcoombe** [comment]
Great, glad to hear that the test data is working for you now! 

It looks like you've edited your original comment with an updated log. How much memory do you have on the machine that you're running ABySS on? That error often comes up if ABySS runs out of memory. 

Just as a note - please do avoid editing previous comments to remove what you said or substantially change the content. It's helpful for other users to see how you encountered and resolved the problems.
