### ISSUE TITLE
Abyss 2.3.5 conda installed: pipeline stops at abyss-rresolver-short

### ISSUE THREAD

**Issue by MolZoo** [bcgsc/abyss#456]
I am running abyss on 5 nodes np=5, 128G per node, j=140, k=80, B=80G or B=100G on an eukaryotic (ca.2.8G size) data set (60fold) on HPC with container storage. The data set contains 17 paired-end samples. The sampling is working perfect and fast with B=80G or 100G. $NAME-1.dot and $NAME-1.fa is saved in container (13.10GB 17.79GB). 

Abyss-pe command line:
#!/bin/bash 
eval "$(conda shell.bash hook)"
conda activate abyss-env
dirData=/dss/dssfs02/lwp-dss-0001/pr45wo/pr45wo-dss-0000/rawData_myodes
export TMPDIR=/dss/lxclscratch/0D/gi23huc2/tmp
abyss-pe -C /dss/dssfs02/lwp-dss-0001/pr45wo/pr45wo-dss-0000/abyss_myodes_all_case/k80inlg name=CASEinlg B=80G j=140 np=5 k=80 v=-v in="$dirData/308Ham_S33_R1_ptrimmed.fastq.gz $dirData/308Ham_S33_R2_ptrimmed.fastq.gz …" contigs scaffolds 2>&1 | tee abyss.log

However the following error appears: (end of log file)
.......
 abyss-rresolver-short -v -b80G -f0.8 -j140 -k80 \
 -h CASEinlg-1-rr --dot -c CASEinlg-1-rr.fa \
-g CASEinlg-1-rr.dot CASEinlg-1.fa CASEinlg-1.dot /dss/dssfs02/lwp-dss-0001/pr45wo/pr45wo-dss-0000/rawData_myodes/308Ham_S33_R1_ptrimmed.fastq.gz ….
Loading contig graph from `CASEinlg-1.dot'...
Contig graph loaded.
V=177119334 E=300755048 E/V=1.7
Degree:  █▄
        01234
0: 1.4% 1: 64% 2-4: 35% 5+: 0.032% max: 5464
Loading contigs from `CASEinlg-1.fa'...
Contigs loaded.
Determining read stats...
[2022-09-23 20:43:11] [31m[ERROR] [0mProcess pipeline: opening comm pipe failed: No such file or directory
[2022-09-23 20:43:11] [31m[ERROR] [0mProcess pipeline: Communication failure.
[2022-09-23 20:43:12] [31m[ERROR] [0mProcess pipeline: Spawner process failed.
make: *** [/dss/dsshome1/lxc0D/gi23huc2/.conda/envs/abyss-env/bin/abyss-pe.Makefile:585: CASEinlg-1-rr.dot] Segmentation fault (core dumped).

**Comment by vlad0x00** [comment]
Could be a filesystem issue. Can you run `df -T` and post the values from the `Type` column here of root dirs for `/dss/lxclscratch/0D/gi23huc2/tmp` and `/dss/dssfs02/lwp-dss-0001/pr45wo/pr45wo-dss-0000/abyss_myodes_all_case/k80inlg`.
@lcoombe and @jowong4 , this might also simply be happening because of outdated btllib packaged with RResolver. Removing it from there and instead adding it as a dependency would not be a bad idea.

**Comment by MolZoo** [comment]
Here the info
lxclscratch              gpfs      3379902808064   48488906752  3331413901312    2% /dss/lxclscratch
dssfs02                  gpfs     12154870693888 6404482121728  5750388572160   53% /dss/dssfs02
I will also add btllib as a dependency

**Comment by vlad0x00** [comment]
Hm, that filesystem might not support pipes. I've released a new version of btllib (1.4.9) that will reduce the chance of that being an issue, but btllib in ABySS would need to be updated. Just adding it as a dependency wouldn't work because ABySS needs to be told to use it. @lcoombe or @jowong4 might be able to help you with that.

**Comment by MolZoo** [comment]
Hi @lcoombe and @jowong
please could you support me with some information about how to add btllib (1.4.9) in abyss 2.3.5 (conda installed)
Thank you. Best Ralph

**Comment by lcoombe** [comment]
Hi @MolZoo,
We'll work on updating btllib in ABySS in the coming days - we'll keep you updated!

**Comment by vlad0x00** [comment]
@MolZoo That wouldn't cause this error, but you're right that the two shouldn't be used together. The recommended usage is just to specify the `-B` parameter; `np` should be removed.

**Comment by lcoombe** [comment]
Thanks @vlad0x00!

And @MolZoo - sorry for the delay, but @jowong4 is planning to update btllib in ABySS in the next week.

**Comment by lcoombe** [comment]
We're still working on the btllib update fix - thanks for your patience!

**Comment by lcoombe** [comment]
@jwcodee Any updates on the next ABySS release?
