### ISSUE TITLE
run in conda 

### ISSUE THREAD

**Issue by deyuanyang** [bcgsc/abyss#462]
Hi，

I use conda install abyss， It occurs an error when I run it in  abyss environment.  How to solve it?

(abyss) [yanjie@localhost A3389]$ abyss-pe name= A3389_abyss k=96  B=100G in='A3389_1.clean.fq.gz A3389_2.clean.fq.gz'
/home/yanjie/miniconda3/envs/abyss/bin/abyss-pe.Makefile:151: *** empty variable name.  Stop.

**Comment by lcoombe** [comment]
Hi @deyuanyang,

It looks like you have an extra space in your command between `name=` and `A3389_abyss` - I think this is probably what's causing the issue. Try deleting that space and launching the command again.

Thank you for your interest in ABySS!
Lauren

**Comment by deyuanyang** [comment]
Hi lcoombe,

Many thanks.
It works well now.
Deyuan
