### ISSUE TITLE
Error - terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by sumade123** [bcgsc/abyss#472]
Hi,

I recieved the error "terminate called after throwing an instance of 'std::length_error'" at the abyss-rresolver-short step.

What could cause this issue?

I have previously used this install of ABySS to successfully assemble another (larger) genome, and also the ABySS sample/test data was successfully assembled.

Thanks

- ABySS 2.3.5
- CentOS Linux release 7.6.1810

# Assembly error

- [ ] complete `abyss-pe` command line

abyss-pe --directory=/scratch/61e3-e1217e236ab0/nspd/Cla23 k=81 kc=2 j=8 B=80G name=cla23 lib='pea peb' pea='/scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_D4YHXEID5_L3_1.fq.gz /scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_D4YHXEID5_L3_2.fq.gz' peb='/scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_HW2NGDSX3_L1_1.fq.gz /scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_HW2NGDSX3_L1_2.fq.gz'

The machine has 200G memory.

- [ ] last 20 lines of the output of `abyss-pe`

TMPDIR /tmp
make: Entering directory `/scratch/61e3-e1217e236ab0/nspd/Cla23'
abyss-rresolver-short  -b80G -f0.8 -j8 -k81 \
 -h cla23-1-rr --dot -c cla23-1-rr.fa \
-g cla23-1-rr.dot cla23-1.fa cla23-1.dot /scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_D4YHXEID5_L3_1.fq.gz /scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_D4YHXEID5_L3_2.fq.gz /scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_HW2NGDSX3_L1_1.fq.gz /scratch/61e3-e1217e236ab0/nspd/Cla23/Cla23_AELN221023978-1A_HW2NGDSX3_L1_2.fq.gz
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
make: *** [cla23-1-rr.dot] Aborted
make: Leaving directory `/scratch/61e3-e1217e236ab0/nspd/Cla23'

- [ ] number of sequenced bases - 91292702400
- [ ] estimated genome size and ploidy - diploid, ~1.5 gb genome size
- [ ] estimated sequencing depth of coverage - 60X

**Comment by lcoombe** [comment]
Hello @sumade123,

Could you also provide your full log? That will help us to get started with helping you troubleshoot.

Thank you for your interest in ABySS!
Lauren

**Comment by sumade123** [comment]
Hi. Thanks, what is the full log - I have the full standard output if that is what you mean? It seems no .log files or similar have been generated. 

The read length is 150bp.

Thanks

**Comment by lcoombe** [comment]
Yes, the full standard output and error
