### ISSUE TITLE
Abyss - error Makefile:667

### ISSUE THREAD

**Issue by desmodus1984** [bcgsc/abyss#477]
# Please report

- [ ] version of ABySS with `abyss-pe version`
- [ ] (abyss) [juaguila@u01 abyss-763]$ abyss-pe version
bash: line 0: test: -le: unary operator expected
abyss-pe (ABySS) 2.3.7
Written by Shaun Jackman and Anthony Raymond.

Copyright 2012 Canada's Michael Smith Genome Science Centre
- [ ] distribution of Linux with `lsb_release -d`

(abyss) [juaguila@u01 abyss-763]$ lsb_release -d
bash: lsb_release: command not found
(base) [juaguila@u05 ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# Assembly error

- [ ] complete `abyss-pe` command line
- [ ] (after loading conda and abyss environment)
nohup abyss-pe name=763 k=96 B=10G G=200M j=10 in='../763-t1.fq.gz ../763-t2.fq.gz' 

- [ ] last 20 lines of the output of `abyss-pe`
tail -n 20 nohup.out 
Unique path: 37072
No possible paths: 12082
No valid paths: 8
Repetitive: 0
Multiple valid paths: 347
Too many solutions: 0
Too complex: 1

The minimum number of pairs in a distance estimate is 10.
The minimum number of pairs used in a path is 10.
abyss-index  --fai 763-3.fa
Reading `763-3.fa'...
Writing `763-3.fa.fai'...
abyss-index  --fai 763-4.fa
Reading `763-4.fa'...
Writing `763-4.fa.fai'...
cat 763-3.fa.fai 763-4.fa.fai \
	| MergePaths   -j10 -k96 -s1000 -G200M  -o 763-4.path2 - 763-4.path1
MergePaths: invalid option: `-G200M'
make: *** [/home/juaguila/.conda/envs/abyss/bin/abyss-pe.Makefile:667: 763-4.path2] Error 1

- [ ] number of sequenced bases * GB
- [ ] estimated genome size and ploidy diploid: 185 MB by JellyFish
- [ ] estimated sequencing depth of coverage
about 50 X

I installed Abyss in conda which worked fine, but then it failed during assembly.
I ran it in a server as shown above which has 54 cores and 500GB of RAM.

Any reason why it did fail?

Thanks;

**Comment by lcoombe** [comment]
Hi @desmodus1984,

Could you try a fresh ABySS run, specifying `G=200000000` or `G=200e6` instead? I believe that it is failing due to using the `M` unit instead of providing the raw genome size number. 

Thanks for your interest in ABySS!
Lauren

**Comment by desmodus1984** [comment]
Hi,
I did try the suggestion and it worked.
I wanted to ask a question.
Do you think that assembly will benefit from merging paired-end reads and use them as single-end reads?
or it won't make much difference and just use straight trimmed paired-end reads as forward/reverse reads in a Bloom filter.

Thanks.
