### ISSUE TITLE
suspicious memory leak in 'dialign/museq.c'

### ISSUE THREAD

**Issue by emollier** [bcgsc/abyss#481]
Greetings,

For information, we received downstream in the Debian bug tracking system the following report, recorded as [Debian bug #1080071]:
> We are researching static analysis for recurring vulnerabilities. When using
> our tool to test on 'abyss', we found a suspicious memory-leak bug at 'main'
> in 'dialign/museq.c'. The memory that 'salgn' in line 155 points to, allocated
> in line 48 of 'dialign/alig.c', would not be freed before 'exit' in line 313.
> We suggest adding a function to deallocate memory before exit.

Have a nice day,  :)
Étienne.

- [x] version of ABySS with `abyss-pe version`: 2.3.8-1
- [x] distribution of Linux with `lsb_release -d`: Debian GNU/Linux trixie/sid

[Debian bug #1080071]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080071

**Comment by jwcodee** [comment]
@emollier Thanks for informing us of this memory leak. The code comes from a third party but we have added code to deallocate the memory used by the data structures before main in version 2.3.9 of ABySS.

**Comment by emollier** [comment]
Great, thanks for the fix!  I'm proceeding to bump the abyss version in Debian so the issue can be closed on our side.

Cheers!
