### ISSUE TITLE
abyss-map crashes when a FASTA header matches the query better than the sequence

### ISSUE THREAD

**Issue by ahammel** [bcgsc/abyss#59]
For instance:

```
$ pwd
/projects/trans_scratch/validations/abyss_map_crash
$ cat test.fq
@FOO
NNNCCCNNN
+
#########
$ cat good.fa
>AAA
CCC
$ cat bad.fa
>CCC
AAA
$ ./abyss-1.5.2/Map/abyss-map ./test.fq bad.fa > /dev/null
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
abyss-map: ../DataLayer/FastaIndex.h:101: boost::tuples::tuple<const FAIRecord&, long unsigned int, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> FastaIndex::operator[](size_t) const: Assertion `it != m_data.begin()' failed.
Aborted
$ ./abyss-1.5.2/Map/abyss-map ./test.fq good.fa > /dev/null
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
# All good
```

That's pretty inconvenient for us when, for instance, we're using the header to track which sequence variant we're looking for in the query.

For a quick work-around, it would be nice if crash message identified the problematic sequence so I can change the name.

Cheers,
Alex

**Comment by rmar3a** [comment]
Hi,

I was wondering if this bug will be fixed?

Thank you,
Richard

**Comment by benvvalk** [comment]
@rmar3a Thanks for the reminder.  Sure, I will try to fix it in the near future and will send you a patch if I am successful.

**Comment by sjackman** [comment]
Hi, Richard. If the matching text is in the comment rather than the ID of the FASTA header, a workaround is to strip comments using seqtk or similar.

```
❯❯❯ brew install seqtk
❯❯❯ seqtk seq -C - <<EOF
>1 abc
ACGT
EOF
>1
ACGT
```

**Comment by sjackman** [comment]
And please accept my apologies for introducing this rather unsightly bug.
