### ISSUE TITLE
Compilation error with icc / sparsehash-2.0.2

### ISSUE THREAD

**Issue by prehensilecode** [bcgsc/abyss#64]
I have:
- gcc 4.8.1
- sparsehash 2.0.2
- abyss 1.5.2

sparsehash built and tested OK.

abyss configure went OK, and found sparsehash. During make, these errors appear:

```
make[2]: Entering directory `/mnt/HA/opt/src/abyss-1.5.2/Assembly'
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I../DataLayer -I/mnt/HA/opt/src/abyss-1.5.2    -I/mnt/HA/opt/sparsehash/gcc/2.0.2/include -isystem/mnt/HA/opt/src/abyss-1.5.2/boost_1_55_0 -Wall -Wextra -Werror -g -O2 -MT libassembly_a-AssemblyAlgorithms.o -MD -MP -MF .deps/libassembly_a-AssemblyAlgorithms.Tpo -c -o libassembly_a-AssemblyAlgorithms.o `test -f 'AssemblyAlgorithms.cpp' || echo './'`AssemblyAlgorithms.cpp
In file included from /mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/sparsehashtable.h:105:0,
                 from /mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/sparse_hash_map:93,
                 from /mnt/HA/opt/sparsehash/gcc/2.0.2/include/google/sparse_hash_map:34,
                 from ISequenceCollection.h:9,
                 from SequenceCollection.h:5,
                 from BranchGroup.h:5,
                 from AssemblyAlgorithms.h:4,
                 from AssemblyAlgorithms.cpp:1:
/mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/hashtable-common.h: In function ‘bool google::sparsehash_internal::read_bigendian_number(INPUT*, IntType*, size_t)’:
/mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/hashtable-common.h:167:29: error: typedef ‘serializing_int_requires_an_unsigned_type’ locally defined but not used [-Werror=unused-local-typedefs]
                             serializing_int_requires_an_unsigned_type);
                             ^
/mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/hashtable-common.h:54:49: note: in definition of macro ‘SPARSEHASH_COMPILE_ASSERT’
   typedef SparsehashCompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                                 ^
/mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/hashtable-common.h: In function ‘bool google::sparsehash_internal::write_bigendian_number(OUTPUT*, IntType, size_t)’:
/mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/hashtable-common.h:180:29: error: typedef ‘serializing_int_requires_an_unsigned_type’ locally defined but not used [-Werror=unused-local-typedefs]
                             serializing_int_requires_an_unsigned_type);
                             ^
/mnt/HA/opt/sparsehash/gcc/2.0.2/include/sparsehash/internal/hashtable-common.h:54:49: note: in definition of macro ‘SPARSEHASH_COMPILE_ASSERT’
   typedef SparsehashCompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                                 ^
cc1plus: all warnings being treated as errors
make[2]: *** [libassembly_a-AssemblyAlgorithms.o] Error 1
make[2]: Leaving directory `/mnt/HA/opt/src/abyss-1.5.2/Assembly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/HA/opt/src/abyss-1.5.2'
make: *** [all] Error 2
```

Editing `config.status` to remove `-Werror` allows make to complete successfully.

**Comment by benvvalk** [comment]
Hi prehensilecode,

You can work around the issue by setting CFLAGS="-Wno-error" and CXXFLAGS="-Wno-error" before running the configure step, i.e.:

```
$ export CFLAGS='-Wno-error'
$ export CXXFLAGS='-Wno-error'
$ ./configure <...your usual args here...>
$ make
```

They are not serious errors.  The problem is just that we have set ABySS to treat compiler warnings as errors by default (in order to discipline ourselves to write cleanly-compiling code), but in your particular setup (compiler/OS/sparsehash version) sparsehash generates a few innocuous warnings.

**Comment by sjackman** [comment]
That would also have the side effect of disabling optimization. Try instead:
```sh
./configure CFLAGS='-g -O2 -Wno-error' CXXFLAGS='-g -O2 -Wno-error'
make
```

**Comment by sjackman** [comment]
For the record, the default values are:
```makefile
CXXFLAGS = -g -O2
AM_CXXFLAGS = -Wall -Wextra -Werror
```

**Comment by benvvalk** [comment]
Good to know.  Thank you, Shaun.

**Comment by sjackman** [comment]
I'm not able to reproduce this issue with ABySS head, gcc 4.8.4, sparsehash 2.0.2.

```
❯❯❯ brew list --versions gcc48 google-sparsehash abyss
gcc48 4.8.4
google-sparsehash 2.0.2_gcc
abyss 1.5.2
```

**Comment by nortex** [comment]
Hi, I have the same error but adding the flags doesn't solve the problem... What can i do? i tried to build 1.5.2 and 1.3.7 versions of abyss and both give same error on compilation of abyss

**Comment by sjackman** [comment]
Are you able to use ABySS 2.0.2, or is this for use with Trans-ABySS?

**Comment by nortex** [comment]
I tried the ABySS 2.0.2 version too, always get this error. I am using Intel compilers.

**Comment by nortex** [comment]
When trying to install ABySS version 2.0.2 with Boost 1.63 i get this error:

`../Assembly/BranchGroup.h(214): error: no instance of overloaded function "std::swap" matches the specified type
        inline void swap(BranchGroup&, BranchGroup&) { assert(false); }
                    ^

compilation aborted for abyss.cc (code 2)
make[2]: *** [ABYSS-abyss.o] Error 2`

Any ideas what is that "std::swap" error and how can i bypass that?

**Comment by sjackman** [comment]
We can look into the error. Would you consider using `gcc` rather than the Intel Compiler?
You may also wish to try installing ABySS using Linuxbrew https://linuxbrew.sh
```
brew install homebrew/science/abyss
```

**Comment by benvvalk** [comment]
I believe we still have an active license for the Intel Compiler at the GSC.  I'll see if I can fix this.

**Comment by emsisson** [comment]
I was able to compile abyss 2.3.1 with sparsehash 2.0.2 in RHEL 7.9, but I had to use a later version of GCC. Version 9.3.0 worked for me.
