### ISSUE TITLE
Force abyss-pe to run with ABYSS instead of ABYSS-P

### ISSUE THREAD

**Issue by yesimon** [bcgsc/abyss#70]
The makefile for abyss-pe normally tries to run ABYSS-P if cluster compute vars are in the environment or np is set. Is there a way to force running ABYSS even if cluster variables are set? Right now I have commented out the section in abyss-pe that detects mpirun.

**Comment by sjackman** [comment]
Unset `NSLOTS` (or the equivalent for your scheduler) before you run `abyss-pe`.

```sh
unset NSLOTS
abyss-pe …
```

**Comment by benvvalk** [comment]
Thanks, Shaun!
