### ISSUE TITLE
abyss-bloom enhancements

### ISSUE THREAD

**Issue by bschiffthaler** [bcgsc/abyss#74]
Hi, I wrote two additions to abyss-bloom in my fork [here](https://github.com/bschiffthaler/abyss), mainly to use it for reference free comparisons of data. Firstly, I implemented some binary similarity calculations to compare two bloom filters (Jaccard, Czekanowski, Forbes). Secondly, I added a function to output a FASTA of k-mers, which are in the Bloom filter, to stdout.

Changes are so far only in `Bloom/bloom.cc`

I was wondering if you want to merge this into the main repo.

**Comment by benvvalk** [comment]
Neat :-) These are handy features.  Thanks very much for sharing your code, @bschiffthaler!  I pulled your commits into our master (commit dbd3c661285e5db765decc5bc04f336a55fcfa00).

**Comment by sjackman** [comment]
See 0959c62 and 7e8b010 for @bschiffthaler 's commits.

**Comment by sjackman** [comment]
Thanks for you contribution!

**Comment by sjackman** [comment]
See

+ [Jaccard Index](https://en.wikipedia.org/wiki/Jaccard_index)
+ Czekanowski, aka [Sørensen–Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient)

I haven't found a good online reference for the Forbes distance. All I found was this Google Books [page](https://books.google.ca/books?id=03iAsdAcXHcC&pg=PA698&lpg=PA698&dq=Jaccard,+Czekanowski,+Forbes&source=bl&ots=SIAUTdZocE&sig=7drSlimkvE9tAEKFNXadhAOCufI&hl=en&sa=X&ei=D5aJVaKkIcqxogTk-r6ADw&ved=0CCUQ6AEwAQ#v=onepage&q=Jaccard%2C%20Czekanowski%2C%20Forbes&f=false). Do you have a link?

**Comment by bschiffthaler** [comment]
Sure, I was using [this[(http://www.iiisci.org/Journal/CV$/sci/pdfs/GS315JG.pdf) paper as a general reference. I included it as a correlation-based means of similarity calculation. If you let:

a - cases where both bits are 1 (1/1)
b - cases where 1/0
c - cases where 0/1
n - all cases

Forbes similarity (called Forbes II in the aforementioned paper) is calculated as:
![screenshot 2015-06-23 23 30 20](https://cloud.githubusercontent.com/assets/8308279/8317738/e0ced84a-19ff-11e5-88a7-69a868fef280.png)

**Comment by sjackman** [comment]
Thanks. That paper is a useful reference.
