### ISSUE TITLE
Invalid LICENSE file 

### ISSUE THREAD

**Issue by kblin** [bcgsc/abyss#75]
Hi folks,
The usual "I am not a lawyer" disclaimer applies for the following.
While I very much appreciate you distributing ABySS under a GPLv3 license, I don't think your "non-commercial" additional requirement results in a valid license. While of course the copyright holder gets to pick whatever license they like, if I were to distribute ABySS without making money of it, I could only distribute it under the GPL, as the GPL doesn't allow me to add any additional restrictions. Thus, the "non-commercial" part would be lost in the intermediate step, allowing all use under the GPLv3. I assume that's not what you had in mind when you selected this wording on the license.
Additionally, I don't think you're allowed to use the GPL license text in the current altered form.

Regards,
Kai

**Comment by sjackman** [comment]
Thanks for you concern, Kai. It is a sticky point, and I do not know the answer for certain. My interpretation is below. I also am not a lawyer, and I also am not the copyright holder, and so I do not pick the license, though I do have input.

> I could only distribute it under the GPL, as the GPL doesn't allow me to add any additional restrictions. Thus, the "non-commercial" part would be lost in the intermediate step, allowing all use under the GPLv3.

The license gives you the right to redistribute the software. I do not believe that the recipient receiving a copy of the software from you also conveys to the recipient a license to run the software. That right may only be conveyed by the copyright holder.

> Additionally, I don't think you're allowed to use the GPL license text in the current altered form.

The GPL license text is not modified. The GPL license text starts at [line 24, "GNU GENERAL PUBLIC LICENSE"](https://github.com/bcgsc/abyss/blob/master/LICENSE#L24). Everything above that is preamble.

**Comment by tjanez** [comment]
@sjackman, I'm afraid you reasoning is incorrect.

The [GPL FAQ](http://www.gnu.org/licenses/gpl-faq.html#NoMilitary) clearly states that one can not license code under the GPL and add a restriction that it can't be used for commercial purposes:
> **I'd like to license my code under the GPL, but I'd also like to make it clear that it can't be used for military and/or commercial uses. Can I do this? (#NoMilitary)**

>  No, because those two goals contradict each other. The GNU GPL is designed specifically to prevent the addition of further restrictions. GPLv3 allows a very limited set of them, in section 7, but any other added restriction can be removed by the user.

So, the software is actually not licensed under GPLv3. Rather, it uses a custom license that is similar to GPLv3 but removes the freedom to use the software for commercial purposes.

In my opinion, this should be more clearly stated. As it is right now, users are mislead into thinking that the software is licensed under GPLv3.

**Comment by sjackman** [comment]
I'm on vacation until the new year, Tadej. Feel free to bump this thread in the new year to continue this conversation.
