### ISSUE TITLE
Error with Assertion `isalpha(seq[0])' failed

### ISSUE THREAD

**Issue by verne91** [bcgsc/abyss#84]
Hi everyone,

When I run the ABySS, I got an error with the message of 

```
ABYSS-P: ../Assembly/LoadAlgorithm.h:48: bool AssemblyAlgorithms::loadSequence(Graph *, std::basic_string<char, std::char_traits<char>, std::allocator<char>> &) [with Graph = NetworkSequenceCollection]: Assertion `isalpha(seq[0])' failed.
```

So, how to deal with it?

**Comment by benvvalk** [comment]
Hi Sun,

This is a FASTA parsing error.  (It is complaining that there are illegal characters in your FASTA/FASTQ sequences.)

I suspect that there is a problem with either your `abyss-pe` command or the formatting of your input FASTA/FASTQ file(s).   In order to help I would need more info, though.  Would you be able to provide me with:

* your full abyss-pe command line
* the first 8 lines of your input FASTA/FASTQ files?
* the full log output from your abyss-pe command (I recommend adding `v=-v` for verbose logging)

?

**Comment by verne91** [comment]
abyss-pe command line:
abyss-pe np=16 mpirun=$MPIRUN name=rice_simu k=71 v=-v in='reads1_title.fq reads2_title.fq'

first 8 lines of reads1_title.fq:
@>chr01|234586208|+/1
CACCGCCCGCCGCCTGTTCGATTGAAGAAAAGAGAAGCGAAGAGCAAAAAGAAAAGAAAGGAGAAAAGAGAAGAACAAAGAACATGGGTCCCACTTTTTT
+
_baee`ecggfggiiiifidhiibhhgggihidhifiehhihheiZghggbfhgicchgiaieb^dcahdic]acc^b_]cbYcbccc[bdbbccccbbc
@>chr01|365445088|-/1
GTGAAGATTTGACTTCTCTGGATAAAGGTCTTCTGGAGAAGCAGCAATATCTTCAGTCCCTCAAGACATTACTTGTGAGACATTGTGAAAACCTAAGACA
+
bb_eeeccgfgegaifififighhiibghigf[i_bhihhiiffhf_iiighdggdcdddiic^ccZccbah`bbccbccba_cc`cbccc`Rccbacba

reads2_title.fq:
@>chr01|234586608|-/2
CAATATTGTACCTTGAGGGATACATTATATATGGTATTACAACAGGACACAATTTAAAATAAGCATCAATATAAGGGGTTTAAAGTGACTAAGGCTAGAA
+
b__eeeeegggggfhfhih`iahiiiiifiihhbfcahWgiihfgfbheehhgcfc\bhcfdgchfbcecccd`c]b`gcbccbc_ccc`ccVabc]bbc
@>chr01|365444688|+/2
TAACAAGTTTTTGCATCTTGCTATGGAAACATCATTCAGATTTTTCAGAGTCCTAAACACTTCCTCTGATGGAAGTTTCTCTATGTTACAGCAGCTGAAC
+
b_beeeeeafgfgihhhhfghiiiiiihehihfdgii]dhUdiffgheechfiddhgcccd]a_dac]aac_gc`aagccacccab[ddbccWbcX`ccc

The full log:
/lustre/usr/intel/2015/impi/5.0.1.035/intel64/bin/mpirun -np 16 ABYSS-P -k71 -q3 -v   --coverage-hist=coverage.hist -s rice_simu-bubbles.fa  -o rice_simu-1.fa /lustre/home/clswcc/csun/BA/simu_data/rice/reads1_title.fq /lustre/home/clswcc/csun/BA/simu_data/rice/reads2_title.fq 
ABySS 1.9.0
ABYSS-P -k71 -q3 -v --coverage-hist=coverage.hist -s rice_simu-bubbles.fa -o rice_simu-1.fa /lustre/home/clswcc/csun/BA/simu_data/rice/reads1_title.fq /lustre/home/clswcc/csun/BA/simu_data/rice/reads2_title.fq
Running on 16 processors
0: Running on host node119
1: Running on host node119
23: Running on host node119
45: Running on host node119
678: Running on host node119
9: Running on host node119
1011: Running on host node119
121314: Running on host node119
15: Running on host node119
: Running on host node119
: Running on host node119
: Running on host node119
: Running on host node119
: Running on host node119
: Running on host node119
: Running on host node119
0: Reading `/lustre/home/clswcc/csun/BA/simu_data/rice/reads1_title.fq'...
1: Reading `/lustre/home/clswcc/csun/BA/simu_data/rice/reads2_title.fq'...
0: Read 100000 reads. 0: Hash load: 351726 / 268435456 = 0.00131 using 107 MB
1: Read 100000 reads. 1: Hash load: 379451 / 268435456 = 0.00141 using 109 MB
0: Read 200000 reads. 0: Hash load: 705561 / 268435456 = 0.00263 using 124 MB
1: Read 200000 reads. 1: Hash load: 733191 / 268435456 = 0.00273 using 125 MB
APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)

**Comment by sjackman** [comment]
It looks like you'll have to dig deeper than the first 8 lines. Can you send the first one million lines to Ben in a private e-mail, or post them online somewhere?

**Comment by benvvalk** [comment]
I just noticed that the read IDs start with `@>` instead of `@`, which is a bit unusual.  Could you try removing the `>` at the beginning of each read ID?

For example, I think the first read ID should probably be:
`@chr01|234586208|+/1`
instead of:
`@>chr01|234586208|+/1`

**Comment by verne91** [comment]
Hi, @benvvalk 

In the Issue #85 , the header line of fastq files are same with this one, but it report another bugs.

**Comment by benvvalk** [comment]
Hi @verne91,

Sorry, I'm don't understand why you would get two different errors when using exactly the same input files.  Could you please try fixing the FASTA headers anyhow to see what would happen? I think it might be informative.

**Comment by verne91** [comment]
Hi @benvvalk ,

The input files are the same only on the header line. They both start with '@>'.
Then I would modify the headers to test.

**Comment by verne91** [comment]
Hi @benvvalk ,

After I fix the input files, the err log is the same with the last time.

**Comment by benvvalk** [comment]
Hi @verne91,

Okay, thanks for trying with the fixed headers.  Since the ABySS FASTA parser is heavily used for several years, I think it is most likely a problem with the formatting of your file.  Here are some more suggestions to debug the problem:

* use `tail` to look at the last few lines of the file, to make sure it is not corrupted 
* check that the number of lines is a multiple of 4
* run the file through a different tool that accepts FASTQ as input, to make sure that the problem is not ABySS-specific (e.g. `seqtk`, `FASTX-Toolkit`)
* run the file through a FASTQ validator.  This looks like it might help, although I have not tried it personally: http://genome.sph.umich.edu/wiki/FastQValidator.
* add a printf statement to the ABySS FastaReader class and print out the line number where the error occurs

Unfortunately, I can't debug the problem for you unless I have access to the data.

**Comment by sjackman** [comment]
Once we sort out the cause of this issue, Ben, it would be great if we could replace the `assert` failure with an error message that prints the line number of the problem FASTA sequence using the `FastaReader::die` method.

**Comment by sjackman** [comment]
@verne91 The log indicates that the error occurs somewhere between the 100,000th read and the 200,000th read. If you could send the first million lines of the FASTQ file to Ben with Dropbox or something it would help speed up troubleshooting.

**Comment by verne91** [comment]
Hi @benvvalk , 

I use FastQValidator to test my input file.
The results are below:
Input and filter stats:
        Input sequences: 94,000,000
        Input bases: 9,400,000,000
        Input mean length: 100.00
        Good sequences: 44,162,310 (46.98%)
        Good bases: 4,416,230,844
        Good mean length: 100.00
        Bad sequences: 49,837,690 (53.02%)
        Bad bases: 4,983,768,690
        Bad mean length: 100.00
        Sequences filtered by specified parameters:
        derep: 49837690

We can't connect to dropbox in China, can I upload the data to other cloud drives?

**Comment by benvvalk** [comment]
Interesting.  Doesnt' FASTQValidator tell you where the bad characters are? I thought that was the purpose of the program.

You may also be able to run this command to highlight illegal characters in your sequence data and view them in `less`:
```
awk '(NR-1)%4==1' reads1_title.fq | LC_ALL=C egrep --color=always '[^a-zA-Z]' | less -R
```

Also, I believe you should be able to attach the file directly to this ticket, if it is not too large (please use gzip).  As Shaun suggested, you can probably just send the first part of the file (e.g. first million records), as long as it reproduces the error.  (Use the `head` program to create a partial file and please test that the partial file still produces the error.)

**Comment by verne91** [comment]
I find many Ns in the output, I think I should remove the reads contain Ns.

**Comment by benvvalk** [comment]
@verne91 Sure, that is worth a try.
