### ISSUE TITLE
Make sqlite3 an optional dependency

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#86]
Many users have been having trouble compiling ABySS 1.9.0 because of a newly-introduced dependency on sqlite3.  This dependency is unnecessary and will be made optional in the next ABySS release.

The sqlite3 dependency has already been removed in the latest revision of abyss on github, so users that are having trouble with the sqlite3 dependency are recommended to `git clone git@github.com:bcgsc/abyss.git` and compile that, instead of version 1.9.0.

Alternatively, the user may satisfy the sqlite3 dependency of ABySS 1.9.0. by doing one of the following:
1. install `sqlite3` and `sqlite3-dev`/`sqlite3-devel` packages on their system using their package manager, OR
2. install sqlite3 from the source tarball: https://www.sqlite.org/2015/sqlite-autoconf-3081101.tar.gz

If sqlite3 is installed to a non-standard location (e.g. the user's home directory), then the `--with-sqlite=<directory>` flag must be supplied to the ABySS `configure` script, where `<directory>` is the base installation directory for sqlite3.  The base installation directory for sqlite3 will have an `include` subdirectory containing `sqlite3.h` and `lib` subdirectory containing `libsqlite3.so`.  Common values for `<directory>` are `/usr` or the user's home directory (e.g. `/home/johndoe`).

**Comment by sjackman** [comment]
This issue is fixed.
