### ISSUE TITLE
Sealer does not implement -D option

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#89]
Sealer advertises a `-D` option in the `--help` output which specifies the offset distance between the gap and the flank sequences, but doesn't actually implement the option.

**Comment by CarolineOhrman** [comment]
I've seen the same thing. Flanks are identical running with or without -D option

**Comment by sjackman** [comment]
Although options `-D` and `--flank-distance` are parsed and the value stored in `opt::flankDistance`, I don't see this variable used in the code base anywhere. @benvvalk Shall we delete this option?
https://github.com/bcgsc/abyss/search?q=flankDistance

**Comment by sjackman** [comment]
This issue will be fixed in the next release of ABySS.
