### ISSUE TITLE
Recipe for target '<name>' failed -- Fails while "generating adjacency?"

### ISSUE THREAD

**Issue by mebbert** [bcgsc/abyss#91]
Dear abyss,

Thank you for your help and support. I'm assembling a genome but I get the following error (output truncated):

    Loaded 2601815360 k-mer
    Minimum k-mer coverage is 2
    Using a coverage threshold of 2...
    The median k-mer coverage is 6
    The reconstruction is 1556402828
    The k-mer coverage threshold is 2.44949
    Setting parameter e (erode) to 2
    Setting parameter E (erodeStrand) to 1
    Setting parameter c (coverage) to 2.44949
    Generating adjacency
    Reaping losing child 0x23b7cf0 PID 45187
    /usr/local/bin/abyss-pe:471: recipe for target '<name>-1.fa' failed
    make: *** [<name>-1.fa] Killed
    Removing child 0x23b7cf0 PID 45187 from chain.
    make: Leaving directory 'path/to/abyss/k29'

Comparing this output to that using the provided test data, it appears abyss is failing while "generating adjacency." I don't see any existing issues on this matter. I also ran it with -d (debug) to see if there were any obvious errors, but I don't see anything.

Any ideas?

Thanks again!

**Comment by sjackman** [comment]
Please post the exact command line that you used. That error message is produced by GNU make.

**Comment by mebbert** [comment]
Here you go:

    abyss-pe -C k29 k=29 -d name=<name> in='~/<name>/abyss/special_fastqs_for_abyss/15269-Shotgun_S13_L003_R1_001.fastq.gz ~/<name>/abyss/special_fastqs_for_abyss/15269-Shotgun_S13_L003_R2_001.fastq.gz'

The "special" fastqs were to add '\1' and '\2' to the read names. Here are a couple for inspection, just in case.

    @D00723:25:C6C71ANXX:3:1101:1481:2023/1
    NTTGTGTTTGATGGCTGAGCTTGCACAATGGTGGCTCAGCTGTTCTATTCACAGGGTTTGCTTTTAATTTTCTAAACATTCGCAAAAAGACTTCCCTTAACCATCCCTATGACATCCCAACGATT
    +
    #<<BBFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFFFFFFFFFFFFFFF/BBBFF<FBFFFFFFF/BF<<<BFFFFBBF/F/FF//FFF/FFFFFBFFFF/B<FFFFFFFF////<<

    @D00723:25:C6C71ANXX:3:1101:1481:2023/2
    AGCTATATGTTTCCTAATCAAGACCATATTAAAGCCATTACTTTAATCAAGACAATTTCCTTCGAGCCAGTCCCCTTCTTTTAAAATATCTATTTCTCATTATTCTAACCACTTCTTTCTTCTGC
    +
    BBBBBFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFF<B<<FB<FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBF

**Comment by sjackman** [comment]
Adding /1 and /2 should not be necessary.
Please remove -d from the command line and add `v=-v` to enable verbose logging.

**Comment by mebbert** [comment]
Without /1 and /2 I got the error `All reads are mateless` and followed the tips here: https://www.biostars.org/p/93814/

Here is what the read IDs looked like before:

    @D00723:25:C6C71ANXX:3:1101:1481:2023 1:N:0:13
    ...

    @D00723:25:C6C71ANXX:3:1101:1481:2023 2:N:0:13
    ...

I'll rerun and report. Thanks!

**Comment by sjackman** [comment]
Ben, do you see any problem with this read naming scheme?

**Comment by sjackman** [comment]
What version of ABySS are you running? Please report `abyss-pe version`

**Comment by mebbert** [comment]
\
    abyss-pe (ABySS) 1.9.0
    \
    Written by Shaun Jackman and Anthony Raymond.
    \
    
    \
    Copyright 2012 Canada's Michael Smith Genome Science Centre

**Comment by benvvalk** [comment]
@sjackman Thanks for your help. I agree -- the read names should work fine as is.

@mebbert:

Your `abyss-pe` command looks good.  

Unfortunately, ABySS will sometimes output the "all reads are mateless" message in situations where the real problem is actually an error in an upstream command.   It is necessary to see the full log output with the verbose (`-v`) option enabled to determine what the real problem is.  Most commonly, the real issue is that the user runs out of RAM during the alignments stage.  Alignments are performed with the `abyss-map` program by default, and `abyss-map` requires an amount of RAM that is roughly 10 times size of the assembly file (<name>-3.fa) on disk.   

Since the "all reads are mateless" happens at a later stage in the ABySS pipeline than the original error you posted above ("Reaping losing child 0x23b7cf0 PID 45187"), your second run actually proceeded further through the assembly pipeline.

**Comment by mebbert** [comment]
The process reran without issue. It must have been a memory issue because I originally had five jobs running at once (different k values). The machine I'm using has 256GB of RAM, so I didn't think it would be an issue, but by casual observance, it looks like each job uses about 25% of that.

Thanks for your help. I wouldn't have ever guessed it was a memory issue based on the errors!

Is there a good way to determine the best k value without completing the entire run 20 times?

**Comment by benvvalk** [comment]
Great, glad to hear!

Regarding your question about best k value: running assemblies for a range of different k values is indeed the usual method.  [KmerGenie](http://kmergenie.bx.psu.edu/) is a tool that estimates the optimal k value based on read subsampling and k-mer histograms -- if you're feeling adventurous you can give that a try.  (I'm not aware of any competitors, but there may be some out there).

**Comment by sjackman** [comment]
As Ben said, just a binary search, unfortunately. I'd like to automate that task one day. Without knowing anything else about your data set, two thirds of your read length is a good place to start.
