### ISSUE TITLE
abyss-pe has issue with bwa mem

### ISSUE THREAD

**Issue by tnheider** [bcgsc/abyss#92]
abyss-pe failed to run bwa mem with the following command:
abyss-pe name=results/45k k=45 np=35 lib='pe1' long='long1' pe1='inputs/reads-1.fq inputs/reads-2.fq' long='inputs/transcripts.fa'

the relevant line from stderr is
bwa mem -a -t35 -S -P -k45 results/45k-8.fa  \
        |gzip >inputs/transcripts.fa-8.sam.gz

Just from a brief look, it looks like it's an error in bin/abyss-pe line 666 which reads:
        bwa mem -a -t$j -S -P -k$l $(name)-8.fa $(strip $($*)) \
and should be:
        bwa mem -a -t $j -S -P -k $l $(name)-8.fa $(strip $($*)) \

**Comment by benvvalk** [comment]
@tnheider Was there an actual error message?  Can you please post the full log output?

For bwa, I don't think it matters if there is a space between the switches (e.g. -k) and the arguments (e.g. $l).  I have previously used the `long` option of `abyss-pe` without any problems.

**Comment by tnheider** [comment]
Oh ok, I am probably making some other mistake then (is this the correct place to discuss this?). I changed the command to
abyss-pe name=a45k k=45 np=35 lib='pe1' long='long1' pe1='reads-1.fq reads-2.fq' long='transcripts.fa' in case it was something with being run from another directory, the stderr ends with the following:

[main] CMD: bwa index a45k-8.fa
[main] Real time: 12.470 sec; CPU: 11.815 sec

Usage: bwa mem [options] <idxbase> <in1.fq> [in2.fq]

Algorithm options:

       -t INT        number of threads [35]
       -k INT        minimum seed length [45]
       -w INT        band width for banded alignment [100]
       -d INT        off-diagonal X-dropoff [100]
       -r FLOAT      look for internal seeds inside a seed longer than {-k} * FLOAT [1.5]
       -y INT        seed occurrence for the 3rd round seeding [20]
       -c INT        skip seeds with more than INT occurrences [500]
       -D FLOAT      drop chains shorter than FLOAT fraction of the longest overlapping chain [0.50]
       -W INT        discard a chain if seeded bases shorter than INT [0]
       -m INT        perform at most INT rounds of mate rescues for each read [50]
       -S            skip mate rescue
       -P            skip pairing; mate rescue performed unless -S also in use
       -e            discard full-length exact matches

Scoring options:

       -A INT        score for a sequence match, which scales options -TdBOELU unless overridden [1]
       -B INT        penalty for a mismatch [4]
       -O INT[,INT]  gap open penalties for deletions and insertions [6,6]
       -E INT[,INT]  gap extension penalty; a gap of size k cost '{-O} + {-E}*k' [1,1]
       -L INT[,INT]  penalty for 5'- and 3'-end clipping [5,5]
       -U INT        penalty for an unpaired read pair [17]

       -x STR        read type. Setting -x changes multiple parameters unless overriden [null]
                     pacbio: -k17 -W40 -r10 -A1 -B1 -O1 -E1 -L0  (PacBio reads to ref)
                     ont2d: -k14 -W20 -r10 -A1 -B1 -O1 -E1 -L0  (Oxford Nanopore 2D-reads to ref)
                     intractg: -B9 -O16 -L5  (intra-species contigs to ref)

Input/output options:

       -p            smart pairing (ignoring in2.fq)
       -R STR        read group header line such as '@RG\tID:foo\tSM:bar' [null]
       -H STR/FILE   insert STR to header if it starts with @; or insert lines in FILE [null]
       -j            treat ALT contigs as part of the primary assembly (i.e. ignore <idxbase>.alt file)

       -v INT        verbose level: 1=error, 2=warning, 3=message, 4+=debugging [3]
       -T INT        minimum score to output [30]
       -h INT[,INT]  if there are <INT hits with score >80% of the max score, output all in XA [5,200]
       -a            output all alignments for SE or unpaired PE
       -C            append FASTA/FASTQ comment to SAM output
       -V            output the reference FASTA header in the XR tag
       -Y            use soft clipping for supplementary alignments
       -M            mark shorter split hits as secondary

       -I FLOAT[,FLOAT[,INT[,INT]]]
                     specify the mean, standard deviation (10% of the mean if absent), max
                     (4 sigma from the mean if absent) and min of the insert size distribution.
                     FR orientation only. [inferred]

Note: Please read the man page for detailed description of the command line and options.

make: *** [transcripts.fa-8.sam.gz] Error 1
make: *** Deleting file `transcripts.fa-8.sam.gz'

and the stdout ends with:

bwa index a45k-8.fa
bwa mem -a -t 35 -S -P -k 45 a45k-8.fa  \
        |gzip >transcripts.fa-8.sam.gz

That is the step that is mapping the transcriptome to the contigs for scaffolding correct? Should it be reading the transcriptome fasta file in from the stdin or is bwa mem passed the file name for mapping? Am I missing something?

**Comment by benvvalk** [comment]
I see the problem now.

Change your `abyss-pe` command to:

abyss-pe name=results/45k k=45 np=35 lib='pe1' long='long1' pe1='inputs/reads-1.fq inputs/reads-2.fq' *long1*='inputs/transcripts.fa'

Note the change from `long` to `long1`.

**Comment by benvvalk** [comment]
It is totally fine to post issues by the way.  According to preference, you may also make a post on BioStars with the tag "abyss" or on the ABySS Google Group.

**Comment by tnheider** [comment]
Thank you for the help!

**Comment by benvvalk** [comment]
You're welcome.
