### ISSUE TITLE
Sealer requires read file arguments even when using a pre-built Bloom filter

### ISSUE THREAD

**Issue by benvvalk** [bcgsc/abyss#93]

**Comment by sjackman** [comment]
Yes, please. Ideally a Bloom filter could be specified as a positional parameter (without an option) and the software would detect whether it's a Bloom filter or reads. That should be pretty straight forward as long as the first line of the Bloom filter file format is some identifying text.

**Comment by benvvalk** [comment]
Good idea, Shaun.

**Comment by benvvalk** [comment]
Fixed in 2f3b868 / 5a8f707.

You still can't specify Bloom filters as positional arguments, but now the input FASTQs are only required when it makes sense.
