### ISSUE TITLE
Bugs in abyss-layout and abyss-filtergraph

### ISSUE THREAD

**Issue by dbrowneup** [bcgsc/abyss#95]
Hi guys,

I used abyss-overlap to find all overlaps in a set of contigs derived from multiple assemblies. This worked well, resulting in an overlap graph:

V=143060 E=140478 E/V=0.982
Degree: █▂
        01234
0: 68% 1: 25% 2-4: 3.5% 5+: 3.1% max: 476

But there's something that abyss-layout doesn't like, because it throws this error:

`abyss-layout: ../Common/Dictionary.h:74: cstring Dictionary::getName(unsigned int) const: Assertion 'index < m_vec.size()' failed.
/home/dbrowne/.lsbatch/1454306518.2174747.shell: line 14:  2958 Aborted                 (core dumped) $ABYSS_PATH/abyss-layout -s 1000 -m 100 -k 1000 -o SXPX_SEQ1K_99-1.path -g SX
PX_SEQ1K_99-2.dot SXPX_SEQ1K_99-1.dot`

However, I was able to get around this by switching to abyss-filtergraph and using the --assemble option to merge the unambiguous paths, followed by MergeContigs to write the new fasta file.

Unfortunately, I managed to hit a big in abyss-filtergraph too. While the program worked for the above contig set, when I tried to run the same pipeline on a different contig set, it didn't work. Here's the overlap graph for the second contig set:

V=295712 E=339516 E/V=1.15
Degree: ▆█
        01234
0: 39% 1: 54% 2-4: 4.7% 5+: 2.1% max: 590

And here's the abyss-filtergraph error:

`abyss-filtergraph: ../Common/ContigProperties.h:174: ContigProperties &operator+=(ContigProperties &, const T &) [with T = Distance]: Assertion '(int)a.length + (int)b.distance > 0' failed.
/home/dbrowne/.lsbatch/1454478386.2176966.shell: line 14: 28106 Aborted                 (core dumped) $ABYSS_PATH/abyss-filtergraph -v -k 1000 -m 100 --dot --no-SS --no-shim --assemble -g SXPX_SEQ1K_100-2.dot SXPX_SEQ1K_100-1.dot SXPX_SEQ1K_100-1.fa > SXPX_SEQ1K_100-1.path`

**Comment by sjackman** [comment]
For the second error, try applying the following patch:
```diff
diff --git a/Common/ContigProperties.h b/Common/ContigProperties.h
index 215b140..07ff1db 100644
--- a/Common/ContigProperties.h
+++ b/Common/ContigProperties.h
@@ -171,7 +171,7 @@ struct Distance {
 template <typename T>
 ContigProperties& operator+=(ContigProperties& a, const T& b)
 {
-	assert((int)a.length + (int)b.distance > 0);
+	assert((int)a.length + (int)b.distance >= 0);
 	a.length += b.distance;
 	return a;
 }
```

For the first error, I'm not sure. If you can post the adjacency graph somewhere that we can download it, we can try to reproduce the error and look into it. `abyss-layout` was never used in the main ABySS pipeline, so it doesn't receive much testing.

**Comment by dbrowneup** [comment]
Thanks Shaun! I'm re-compiling now with that change in place. I'll test it out soon and let you know if it works.

With respect to abyss-layout, I'm not too worried about getting that to work, seeing as abyss-filtergraph does the job just fine. If the patch you provided for filtergraph fixes the problem, I don't really need abyss-layout at all. Of course, I'm happy to help you debug it if you'd like. The graph isn't too big, so I could probably just email it to you.

**Comment by dbrowneup** [comment]
The path to abyss-filtergraph worked like a charm!

**Comment by sjackman** [comment]
Great. I'm glad that you've got it working. I'm happy to see people using the components of ABySS outside of the standard pipeline. I'd like to see more remixing of assembly software components.

**Comment by sjackman** [comment]
I'll mention that ABySS supports (can read and write) the [GFA file format](https://github.com/pmelsted/GFA-spec) for assembly graphs. Hopefully more tools will be implementing it.
