### ISSUE TITLE
SAM Seq and Qual from abyss-map

### ISSUE THREAD

**Issue by dbrowneup** [bcgsc/abyss#96]
Following up on a comment in a thread from several years ago:

https://groups.google.com/d/msg/abyss-users/FgDjyfHChiI/lgyRJoMwTaUJ

It seems like the --enable-samseqqual option is not recognized by ./configure. Probably a super low priority for you guys, but it would be really cool if this worked!

**Comment by sjackman** [comment]
The undocumented `abyss-map-ssq` outputs SAM seq and qual. Not the best name, in my opinion.

**Comment by dbrowneup** [comment]
A note for anyone reading this in the future: if you want to use `abyss-fixmate`, you will also want to use `abyss-fixmate-ssq`. An example:

```
abyss-map-ssq -v -j20 -l50 ../02_Separated_Pairs/Library.SXPX.L.fq.gz ../02_Separated_Pairs/Library.SXPX.R.fq.gz ../SEQ1K_100_OLC.fa \
      | abyss-fixmate-ssq --all --qname -v \
      | samtools view -@ 20 -Sb - \
      | samtools sort -@ 20 -O bam -T SXPX_MAP_SEQ1K_100_OLC > SXPX_MAP_SEQ1K_100_OLC.bam \
      && samtools index SXPX_MAP_SEQ1K_100_OLC.bam
```
