### ISSUE TITLE
Sealer EXCEEDED_MEM_LIMIT error

### ISSUE THREAD

**Issue by dbrowneup** [bcgsc/abyss#98]
Hi guys,

I'm trying to run Sealer on a set of scaffolds, and although the program completed without raising any errors, it failed to actually seal any gaps.

For some reason, all the flanks fall under the category of "Exceeded mem limit"

But I find that rather baffling, because I used -j20 and -s2000, so there should've been 40 GB of memory available for graph searches.

I've attached the output of the job (submitted to a cluster using LSF) as well as the trace file written by Sealer. According to the job output, the maximum memory used during the whole job was 86 MB.

Any advice on how to make this work properly would be greatly appreciated.

Best,
Dan

[OUT_SEQ1K_100_Contig_Test.txt](https://github.com/bcgsc/abyss/files/141409/OUT_SEQ1K_100_Contig_Test.txt)
[Sealer_Trace_File.txt](https://github.com/bcgsc/abyss/files/141410/Sealer_Trace_File.txt)

**Comment by benvvalk** [comment]
Hi Dan,

Try setting the `-s` (`--search-mem`) to a really high value, e.g. `-s 100G`.  It shouldn't do any harm to set it to a really high value, even if the value is greater than the memory available on the machine (the default value of `-s` is `500M`.)

We should get rid of that `--search-mem` option completely, since it doesn't work very well and isn't really needed.

**Comment by dbrowneup** [comment]
Oh you know it just occurred to me - I set it `-s2000`. But I can see the default is `500M` and your suggestion is `-s100G`. Perhaps it bugged out on me because I failed to include either `M` or `G` at the end of my number?

**Comment by benvvalk** [comment]
Yeah, it's in bytes by default, so that's the issue!

**Comment by dbrowneup** [comment]
Haha okay, I will adjust my parameters accordingly and retry. I had also set `-b10000`. So I'll try it with `-s2000M` and `-b10000M`.
