### ISSUE TITLE
Bug in abyss-scaffold when using abyss-longseqdist

### ISSUE THREAD

**Issue by dbrowneup** [bcgsc/abyss#99]
Hi guys,

I have a _de novo_ PACBIO assembly (made with Quiver/HGAP/Falcon) which I am using to scaffold a composite ABySS Illumina assembly. I am doing this with these commands:

```
bwa mem -t10 -W500 -r10 -k250 -c200 ../../SEQ1K_100-11.fa ../PBDN_BESST_10K.fa | gzip > PB_LSD_BWA.sam.gz
abyss-longseqdist -v -k100 --min-gap=1 PB_LSD_BWA.sam.gz | grep -v "l=" > PB_LSD_BWA.dist.dot
abyss-scaffold -v -k100 -s1000 --min-gap=1 -n1 --complex -g SEQ1K_100-11_LSD.dot -o SEQ1K_100-11_LSD.path ../../SEQ1K_100-11.dot PB_LSD_BWA.dist.dot
MergeContigs -v -k100 --adj -g SEQ1K_100-12_LSD.dot -o SEQ1K_100-12_LSF.fa ../../SEQ1K_100-11.fa SEQ1K_100-11_LSD.dot SEQ1K_100-11_LSD.path
```

And it works beautifully! ... until abyss-scaffold hits this bug:

```
abyss-scaffold: scaffold.cc:498: bool isOverlap(const DistanceEst &): Assertion `d.distance < 0' failed.
/home/dbrowne/.lsbatch/1456196795.2230123.shell: line 12: 28184 Aborted                 (core dumped) abyss-scaffold -v -k100 -s1000 --min-gap=1 -n1 --complex -g SEQ1K_100-11_LSD.dot -o SEQ1K_100-11_LSD.path ../../SEQ1K_100-11.dot PB_LSD_BWA.dist.dot
```

Attached is the full output log, for reference.

[OUT_PB_LSD_TEST_v2.4.txt](https://github.com/bcgsc/abyss/files/141911/OUT_PB_LSD_TEST_v2.4.txt)

**Comment by sjackman** [comment]
https://github.com/bcgsc/abyss/blob/master/Scaffold/scaffold.cc#L498
```c++
/** Return whether the specified distance estimate is an exact
 * overlap.
 */
static bool isOverlap(const DistanceEst& d)
{
	if (d.stdDev == 0) {
		assert(d.distance < 0);
		return true;
	} else
		return false;
}
```

**Comment by sjackman** [comment]
If the estimated error of the distance estimate is exactly 0, `abyss-scaffold` asserts that the distance estimate is negative, that is, the two sequences overlap. If you're comfortable with `sed`, I would replace the `e=0` lines in the file `SEQ1K_100-11.dot` with `e=1`. `abyss-scaffold` doesn't use the value of `e` other than in this one place.

If it's easier to change the code, change it to
```c++
static bool isOverlap(const DistanceEst& d)
{
    d.stdDev == 0 && d.distance < 0;
}
```

`abyss-longseqdist` probably shouldn't be writing out `e=0` for positive distance estimates. `e=0.1` would be better I think.

**Comment by benvvalk** [comment]
Thanks, Shaun!

**Comment by sjackman** [comment]
Tony wrote `abyss-longseqdist` assuming that the input sequences were essentially free of indel errors, hence the `e=0` estimate.

**Comment by benvvalk** [comment]
Ah, I see.

**Comment by dbrowneup** [comment]
When I inspect `SEQ1K_100-11.dot` with `grep "e=0" SEQ1K_100-11.dot` nothing is returned. Similarly, `grep` does not find `e=1` in that file either. When I inspect the output of `abyss-longseqdist`, the file `PB_LSD_BWA.dist.dot` with `grep`, output is only returned for `e=1` but not `e=0`. Maybe the best thing for me to do is change the code as you've suggested?

**Comment by dbrowneup** [comment]
Perhaps it is worth mentioning that `SEQ1K_100-11.dot` is written in the adj format, not the dot format.

**Comment by sjackman** [comment]
The output format of `abyss-longseqdist` should be `dot`. I haven't tested it though. It also doesn't provide any options to change the output format, unlike other ABySS graph tools. https://github.com/bcgsc/abyss/blob/master/Scaffold/longseqdist.cpp#L60

Changing the code would be just fine.

**Comment by dbrowneup** [comment]
Hey Shaun,

I changed the code to exactly what you said...

```
static bool isOverlap(const DistanceEst& d)
{
    d.distance < 0 && d.stdDev == 0;
}
```

But I'm wondering, does that actually do anything? Seems to me like nothing is being returned. Should I perhaps change it to something like...

```
static bool isOverlap(const DistanceEst& d)
{
    if (d.distance < 0 && d.stdDev == 0) {
        return true;
    } else
        return false;
}
```

Then again, I don't know C or C++, so I really have no idea what I'm talking about haha. All that said, the code you suggested led to `abyss-scaffold` working. However, now I'm running into problems downstream of that, trying to merge the contigs.

With this series of commands (and your suggested code):
```
bwa mem -t10 -W500 -r10 -k250 -c200 ../../SEQ1K_100-11.fa ../PBDN_BESST_10K.fa | gzip > PB_LSD_BWA.sam.gz
abyss-longseqdist -v -k100 --min-gap=1 PB_LSD_BWA.sam.gz | grep -v "l=" > PB_LSD_BWA.dist.dot
$ABYSS_PATH/abyss-scaffold -v -k100 -s1000 --min-gap=1 -n1 --complex -g SEQ1K_100-11_LSD.dot -o SEQ1K_100-11_LSD.path ../../SEQ1K_100-11.dot PB_LSD_BWA.dist.dot
MergeContigs -v -k100 --adj -g SEQ1K_100-12_LSD.dot -o SEQ1K_100-12_LSF.fa ../../SEQ1K_100-11.fa SEQ1K_100-11_LSD.dot SEQ1K_100-11_LSD.path
```

This is what I get:

```
...
Assembled 5723 contigs in 1384 scaffolds.
V=14374 E=8910 E/V=0.62
Degree: ▅█
        01234
0: 39% 1: 61% 2-4: 0.55% 5+: 0% max: 3
n       n:1000  L50     min     N80     N50     N20     E-size  max     sum     name
19693   19693   1413    1000    5533    26993   74429   63682   1032859 166.8e6
Reading `SEQ1K_100-11_LSD.dot'...
Read 14374 vertices. Using 2.33 MB of memory.
Reading `../../SEQ1K_100-11.fa'...
Read 7187 sequences. Using 86.3 MB of memory.
Reading `SEQ1K_100-11_LSD.path'...
Read 1384 paths. Using 86.3 MB of memory.
Writing `SEQ1K_100-12_LSD.dot'...
V=5696 E=232 E/V=0.0407
Degree: █
        01234
0: 97% 1: 1.2% 2-4: 1.4% 5+: 0% max: 3
The minimum coverage of single-end contigs is inf.
The minimum coverage of merged contigs is inf.
n       n:200   L50     min     N80     N50     N20     E-size  max     sum     name
2848    2848    404     1000    19300   45358   84361   87993   1024877 62.64e6 SEQ1K_100-12_LSF.fa
```

I realize however, that I am skipping some of the steps that are in the default pipeline. So I tried this instead:

```
bwa mem -t10 -W500 -r10 -k250 -c200 ../../SEQ1K_100-11.fa ../PBDN_BESST_10K.fa | gzip > PB_LSD_BWA.sam.gz
abyss-longseqdist -v -k100 --min-gap=0 PB_LSD_BWA.sam.gz | grep -v "l=" > PB_LSD_BWA.dist.dot
$ABYSS_PATH/abyss-scaffold -v -k100 -s1000 --min-gap=0 -n1 --complex -g SEQ1K_100-11_LSD.dot -o SEQ1K_100-11_LSD.path ../../SEQ1K_100-11.dot PB_LSD_BWA.dist.dot
$ABYSS_PATH/PathConsensus -v --dot -k100 -p1 -s SEQ1K_100-12_LSD.fa -g SEQ1K_100-12_LSD.dot -o SEQ1K_100-12_LSD.path ../../SEQ1K_100-11.fa ../../SEQ1K_100-11.dot SEQ1K_100-11_LSD.path
cat ../../SEQ1K_100-11.fa SEQ1K_100-12_LSD.fa \
        |$ABYSS_PATH/MergeContigs -v -k100 -o SEQ1K_100-13_LSD.fa - SEQ1K_100-12_LSD.dot SEQ1K_100-12_LSD.path
```

And now I hit a bug with MergeContigs:

```
...
Assembled 5723 contigs in 1384 scaffolds.
V=14374 E=8910 E/V=0.62
Degree: ▅█
        01234
0: 39% 1: 61% 2-4: 0.55% 5+: 0% max: 3
n       n:1000  L50     min     N80     N50     N20     E-size  max     sum     name
19693   19693   1412    1000    5533    27001   74429   63688   1032859 166.8e6
Reading `../../SEQ1K_100-11.dot'...
Reading `../../SEQ1K_100-11.fa'...
Reading `SEQ1K_100-11_LSD.path'...
Read 1384 paths
Ambiguous paths: 4339
Merged:          334
No paths:        4005
Too many paths:  0
Too complex:     0
Dissimilar:      0
Reading `SEQ1K_100-12_LSD.dot'...
Read 48064 vertices. Using 5.21 MB of memory.
Reading `-'...
Read 24032 sequences. Using 178 MB of memory.
Reading `SEQ1K_100-12_LSD.path'...
Read 1384 paths. Using 178 MB of memory.
MergeContigs: MergeContigs.cpp:199: void mergeContigs(const ContigGraph<DirectedGraph<ContigProperties, Distance>> &, const std::vector<Contig, std::allocator<Contig>> &, ContigNode, ContigNode, s
td::basic_string<char, std::char_traits<char>, std::allocator<char>> &, const std::vector<ContigNode, std::allocator<ContigNode>> &): Assertion `d < 0' failed.
/home/dbrowne/.lsbatch/1456613275.2238350.shell: line 17: 11717 Done                    cat ../../SEQ1K_100-11.fa SEQ1K_100-12_LSD.fa
     11718 Aborted                 (core dumped) | $ABYSS_PATH/MergeContigs -v -k100 -o SEQ1K_100-13_LSD.fa - SEQ1K_100-12_LSD.dot SEQ1K_100-12_LSD.path
```

Thoughts?

**Comment by sjackman** [comment]
Sorry, I've been coding in Ruby for too long (`return` is optional in Ruby). It should have been

```c++
static bool isOverlap(const DistanceEst& d)
{
    return d.distance < 0 && d.stdDev == 0;
}
```

**Comment by sjackman** [comment]
The failed assertion is at https://github.com/bcgsc/abyss/blob/master/MergePaths/MergeContigs.cpp#L199

**Comment by sjackman** [comment]
A path in a `.path` file looks like `1+ 50N 2+ 3+ 50N 4+`. There is a gap between `1+` and `2+`, but no gap between `2+` and `3+`. The assertion is saying that `2+` and `3+` must be adjacent in the contig overlap graph, that is, the two contigs must overlap.

**Comment by dbrowneup** [comment]
I'm thinking maybe this isn't the way to go in terms of integrating the PACBIO data that I have. Looking at the `.path` file, here's what I see:

```
[dbrowne@ada2 PB_LSD_TEST_v2.5]$ head SEQ1K_100-12_LSD.path
96904652	104538- 99N 45176785- 99N 96891371- 99N 96816549- 99N 96901803-
96904653	106688- 99N 96903269- 96898881- 99N 96900316- 99N 38175804-
96904654	116544+ 99N 48580709+
96904655	236176- 99N 96902409+
96904656	285739+ 99N 96900250- 99N 95513782-
96904657	322121+ 99N 96902685-
96904658	333218+ 99N 96883001- 99N 96892361+ 99N 96799609+
96904659	710833- 99N 29274748-
96904660	744061+ 99N 39085553+ 99N 46344486- 99N 96901623- 99N 96901192+ 99N 96899064-
96904661	925951- 99N 46821176+ 99N 96876793- 86269120- 99N 96894420- 96904613+
```
All of the gaps are reported as 99N, which I don't think is accurate. I believe I understand why it is this way - that the `abyss-longseqdist` program was written to scaffold with transcriptome contigs, which give you no information about gap size. Thus the gap is simply reported as k-1, and since I have k=100, the gaps are 99N.

But since I am working with PACBIO data, I think it is highly likely that there is good information about the gap size available. I know this is probably not some easy patch to write though, so I understand if you guys would like to close this issue.

If only I could write C/C++ maybe I could implement this! I imagine that by inspecting the alignments, one could calculate the bp between the two query sequences aligned to the reference PACBIO contig. Not only could you scaffold, but you wouldn't need to fill with Ns either, since you'd have the known sequence.

**Comment by sjackman** [comment]
Yes, estimating the gap size would be a useful feature. It's not on our immediate radar, but could definitely happen one day.

**Comment by sjackman** [comment]
You can use LINKS to scaffold ABySS assemblies with PacBio data.
See https://github.com/bcgsc/abyss-dev/pull/29
and http://www.bcgsc.ca/platform/bioinfo/software/links
